// Code generated by ent, DO NOT EDIT.

package teacherattendance

import (
	"go-seed/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.TeacherAttendance {
	return predicate.TeacherAttendance(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.TeacherAttendance {
	return predicate.TeacherAttendance(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.TeacherAttendance {
	return predicate.TeacherAttendance(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.TeacherAttendance {
	return predicate.TeacherAttendance(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.TeacherAttendance {
	return predicate.TeacherAttendance(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.TeacherAttendance {
	return predicate.TeacherAttendance(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.TeacherAttendance {
	return predicate.TeacherAttendance(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.TeacherAttendance {
	return predicate.TeacherAttendance(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.TeacherAttendance {
	return predicate.TeacherAttendance(sql.FieldLTE(FieldID, id))
}

// TeacherID applies equality check predicate on the "teacher_id" field. It's identical to TeacherIDEQ.
func TeacherID(v uuid.UUID) predicate.TeacherAttendance {
	return predicate.TeacherAttendance(sql.FieldEQ(FieldTeacherID, v))
}

// Date applies equality check predicate on the "date" field. It's identical to DateEQ.
func Date(v time.Time) predicate.TeacherAttendance {
	return predicate.TeacherAttendance(sql.FieldEQ(FieldDate, v))
}

// Remarks applies equality check predicate on the "remarks" field. It's identical to RemarksEQ.
func Remarks(v string) predicate.TeacherAttendance {
	return predicate.TeacherAttendance(sql.FieldEQ(FieldRemarks, v))
}

// TeacherIDEQ applies the EQ predicate on the "teacher_id" field.
func TeacherIDEQ(v uuid.UUID) predicate.TeacherAttendance {
	return predicate.TeacherAttendance(sql.FieldEQ(FieldTeacherID, v))
}

// TeacherIDNEQ applies the NEQ predicate on the "teacher_id" field.
func TeacherIDNEQ(v uuid.UUID) predicate.TeacherAttendance {
	return predicate.TeacherAttendance(sql.FieldNEQ(FieldTeacherID, v))
}

// TeacherIDIn applies the In predicate on the "teacher_id" field.
func TeacherIDIn(vs ...uuid.UUID) predicate.TeacherAttendance {
	return predicate.TeacherAttendance(sql.FieldIn(FieldTeacherID, vs...))
}

// TeacherIDNotIn applies the NotIn predicate on the "teacher_id" field.
func TeacherIDNotIn(vs ...uuid.UUID) predicate.TeacherAttendance {
	return predicate.TeacherAttendance(sql.FieldNotIn(FieldTeacherID, vs...))
}

// DateEQ applies the EQ predicate on the "date" field.
func DateEQ(v time.Time) predicate.TeacherAttendance {
	return predicate.TeacherAttendance(sql.FieldEQ(FieldDate, v))
}

// DateNEQ applies the NEQ predicate on the "date" field.
func DateNEQ(v time.Time) predicate.TeacherAttendance {
	return predicate.TeacherAttendance(sql.FieldNEQ(FieldDate, v))
}

// DateIn applies the In predicate on the "date" field.
func DateIn(vs ...time.Time) predicate.TeacherAttendance {
	return predicate.TeacherAttendance(sql.FieldIn(FieldDate, vs...))
}

// DateNotIn applies the NotIn predicate on the "date" field.
func DateNotIn(vs ...time.Time) predicate.TeacherAttendance {
	return predicate.TeacherAttendance(sql.FieldNotIn(FieldDate, vs...))
}

// DateGT applies the GT predicate on the "date" field.
func DateGT(v time.Time) predicate.TeacherAttendance {
	return predicate.TeacherAttendance(sql.FieldGT(FieldDate, v))
}

// DateGTE applies the GTE predicate on the "date" field.
func DateGTE(v time.Time) predicate.TeacherAttendance {
	return predicate.TeacherAttendance(sql.FieldGTE(FieldDate, v))
}

// DateLT applies the LT predicate on the "date" field.
func DateLT(v time.Time) predicate.TeacherAttendance {
	return predicate.TeacherAttendance(sql.FieldLT(FieldDate, v))
}

// DateLTE applies the LTE predicate on the "date" field.
func DateLTE(v time.Time) predicate.TeacherAttendance {
	return predicate.TeacherAttendance(sql.FieldLTE(FieldDate, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.TeacherAttendance {
	return predicate.TeacherAttendance(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.TeacherAttendance {
	return predicate.TeacherAttendance(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.TeacherAttendance {
	return predicate.TeacherAttendance(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.TeacherAttendance {
	return predicate.TeacherAttendance(sql.FieldNotIn(FieldStatus, vs...))
}

// RemarksEQ applies the EQ predicate on the "remarks" field.
func RemarksEQ(v string) predicate.TeacherAttendance {
	return predicate.TeacherAttendance(sql.FieldEQ(FieldRemarks, v))
}

// RemarksNEQ applies the NEQ predicate on the "remarks" field.
func RemarksNEQ(v string) predicate.TeacherAttendance {
	return predicate.TeacherAttendance(sql.FieldNEQ(FieldRemarks, v))
}

// RemarksIn applies the In predicate on the "remarks" field.
func RemarksIn(vs ...string) predicate.TeacherAttendance {
	return predicate.TeacherAttendance(sql.FieldIn(FieldRemarks, vs...))
}

// RemarksNotIn applies the NotIn predicate on the "remarks" field.
func RemarksNotIn(vs ...string) predicate.TeacherAttendance {
	return predicate.TeacherAttendance(sql.FieldNotIn(FieldRemarks, vs...))
}

// RemarksGT applies the GT predicate on the "remarks" field.
func RemarksGT(v string) predicate.TeacherAttendance {
	return predicate.TeacherAttendance(sql.FieldGT(FieldRemarks, v))
}

// RemarksGTE applies the GTE predicate on the "remarks" field.
func RemarksGTE(v string) predicate.TeacherAttendance {
	return predicate.TeacherAttendance(sql.FieldGTE(FieldRemarks, v))
}

// RemarksLT applies the LT predicate on the "remarks" field.
func RemarksLT(v string) predicate.TeacherAttendance {
	return predicate.TeacherAttendance(sql.FieldLT(FieldRemarks, v))
}

// RemarksLTE applies the LTE predicate on the "remarks" field.
func RemarksLTE(v string) predicate.TeacherAttendance {
	return predicate.TeacherAttendance(sql.FieldLTE(FieldRemarks, v))
}

// RemarksContains applies the Contains predicate on the "remarks" field.
func RemarksContains(v string) predicate.TeacherAttendance {
	return predicate.TeacherAttendance(sql.FieldContains(FieldRemarks, v))
}

// RemarksHasPrefix applies the HasPrefix predicate on the "remarks" field.
func RemarksHasPrefix(v string) predicate.TeacherAttendance {
	return predicate.TeacherAttendance(sql.FieldHasPrefix(FieldRemarks, v))
}

// RemarksHasSuffix applies the HasSuffix predicate on the "remarks" field.
func RemarksHasSuffix(v string) predicate.TeacherAttendance {
	return predicate.TeacherAttendance(sql.FieldHasSuffix(FieldRemarks, v))
}

// RemarksIsNil applies the IsNil predicate on the "remarks" field.
func RemarksIsNil() predicate.TeacherAttendance {
	return predicate.TeacherAttendance(sql.FieldIsNull(FieldRemarks))
}

// RemarksNotNil applies the NotNil predicate on the "remarks" field.
func RemarksNotNil() predicate.TeacherAttendance {
	return predicate.TeacherAttendance(sql.FieldNotNull(FieldRemarks))
}

// RemarksEqualFold applies the EqualFold predicate on the "remarks" field.
func RemarksEqualFold(v string) predicate.TeacherAttendance {
	return predicate.TeacherAttendance(sql.FieldEqualFold(FieldRemarks, v))
}

// RemarksContainsFold applies the ContainsFold predicate on the "remarks" field.
func RemarksContainsFold(v string) predicate.TeacherAttendance {
	return predicate.TeacherAttendance(sql.FieldContainsFold(FieldRemarks, v))
}

// HasTeacher applies the HasEdge predicate on the "teacher" edge.
func HasTeacher() predicate.TeacherAttendance {
	return predicate.TeacherAttendance(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, TeacherTable, TeacherColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTeacherWith applies the HasEdge predicate on the "teacher" edge with a given conditions (other predicates).
func HasTeacherWith(preds ...predicate.Teacher) predicate.TeacherAttendance {
	return predicate.TeacherAttendance(func(s *sql.Selector) {
		step := newTeacherStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TeacherAttendance) predicate.TeacherAttendance {
	return predicate.TeacherAttendance(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TeacherAttendance) predicate.TeacherAttendance {
	return predicate.TeacherAttendance(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TeacherAttendance) predicate.TeacherAttendance {
	return predicate.TeacherAttendance(sql.NotPredicates(p))
}
