--
-- PostgreSQL database dump
--

\restrict DLXvG1O3cxllo9SckpXWIeXKgCRH9JWvDUivEj6lbhU2SgS1ZNpZchRxuEGXLGc

-- Dumped from database version 14.20 (Ubuntu 14.20-0ubuntu0.22.04.1)
-- Dumped by pg_dump version 14.20 (Ubuntu 14.20-0ubuntu0.22.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: academic_years; Type: TABLE; Schema: public; Owner: negi
--

CREATE TABLE public.academic_years (
    id bigint NOT NULL,
    label character varying NOT NULL,
    start_date timestamp with time zone NOT NULL,
    end_date timestamp with time zone NOT NULL,
    is_current boolean DEFAULT false NOT NULL
);


ALTER TABLE public.academic_years OWNER TO negi;

--
-- Name: academic_years_id_seq; Type: SEQUENCE; Schema: public; Owner: negi
--

ALTER TABLE public.academic_years ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.academic_years_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: classes; Type: TABLE; Schema: public; Owner: negi
--

CREATE TABLE public.classes (
    id bigint NOT NULL,
    name character varying NOT NULL,
    capacity bigint,
    academic_year_id bigint NOT NULL,
    department_id bigint
);


ALTER TABLE public.classes OWNER TO negi;

--
-- Name: classes_id_seq; Type: SEQUENCE; Schema: public; Owner: negi
--

ALTER TABLE public.classes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.classes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: departments; Type: TABLE; Schema: public; Owner: negi
--

CREATE TABLE public.departments (
    id bigint NOT NULL,
    name character varying NOT NULL,
    code character varying,
    description character varying
);


ALTER TABLE public.departments OWNER TO negi;

--
-- Name: departments_id_seq; Type: SEQUENCE; Schema: public; Owner: negi
--

ALTER TABLE public.departments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.departments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: employees; Type: TABLE; Schema: public; Owner: negi
--

CREATE TABLE public.employees (
    id uuid NOT NULL,
    first_name character varying NOT NULL,
    last_name character varying NOT NULL,
    gender character varying,
    date_of_birth timestamp with time zone,
    phone character varying,
    address character varying,
    job_title character varying,
    joining_date timestamp with time zone,
    salary double precision,
    avatar_url character varying,
    is_active boolean DEFAULT true NOT NULL,
    user_id uuid NOT NULL,
    department_id bigint
);


ALTER TABLE public.employees OWNER TO negi;

--
-- Name: events; Type: TABLE; Schema: public; Owner: negi
--

CREATE TABLE public.events (
    id bigint NOT NULL,
    title character varying NOT NULL,
    event_type character varying DEFAULT 'other'::character varying NOT NULL,
    description character varying,
    event_date timestamp with time zone NOT NULL,
    is_all_day boolean DEFAULT false NOT NULL,
    status character varying DEFAULT 'Upcoming'::character varying NOT NULL
);


ALTER TABLE public.events OWNER TO negi;

--
-- Name: events_id_seq; Type: SEQUENCE; Schema: public; Owner: negi
--

ALTER TABLE public.events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exams; Type: TABLE; Schema: public; Owner: negi
--

CREATE TABLE public.exams (
    id bigint NOT NULL,
    title character varying NOT NULL,
    exam_type character varying,
    start_date timestamp with time zone NOT NULL,
    end_date timestamp with time zone NOT NULL,
    max_marks double precision DEFAULT 100 NOT NULL,
    pass_marks double precision DEFAULT 35 NOT NULL,
    class_id bigint,
    subject_id bigint,
    academic_year_id bigint
);


ALTER TABLE public.exams OWNER TO negi;

--
-- Name: exams_id_seq; Type: SEQUENCE; Schema: public; Owner: negi
--

ALTER TABLE public.exams ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exams_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fee_payments; Type: TABLE; Schema: public; Owner: negi
--

CREATE TABLE public.fee_payments (
    id bigint NOT NULL,
    amount_paid double precision NOT NULL,
    payment_date timestamp with time zone NOT NULL,
    payment_status character varying DEFAULT 'unpaid'::character varying NOT NULL,
    payment_method character varying,
    transaction_ref character varying,
    remarks character varying,
    student_id uuid NOT NULL,
    fee_structure_id bigint NOT NULL
);


ALTER TABLE public.fee_payments OWNER TO negi;

--
-- Name: fee_payments_id_seq; Type: SEQUENCE; Schema: public; Owner: negi
--

ALTER TABLE public.fee_payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fee_payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fee_structures; Type: TABLE; Schema: public; Owner: negi
--

CREATE TABLE public.fee_structures (
    id bigint NOT NULL,
    fee_label character varying NOT NULL,
    amount double precision NOT NULL,
    due_date timestamp with time zone,
    class_id bigint NOT NULL,
    academic_year_id bigint NOT NULL
);


ALTER TABLE public.fee_structures OWNER TO negi;

--
-- Name: fee_structures_id_seq; Type: SEQUENCE; Schema: public; Owner: negi
--

ALTER TABLE public.fee_structures ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fee_structures_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: student_attendances; Type: TABLE; Schema: public; Owner: negi
--

CREATE TABLE public.student_attendances (
    id bigint NOT NULL,
    date timestamp with time zone NOT NULL,
    status character varying DEFAULT 'present'::character varying NOT NULL,
    remarks character varying,
    student_id uuid NOT NULL,
    class_id bigint NOT NULL,
    subject_id bigint
);


ALTER TABLE public.student_attendances OWNER TO negi;

--
-- Name: student_attendances_id_seq; Type: SEQUENCE; Schema: public; Owner: negi
--

ALTER TABLE public.student_attendances ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_attendances_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: students; Type: TABLE; Schema: public; Owner: negi
--

CREATE TABLE public.students (
    id uuid NOT NULL,
    roll_number character varying NOT NULL,
    first_name character varying NOT NULL,
    last_name character varying NOT NULL,
    gender character varying,
    date_of_birth timestamp with time zone,
    phone character varying,
    parent_phone character varying,
    address character varying,
    joining_date timestamp with time zone NOT NULL,
    avatar_url character varying,
    user_id uuid,
    class_id bigint
);


ALTER TABLE public.students OWNER TO negi;

--
-- Name: subjects; Type: TABLE; Schema: public; Owner: negi
--

CREATE TABLE public.subjects (
    id bigint NOT NULL,
    name character varying NOT NULL,
    code character varying,
    description character varying
);


ALTER TABLE public.subjects OWNER TO negi;

--
-- Name: subjects_id_seq; Type: SEQUENCE; Schema: public; Owner: negi
--

ALTER TABLE public.subjects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subjects_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tasks; Type: TABLE; Schema: public; Owner: negi
--

CREATE TABLE public.tasks (
    id bigint NOT NULL,
    title character varying NOT NULL,
    details character varying,
    status character varying DEFAULT 'Pending'::character varying NOT NULL,
    priority character varying DEFAULT 'Normal'::character varying NOT NULL,
    progress_pct bigint DEFAULT 0 NOT NULL,
    due_date timestamp with time zone,
    assigned_to uuid,
    assigned_by uuid
);


ALTER TABLE public.tasks OWNER TO negi;

--
-- Name: tasks_id_seq; Type: SEQUENCE; Schema: public; Owner: negi
--

ALTER TABLE public.tasks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tasks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: teacher_attendances; Type: TABLE; Schema: public; Owner: negi
--

CREATE TABLE public.teacher_attendances (
    id bigint NOT NULL,
    date timestamp with time zone NOT NULL,
    status character varying DEFAULT 'present'::character varying NOT NULL,
    remarks character varying,
    teacher_id uuid NOT NULL
);


ALTER TABLE public.teacher_attendances OWNER TO negi;

--
-- Name: teacher_attendances_id_seq; Type: SEQUENCE; Schema: public; Owner: negi
--

ALTER TABLE public.teacher_attendances ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.teacher_attendances_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: teacher_subjects; Type: TABLE; Schema: public; Owner: negi
--

CREATE TABLE public.teacher_subjects (
    teacher_id uuid NOT NULL,
    subject_id bigint NOT NULL
);


ALTER TABLE public.teacher_subjects OWNER TO negi;

--
-- Name: teachers; Type: TABLE; Schema: public; Owner: negi
--

CREATE TABLE public.teachers (
    id uuid NOT NULL,
    first_name character varying NOT NULL,
    last_name character varying NOT NULL,
    gender character varying,
    date_of_birth timestamp with time zone,
    phone character varying,
    address character varying,
    qualification character varying,
    joining_date timestamp with time zone,
    avatar_url character varying,
    user_id uuid NOT NULL,
    department_id bigint
);


ALTER TABLE public.teachers OWNER TO negi;

--
-- Name: users; Type: TABLE; Schema: public; Owner: negi
--

CREATE TABLE public.users (
    id uuid NOT NULL,
    username character varying NOT NULL,
    email character varying NOT NULL,
    password_hash character varying NOT NULL,
    role character varying DEFAULT 'student'::character varying NOT NULL,
    avatar_url character varying,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.users OWNER TO negi;

--
-- Name: academic_years academic_years_pkey; Type: CONSTRAINT; Schema: public; Owner: negi
--

ALTER TABLE ONLY public.academic_years
    ADD CONSTRAINT academic_years_pkey PRIMARY KEY (id);


--
-- Name: classes classes_pkey; Type: CONSTRAINT; Schema: public; Owner: negi
--

ALTER TABLE ONLY public.classes
    ADD CONSTRAINT classes_pkey PRIMARY KEY (id);


--
-- Name: departments departments_pkey; Type: CONSTRAINT; Schema: public; Owner: negi
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_pkey PRIMARY KEY (id);


--
-- Name: employees employees_pkey; Type: CONSTRAINT; Schema: public; Owner: negi
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_pkey PRIMARY KEY (id);


--
-- Name: events events_pkey; Type: CONSTRAINT; Schema: public; Owner: negi
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_pkey PRIMARY KEY (id);


--
-- Name: exams exams_pkey; Type: CONSTRAINT; Schema: public; Owner: negi
--

ALTER TABLE ONLY public.exams
    ADD CONSTRAINT exams_pkey PRIMARY KEY (id);


--
-- Name: fee_payments fee_payments_pkey; Type: CONSTRAINT; Schema: public; Owner: negi
--

ALTER TABLE ONLY public.fee_payments
    ADD CONSTRAINT fee_payments_pkey PRIMARY KEY (id);


--
-- Name: fee_structures fee_structures_pkey; Type: CONSTRAINT; Schema: public; Owner: negi
--

ALTER TABLE ONLY public.fee_structures
    ADD CONSTRAINT fee_structures_pkey PRIMARY KEY (id);


--
-- Name: student_attendances student_attendances_pkey; Type: CONSTRAINT; Schema: public; Owner: negi
--

ALTER TABLE ONLY public.student_attendances
    ADD CONSTRAINT student_attendances_pkey PRIMARY KEY (id);


--
-- Name: students students_pkey; Type: CONSTRAINT; Schema: public; Owner: negi
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT students_pkey PRIMARY KEY (id);


--
-- Name: subjects subjects_pkey; Type: CONSTRAINT; Schema: public; Owner: negi
--

ALTER TABLE ONLY public.subjects
    ADD CONSTRAINT subjects_pkey PRIMARY KEY (id);


--
-- Name: tasks tasks_pkey; Type: CONSTRAINT; Schema: public; Owner: negi
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT tasks_pkey PRIMARY KEY (id);


--
-- Name: teacher_attendances teacher_attendances_pkey; Type: CONSTRAINT; Schema: public; Owner: negi
--

ALTER TABLE ONLY public.teacher_attendances
    ADD CONSTRAINT teacher_attendances_pkey PRIMARY KEY (id);


--
-- Name: teacher_subjects teacher_subjects_pkey; Type: CONSTRAINT; Schema: public; Owner: negi
--

ALTER TABLE ONLY public.teacher_subjects
    ADD CONSTRAINT teacher_subjects_pkey PRIMARY KEY (teacher_id, subject_id);


--
-- Name: teachers teachers_pkey; Type: CONSTRAINT; Schema: public; Owner: negi
--

ALTER TABLE ONLY public.teachers
    ADD CONSTRAINT teachers_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: negi
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: academic_years_label_key; Type: INDEX; Schema: public; Owner: negi
--

CREATE UNIQUE INDEX academic_years_label_key ON public.academic_years USING btree (label);


--
-- Name: class_name_academic_year_id; Type: INDEX; Schema: public; Owner: negi
--

CREATE UNIQUE INDEX class_name_academic_year_id ON public.classes USING btree (name, academic_year_id);


--
-- Name: departments_name_key; Type: INDEX; Schema: public; Owner: negi
--

CREATE UNIQUE INDEX departments_name_key ON public.departments USING btree (name);


--
-- Name: employee_user_id; Type: INDEX; Schema: public; Owner: negi
--

CREATE UNIQUE INDEX employee_user_id ON public.employees USING btree (user_id);


--
-- Name: feestructure_class_id_academic_year_id_fee_label; Type: INDEX; Schema: public; Owner: negi
--

CREATE UNIQUE INDEX feestructure_class_id_academic_year_id_fee_label ON public.fee_structures USING btree (class_id, academic_year_id, fee_label);


--
-- Name: studentattendance_student_id_subject_id_date; Type: INDEX; Schema: public; Owner: negi
--

CREATE UNIQUE INDEX studentattendance_student_id_subject_id_date ON public.student_attendances USING btree (student_id, subject_id, date);


--
-- Name: students_roll_number_key; Type: INDEX; Schema: public; Owner: negi
--

CREATE UNIQUE INDEX students_roll_number_key ON public.students USING btree (roll_number);


--
-- Name: subjects_code_key; Type: INDEX; Schema: public; Owner: negi
--

CREATE UNIQUE INDEX subjects_code_key ON public.subjects USING btree (code);


--
-- Name: teacher_user_id; Type: INDEX; Schema: public; Owner: negi
--

CREATE UNIQUE INDEX teacher_user_id ON public.teachers USING btree (user_id);


--
-- Name: teacherattendance_teacher_id_date; Type: INDEX; Schema: public; Owner: negi
--

CREATE UNIQUE INDEX teacherattendance_teacher_id_date ON public.teacher_attendances USING btree (teacher_id, date);


--
-- Name: users_email_key; Type: INDEX; Schema: public; Owner: negi
--

CREATE UNIQUE INDEX users_email_key ON public.users USING btree (email);


--
-- Name: users_username_key; Type: INDEX; Schema: public; Owner: negi
--

CREATE UNIQUE INDEX users_username_key ON public.users USING btree (username);


--
-- Name: classes classes_academic_years_academic_year; Type: FK CONSTRAINT; Schema: public; Owner: negi
--

ALTER TABLE ONLY public.classes
    ADD CONSTRAINT classes_academic_years_academic_year FOREIGN KEY (academic_year_id) REFERENCES public.academic_years(id);


--
-- Name: classes classes_departments_department; Type: FK CONSTRAINT; Schema: public; Owner: negi
--

ALTER TABLE ONLY public.classes
    ADD CONSTRAINT classes_departments_department FOREIGN KEY (department_id) REFERENCES public.departments(id) ON DELETE SET NULL;


--
-- Name: employees employees_departments_department; Type: FK CONSTRAINT; Schema: public; Owner: negi
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_departments_department FOREIGN KEY (department_id) REFERENCES public.departments(id) ON DELETE SET NULL;


--
-- Name: employees employees_users_user; Type: FK CONSTRAINT; Schema: public; Owner: negi
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_users_user FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: exams exams_academic_years_academic_year; Type: FK CONSTRAINT; Schema: public; Owner: negi
--

ALTER TABLE ONLY public.exams
    ADD CONSTRAINT exams_academic_years_academic_year FOREIGN KEY (academic_year_id) REFERENCES public.academic_years(id) ON DELETE SET NULL;


--
-- Name: exams exams_classes_class; Type: FK CONSTRAINT; Schema: public; Owner: negi
--

ALTER TABLE ONLY public.exams
    ADD CONSTRAINT exams_classes_class FOREIGN KEY (class_id) REFERENCES public.classes(id) ON DELETE SET NULL;


--
-- Name: exams exams_subjects_subject; Type: FK CONSTRAINT; Schema: public; Owner: negi
--

ALTER TABLE ONLY public.exams
    ADD CONSTRAINT exams_subjects_subject FOREIGN KEY (subject_id) REFERENCES public.subjects(id) ON DELETE SET NULL;


--
-- Name: fee_payments fee_payments_fee_structures_fee_structure; Type: FK CONSTRAINT; Schema: public; Owner: negi
--

ALTER TABLE ONLY public.fee_payments
    ADD CONSTRAINT fee_payments_fee_structures_fee_structure FOREIGN KEY (fee_structure_id) REFERENCES public.fee_structures(id);


--
-- Name: fee_payments fee_payments_students_student; Type: FK CONSTRAINT; Schema: public; Owner: negi
--

ALTER TABLE ONLY public.fee_payments
    ADD CONSTRAINT fee_payments_students_student FOREIGN KEY (student_id) REFERENCES public.students(id);


--
-- Name: fee_structures fee_structures_academic_years_academic_year; Type: FK CONSTRAINT; Schema: public; Owner: negi
--

ALTER TABLE ONLY public.fee_structures
    ADD CONSTRAINT fee_structures_academic_years_academic_year FOREIGN KEY (academic_year_id) REFERENCES public.academic_years(id);


--
-- Name: fee_structures fee_structures_classes_class; Type: FK CONSTRAINT; Schema: public; Owner: negi
--

ALTER TABLE ONLY public.fee_structures
    ADD CONSTRAINT fee_structures_classes_class FOREIGN KEY (class_id) REFERENCES public.classes(id);


--
-- Name: student_attendances student_attendances_classes_class; Type: FK CONSTRAINT; Schema: public; Owner: negi
--

ALTER TABLE ONLY public.student_attendances
    ADD CONSTRAINT student_attendances_classes_class FOREIGN KEY (class_id) REFERENCES public.classes(id);


--
-- Name: student_attendances student_attendances_students_student; Type: FK CONSTRAINT; Schema: public; Owner: negi
--

ALTER TABLE ONLY public.student_attendances
    ADD CONSTRAINT student_attendances_students_student FOREIGN KEY (student_id) REFERENCES public.students(id);


--
-- Name: student_attendances student_attendances_subjects_subject; Type: FK CONSTRAINT; Schema: public; Owner: negi
--

ALTER TABLE ONLY public.student_attendances
    ADD CONSTRAINT student_attendances_subjects_subject FOREIGN KEY (subject_id) REFERENCES public.subjects(id) ON DELETE SET NULL;


--
-- Name: students students_classes_class; Type: FK CONSTRAINT; Schema: public; Owner: negi
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT students_classes_class FOREIGN KEY (class_id) REFERENCES public.classes(id) ON DELETE SET NULL;


--
-- Name: students students_users_user; Type: FK CONSTRAINT; Schema: public; Owner: negi
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT students_users_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: tasks tasks_users_assignee; Type: FK CONSTRAINT; Schema: public; Owner: negi
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT tasks_users_assignee FOREIGN KEY (assigned_to) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: tasks tasks_users_assigner; Type: FK CONSTRAINT; Schema: public; Owner: negi
--

ALTER TABLE ONLY public.tasks
    ADD CONSTRAINT tasks_users_assigner FOREIGN KEY (assigned_by) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: teacher_attendances teacher_attendances_teachers_teacher; Type: FK CONSTRAINT; Schema: public; Owner: negi
--

ALTER TABLE ONLY public.teacher_attendances
    ADD CONSTRAINT teacher_attendances_teachers_teacher FOREIGN KEY (teacher_id) REFERENCES public.teachers(id);


--
-- Name: teacher_subjects teacher_subjects_subject_id; Type: FK CONSTRAINT; Schema: public; Owner: negi
--

ALTER TABLE ONLY public.teacher_subjects
    ADD CONSTRAINT teacher_subjects_subject_id FOREIGN KEY (subject_id) REFERENCES public.subjects(id) ON DELETE CASCADE;


--
-- Name: teacher_subjects teacher_subjects_teacher_id; Type: FK CONSTRAINT; Schema: public; Owner: negi
--

ALTER TABLE ONLY public.teacher_subjects
    ADD CONSTRAINT teacher_subjects_teacher_id FOREIGN KEY (teacher_id) REFERENCES public.teachers(id) ON DELETE CASCADE;


--
-- Name: teachers teachers_departments_department; Type: FK CONSTRAINT; Schema: public; Owner: negi
--

ALTER TABLE ONLY public.teachers
    ADD CONSTRAINT teachers_departments_department FOREIGN KEY (department_id) REFERENCES public.departments(id) ON DELETE SET NULL;


--
-- Name: teachers teachers_users_user; Type: FK CONSTRAINT; Schema: public; Owner: negi
--

ALTER TABLE ONLY public.teachers
    ADD CONSTRAINT teachers_users_user FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

\unrestrict DLXvG1O3cxllo9SckpXWIeXKgCRH9JWvDUivEj6lbhU2SgS1ZNpZchRxuEGXLGc

