// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package main

type LoginInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token string `json:"token"`
	Role  string `json:"role"`
}

type SessionCustom struct {
	ID          string `json:"id"`
	SessionName string `json:"sessionName"`
	StartDate   string `json:"startDate"`
	EndDate     string `json:"endDate"`
	Status      string `json:"status"`
	Instructor  string `json:"instructor"`
	Room        string `json:"room"`
}

type CreateSessionCustomInput struct {
	SessionName string `json:"sessionName"`
	StartDate   string `json:"startDate"`
	EndDate     string `json:"endDate"`
	Status      string `json:"status"`
	Instructor  string `json:"instructor"`
	Room        string `json:"room"`
}

type UpdateSessionCustomInput struct {
	ID          string `json:"id"`
	SessionName string `json:"sessionName"`
	StartDate   string `json:"startDate"`
	EndDate     string `json:"endDate"`
	Status      string `json:"status"`
	Instructor  string `json:"instructor"`
	Room        string `json:"room"`
}

type AcademicClassCustom struct {
	ID           string `json:"id"`
	ClassName    string `json:"className"`
	Section      string `json:"section"`
	AcademicYear string `json:"academicYear"`
	Teacher      string `json:"teacher"`
	Status       string `json:"status"`
	StudentCount string `json:"studentCount"`
	RoomNumber   string `json:"roomNumber"`
}

type CreateAcademicClassCustomInput struct {
	ClassName    string `json:"className"`
	Section      string `json:"section"`
	AcademicYear string `json:"academicYear"`
	Teacher      string `json:"teacher"`
	Status       string `json:"status"`
	StudentCount string `json:"studentCount"`
	RoomNumber   string `json:"roomNumber"`
}

type UpdateAcademicClassCustomInput struct {
	ID           string `json:"id"`
	ClassName    string `json:"className"`
	Section      string `json:"section"`
	AcademicYear string `json:"academicYear"`
	Teacher      string `json:"teacher"`
	Status       string `json:"status"`
	StudentCount string `json:"studentCount"`
	RoomNumber   string `json:"roomNumber"`
}

type AcademicSubjectCustom struct {
	ID            string `json:"id"`
	SubjectName   string `json:"subjectName"`
	SubjectCode   string `json:"subjectCode"`
	SubjectType   string `json:"subjectType"`
	Status        string `json:"status"`
	Prerequisites string `json:"prerequisites"`
	Credits       string `json:"credits"`
}

type CreateAcademicSubjectCustomInput struct {
	SubjectName   string `json:"subjectName"`
	SubjectCode   string `json:"subjectCode"`
	SubjectType   string `json:"subjectType"`
	Status        string `json:"status"`
	Prerequisites string `json:"prerequisites"`
	Credits       string `json:"credits"`
}

type UpdateAcademicSubjectCustomInput struct {
	ID            string `json:"id"`
	SubjectName   string `json:"subjectName"`
	SubjectCode   string `json:"subjectCode"`
	SubjectType   string `json:"subjectType"`
	Status        string `json:"status"`
	Prerequisites string `json:"prerequisites"`
	Credits       string `json:"credits"`
}

type CourseCurriculumCustom struct {
	ID                string `json:"id"`
	CourseName        string `json:"courseName"`
	ClassName         string `json:"className"`
	SubjectName       string `json:"subjectName"`
	Description       string `json:"description"`
	Status            string `json:"status"`
	Duration          string `json:"duration"`
	ReferenceMaterial string `json:"referenceMaterial"`
}

type CreateCourseCurriculumCustomInput struct {
	CourseName        string `json:"courseName"`
	ClassName         string `json:"className"`
	SubjectName       string `json:"subjectName"`
	Description       string `json:"description"`
	Status            string `json:"status"`
	Duration          string `json:"duration"`
	ReferenceMaterial string `json:"referenceMaterial"`
}

type UpdateCourseCurriculumCustomInput struct {
	ID                string `json:"id"`
	CourseName        string `json:"courseName"`
	ClassName         string `json:"className"`
	SubjectName       string `json:"subjectName"`
	Description       string `json:"description"`
	Status            string `json:"status"`
	Duration          string `json:"duration"`
	ReferenceMaterial string `json:"referenceMaterial"`
}

type AssignmentCustom struct {
	ID             string `json:"id"`
	ClassName      string `json:"className"`
	SubjectName    string `json:"subjectName"`
	TeacherName    string `json:"teacherName"`
	AssignmentDate string `json:"assignmentDate"`
	Status         string `json:"status"`
	Title          string `json:"title"`
	Deadline       string `json:"deadline"`
	Details        string `json:"details"`
}

type CreateAssignmentCustomInput struct {
	ClassName      string `json:"className"`
	SubjectName    string `json:"subjectName"`
	TeacherName    string `json:"teacherName"`
	AssignmentDate string `json:"assignmentDate"`
	Status         string `json:"status"`
	Title          string `json:"title"`
	Deadline       string `json:"deadline"`
	Details        string `json:"details"`
}

type UpdateAssignmentCustomInput struct {
	ID             string `json:"id"`
	ClassName      string `json:"className"`
	SubjectName    string `json:"subjectName"`
	TeacherName    string `json:"teacherName"`
	AssignmentDate string `json:"assignmentDate"`
	Status         string `json:"status"`
	Title          string `json:"title"`
	Deadline       string `json:"deadline"`
	Details        string `json:"details"`
}

type LessonPlanningCustom struct {
	ID             string `json:"id"`
	TopicName      string `json:"topicName"`
	LessonName     string `json:"lessonName"`
	ClassName      string `json:"className"`
	SubjectName    string `json:"subjectName"`
	TeacherName    string `json:"teacherName"`
	LessonDate     string `json:"lessonDate"`
	Status         string `json:"status"`
	Objectives     string `json:"objectives"`
	TeachingMethod string `json:"teachingMethod"`
}

type CreateLessonPlanningCustomInput struct {
	TopicName      string `json:"topicName"`
	LessonName     string `json:"lessonName"`
	ClassName      string `json:"className"`
	SubjectName    string `json:"subjectName"`
	TeacherName    string `json:"teacherName"`
	LessonDate     string `json:"lessonDate"`
	Status         string `json:"status"`
	Objectives     string `json:"objectives"`
	TeachingMethod string `json:"teachingMethod"`
}

type UpdateLessonPlanningCustomInput struct {
	ID             string `json:"id"`
	TopicName      string `json:"topicName"`
	LessonName     string `json:"lessonName"`
	ClassName      string `json:"className"`
	SubjectName    string `json:"subjectName"`
	TeacherName    string `json:"teacherName"`
	LessonDate     string `json:"lessonDate"`
	Status         string `json:"status"`
	Objectives     string `json:"objectives"`
	TeachingMethod string `json:"teachingMethod"`
}

type HostelRoomCustom struct {
	RoomID              string  `json:"roomId"`
	RoomNumber          string  `json:"roomNumber"`
	RoomType            string  `json:"roomType"`
	Floor               int     `json:"floor"`
	Capacity            int     `json:"capacity"`
	OccupiedStatus      string  `json:"occupiedStatus"`
	CurrentOccupants    int     `json:"currentOccupants"`
	PriceFees           float64 `json:"priceFees"`
	RoomCondition       string  `json:"roomCondition"`
	DateAssigned        string  `json:"dateAssigned"`
	RoomSupervisorStaff string  `json:"roomSupervisorStaff"`
	HostelBlock         string  `json:"hostelBlock"`
	CheckInDate         string  `json:"checkInDate"`
	CheckOutDate        string  `json:"checkOutDate"`
	RoomTypeCode        string  `json:"roomTypeCode"`
	RoomDescription     string  `json:"roomDescription"`
}

type CreateHostelRoomCustomInput struct {
	RoomNumber          string  `json:"roomNumber"`
	RoomType            string  `json:"roomType"`
	Floor               int     `json:"floor"`
	Capacity            int     `json:"capacity"`
	OccupiedStatus      string  `json:"occupiedStatus"`
	CurrentOccupants    int     `json:"currentOccupants"`
	PriceFees           float64 `json:"priceFees"`
	RoomCondition       string  `json:"roomCondition"`
	DateAssigned        string  `json:"dateAssigned"`
	RoomSupervisorStaff string  `json:"roomSupervisorStaff"`
	HostelBlock         string  `json:"hostelBlock"`
	CheckInDate         string  `json:"checkInDate"`
	CheckOutDate        string  `json:"checkOutDate"`
	RoomTypeCode        string  `json:"roomTypeCode"`
	RoomDescription     string  `json:"roomDescription"`
}

type UpdateHostelRoomCustomInput struct {
	RoomID              string  `json:"roomId"`
	RoomNumber          string  `json:"roomNumber"`
	RoomType            string  `json:"roomType"`
	Floor               int     `json:"floor"`
	Capacity            int     `json:"capacity"`
	OccupiedStatus      string  `json:"occupiedStatus"`
	CurrentOccupants    int     `json:"currentOccupants"`
	PriceFees           float64 `json:"priceFees"`
	RoomCondition       string  `json:"roomCondition"`
	DateAssigned        string  `json:"dateAssigned"`
	RoomSupervisorStaff string  `json:"roomSupervisorStaff"`
	HostelBlock         string  `json:"hostelBlock"`
	CheckInDate         string  `json:"checkInDate"`
	CheckOutDate        string  `json:"checkOutDate"`
	RoomTypeCode        string  `json:"roomTypeCode"`
	RoomDescription     string  `json:"roomDescription"`
}

type HostelRoomTypeCustom struct {
	RoomTypeID      string  `json:"roomTypeId"`
	RoomTypeName    string  `json:"roomTypeName"`
	Capacity        int     `json:"capacity"`
	RoomCategory    string  `json:"roomCategory"`
	RoomDescription string  `json:"roomDescription"`
	RoomPrice       float64 `json:"roomPrice"`
	RoomFacilities  string  `json:"roomFacilities"`
	RoomArea        float64 `json:"roomArea"`
	RoomCondition   string  `json:"roomCondition"`
	RoomTypeCode    string  `json:"roomTypeCode"`
	CreatedAt       string  `json:"createdAt"`
	UpdatedAt       string  `json:"updatedAt"`
	Status          string  `json:"status"`
	MaxOccupants    int     `json:"maxOccupants"`
}

type CreateHostelRoomTypeCustomInput struct {
	RoomTypeName    string  `json:"roomTypeName"`
	Capacity        int     `json:"capacity"`
	RoomCategory    string  `json:"roomCategory"`
	RoomDescription string  `json:"roomDescription"`
	RoomPrice       float64 `json:"roomPrice"`
	RoomFacilities  string  `json:"roomFacilities"`
	RoomArea        float64 `json:"roomArea"`
	RoomCondition   string  `json:"roomCondition"`
	RoomTypeCode    string  `json:"roomTypeCode"`
	Status          string  `json:"status"`
	MaxOccupants    int     `json:"maxOccupants"`
}

type UpdateHostelRoomTypeCustomInput struct {
	RoomTypeID      string  `json:"roomTypeId"`
	RoomTypeName    string  `json:"roomTypeName"`
	Capacity        int     `json:"capacity"`
	RoomCategory    string  `json:"roomCategory"`
	RoomDescription string  `json:"roomDescription"`
	RoomPrice       float64 `json:"roomPrice"`
	RoomFacilities  string  `json:"roomFacilities"`
	RoomArea        float64 `json:"roomArea"`
	RoomCondition   string  `json:"roomCondition"`
	RoomTypeCode    string  `json:"roomTypeCode"`
	Status          string  `json:"status"`
	MaxOccupants    int     `json:"maxOccupants"`
}

type HostelAllocationCustom struct {
	ID             string `json:"id"`
	Img            string `json:"img"`
	StudentName    string `json:"student_name"`
	RollNo         string `json:"roll_no"`
	HostelName     string `json:"hostel_name"`
	RoomNo         string `json:"room_no"`
	RoomType       string `json:"room_type"`
	AllocationDate string `json:"allocation_date"`
	Status         string `json:"status"`
}

type CreateHostelAllocationCustomInput struct {
	Img            string `json:"img"`
	StudentName    string `json:"student_name"`
	RollNo         string `json:"roll_no"`
	HostelName     string `json:"hostel_name"`
	RoomNo         string `json:"room_no"`
	RoomType       string `json:"room_type"`
	AllocationDate string `json:"allocation_date"`
	Status         string `json:"status"`
}

type UpdateHostelAllocationCustomInput struct {
	ID             string `json:"id"`
	Img            string `json:"img"`
	StudentName    string `json:"student_name"`
	RollNo         string `json:"roll_no"`
	HostelName     string `json:"hostel_name"`
	RoomNo         string `json:"room_no"`
	RoomType       string `json:"room_type"`
	AllocationDate string `json:"allocation_date"`
	Status         string `json:"status"`
}

type HostelAttendanceCustom struct {
	ID             string `json:"id"`
	Img            string `json:"img"`
	StudentName    string `json:"student_name"`
	RollNo         string `json:"roll_no"`
	HostelName     string `json:"hostel_name"`
	RoomNo         string `json:"room_no"`
	AttendanceDate string `json:"attendance_date"`
	Status         string `json:"status"`
	Note           string `json:"note"`
}

type CreateHostelAttendanceCustomInput struct {
	Img            string `json:"img"`
	StudentName    string `json:"student_name"`
	RollNo         string `json:"roll_no"`
	HostelName     string `json:"hostel_name"`
	RoomNo         string `json:"room_no"`
	AttendanceDate string `json:"attendance_date"`
	Status         string `json:"status"`
	Note           string `json:"note"`
}

type UpdateHostelAttendanceCustomInput struct {
	ID             string `json:"id"`
	Img            string `json:"img"`
	StudentName    string `json:"student_name"`
	RollNo         string `json:"roll_no"`
	HostelName     string `json:"hostel_name"`
	RoomNo         string `json:"room_no"`
	AttendanceDate string `json:"attendance_date"`
	Status         string `json:"status"`
	Note           string `json:"note"`
}

type HostelFeeCustom struct {
	ID            string  `json:"id"`
	Img           string  `json:"img"`
	StudentName   string  `json:"student_name"`
	RollNo        string  `json:"roll_no"`
	HostelName    string  `json:"hostel_name"`
	RoomNo        string  `json:"room_no"`
	FeeType       string  `json:"fee_type"`
	Amount        float64 `json:"amount"`
	PaymentDate   string  `json:"payment_date"`
	PaymentStatus string  `json:"payment_status"`
}

type CreateHostelFeeCustomInput struct {
	Img           string  `json:"img"`
	StudentName   string  `json:"student_name"`
	RollNo        string  `json:"roll_no"`
	HostelName    string  `json:"hostel_name"`
	RoomNo        string  `json:"room_no"`
	FeeType       string  `json:"fee_type"`
	Amount        float64 `json:"amount"`
	PaymentDate   string  `json:"payment_date"`
	PaymentStatus string  `json:"payment_status"`
}

type UpdateHostelFeeCustomInput struct {
	ID            string  `json:"id"`
	Img           string  `json:"img"`
	StudentName   string  `json:"student_name"`
	RollNo        string  `json:"roll_no"`
	HostelName    string  `json:"hostel_name"`
	RoomNo        string  `json:"room_no"`
	FeeType       string  `json:"fee_type"`
	Amount        float64 `json:"amount"`
	PaymentDate   string  `json:"payment_date"`
	PaymentStatus string  `json:"payment_status"`
}

type DepartmentCustom struct {
	ID              string `json:"id"`
	Img             string `json:"img"`
	DepartmentName  string `json:"department_name"`
	Hod             string `json:"hod"`
	Phone           string `json:"phone"`
	Email           string `json:"email"`
	StudentCapacity string `json:"student_capacity"`
	EstablishedYear string `json:"establishedYear"`
	TotalFaculty    string `json:"totalFaculty"`
}

type CreateDepartmentCustomInput struct {
	Img             string `json:"img"`
	DepartmentName  string `json:"department_name"`
	Hod             string `json:"hod"`
	Phone           string `json:"phone"`
	Email           string `json:"email"`
	StudentCapacity string `json:"student_capacity"`
	EstablishedYear string `json:"establishedYear"`
	TotalFaculty    string `json:"totalFaculty"`
}

type UpdateDepartmentCustomInput struct {
	ID              string `json:"id"`
	Img             string `json:"img"`
	DepartmentName  string `json:"department_name"`
	Hod             string `json:"hod"`
	Phone           string `json:"phone"`
	Email           string `json:"email"`
	StudentCapacity string `json:"student_capacity"`
	EstablishedYear string `json:"establishedYear"`
	TotalFaculty    string `json:"totalFaculty"`
}

type AcademicReportCustom struct {
	ID           string `json:"id"`
	Img          string `json:"img"`
	ReportType   string `json:"reportType"`
	ClassName    string `json:"className"`
	Subject      string `json:"subject"`
	AcademicYear string `json:"academicYear"`
	Term         string `json:"term"`
	GeneratedBy  string `json:"generatedBy"`
	Date         string `json:"date"`
	Status       string `json:"status"`
}

type CreateAcademicReportCustomInput struct {
	Img          string `json:"img"`
	ReportType   string `json:"reportType"`
	ClassName    string `json:"className"`
	Subject      string `json:"subject"`
	AcademicYear string `json:"academicYear"`
	Term         string `json:"term"`
	GeneratedBy  string `json:"generatedBy"`
	Date         string `json:"date"`
	Status       string `json:"status"`
}

type UpdateAcademicReportCustomInput struct {
	ID           string `json:"id"`
	Img          string `json:"img"`
	ReportType   string `json:"reportType"`
	ClassName    string `json:"className"`
	Subject      string `json:"subject"`
	AcademicYear string `json:"academicYear"`
	Term         string `json:"term"`
	GeneratedBy  string `json:"generatedBy"`
	Date         string `json:"date"`
	Status       string `json:"status"`
}

type AttendanceReportCustom struct {
	ID                   string  `json:"id"`
	Img                  string  `json:"img"`
	ReportType           string  `json:"reportType"`
	ClassName            string  `json:"className"`
	DateFrom             string  `json:"dateFrom"`
	DateTo               string  `json:"dateTo"`
	AttendancePercentage float64 `json:"attendancePercentage"`
	GeneratedBy          string  `json:"generatedBy"`
	Date                 string  `json:"date"`
	Status               string  `json:"status"`
}

type CreateAttendanceReportCustomInput struct {
	Img                  string  `json:"img"`
	ReportType           string  `json:"reportType"`
	ClassName            string  `json:"className"`
	DateFrom             string  `json:"dateFrom"`
	DateTo               string  `json:"dateTo"`
	AttendancePercentage float64 `json:"attendancePercentage"`
	GeneratedBy          string  `json:"generatedBy"`
	Date                 string  `json:"date"`
	Status               string  `json:"status"`
}

type UpdateAttendanceReportCustomInput struct {
	ID                   string  `json:"id"`
	Img                  string  `json:"img"`
	ReportType           string  `json:"reportType"`
	ClassName            string  `json:"className"`
	DateFrom             string  `json:"dateFrom"`
	DateTo               string  `json:"dateTo"`
	AttendancePercentage float64 `json:"attendancePercentage"`
	GeneratedBy          string  `json:"generatedBy"`
	Date                 string  `json:"date"`
	Status               string  `json:"status"`
}

type FeeReportCustom struct {
	ID          string  `json:"id"`
	Img         string  `json:"img"`
	ReportType  string  `json:"reportType"`
	FeeCategory string  `json:"feeCategory"`
	DateFrom    string  `json:"dateFrom"`
	DateTo      string  `json:"dateTo"`
	TotalAmount float64 `json:"totalAmount"`
	GeneratedBy string  `json:"generatedBy"`
	Date        string  `json:"date"`
	Status      string  `json:"status"`
}

type CreateFeeReportCustomInput struct {
	Img         string  `json:"img"`
	ReportType  string  `json:"reportType"`
	FeeCategory string  `json:"feeCategory"`
	DateFrom    string  `json:"dateFrom"`
	DateTo      string  `json:"dateTo"`
	TotalAmount float64 `json:"totalAmount"`
	GeneratedBy string  `json:"generatedBy"`
	Date        string  `json:"date"`
	Status      string  `json:"status"`
}

type UpdateFeeReportCustomInput struct {
	ID          string  `json:"id"`
	Img         string  `json:"img"`
	ReportType  string  `json:"reportType"`
	FeeCategory string  `json:"feeCategory"`
	DateFrom    string  `json:"dateFrom"`
	DateTo      string  `json:"dateTo"`
	TotalAmount float64 `json:"totalAmount"`
	GeneratedBy string  `json:"generatedBy"`
	Date        string  `json:"date"`
	Status      string  `json:"status"`
}

type ExamReportCustom struct {
	ID             string  `json:"id"`
	Img            string  `json:"img"`
	ExamName       string  `json:"examName"`
	ClassName      string  `json:"className"`
	Subject        string  `json:"subject"`
	ExamDate       string  `json:"examDate"`
	PassPercentage float64 `json:"passPercentage"`
	AverageMarks   float64 `json:"averageMarks"`
	GeneratedBy    string  `json:"generatedBy"`
	Date           string  `json:"date"`
	Status         string  `json:"status"`
}

type CreateExamReportCustomInput struct {
	Img            string  `json:"img"`
	ExamName       string  `json:"examName"`
	ClassName      string  `json:"className"`
	Subject        string  `json:"subject"`
	ExamDate       string  `json:"examDate"`
	PassPercentage float64 `json:"passPercentage"`
	AverageMarks   float64 `json:"averageMarks"`
	GeneratedBy    string  `json:"generatedBy"`
	Date           string  `json:"date"`
	Status         string  `json:"status"`
}

type UpdateExamReportCustomInput struct {
	ID             string  `json:"id"`
	Img            string  `json:"img"`
	ExamName       string  `json:"examName"`
	ClassName      string  `json:"className"`
	Subject        string  `json:"subject"`
	ExamDate       string  `json:"examDate"`
	PassPercentage float64 `json:"passPercentage"`
	AverageMarks   float64 `json:"averageMarks"`
	GeneratedBy    string  `json:"generatedBy"`
	Date           string  `json:"date"`
	Status         string  `json:"status"`
}

type CustomReportCustom struct {
	ID          string `json:"id"`
	ReportName  string `json:"reportName"`
	Description string `json:"description"`
	Category    string `json:"category"`
	CreatedBy   string `json:"createdBy"`
	Date        string `json:"date"`
	Status      string `json:"status"`
}

type CreateCustomReportCustomInput struct {
	ReportName  string `json:"reportName"`
	Description string `json:"description"`
	Category    string `json:"category"`
	CreatedBy   string `json:"createdBy"`
	Date        string `json:"date"`
	Status      string `json:"status"`
}

type UpdateCustomReportCustomInput struct {
	ID          string `json:"id"`
	ReportName  string `json:"reportName"`
	Description string `json:"description"`
	Category    string `json:"category"`
	CreatedBy   string `json:"createdBy"`
	Date        string `json:"date"`
	Status      string `json:"status"`
}

type TodayScheduleCustom struct {
	ID       string `json:"id"`
	Subject  string `json:"subject"`
	Class    string `json:"class"`
	Time     string `json:"time"`
	Duration string `json:"duration"`
	Room     string `json:"room"`
	Status   string `json:"status"`
}

type CreateTodayScheduleCustomInput struct {
	Subject  string `json:"subject"`
	Class    string `json:"class"`
	Time     string `json:"time"`
	Duration string `json:"duration"`
	Room     string `json:"room"`
	Status   string `json:"status"`
}

type UpdateTodayScheduleCustomInput struct {
	ID       string `json:"id"`
	Subject  string `json:"subject"`
	Class    string `json:"class"`
	Time     string `json:"time"`
	Duration string `json:"duration"`
	Room     string `json:"room"`
	Status   string `json:"status"`
}

type TeacherClassCustom struct {
	ID        string `json:"id"`
	ClassName string `json:"className"`
	Subject   string `json:"subject"`
	Time      string `json:"time"`
	RoomNo    string `json:"roomNo"`
}

type CreateTeacherClassCustomInput struct {
	ClassName string `json:"className"`
	Subject   string `json:"subject"`
	Time      string `json:"time"`
	RoomNo    string `json:"roomNo"`
}

type UpdateTeacherClassCustomInput struct {
	ID        string `json:"id"`
	ClassName string `json:"className"`
	Subject   string `json:"subject"`
	Time      string `json:"time"`
	RoomNo    string `json:"roomNo"`
}

type TeacherLessonPlanCustom struct {
	ID            string `json:"id"`
	Class         string `json:"class"`
	Subject       string `json:"subject"`
	Topic         string `json:"topic"`
	Date          string `json:"date"`
	Status        string `json:"status"`
	LessonDetails string `json:"lessonDetails"`
}

type CreateTeacherLessonPlanCustomInput struct {
	Class         string `json:"class"`
	Subject       string `json:"subject"`
	Topic         string `json:"topic"`
	Date          string `json:"date"`
	Status        string `json:"status"`
	LessonDetails string `json:"lessonDetails"`
}

type UpdateTeacherLessonPlanCustomInput struct {
	ID            string `json:"id"`
	Class         string `json:"class"`
	Subject       string `json:"subject"`
	Topic         string `json:"topic"`
	Date          string `json:"date"`
	Status        string `json:"status"`
	LessonDetails string `json:"lessonDetails"`
}

type StudentStudyMaterialCustom struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Subject     string `json:"subject"`
	Type        string `json:"type"`
	Date        string `json:"date"`
	DownloadURL string `json:"downloadUrl"`
}

type CreateStudentStudyMaterialCustomInput struct {
	Title       string `json:"title"`
	Subject     string `json:"subject"`
	Type        string `json:"type"`
	Date        string `json:"date"`
	DownloadURL string `json:"downloadUrl"`
}

type UpdateStudentStudyMaterialCustomInput struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Subject     string `json:"subject"`
	Type        string `json:"type"`
	Date        string `json:"date"`
	DownloadURL string `json:"downloadUrl"`
}

type TeacherStudyMaterialCustom struct {
	ID         string `json:"id"`
	Class      string `json:"class"`
	Subject    string `json:"subject"`
	Title      string `json:"title"`
	Type       string `json:"type"`
	UploadDate string `json:"uploadDate"`
	FileURL    string `json:"fileUrl"`
}

type CreateTeacherStudyMaterialCustomInput struct {
	Class      string `json:"class"`
	Subject    string `json:"subject"`
	Title      string `json:"title"`
	Type       string `json:"type"`
	UploadDate string `json:"uploadDate"`
	FileURL    string `json:"fileUrl"`
}

type UpdateTeacherStudyMaterialCustomInput struct {
	ID         string `json:"id"`
	Class      string `json:"class"`
	Subject    string `json:"subject"`
	Title      string `json:"title"`
	Type       string `json:"type"`
	UploadDate string `json:"uploadDate"`
	FileURL    string `json:"fileUrl"`
}

type TeacherAssignmentCustom struct {
	ID           string `json:"id"`
	Class        string `json:"class"`
	Subject      string `json:"subject"`
	Title        string `json:"title"`
	AssignedDate string `json:"assignedDate"`
	DueDate      string `json:"dueDate"`
	Status       string `json:"status"`
	Submissions  int    `json:"submissions"`
}

type CreateTeacherAssignmentCustomInput struct {
	Class        string `json:"class"`
	Subject      string `json:"subject"`
	Title        string `json:"title"`
	AssignedDate string `json:"assignedDate"`
	DueDate      string `json:"dueDate"`
	Status       string `json:"status"`
	Submissions  int    `json:"submissions"`
}

type UpdateTeacherAssignmentCustomInput struct {
	ID           string `json:"id"`
	Class        string `json:"class"`
	Subject      string `json:"subject"`
	Title        string `json:"title"`
	AssignedDate string `json:"assignedDate"`
	DueDate      string `json:"dueDate"`
	Status       string `json:"status"`
	Submissions  int    `json:"submissions"`
}

type TeacherClassStudentCustom struct {
	ID         string `json:"id"`
	RollNo     string `json:"rollNo"`
	Name       string `json:"name"`
	Gender     string `json:"gender"`
	ParentName string `json:"parentName"`
	Mobile     string `json:"mobile"`
	Email      string `json:"email"`
	Address    string `json:"address"`
}

type CreateTeacherClassStudentCustomInput struct {
	RollNo     string `json:"rollNo"`
	Name       string `json:"name"`
	Gender     string `json:"gender"`
	ParentName string `json:"parentName"`
	Mobile     string `json:"mobile"`
	Email      string `json:"email"`
	Address    string `json:"address"`
}

type UpdateTeacherClassStudentCustomInput struct {
	ID         string `json:"id"`
	RollNo     string `json:"rollNo"`
	Name       string `json:"name"`
	Gender     string `json:"gender"`
	ParentName string `json:"parentName"`
	Mobile     string `json:"mobile"`
	Email      string `json:"email"`
	Address    string `json:"address"`
}

type TeacherStudentAttendanceCustom struct {
	ID      string `json:"id"`
	RollNo  string `json:"rollNo"`
	Name    string `json:"name"`
	Date    string `json:"date"`
	Status  string `json:"status"`
	Remarks string `json:"remarks"`
}

type CreateTeacherStudentAttendanceCustomInput struct {
	RollNo  string `json:"rollNo"`
	Name    string `json:"name"`
	Date    string `json:"date"`
	Status  string `json:"status"`
	Remarks string `json:"remarks"`
}

type UpdateTeacherStudentAttendanceCustomInput struct {
	ID      string `json:"id"`
	RollNo  string `json:"rollNo"`
	Name    string `json:"name"`
	Date    string `json:"date"`
	Status  string `json:"status"`
	Remarks string `json:"remarks"`
}

type TeacherStudentPerformanceCustom struct {
	ID            string `json:"id"`
	RollNo        string `json:"rollNo"`
	Name          string `json:"name"`
	Subject       string `json:"subject"`
	InternalMarks int    `json:"internalMarks"`
	ExternalMarks int    `json:"externalMarks"`
	TotalMarks    int    `json:"totalMarks"`
	Grade         string `json:"grade"`
}

type CreateTeacherStudentPerformanceCustomInput struct {
	RollNo        string `json:"rollNo"`
	Name          string `json:"name"`
	Subject       string `json:"subject"`
	InternalMarks int    `json:"internalMarks"`
	ExternalMarks int    `json:"externalMarks"`
	TotalMarks    int    `json:"totalMarks"`
	Grade         string `json:"grade"`
}

type UpdateTeacherStudentPerformanceCustomInput struct {
	ID            string `json:"id"`
	RollNo        string `json:"rollNo"`
	Name          string `json:"name"`
	Subject       string `json:"subject"`
	InternalMarks int    `json:"internalMarks"`
	ExternalMarks int    `json:"externalMarks"`
	TotalMarks    int    `json:"totalMarks"`
	Grade         string `json:"grade"`
}

type TeacherMarksEntryCustom struct {
	ID            string `json:"id"`
	RollNo        string `json:"rollNo"`
	StudentName   string `json:"studentName"`
	Class         string `json:"class"`
	Subject       string `json:"subject"`
	MarksObtained int    `json:"marksObtained"`
	MaxMarks      int    `json:"maxMarks"`
	Status        string `json:"status"`
}

type CreateTeacherMarksEntryCustomInput struct {
	RollNo        string `json:"rollNo"`
	StudentName   string `json:"studentName"`
	Class         string `json:"class"`
	Subject       string `json:"subject"`
	MarksObtained int    `json:"marksObtained"`
	MaxMarks      int    `json:"maxMarks"`
	Status        string `json:"status"`
}

type UpdateTeacherMarksEntryCustomInput struct {
	ID            string `json:"id"`
	RollNo        string `json:"rollNo"`
	StudentName   string `json:"studentName"`
	Class         string `json:"class"`
	Subject       string `json:"subject"`
	MarksObtained int    `json:"marksObtained"`
	MaxMarks      int    `json:"maxMarks"`
	Status        string `json:"status"`
}

type TeacherGradeSubmissionCustom struct {
	ID             string `json:"id"`
	RollNo         string `json:"rollNo"`
	StudentName    string `json:"studentName"`
	AverageMarks   int    `json:"averageMarks"`
	Grade          string `json:"grade"`
	Status         string `json:"status"`
	SubmissionDate string `json:"submissionDate"`
}

type CreateTeacherGradeSubmissionCustomInput struct {
	RollNo         string `json:"rollNo"`
	StudentName    string `json:"studentName"`
	AverageMarks   int    `json:"averageMarks"`
	Grade          string `json:"grade"`
	Status         string `json:"status"`
	SubmissionDate string `json:"submissionDate"`
}

type UpdateTeacherGradeSubmissionCustomInput struct {
	ID             string `json:"id"`
	RollNo         string `json:"rollNo"`
	StudentName    string `json:"studentName"`
	AverageMarks   int    `json:"averageMarks"`
	Grade          string `json:"grade"`
	Status         string `json:"status"`
	SubmissionDate string `json:"submissionDate"`
}

type TeacherTimetableCustom struct {
	ID       string `json:"id"`
	Day      string `json:"day"`
	TimeSlot string `json:"timeSlot"`
	Subject  string `json:"subject"`
	Class    string `json:"class"`
	Room     string `json:"room"`
}

type CreateTeacherTimetableCustomInput struct {
	Day      string `json:"day"`
	TimeSlot string `json:"timeSlot"`
	Subject  string `json:"subject"`
	Class    string `json:"class"`
	Room     string `json:"room"`
}

type UpdateTeacherTimetableCustomInput struct {
	ID       string `json:"id"`
	Day      string `json:"day"`
	TimeSlot string `json:"timeSlot"`
	Subject  string `json:"subject"`
	Class    string `json:"class"`
	Room     string `json:"room"`
}

type TeacherSubstitutionRequestCustom struct {
	ID       string `json:"id"`
	Date     string `json:"date"`
	TimeSlot string `json:"timeSlot"`
	Class    string `json:"class"`
	Subject  string `json:"subject"`
	Reason   string `json:"reason"`
	Status   string `json:"status"`
}

type CreateTeacherSubstitutionRequestCustomInput struct {
	Date     string `json:"date"`
	TimeSlot string `json:"timeSlot"`
	Class    string `json:"class"`
	Subject  string `json:"subject"`
	Reason   string `json:"reason"`
	Status   string `json:"status"`
}

type UpdateTeacherSubstitutionRequestCustomInput struct {
	ID       string `json:"id"`
	Date     string `json:"date"`
	TimeSlot string `json:"timeSlot"`
	Class    string `json:"class"`
	Subject  string `json:"subject"`
	Reason   string `json:"reason"`
	Status   string `json:"status"`
}

type TeacherNoticeCustom struct {
	ID       string `json:"id"`
	Title    string `json:"title"`
	Date     string `json:"date"`
	Category string `json:"category"`
	Details  string `json:"details"`
}

type CreateTeacherNoticeCustomInput struct {
	Title    string `json:"title"`
	Date     string `json:"date"`
	Category string `json:"category"`
	Details  string `json:"details"`
}

type UpdateTeacherNoticeCustomInput struct {
	ID       string `json:"id"`
	Title    string `json:"title"`
	Date     string `json:"date"`
	Category string `json:"category"`
	Details  string `json:"details"`
}

type TeacherAnnouncementCustom struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Date        string `json:"date"`
	Target      string `json:"target"`
	Description string `json:"description"`
}

type CreateTeacherAnnouncementCustomInput struct {
	Title       string `json:"title"`
	Date        string `json:"date"`
	Target      string `json:"target"`
	Description string `json:"description"`
}

type UpdateTeacherAnnouncementCustomInput struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Date        string `json:"date"`
	Target      string `json:"target"`
	Description string `json:"description"`
}

type TeacherDailyAttendanceCustom struct {
	ID          string `json:"id"`
	RollNo      string `json:"rollNo"`
	StudentName string `json:"studentName"`
	Class       string `json:"class"`
	Date        string `json:"date"`
	Status      string `json:"status"`
	Note        string `json:"note"`
}

type CreateTeacherDailyAttendanceCustomInput struct {
	RollNo      string `json:"rollNo"`
	StudentName string `json:"studentName"`
	Class       string `json:"class"`
	Date        string `json:"date"`
	Status      string `json:"status"`
	Note        string `json:"note"`
}

type UpdateTeacherDailyAttendanceCustomInput struct {
	ID          string `json:"id"`
	RollNo      string `json:"rollNo"`
	StudentName string `json:"studentName"`
	Class       string `json:"class"`
	Date        string `json:"date"`
	Status      string `json:"status"`
	Note        string `json:"note"`
}

type TeacherAttendanceSummaryCustom struct {
	ID                   string `json:"id"`
	Class                string `json:"class"`
	Subject              string `json:"subject"`
	TotalStudents        int    `json:"totalStudents"`
	Present              int    `json:"present"`
	Absent               int    `json:"absent"`
	OnLeave              int    `json:"onLeave"`
	AttendancePercentage string `json:"attendancePercentage"`
	Date                 string `json:"date"`
}

type CreateTeacherAttendanceSummaryCustomInput struct {
	Class                string `json:"class"`
	Subject              string `json:"subject"`
	TotalStudents        int    `json:"totalStudents"`
	Present              int    `json:"present"`
	Absent               int    `json:"absent"`
	OnLeave              int    `json:"onLeave"`
	AttendancePercentage string `json:"attendancePercentage"`
	Date                 string `json:"date"`
}

type UpdateTeacherAttendanceSummaryCustomInput struct {
	ID                   string `json:"id"`
	Class                string `json:"class"`
	Subject              string `json:"subject"`
	TotalStudents        int    `json:"totalStudents"`
	Present              int    `json:"present"`
	Absent               int    `json:"absent"`
	OnLeave              int    `json:"onLeave"`
	AttendancePercentage string `json:"attendancePercentage"`
	Date                 string `json:"date"`
}

type TeacherLeaveStatusCustom struct {
	ID        string `json:"id"`
	LeaveType string `json:"leaveType"`
	StartDate string `json:"startDate"`
	EndDate   string `json:"endDate"`
	Days      int    `json:"days"`
	ApplyDate string `json:"applyDate"`
	Status    string `json:"status"`
	Reason    string `json:"reason"`
}

type CreateTeacherLeaveStatusCustomInput struct {
	LeaveType string `json:"leaveType"`
	StartDate string `json:"startDate"`
	EndDate   string `json:"endDate"`
	Days      int    `json:"days"`
	ApplyDate string `json:"applyDate"`
	Status    string `json:"status"`
	Reason    string `json:"reason"`
}

type UpdateTeacherLeaveStatusCustomInput struct {
	ID        string `json:"id"`
	LeaveType string `json:"leaveType"`
	StartDate string `json:"startDate"`
	EndDate   string `json:"endDate"`
	Days      int    `json:"days"`
	ApplyDate string `json:"applyDate"`
	Status    string `json:"status"`
	Reason    string `json:"reason"`
}

type TeacherLectureCustom struct {
	ID                    string `json:"id"`
	SubjectName           string `json:"subjectName"`
	Class                 string `json:"class"`
	Date                  string `json:"date"`
	Time                  string `json:"time"`
	Status                string `json:"status"`
	TeacherID             string `json:"teacher_id"`
	SubjectID             string `json:"subject_id"`
	StudentGroup          string `json:"student_group"`
	Duration              int    `json:"duration"`
	Location              string `json:"location"`
	AttendanceCount       int    `json:"attendance_count"`
	CreatedAt             string `json:"created_at"`
	UpdatedAt             string `json:"updated_at"`
	ReasonForCancellation string `json:"reason_for_cancellation"`
}

type CreateTeacherLectureCustomInput struct {
	SubjectName           string `json:"subjectName"`
	Class                 string `json:"class"`
	Date                  string `json:"date"`
	Time                  string `json:"time"`
	Status                string `json:"status"`
	TeacherID             string `json:"teacher_id"`
	SubjectID             string `json:"subject_id"`
	StudentGroup          string `json:"student_group"`
	Duration              int    `json:"duration"`
	Location              string `json:"location"`
	AttendanceCount       int    `json:"attendance_count"`
	ReasonForCancellation string `json:"reason_for_cancellation"`
}

type UpdateTeacherLectureCustomInput struct {
	ID                    string `json:"id"`
	SubjectName           string `json:"subjectName"`
	Class                 string `json:"class"`
	Date                  string `json:"date"`
	Time                  string `json:"time"`
	Status                string `json:"status"`
	TeacherID             string `json:"teacher_id"`
	SubjectID             string `json:"subject_id"`
	StudentGroup          string `json:"student_group"`
	Duration              int    `json:"duration"`
	Location              string `json:"location"`
	AttendanceCount       int    `json:"attendance_count"`
	ReasonForCancellation string `json:"reason_for_cancellation"`
}

type StudentHomeworkCustom struct {
	ID             string `json:"id"`
	Class          string `json:"class"`
	Section        string `json:"section"`
	Subject        string `json:"subject"`
	HomeworkTitle  string `json:"homeworkTitle"`
	AssignedBy     string `json:"assignedBy"`
	HomeworkDate   string `json:"homeworkDate"`
	SubmissionDate string `json:"submissionDate"`
	EvaluationDate string `json:"evaluationDate"`
	Status         string `json:"status"`
	Grade          string `json:"grade"`
	Feedback       string `json:"feedback"`
	Attachments    string `json:"attachments"`
	LateSubmission bool   `json:"lateSubmission"`
}

type CreateStudentHomeworkCustomInput struct {
	Class          string `json:"class"`
	Section        string `json:"section"`
	Subject        string `json:"subject"`
	HomeworkTitle  string `json:"homeworkTitle"`
	AssignedBy     string `json:"assignedBy"`
	HomeworkDate   string `json:"homeworkDate"`
	SubmissionDate string `json:"submissionDate"`
	EvaluationDate string `json:"evaluationDate"`
	Status         string `json:"status"`
	Grade          string `json:"grade"`
	Feedback       string `json:"feedback"`
	Attachments    string `json:"attachments"`
	LateSubmission bool   `json:"lateSubmission"`
}

type UpdateStudentHomeworkCustomInput struct {
	ID             string `json:"id"`
	Class          string `json:"class"`
	Section        string `json:"section"`
	Subject        string `json:"subject"`
	HomeworkTitle  string `json:"homeworkTitle"`
	AssignedBy     string `json:"assignedBy"`
	HomeworkDate   string `json:"homeworkDate"`
	SubmissionDate string `json:"submissionDate"`
	EvaluationDate string `json:"evaluationDate"`
	Status         string `json:"status"`
	Grade          string `json:"grade"`
	Feedback       string `json:"feedback"`
	Attachments    string `json:"attachments"`
	LateSubmission bool   `json:"lateSubmission"`
}

type StudentTimetableCustom struct {
	ID         string `json:"id"`
	Day        string `json:"day"`
	DateLabel  string `json:"date_label"`
	Subject    string `json:"subject"`
	Time       string `json:"time"`
	Room       string `json:"room"`
	Teacher    string `json:"teacher"`
	Type       string `json:"type"`
	ColorClass string `json:"color_class"`
	Icon       string `json:"icon"`
}

type CreateStudentTimetableCustomInput struct {
	Day        string `json:"day"`
	DateLabel  string `json:"date_label"`
	Subject    string `json:"subject"`
	Time       string `json:"time"`
	Room       string `json:"room"`
	Teacher    string `json:"teacher"`
	Type       string `json:"type"`
	ColorClass string `json:"color_class"`
	Icon       string `json:"icon"`
}

type UpdateStudentTimetableCustomInput struct {
	ID         string `json:"id"`
	Day        string `json:"day"`
	DateLabel  string `json:"date_label"`
	Subject    string `json:"subject"`
	Time       string `json:"time"`
	Room       string `json:"room"`
	Teacher    string `json:"teacher"`
	Type       string `json:"type"`
	ColorClass string `json:"color_class"`
	Icon       string `json:"icon"`
}

type StudentSyllabusCustom struct {
	ID          string `json:"id"`
	Subject     string `json:"subject"`
	Class       string `json:"class"`
	Title       string `json:"title"`
	Type        string `json:"type"`
	Date        string `json:"date"`
	DownloadURL string `json:"download_url"`
}

type CreateStudentSyllabusCustomInput struct {
	Subject     string `json:"subject"`
	Class       string `json:"class"`
	Title       string `json:"title"`
	Type        string `json:"type"`
	Date        string `json:"date"`
	DownloadURL string `json:"download_url"`
}

type UpdateStudentSyllabusCustomInput struct {
	ID          string `json:"id"`
	Subject     string `json:"subject"`
	Class       string `json:"class"`
	Title       string `json:"title"`
	Type        string `json:"type"`
	Date        string `json:"date"`
	DownloadURL string `json:"download_url"`
}

type TeacherSubjectTaughtCustom struct {
	ID            string `json:"id"`
	SubjectName   string `json:"subject_name"`
	Class         string `json:"class"`
	TotalStudents int    `json:"total_students"`
}

type CreateTeacherSubjectTaughtCustomInput struct {
	SubjectName   string `json:"subject_name"`
	Class         string `json:"class"`
	TotalStudents int    `json:"total_students"`
}

type UpdateTeacherSubjectTaughtCustomInput struct {
	ID            string `json:"id"`
	SubjectName   string `json:"subject_name"`
	Class         string `json:"class"`
	TotalStudents int    `json:"total_students"`
}

type StudentHallTicketCustom struct {
	ID          string `json:"id"`
	ExamName    string `json:"exam_name"`
	Subject     string `json:"subject"`
	ExamDate    string `json:"exam_date"`
	StartTime   string `json:"start_time"`
	RoomNo      string `json:"room_no"`
	RollNo      string `json:"roll_no"`
	DownloadURL string `json:"download_url"`
}

type CreateStudentHallTicketCustomInput struct {
	ExamName    string `json:"exam_name"`
	Subject     string `json:"subject"`
	ExamDate    string `json:"exam_date"`
	StartTime   string `json:"start_time"`
	RoomNo      string `json:"room_no"`
	RollNo      string `json:"roll_no"`
	DownloadURL string `json:"download_url"`
}

type UpdateStudentHallTicketCustomInput struct {
	ID          string `json:"id"`
	ExamName    string `json:"exam_name"`
	Subject     string `json:"subject"`
	ExamDate    string `json:"exam_date"`
	StartTime   string `json:"start_time"`
	RoomNo      string `json:"room_no"`
	RollNo      string `json:"roll_no"`
	DownloadURL string `json:"download_url"`
}

type StudentResultCustom struct {
	ID            string  `json:"id"`
	ExamName      string  `json:"exam_name"`
	TotalSubjects int     `json:"total_subjects"`
	TotalMarks    int     `json:"total_marks"`
	ObtainedMarks int     `json:"obtained_marks"`
	Percentage    float64 `json:"percentage"`
	Grade         string  `json:"grade"`
	ResultStatus  string  `json:"result_status"`
	PublishedDate string  `json:"published_date"`
}

type CreateStudentResultCustomInput struct {
	ExamName      string  `json:"exam_name"`
	TotalSubjects int     `json:"total_subjects"`
	TotalMarks    int     `json:"total_marks"`
	ObtainedMarks int     `json:"obtained_marks"`
	Percentage    float64 `json:"percentage"`
	Grade         string  `json:"grade"`
	ResultStatus  string  `json:"result_status"`
	PublishedDate string  `json:"published_date"`
}

type UpdateStudentResultCustomInput struct {
	ID            string  `json:"id"`
	ExamName      string  `json:"exam_name"`
	TotalSubjects int     `json:"total_subjects"`
	TotalMarks    int     `json:"total_marks"`
	ObtainedMarks int     `json:"obtained_marks"`
	Percentage    float64 `json:"percentage"`
	Grade         string  `json:"grade"`
	ResultStatus  string  `json:"result_status"`
	PublishedDate string  `json:"published_date"`
}

type StudentReportCardCustom struct {
	ID            string  `json:"id"`
	AcademicYear  string  `json:"academic_year"`
	ClassName     string  `json:"class_name"`
	ExamName      string  `json:"exam_name"`
	TotalMarks    int     `json:"total_marks"`
	ObtainedMarks int     `json:"obtained_marks"`
	Percentage    float64 `json:"percentage"`
	Grade         string  `json:"grade"`
	Result        string  `json:"result"`
	DownloadURL   string  `json:"download_url"`
}

type CreateStudentReportCardCustomInput struct {
	AcademicYear  string  `json:"academic_year"`
	ClassName     string  `json:"class_name"`
	ExamName      string  `json:"exam_name"`
	TotalMarks    int     `json:"total_marks"`
	ObtainedMarks int     `json:"obtained_marks"`
	Percentage    float64 `json:"percentage"`
	Grade         string  `json:"grade"`
	Result        string  `json:"result"`
	DownloadURL   string  `json:"download_url"`
}

type UpdateStudentReportCardCustomInput struct {
	ID            string  `json:"id"`
	AcademicYear  string  `json:"academic_year"`
	ClassName     string  `json:"class_name"`
	ExamName      string  `json:"exam_name"`
	TotalMarks    int     `json:"total_marks"`
	ObtainedMarks int     `json:"obtained_marks"`
	Percentage    float64 `json:"percentage"`
	Grade         string  `json:"grade"`
	Result        string  `json:"result"`
	DownloadURL   string  `json:"download_url"`
}

type StudentMonthlySummaryCustom struct {
	ID         string  `json:"id"`
	Month      string  `json:"month"`
	TotalDays  int     `json:"total_days"`
	Present    int     `json:"present"`
	Absent     int     `json:"absent"`
	Late       int     `json:"late"`
	HalfDay    int     `json:"half_day"`
	Percentage float64 `json:"percentage"`
}

type CreateStudentMonthlySummaryCustomInput struct {
	Month      string  `json:"month"`
	TotalDays  int     `json:"total_days"`
	Present    int     `json:"present"`
	Absent     int     `json:"absent"`
	Late       int     `json:"late"`
	HalfDay    int     `json:"half_day"`
	Percentage float64 `json:"percentage"`
}

type UpdateStudentMonthlySummaryCustomInput struct {
	ID         string  `json:"id"`
	Month      string  `json:"month"`
	TotalDays  int     `json:"total_days"`
	Present    int     `json:"present"`
	Absent     int     `json:"absent"`
	Late       int     `json:"late"`
	HalfDay    int     `json:"half_day"`
	Percentage float64 `json:"percentage"`
}

type StudentMyAttendanceCustom struct {
	ID           string `json:"id"`
	Date         string `json:"date"`
	Status       string `json:"status"`
	CheckIn      string `json:"check_in"`
	CheckOut     string `json:"check_out"`
	WorkingHours string `json:"working_hours"`
	Remarks      string `json:"remarks"`
}

type CreateStudentMyAttendanceCustomInput struct {
	Date         string `json:"date"`
	Status       string `json:"status"`
	CheckIn      string `json:"check_in"`
	CheckOut     string `json:"check_out"`
	WorkingHours string `json:"working_hours"`
	Remarks      string `json:"remarks"`
}

type UpdateStudentMyAttendanceCustomInput struct {
	ID           string `json:"id"`
	Date         string `json:"date"`
	Status       string `json:"status"`
	CheckIn      string `json:"check_in"`
	CheckOut     string `json:"check_out"`
	WorkingHours string `json:"working_hours"`
	Remarks      string `json:"remarks"`
}

type StudentLeaveRequestCustom struct {
	ID        string `json:"id"`
	ClassName string `json:"class_name"`
	Section   string `json:"section"`
	ApplyDate string `json:"apply_date"`
	FromDate  string `json:"from_date"`
	ToDate    string `json:"to_date"`
	Reason    string `json:"reason"`
	Status    string `json:"status"`
}

type CreateStudentLeaveRequestCustomInput struct {
	ClassName string `json:"class_name"`
	Section   string `json:"section"`
	ApplyDate string `json:"apply_date"`
	FromDate  string `json:"from_date"`
	ToDate    string `json:"to_date"`
	Reason    string `json:"reason"`
	Status    string `json:"status"`
}

type UpdateStudentLeaveRequestCustomInput struct {
	ID        string `json:"id"`
	ClassName string `json:"class_name"`
	Section   string `json:"section"`
	ApplyDate string `json:"apply_date"`
	FromDate  string `json:"from_date"`
	ToDate    string `json:"to_date"`
	Reason    string `json:"reason"`
	Status    string `json:"status"`
}

type StudentFeeReceiptCustom struct {
	ID          string `json:"id"`
	ReceiptNo   string `json:"receipt_no"`
	FeeType     string `json:"fee_type"`
	PaymentDate string `json:"payment_date"`
	PaidAmount  int    `json:"paid_amount"`
	PaymentMode string `json:"payment_mode"`
	Status      string `json:"status"`
}

type CreateStudentFeeReceiptCustomInput struct {
	ReceiptNo   string `json:"receipt_no"`
	FeeType     string `json:"fee_type"`
	PaymentDate string `json:"payment_date"`
	PaidAmount  int    `json:"paid_amount"`
	PaymentMode string `json:"payment_mode"`
	Status      string `json:"status"`
}

type UpdateStudentFeeReceiptCustomInput struct {
	ID          string `json:"id"`
	ReceiptNo   string `json:"receipt_no"`
	FeeType     string `json:"fee_type"`
	PaymentDate string `json:"payment_date"`
	PaidAmount  int    `json:"paid_amount"`
	PaymentMode string `json:"payment_mode"`
	Status      string `json:"status"`
}

type StudentDueFeeCustom struct {
	ID          string `json:"id"`
	FeeType     string `json:"fee_type"`
	DueDate     string `json:"due_date"`
	TotalAmount int    `json:"total_amount"`
	DueAmount   int    `json:"due_amount"`
	LateFee     int    `json:"late_fee"`
	TotalDue    int    `json:"total_due"`
}

type CreateStudentDueFeeCustomInput struct {
	FeeType     string `json:"fee_type"`
	DueDate     string `json:"due_date"`
	TotalAmount int    `json:"total_amount"`
	DueAmount   int    `json:"due_amount"`
	LateFee     int    `json:"late_fee"`
	TotalDue    int    `json:"total_due"`
}

type UpdateStudentDueFeeCustomInput struct {
	ID          string `json:"id"`
	FeeType     string `json:"fee_type"`
	DueDate     string `json:"due_date"`
	TotalAmount int    `json:"total_amount"`
	DueAmount   int    `json:"due_amount"`
	LateFee     int    `json:"late_fee"`
	TotalDue    int    `json:"total_due"`
}

type StudentFeeDetailCustom struct {
	ID            string `json:"id"`
	FeeType       string `json:"fee_type"`
	DueDate       string `json:"due_date"`
	Amount        int    `json:"amount"`
	PaidAmount    int    `json:"paid_amount"`
	BalanceAmount int    `json:"balance_amount"`
	Status        string `json:"status"`
	PaymentMethod string `json:"payment_method"`
}

type CreateStudentFeeDetailCustomInput struct {
	FeeType       string `json:"fee_type"`
	DueDate       string `json:"due_date"`
	Amount        int    `json:"amount"`
	PaidAmount    int    `json:"paid_amount"`
	BalanceAmount int    `json:"balance_amount"`
	Status        string `json:"status"`
	PaymentMethod string `json:"payment_method"`
}

type UpdateStudentFeeDetailCustomInput struct {
	ID            string `json:"id"`
	FeeType       string `json:"fee_type"`
	DueDate       string `json:"due_date"`
	Amount        int    `json:"amount"`
	PaidAmount    int    `json:"paid_amount"`
	BalanceAmount int    `json:"balance_amount"`
	Status        string `json:"status"`
	PaymentMethod string `json:"payment_method"`
}

type StudentOnlinePaymentCustom struct {
	ID             string `json:"id"`
	TransactionID  string `json:"transaction_id"`
	FeeType        string `json:"fee_type"`
	PaymentDate    string `json:"payment_date"`
	Amount         int    `json:"amount"`
	PaymentGateway string `json:"payment_gateway"`
	Status         string `json:"status"`
}

type CreateStudentOnlinePaymentCustomInput struct {
	TransactionID  string `json:"transaction_id"`
	FeeType        string `json:"fee_type"`
	PaymentDate    string `json:"payment_date"`
	Amount         int    `json:"amount"`
	PaymentGateway string `json:"payment_gateway"`
	Status         string `json:"status"`
}

type UpdateStudentOnlinePaymentCustomInput struct {
	ID             string `json:"id"`
	TransactionID  string `json:"transaction_id"`
	FeeType        string `json:"fee_type"`
	PaymentDate    string `json:"payment_date"`
	Amount         int    `json:"amount"`
	PaymentGateway string `json:"payment_gateway"`
	Status         string `json:"status"`
}

type StudentMyIssuedBookCustom struct {
	ID         string `json:"id"`
	BookTitle  string `json:"book_title"`
	Author     string `json:"author"`
	IsbnNo     string `json:"isbn_no"`
	IssueDate  string `json:"issue_date"`
	DueDate    string `json:"due_date"`
	ReturnDate string `json:"return_date"`
	Status     string `json:"status"`
}

type CreateStudentMyIssuedBookCustomInput struct {
	BookTitle  string `json:"book_title"`
	Author     string `json:"author"`
	IsbnNo     string `json:"isbn_no"`
	IssueDate  string `json:"issue_date"`
	DueDate    string `json:"due_date"`
	ReturnDate string `json:"return_date"`
	Status     string `json:"status"`
}

type UpdateStudentMyIssuedBookCustomInput struct {
	ID         string `json:"id"`
	BookTitle  string `json:"book_title"`
	Author     string `json:"author"`
	IsbnNo     string `json:"isbn_no"`
	IssueDate  string `json:"issue_date"`
	DueDate    string `json:"due_date"`
	ReturnDate string `json:"return_date"`
	Status     string `json:"status"`
}

type StudentDueDateCustom struct {
	ID            string `json:"id"`
	BookTitle     string `json:"book_title"`
	IsbnNo        string `json:"isbn_no"`
	DueDate       string `json:"due_date"`
	DaysRemaining int    `json:"days_remaining"`
	FineAmount    int    `json:"fine_amount"`
	Status        string `json:"status"`
}

type CreateStudentDueDateCustomInput struct {
	BookTitle     string `json:"book_title"`
	IsbnNo        string `json:"isbn_no"`
	DueDate       string `json:"due_date"`
	DaysRemaining int    `json:"days_remaining"`
	FineAmount    int    `json:"fine_amount"`
	Status        string `json:"status"`
}

type UpdateStudentDueDateCustomInput struct {
	ID            string `json:"id"`
	BookTitle     string `json:"book_title"`
	IsbnNo        string `json:"isbn_no"`
	DueDate       string `json:"due_date"`
	DaysRemaining int    `json:"days_remaining"`
	FineAmount    int    `json:"fine_amount"`
	Status        string `json:"status"`
}

type StudentBookHistoryCustom struct {
	ID         string `json:"id"`
	BookTitle  string `json:"book_title"`
	Author     string `json:"author"`
	IsbnNo     string `json:"isbn_no"`
	IssueDate  string `json:"issue_date"`
	ReturnDate string `json:"return_date"`
	Category   string `json:"category"`
}

type CreateStudentBookHistoryCustomInput struct {
	BookTitle  string `json:"book_title"`
	Author     string `json:"author"`
	IsbnNo     string `json:"isbn_no"`
	IssueDate  string `json:"issue_date"`
	ReturnDate string `json:"return_date"`
	Category   string `json:"category"`
}

type UpdateStudentBookHistoryCustomInput struct {
	ID         string `json:"id"`
	BookTitle  string `json:"book_title"`
	Author     string `json:"author"`
	IsbnNo     string `json:"isbn_no"`
	IssueDate  string `json:"issue_date"`
	ReturnDate string `json:"return_date"`
	Category   string `json:"category"`
}

type StudentMyRouteCustom struct {
	ID          string `json:"id"`
	RouteName   string `json:"route_name"`
	StopName    string `json:"stop_name"`
	PickupTime  string `json:"pickup_time"`
	DropTime    string `json:"drop_time"`
	Distance    string `json:"distance"`
	MonthlyFees int    `json:"monthly_fees"`
}

type CreateStudentMyRouteCustomInput struct {
	RouteName   string `json:"route_name"`
	StopName    string `json:"stop_name"`
	PickupTime  string `json:"pickup_time"`
	DropTime    string `json:"drop_time"`
	Distance    string `json:"distance"`
	MonthlyFees int    `json:"monthly_fees"`
}

type UpdateStudentMyRouteCustomInput struct {
	ID          string `json:"id"`
	RouteName   string `json:"route_name"`
	StopName    string `json:"stop_name"`
	PickupTime  string `json:"pickup_time"`
	DropTime    string `json:"drop_time"`
	Distance    string `json:"distance"`
	MonthlyFees int    `json:"monthly_fees"`
}

type StudentVehicleDetailCustom struct {
	ID            string `json:"id"`
	VehicleNo     string `json:"vehicle_no"`
	VehicleModel  string `json:"vehicle_model"`
	DriverName    string `json:"driver_name"`
	DriverContact string `json:"driver_contact"`
	VehicleType   string `json:"vehicle_type"`
	Capacity      int    `json:"capacity"`
}

type CreateStudentVehicleDetailCustomInput struct {
	VehicleNo     string `json:"vehicle_no"`
	VehicleModel  string `json:"vehicle_model"`
	DriverName    string `json:"driver_name"`
	DriverContact string `json:"driver_contact"`
	VehicleType   string `json:"vehicle_type"`
	Capacity      int    `json:"capacity"`
}

type UpdateStudentVehicleDetailCustomInput struct {
	ID            string `json:"id"`
	VehicleNo     string `json:"vehicle_no"`
	VehicleModel  string `json:"vehicle_model"`
	DriverName    string `json:"driver_name"`
	DriverContact string `json:"driver_contact"`
	VehicleType   string `json:"vehicle_type"`
	Capacity      int    `json:"capacity"`
}

type StudentHostelRoomDetailCustom struct {
	ID           string `json:"id"`
	RoomNo       string `json:"room_no"`
	RoomType     string `json:"room_type"`
	HostelName   string `json:"hostel_name"`
	NoOfBeds     int    `json:"no_of_beds"`
	Availability string `json:"availability"`
	Rent         int    `json:"rent"`
}

type CreateStudentHostelRoomDetailCustomInput struct {
	RoomNo       string `json:"room_no"`
	RoomType     string `json:"room_type"`
	HostelName   string `json:"hostel_name"`
	NoOfBeds     int    `json:"no_of_beds"`
	Availability string `json:"availability"`
	Rent         int    `json:"rent"`
}

type UpdateStudentHostelRoomDetailCustomInput struct {
	ID           string `json:"id"`
	RoomNo       string `json:"room_no"`
	RoomType     string `json:"room_type"`
	HostelName   string `json:"hostel_name"`
	NoOfBeds     int    `json:"no_of_beds"`
	Availability string `json:"availability"`
	Rent         int    `json:"rent"`
}

type StudentHostelFeeCustom struct {
	ID            string `json:"id"`
	InvoiceNo     string `json:"invoice_no"`
	RoomNo        string `json:"room_no"`
	HostelName    string `json:"hostel_name"`
	FeeType       string `json:"fee_type"`
	Amount        int    `json:"amount"`
	Date          string `json:"date"`
	PaymentStatus string `json:"payment_status"`
}

type CreateStudentHostelFeeCustomInput struct {
	InvoiceNo     string `json:"invoice_no"`
	RoomNo        string `json:"room_no"`
	HostelName    string `json:"hostel_name"`
	FeeType       string `json:"fee_type"`
	Amount        int    `json:"amount"`
	Date          string `json:"date"`
	PaymentStatus string `json:"payment_status"`
}

type UpdateStudentHostelFeeCustomInput struct {
	ID            string `json:"id"`
	InvoiceNo     string `json:"invoice_no"`
	RoomNo        string `json:"room_no"`
	HostelName    string `json:"hostel_name"`
	FeeType       string `json:"fee_type"`
	Amount        int    `json:"amount"`
	Date          string `json:"date"`
	PaymentStatus string `json:"payment_status"`
}

type StudentHostelComplaintCustom struct {
	ID             string `json:"id"`
	ComplaintTitle string `json:"complaint_title"`
	ComplaintType  string `json:"complaint_type"`
	Date           string `json:"date"`
	Description    string `json:"description"`
	Status         string `json:"status"`
}

type CreateStudentHostelComplaintCustomInput struct {
	ComplaintTitle string `json:"complaint_title"`
	ComplaintType  string `json:"complaint_type"`
	Date           string `json:"date"`
	Description    string `json:"description"`
	Status         string `json:"status"`
}

type UpdateStudentHostelComplaintCustomInput struct {
	ID             string `json:"id"`
	ComplaintTitle string `json:"complaint_title"`
	ComplaintType  string `json:"complaint_type"`
	Date           string `json:"date"`
	Description    string `json:"description"`
	Status         string `json:"status"`
}
