// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package main

type LoginInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token string `json:"token"`
	Role  string `json:"role"`
}
