// Code generated by ent, DO NOT EDIT.

package feestructure

import (
	"go-seed/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldLTE(FieldID, id))
}

// ClassID applies equality check predicate on the "class_id" field. It's identical to ClassIDEQ.
func ClassID(v uuid.UUID) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldEQ(FieldClassID, v))
}

// AcademicYearID applies equality check predicate on the "academic_year_id" field. It's identical to AcademicYearIDEQ.
func AcademicYearID(v uuid.UUID) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldEQ(FieldAcademicYearID, v))
}

// FeeLabel applies equality check predicate on the "fee_label" field. It's identical to FeeLabelEQ.
func FeeLabel(v string) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldEQ(FieldFeeLabel, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldEQ(FieldAmount, v))
}

// DueDate applies equality check predicate on the "due_date" field. It's identical to DueDateEQ.
func DueDate(v time.Time) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldEQ(FieldDueDate, v))
}

// ClassIDEQ applies the EQ predicate on the "class_id" field.
func ClassIDEQ(v uuid.UUID) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldEQ(FieldClassID, v))
}

// ClassIDNEQ applies the NEQ predicate on the "class_id" field.
func ClassIDNEQ(v uuid.UUID) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldNEQ(FieldClassID, v))
}

// ClassIDIn applies the In predicate on the "class_id" field.
func ClassIDIn(vs ...uuid.UUID) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldIn(FieldClassID, vs...))
}

// ClassIDNotIn applies the NotIn predicate on the "class_id" field.
func ClassIDNotIn(vs ...uuid.UUID) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldNotIn(FieldClassID, vs...))
}

// AcademicYearIDEQ applies the EQ predicate on the "academic_year_id" field.
func AcademicYearIDEQ(v uuid.UUID) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldEQ(FieldAcademicYearID, v))
}

// AcademicYearIDNEQ applies the NEQ predicate on the "academic_year_id" field.
func AcademicYearIDNEQ(v uuid.UUID) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldNEQ(FieldAcademicYearID, v))
}

// AcademicYearIDIn applies the In predicate on the "academic_year_id" field.
func AcademicYearIDIn(vs ...uuid.UUID) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldIn(FieldAcademicYearID, vs...))
}

// AcademicYearIDNotIn applies the NotIn predicate on the "academic_year_id" field.
func AcademicYearIDNotIn(vs ...uuid.UUID) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldNotIn(FieldAcademicYearID, vs...))
}

// FeeLabelEQ applies the EQ predicate on the "fee_label" field.
func FeeLabelEQ(v string) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldEQ(FieldFeeLabel, v))
}

// FeeLabelNEQ applies the NEQ predicate on the "fee_label" field.
func FeeLabelNEQ(v string) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldNEQ(FieldFeeLabel, v))
}

// FeeLabelIn applies the In predicate on the "fee_label" field.
func FeeLabelIn(vs ...string) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldIn(FieldFeeLabel, vs...))
}

// FeeLabelNotIn applies the NotIn predicate on the "fee_label" field.
func FeeLabelNotIn(vs ...string) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldNotIn(FieldFeeLabel, vs...))
}

// FeeLabelGT applies the GT predicate on the "fee_label" field.
func FeeLabelGT(v string) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldGT(FieldFeeLabel, v))
}

// FeeLabelGTE applies the GTE predicate on the "fee_label" field.
func FeeLabelGTE(v string) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldGTE(FieldFeeLabel, v))
}

// FeeLabelLT applies the LT predicate on the "fee_label" field.
func FeeLabelLT(v string) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldLT(FieldFeeLabel, v))
}

// FeeLabelLTE applies the LTE predicate on the "fee_label" field.
func FeeLabelLTE(v string) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldLTE(FieldFeeLabel, v))
}

// FeeLabelContains applies the Contains predicate on the "fee_label" field.
func FeeLabelContains(v string) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldContains(FieldFeeLabel, v))
}

// FeeLabelHasPrefix applies the HasPrefix predicate on the "fee_label" field.
func FeeLabelHasPrefix(v string) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldHasPrefix(FieldFeeLabel, v))
}

// FeeLabelHasSuffix applies the HasSuffix predicate on the "fee_label" field.
func FeeLabelHasSuffix(v string) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldHasSuffix(FieldFeeLabel, v))
}

// FeeLabelEqualFold applies the EqualFold predicate on the "fee_label" field.
func FeeLabelEqualFold(v string) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldEqualFold(FieldFeeLabel, v))
}

// FeeLabelContainsFold applies the ContainsFold predicate on the "fee_label" field.
func FeeLabelContainsFold(v string) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldContainsFold(FieldFeeLabel, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldLTE(FieldAmount, v))
}

// DueDateEQ applies the EQ predicate on the "due_date" field.
func DueDateEQ(v time.Time) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldEQ(FieldDueDate, v))
}

// DueDateNEQ applies the NEQ predicate on the "due_date" field.
func DueDateNEQ(v time.Time) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldNEQ(FieldDueDate, v))
}

// DueDateIn applies the In predicate on the "due_date" field.
func DueDateIn(vs ...time.Time) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldIn(FieldDueDate, vs...))
}

// DueDateNotIn applies the NotIn predicate on the "due_date" field.
func DueDateNotIn(vs ...time.Time) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldNotIn(FieldDueDate, vs...))
}

// DueDateGT applies the GT predicate on the "due_date" field.
func DueDateGT(v time.Time) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldGT(FieldDueDate, v))
}

// DueDateGTE applies the GTE predicate on the "due_date" field.
func DueDateGTE(v time.Time) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldGTE(FieldDueDate, v))
}

// DueDateLT applies the LT predicate on the "due_date" field.
func DueDateLT(v time.Time) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldLT(FieldDueDate, v))
}

// DueDateLTE applies the LTE predicate on the "due_date" field.
func DueDateLTE(v time.Time) predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldLTE(FieldDueDate, v))
}

// DueDateIsNil applies the IsNil predicate on the "due_date" field.
func DueDateIsNil() predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldIsNull(FieldDueDate))
}

// DueDateNotNil applies the NotNil predicate on the "due_date" field.
func DueDateNotNil() predicate.FeeStructure {
	return predicate.FeeStructure(sql.FieldNotNull(FieldDueDate))
}

// HasClass applies the HasEdge predicate on the "class" edge.
func HasClass() predicate.FeeStructure {
	return predicate.FeeStructure(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ClassTable, ClassColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasClassWith applies the HasEdge predicate on the "class" edge with a given conditions (other predicates).
func HasClassWith(preds ...predicate.Class) predicate.FeeStructure {
	return predicate.FeeStructure(func(s *sql.Selector) {
		step := newClassStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAcademicYear applies the HasEdge predicate on the "academic_year" edge.
func HasAcademicYear() predicate.FeeStructure {
	return predicate.FeeStructure(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, AcademicYearTable, AcademicYearColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAcademicYearWith applies the HasEdge predicate on the "academic_year" edge with a given conditions (other predicates).
func HasAcademicYearWith(preds ...predicate.AcademicYear) predicate.FeeStructure {
	return predicate.FeeStructure(func(s *sql.Selector) {
		step := newAcademicYearStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FeeStructure) predicate.FeeStructure {
	return predicate.FeeStructure(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FeeStructure) predicate.FeeStructure {
	return predicate.FeeStructure(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FeeStructure) predicate.FeeStructure {
	return predicate.FeeStructure(sql.NotPredicates(p))
}
