// Code generated by ent, DO NOT EDIT.

package feepayment

import (
	"fmt"
	"io"
	"strconv"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the feepayment type in the database.
	Label = "fee_payment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStudentID holds the string denoting the student_id field in the database.
	FieldStudentID = "student_id"
	// FieldFeeStructureID holds the string denoting the fee_structure_id field in the database.
	FieldFeeStructureID = "fee_structure_id"
	// FieldAmountPaid holds the string denoting the amount_paid field in the database.
	FieldAmountPaid = "amount_paid"
	// FieldPaymentDate holds the string denoting the payment_date field in the database.
	FieldPaymentDate = "payment_date"
	// FieldPaymentStatus holds the string denoting the payment_status field in the database.
	FieldPaymentStatus = "payment_status"
	// FieldPaymentMethod holds the string denoting the payment_method field in the database.
	FieldPaymentMethod = "payment_method"
	// FieldTransactionRef holds the string denoting the transaction_ref field in the database.
	FieldTransactionRef = "transaction_ref"
	// FieldRemarks holds the string denoting the remarks field in the database.
	FieldRemarks = "remarks"
	// EdgeStudent holds the string denoting the student edge name in mutations.
	EdgeStudent = "student"
	// EdgeFeeStructure holds the string denoting the fee_structure edge name in mutations.
	EdgeFeeStructure = "fee_structure"
	// Table holds the table name of the feepayment in the database.
	Table = "fee_payments"
	// StudentTable is the table that holds the student relation/edge.
	StudentTable = "fee_payments"
	// StudentInverseTable is the table name for the Student entity.
	// It exists in this package in order to avoid circular dependency with the "student" package.
	StudentInverseTable = "students"
	// StudentColumn is the table column denoting the student relation/edge.
	StudentColumn = "student_id"
	// FeeStructureTable is the table that holds the fee_structure relation/edge.
	FeeStructureTable = "fee_payments"
	// FeeStructureInverseTable is the table name for the FeeStructure entity.
	// It exists in this package in order to avoid circular dependency with the "feestructure" package.
	FeeStructureInverseTable = "fee_structures"
	// FeeStructureColumn is the table column denoting the fee_structure relation/edge.
	FeeStructureColumn = "fee_structure_id"
)

// Columns holds all SQL columns for feepayment fields.
var Columns = []string{
	FieldID,
	FieldStudentID,
	FieldFeeStructureID,
	FieldAmountPaid,
	FieldPaymentDate,
	FieldPaymentStatus,
	FieldPaymentMethod,
	FieldTransactionRef,
	FieldRemarks,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// PaymentStatus defines the type for the "payment_status" enum field.
type PaymentStatus string

// PaymentStatusUnpaid is the default value of the PaymentStatus enum.
const DefaultPaymentStatus = PaymentStatusUnpaid

// PaymentStatus values.
const (
	PaymentStatusUnpaid  PaymentStatus = "unpaid"
	PaymentStatusPartial PaymentStatus = "partial"
	PaymentStatusPaid    PaymentStatus = "paid"
	PaymentStatusOverdue PaymentStatus = "overdue"
)

func (ps PaymentStatus) String() string {
	return string(ps)
}

// PaymentStatusValidator is a validator for the "payment_status" field enum values. It is called by the builders before save.
func PaymentStatusValidator(ps PaymentStatus) error {
	switch ps {
	case PaymentStatusUnpaid, PaymentStatusPartial, PaymentStatusPaid, PaymentStatusOverdue:
		return nil
	default:
		return fmt.Errorf("feepayment: invalid enum value for payment_status field: %q", ps)
	}
}

// OrderOption defines the ordering options for the FeePayment queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByStudentID orders the results by the student_id field.
func ByStudentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStudentID, opts...).ToFunc()
}

// ByFeeStructureID orders the results by the fee_structure_id field.
func ByFeeStructureID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeeStructureID, opts...).ToFunc()
}

// ByAmountPaid orders the results by the amount_paid field.
func ByAmountPaid(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmountPaid, opts...).ToFunc()
}

// ByPaymentDate orders the results by the payment_date field.
func ByPaymentDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaymentDate, opts...).ToFunc()
}

// ByPaymentStatus orders the results by the payment_status field.
func ByPaymentStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaymentStatus, opts...).ToFunc()
}

// ByPaymentMethod orders the results by the payment_method field.
func ByPaymentMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPaymentMethod, opts...).ToFunc()
}

// ByTransactionRef orders the results by the transaction_ref field.
func ByTransactionRef(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTransactionRef, opts...).ToFunc()
}

// ByRemarks orders the results by the remarks field.
func ByRemarks(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemarks, opts...).ToFunc()
}

// ByStudentField orders the results by student field.
func ByStudentField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newStudentStep(), sql.OrderByField(field, opts...))
	}
}

// ByFeeStructureField orders the results by fee_structure field.
func ByFeeStructureField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFeeStructureStep(), sql.OrderByField(field, opts...))
	}
}
func newStudentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(StudentInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, StudentTable, StudentColumn),
	)
}
func newFeeStructureStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FeeStructureInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, FeeStructureTable, FeeStructureColumn),
	)
}

// MarshalGQL implements graphql.Marshaler interface.
func (e PaymentStatus) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *PaymentStatus) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = PaymentStatus(str)
	if err := PaymentStatusValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid PaymentStatus", str)
	}
	return nil
}
