// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

type AdmissionInquiry struct {
	InquiryID          string `json:"inquiryId"`
	StudentName        string `json:"studentName"`
	GuardianName       string `json:"guardianName"`
	ContactNumber      string `json:"contactNumber"`
	EmailAddress       string `json:"emailAddress"`
	DateOfInquiry      string `json:"dateOfInquiry"`
	ProgramOfInterest  string `json:"programOfInterest"`
	PreferredStartDate string `json:"preferredStartDate"`
	InquirySource      string `json:"inquirySource"`
	Status             string `json:"status"`
	Notes              string `json:"notes"`
	FollowUpDate       string `json:"followUpDate"`
	AssignedTo         string `json:"assignedTo"`
	CampusLocation     string `json:"campusLocation"`
	PreviousEducation  string `json:"previousEducation"`
	Img                string `json:"img"`
}

type AssignClassTeacher struct {
	ID               string  `json:"id"`
	TeacherID        string  `json:"teacherId"`
	TeacherName      string  `json:"teacherName"`
	Img              *string `json:"img,omitempty"`
	ClassID          string  `json:"classId"`
	ClassName        string  `json:"className"`
	Subject          string  `json:"subject"`
	StartDate        string  `json:"startDate"`
	EndDate          string  `json:"endDate"`
	AssignedBy       string  `json:"assignedBy"`
	AssignmentStatus string  `json:"assignmentStatus"`
	AcademicYear     string  `json:"academicYear"`
	ClassTiming      string  `json:"classTiming"`
	RoomNumber       string  `json:"roomNumber"`
}

type ClassInfo struct {
	ClassID   string `json:"classId"`
	ClassName string `json:"className"`
	ClassCode string `json:"classCode"`
}

type Complaint struct {
	ComplaintID           string `json:"complaintId"`
	ComplaintDate         string `json:"complaintDate"`
	ComplaintTime         string `json:"complaintTime"`
	ComplainantName       string `json:"complainantName"`
	Img                   string `json:"img"`
	ComplainantType       string `json:"complainantType"`
	StudentName           string `json:"studentName"`
	ComplaintDescription  string `json:"complaintDescription"`
	Department            string `json:"department"`
	Status                string `json:"status"`
	AssignedTo            string `json:"assignedTo"`
	ResolutionDescription string `json:"resolutionDescription"`
	ResolutionDate        string `json:"resolutionDate"`
	CreatedAt             string `json:"createdAt"`
	UpdatedAt             string `json:"updatedAt"`
	PriorityLevel         string `json:"priorityLevel"`
	Feedback              string `json:"feedback"`
}

type CreateAdmissionInquiryInput struct {
	StudentName        string  `json:"studentName"`
	GuardianName       string  `json:"guardianName"`
	ContactNumber      string  `json:"contactNumber"`
	EmailAddress       string  `json:"emailAddress"`
	DateOfInquiry      string  `json:"dateOfInquiry"`
	ProgramOfInterest  string  `json:"programOfInterest"`
	PreferredStartDate string  `json:"preferredStartDate"`
	InquirySource      string  `json:"inquirySource"`
	Status             string  `json:"status"`
	Notes              *string `json:"notes,omitempty"`
	FollowUpDate       *string `json:"followUpDate,omitempty"`
	AssignedTo         *string `json:"assignedTo,omitempty"`
	CampusLocation     *string `json:"campusLocation,omitempty"`
	PreviousEducation  *string `json:"previousEducation,omitempty"`
	Img                *string `json:"img,omitempty"`
}

type CreateAssignClassTeacherInput struct {
	TeacherID        string  `json:"teacherId"`
	TeacherName      string  `json:"teacherName"`
	Img              *string `json:"img,omitempty"`
	ClassID          string  `json:"classId"`
	ClassName        string  `json:"className"`
	Subject          string  `json:"subject"`
	StartDate        string  `json:"startDate"`
	EndDate          string  `json:"endDate"`
	AssignedBy       string  `json:"assignedBy"`
	AssignmentStatus string  `json:"assignmentStatus"`
	AcademicYear     string  `json:"academicYear"`
	ClassTiming      string  `json:"classTiming"`
	RoomNumber       string  `json:"roomNumber"`
}

type CreateComplaintInput struct {
	ComplaintDate         string  `json:"complaintDate"`
	ComplaintTime         string  `json:"complaintTime"`
	ComplainantName       string  `json:"complainantName"`
	Img                   *string `json:"img,omitempty"`
	ComplainantType       string  `json:"complainantType"`
	StudentName           *string `json:"studentName,omitempty"`
	ComplaintDescription  string  `json:"complaintDescription"`
	Department            string  `json:"department"`
	Status                string  `json:"status"`
	AssignedTo            *string `json:"assignedTo,omitempty"`
	ResolutionDescription *string `json:"resolutionDescription,omitempty"`
	ResolutionDate        *string `json:"resolutionDate,omitempty"`
	PriorityLevel         string  `json:"priorityLevel"`
	Feedback              *string `json:"feedback,omitempty"`
}

type CreateTeacherInfoInput struct {
	Img                   *string `json:"img,omitempty"`
	Name                  string  `json:"name"`
	Gender                string  `json:"gender"`
	Email                 string  `json:"email"`
	Department            string  `json:"department"`
	Mobile                string  `json:"mobile"`
	Degree                string  `json:"degree"`
	Address               string  `json:"address"`
	HireDate              string  `json:"hireDate"`
	Salary                string  `json:"salary"`
	SubjectSpecialization string  `json:"subjectSpecialization"`
	ExperienceYears       int     `json:"experienceYears"`
	Status                string  `json:"status"`
	Birthdate             string  `json:"birthdate"`
	Bio                   *string `json:"bio,omitempty"`
}

type CreateVisitorInput struct {
	VisitorName             string  `json:"visitorName"`
	VisitDate               string  `json:"visitDate"`
	VisitTime               string  `json:"visitTime"`
	PurposeOfVisit          string  `json:"purposeOfVisit"`
	ContactNumber           string  `json:"contactNumber"`
	VisitorType             string  `json:"visitorType"`
	StudentName             *string `json:"studentName,omitempty"`
	DepartmentPersonVisited string  `json:"departmentPersonVisited"`
	CheckOutTime            *string `json:"checkOutTime,omitempty"`
	IDProofType             *string `json:"idProofType,omitempty"`
	IDProofNumber           *string `json:"idProofNumber,omitempty"`
	Notes                   *string `json:"notes,omitempty"`
}

type LoginInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token string `json:"token"`
	Role  string `json:"role"`
}

type TeacherInfo struct {
	ID                    string  `json:"id"`
	Img                   *string `json:"img,omitempty"`
	Name                  string  `json:"name"`
	Gender                string  `json:"gender"`
	Email                 string  `json:"email"`
	Department            string  `json:"department"`
	Mobile                string  `json:"mobile"`
	Degree                string  `json:"degree"`
	Address               string  `json:"address"`
	HireDate              string  `json:"hireDate"`
	Salary                string  `json:"salary"`
	SubjectSpecialization string  `json:"subjectSpecialization"`
	ExperienceYears       int     `json:"experienceYears"`
	Status                string  `json:"status"`
	Birthdate             string  `json:"birthdate"`
	Bio                   *string `json:"bio,omitempty"`
}

type UpdateAdmissionInquiryInput struct {
	InquiryID          string  `json:"inquiryId"`
	StudentName        string  `json:"studentName"`
	GuardianName       string  `json:"guardianName"`
	ContactNumber      string  `json:"contactNumber"`
	EmailAddress       string  `json:"emailAddress"`
	DateOfInquiry      string  `json:"dateOfInquiry"`
	ProgramOfInterest  string  `json:"programOfInterest"`
	PreferredStartDate string  `json:"preferredStartDate"`
	InquirySource      string  `json:"inquirySource"`
	Status             string  `json:"status"`
	Notes              *string `json:"notes,omitempty"`
	FollowUpDate       *string `json:"followUpDate,omitempty"`
	AssignedTo         *string `json:"assignedTo,omitempty"`
	CampusLocation     *string `json:"campusLocation,omitempty"`
	PreviousEducation  *string `json:"previousEducation,omitempty"`
	Img                *string `json:"img,omitempty"`
}

type UpdateAssignClassTeacherInput struct {
	ID               string  `json:"id"`
	TeacherID        string  `json:"teacherId"`
	TeacherName      string  `json:"teacherName"`
	Img              *string `json:"img,omitempty"`
	ClassID          string  `json:"classId"`
	ClassName        string  `json:"className"`
	Subject          string  `json:"subject"`
	StartDate        string  `json:"startDate"`
	EndDate          string  `json:"endDate"`
	AssignedBy       string  `json:"assignedBy"`
	AssignmentStatus string  `json:"assignmentStatus"`
	AcademicYear     string  `json:"academicYear"`
	ClassTiming      string  `json:"classTiming"`
	RoomNumber       string  `json:"roomNumber"`
}

type UpdateComplaintInput struct {
	ComplaintID           string  `json:"complaintId"`
	ComplaintDate         string  `json:"complaintDate"`
	ComplaintTime         string  `json:"complaintTime"`
	ComplainantName       string  `json:"complainantName"`
	Img                   *string `json:"img,omitempty"`
	ComplainantType       string  `json:"complainantType"`
	StudentName           *string `json:"studentName,omitempty"`
	ComplaintDescription  string  `json:"complaintDescription"`
	Department            string  `json:"department"`
	Status                string  `json:"status"`
	AssignedTo            *string `json:"assignedTo,omitempty"`
	ResolutionDescription *string `json:"resolutionDescription,omitempty"`
	ResolutionDate        *string `json:"resolutionDate,omitempty"`
	PriorityLevel         string  `json:"priorityLevel"`
	Feedback              *string `json:"feedback,omitempty"`
}

type UpdateTeacherInfoInput struct {
	ID                    string  `json:"id"`
	Img                   *string `json:"img,omitempty"`
	Name                  string  `json:"name"`
	Gender                string  `json:"gender"`
	Email                 string  `json:"email"`
	Department            string  `json:"department"`
	Mobile                string  `json:"mobile"`
	Degree                string  `json:"degree"`
	Address               string  `json:"address"`
	HireDate              string  `json:"hireDate"`
	Salary                string  `json:"salary"`
	SubjectSpecialization string  `json:"subjectSpecialization"`
	ExperienceYears       int     `json:"experienceYears"`
	Status                string  `json:"status"`
	Birthdate             string  `json:"birthdate"`
	Bio                   *string `json:"bio,omitempty"`
}

type UpdateVisitorInput struct {
	VisitorID               string  `json:"visitorId"`
	VisitorName             string  `json:"visitorName"`
	VisitDate               string  `json:"visitDate"`
	VisitTime               string  `json:"visitTime"`
	PurposeOfVisit          string  `json:"purposeOfVisit"`
	ContactNumber           string  `json:"contactNumber"`
	VisitorType             string  `json:"visitorType"`
	StudentName             *string `json:"studentName,omitempty"`
	DepartmentPersonVisited string  `json:"departmentPersonVisited"`
	CheckOutTime            *string `json:"checkOutTime,omitempty"`
	IDProofType             *string `json:"idProofType,omitempty"`
	IDProofNumber           *string `json:"idProofNumber,omitempty"`
	Notes                   *string `json:"notes,omitempty"`
}

type Visitor struct {
	VisitorID               string  `json:"visitorId"`
	VisitorName             string  `json:"visitorName"`
	VisitDate               string  `json:"visitDate"`
	VisitTime               string  `json:"visitTime"`
	PurposeOfVisit          string  `json:"purposeOfVisit"`
	ContactNumber           string  `json:"contactNumber"`
	VisitorType             string  `json:"visitorType"`
	StudentName             *string `json:"studentName,omitempty"`
	DepartmentPersonVisited string  `json:"departmentPersonVisited"`
	CheckOutTime            *string `json:"checkOutTime,omitempty"`
	IDProofType             *string `json:"idProofType,omitempty"`
	IDProofNumber           *string `json:"idProofNumber,omitempty"`
	Notes                   *string `json:"notes,omitempty"`
	CreatedAt               string  `json:"createdAt"`
	UpdatedAt               string  `json:"updatedAt"`
}
