# graph/schema.graphqls

# Since ent.graphql will define the base Query and Mutation types,
# we extend the Mutation type here to add custom operations.

extend type Query {
  admissionInquiries: [AdmissionInquiry!]!
  complaints: [Complaint!]!
}

extend type Mutation {
  login(input: LoginInput!): LoginResponse!
  createAdmissionInquiry(input: CreateAdmissionInquiryInput!): AdmissionInquiry!
  updateAdmissionInquiry(input: UpdateAdmissionInquiryInput!): AdmissionInquiry!
  deleteAdmissionInquiry(inquiryId: String!): String!
  createComplaint(input: CreateComplaintInput!): Complaint!
  updateComplaint(input: UpdateComplaintInput!): Complaint!
  deleteComplaint(complaintId: String!): String!
}

input UpdateAdmissionInquiryInput {
  inquiryId: String!
  studentName: String!
  guardianName: String!
  contactNumber: String!
  emailAddress: String!
  dateOfInquiry: String!
  programOfInterest: String!
  preferredStartDate: String!
  inquirySource: String!
  status: String!
  notes: String
  followUpDate: String
  assignedTo: String
  campusLocation: String
  previousEducation: String
  img: String
}

input CreateAdmissionInquiryInput {
  studentName: String!
  guardianName: String!
  contactNumber: String!
  emailAddress: String!
  dateOfInquiry: String!
  programOfInterest: String!
  preferredStartDate: String!
  inquirySource: String!
  status: String!
  notes: String
  followUpDate: String
  assignedTo: String
  campusLocation: String
  previousEducation: String
  img: String
}

input LoginInput {
  username: String!
  password: String!
}

type LoginResponse {
  token: String!
  role: String!
}

type AdmissionInquiry {
  inquiryId: String!
  studentName: String!
  guardianName: String!
  contactNumber: String!
  emailAddress: String!
  dateOfInquiry: String!
  programOfInterest: String!
  preferredStartDate: String!
  inquirySource: String!
  status: String!
  notes: String!
  followUpDate: String!
  assignedTo: String!
  campusLocation: String!
  previousEducation: String!
  img: String!
}

type Complaint {
  complaintId: String!
  complaintDate: String!
  complaintTime: String!
  complainantName: String!
  img: String!
  complainantType: String!
  studentName: String!
  complaintDescription: String!
  department: String!
  status: String!
  assignedTo: String!
  resolutionDescription: String!
  resolutionDate: String!
  createdAt: String!
  updatedAt: String!
  priorityLevel: String!
  feedback: String!
}

input CreateComplaintInput {
  complaintDate: String!
  complaintTime: String!
  complainantName: String!
  img: String
  complainantType: String!
  studentName: String
  complaintDescription: String!
  department: String!
  status: String!
  assignedTo: String
  resolutionDescription: String
  resolutionDate: String
  priorityLevel: String!
  feedback: String
}

input UpdateComplaintInput {
  complaintId: String!
  complaintDate: String!
  complaintTime: String!
  complainantName: String!
  img: String
  complainantType: String!
  studentName: String
  complaintDescription: String!
  department: String!
  status: String!
  assignedTo: String
  resolutionDescription: String
  resolutionDate: String
  priorityLevel: String!
  feedback: String
}

