# graph/schema.graphqls

# Since ent.graphql will define the base Query and Mutation types,
# we extend the Mutation type here to add custom operations.

extend type Query {
  admissionInquiries: [AdmissionInquiry!]!
  complaints: [Complaint!]!
  visitors: [Visitor!]!
  teachersList: [TeacherInfo!]!
  assignClassTeacherList: [AssignClassTeacher!]!
  classList: [ClassList!]!
  studentsList: [StudentInfo!]!
  studentAttendanceList: [StudentAttendanceInfo!]!
  studentPromotionList: [StudentPromotionInfo!]!
  studentCertificateList: [StudentCertificateInfo!]!
  studentDisciplineList: [StudentDisciplineInfo!]!
  studentHealthRecordList: [StudentHealthRecordInfo!]!
  onlineApplications: [OnlineApplication!]!
  entranceExams: [EntranceExam!]!
  meritLists: [MeritList!]!
  seatAllocations: [SeatAllocation!]!
  examTypes: [ExamType!]!
  examSchedules: [ExamSchedule!]!
  hallAllocations: [HallAllocation!]!
  marksEntries: [MarksEntry!]!
  resultGenerations: [ResultGeneration!]!
  reportCards: [ReportCard!]!
  allAssets: [LibraryAsset!]!
  bookStatuses: [BookStatus!]!
  issueReturns: [IssueReturn!]!
  libraryReports: [LibraryReport!]!
  staffList: [Staff!]!
  staffAttendanceList: [StaffAttendance!]!
  leaveRequests: [LeaveRequest!]!
  leaveBalances: [LeaveBalance!]!
  leaveTypesList: [LeaveTypes!]!
  holidays: [Holiday!]!
  todaysAttendanceList: [TodaysAttendance!]!
  employeeSalaryList: [EmployeeSalary!]!
  vehiclesList: [Vehicle!]!
  transportRoutesList: [TransportRoute!]!
  driversList: [Driver!]!
  studentAllocationsList: [StudentAllocation!]!
  transportFeesList: [TransportFee!]!
  noticeBoardsList: [NoticeBoard!]!
  announcementsList: [Announcement!]!
  allFeesList: [Fees!]!
  feesTypesList: [FeesType!]!
  feesDiscountsList: [FeesDiscount!]!
  academicYearList: [AcademicYearCustom!]!
  sessionsList: [SessionCustom!]!
  academicClassesList: [AcademicClassCustom!]!
  academicSubjectsList: [AcademicSubjectCustom!]!
  courseCurriculumsList: [CourseCurriculumCustom!]!
  assignmentsList: [AssignmentCustom!]!
  lessonPlanningsList: [LessonPlanningCustom!]!
  hostelRoomsList: [HostelRoomCustom!]!
  hostelRoomTypesList: [HostelRoomTypeCustom!]!
  hostelAllocationsList: [HostelAllocationCustom!]!
  hostelAttendancesList: [HostelAttendanceCustom!]!
  hostelFeesList: [HostelFeeCustom!]!
  departmentsList: [DepartmentCustom!]!
  academicReportsList: [AcademicReportCustom!]!
  attendanceReportsList: [AttendanceReportCustom!]!
  feeReportsList: [FeeReportCustom!]!
  examReportsList: [ExamReportCustom!]!
  customReportsList: [CustomReportCustom!]!
  todaySchedulesList: [TodayScheduleCustom!]!
  teacherClassesList: [TeacherClassCustom!]!
  teacherLessonPlansList: [TeacherLessonPlanCustom!]!
  studentStudyMaterialsList: [StudentStudyMaterialCustom!]!
  teacherStudyMaterialsList: [TeacherStudyMaterialCustom!]!
  teacherAssignmentsList: [TeacherAssignmentCustom!]!
  teacherClassStudentsList: [TeacherClassStudentCustom!]!
  teacherStudentAttendancesList: [TeacherStudentAttendanceCustom!]!
  teacherStudentPerformancesList: [TeacherStudentPerformanceCustom!]!
  teacherMarksEntriesList: [TeacherMarksEntryCustom!]!
  teacherGradeSubmissionsList: [TeacherGradeSubmissionCustom!]!
  teacherTimetablesList: [TeacherTimetableCustom!]!
  teacherSubstitutionRequestsList: [TeacherSubstitutionRequestCustom!]!
  teacherNoticesList: [TeacherNoticeCustom!]!
  teacherAnnouncementsList: [TeacherAnnouncementCustom!]!
  teacherDailyAttendancesList: [TeacherDailyAttendanceCustom!]!
  teacherAttendanceSummariesList: [TeacherAttendanceSummaryCustom!]!
  teacherLeaveStatusesList: [TeacherLeaveStatusCustom!]!
  teacherLecturesList: [TeacherLectureCustom!]!
}

extend type Mutation {
  login(input: LoginInput!): LoginResponse!
  createAdmissionInquiry(input: CreateAdmissionInquiryInput!): AdmissionInquiry!
  updateAdmissionInquiry(input: UpdateAdmissionInquiryInput!): AdmissionInquiry!
  deleteAdmissionInquiry(inquiryId: String!): String!
  createComplaint(input: CreateComplaintInput!): Complaint!
  updateComplaint(input: UpdateComplaintInput!): Complaint!
  deleteComplaint(complaintId: String!): String!
  createVisitor(input: CreateVisitorInput!): Visitor!
  updateVisitor(input: UpdateVisitorInput!): Visitor!
  deleteVisitor(visitorId: String!): String!
  createTeacher(input: CreateTeacherInfoInput!): TeacherInfo!
  updateTeacher(input: UpdateTeacherInfoInput!): TeacherInfo!
  deleteTeacher(id: String!): String!
  createAssignClassTeacher(input: CreateAssignClassTeacherInput!): AssignClassTeacher!
  updateAssignClassTeacher(input: UpdateAssignClassTeacherInput!): AssignClassTeacher!
  deleteAssignClassTeacher(id: String!): String!
  createStudent(input: CreateStudentInfoInput!): StudentInfo!
  updateStudent(input: UpdateStudentInfoInput!): StudentInfo!
  deleteStudent(id: String!): String!
  createStudentAttendance(input: CreateStudentAttendanceInfoInput!): StudentAttendanceInfo!
  updateStudentAttendance(input: UpdateStudentAttendanceInfoInput!): StudentAttendanceInfo!
  deleteStudentAttendance(id: String!): String!
  createStudentPromotion(input: CreateStudentPromotionInfoInput!): StudentPromotionInfo!
  updateStudentPromotion(input: UpdateStudentPromotionInfoInput!): StudentPromotionInfo!
  deleteStudentPromotion(id: String!): String!
  createStudentCertificate(input: CreateStudentCertificateInfoInput!): StudentCertificateInfo!
  updateStudentCertificate(input: UpdateStudentCertificateInfoInput!): StudentCertificateInfo!
  deleteStudentCertificate(id: String!): String!
  createStudentDiscipline(input: CreateStudentDisciplineInfoInput!): StudentDisciplineInfo!
  updateStudentDiscipline(input: UpdateStudentDisciplineInfoInput!): StudentDisciplineInfo!
  deleteStudentDiscipline(id: String!): String!
  createStudentHealthRecord(input: CreateStudentHealthRecordInfoInput!): StudentHealthRecordInfo!
  updateStudentHealthRecord(input: UpdateStudentHealthRecordInfoInput!): StudentHealthRecordInfo!
  deleteStudentHealthRecord(id: String!): String!
  createOnlineApplication(input: CreateOnlineApplicationInput!): OnlineApplication!
  updateOnlineApplication(input: UpdateOnlineApplicationInput!): OnlineApplication!
  deleteOnlineApplication(id: String!): String!
  createEntranceExam(input: CreateEntranceExamInput!): EntranceExam!
  updateEntranceExam(input: UpdateEntranceExamInput!): EntranceExam!
  deleteEntranceExam(id: String!): String!
  createMeritList(input: CreateMeritListInput!): MeritList!
  updateMeritList(input: UpdateMeritListInput!): MeritList!
  deleteMeritList(id: String!): String!
  createSeatAllocation(input: CreateSeatAllocationInput!): SeatAllocation!
  updateSeatAllocation(input: UpdateSeatAllocationInput!): SeatAllocation!
  deleteSeatAllocation(id: String!): String!
  createExamType(input: CreateExamTypeInput!): ExamType!
  updateExamType(input: UpdateExamTypeInput!): ExamType!
  deleteExamType(id: String!): String!
  createExamSchedule(input: CreateExamScheduleInput!): ExamSchedule!
  updateExamSchedule(input: UpdateExamScheduleInput!): ExamSchedule!
  deleteExamSchedule(id: String!): String!
  createHallAllocation(input: CreateHallAllocationInput!): HallAllocation!
  updateHallAllocation(input: UpdateHallAllocationInput!): HallAllocation!
  deleteHallAllocation(id: String!): String!
  createMarksEntry(input: CreateMarksEntryInput!): MarksEntry!
  updateMarksEntry(input: UpdateMarksEntryInput!): MarksEntry!
  deleteMarksEntry(id: String!): String!
  createResultGeneration(input: CreateResultGenerationInput!): ResultGeneration!
  updateResultGeneration(input: UpdateResultGenerationInput!): ResultGeneration!
  deleteResultGeneration(id: String!): String!
  createReportCard(input: CreateReportCardInput!): ReportCard!
  updateReportCard(input: UpdateReportCardInput!): ReportCard!
  deleteReportCard(id: String!): String!
  createLibraryAsset(input: CreateLibraryAssetInput!): LibraryAsset!
  updateLibraryAsset(input: UpdateLibraryAssetInput!): LibraryAsset!
  deleteLibraryAsset(id: String!): String!
  createBookStatus(input: CreateBookStatusInput!): BookStatus!
  updateBookStatus(input: UpdateBookStatusInput!): BookStatus!
  deleteBookStatus(id: String!): String!
  createIssueReturn(input: CreateIssueReturnInput!): IssueReturn!
  updateIssueReturn(input: UpdateIssueReturnInput!): IssueReturn!
  deleteIssueReturn(id: String!): String!
  createLibraryReport(input: CreateLibraryReportInput!): LibraryReport!
  updateLibraryReport(input: UpdateLibraryReportInput!): LibraryReport!
  deleteLibraryReport(id: String!): String!
  createStaff(input: CreateStaffInput!): Staff!
  updateStaff(input: UpdateStaffInput!): Staff!
  deleteStaff(id: String!): String!
  createStaffAttendance(input: CreateStaffAttendanceInput!): StaffAttendance!
  updateStaffAttendance(input: UpdateStaffAttendanceInput!): StaffAttendance!
  deleteStaffAttendance(id: String!): String!
  createLeaveRequest(input: CreateLeaveRequestInput!): LeaveRequest!
  updateLeaveRequest(input: UpdateLeaveRequestInput!): LeaveRequest!
  deleteLeaveRequest(id: String!): String!
  createLeaveBalance(input: CreateLeaveBalanceInput!): LeaveBalance!
  updateLeaveBalance(input: UpdateLeaveBalanceInput!): LeaveBalance!
  deleteLeaveBalance(id: String!): String!
  createLeaveTypes(input: CreateLeaveTypesInput!): LeaveTypes!
  updateLeaveTypes(input: UpdateLeaveTypesInput!): LeaveTypes!
  deleteLeaveTypes(id: String!): String!
  createHoliday(input: CreateHolidayInput!): Holiday!
  updateHoliday(input: UpdateHolidayInput!): Holiday!
  deleteHoliday(id: String!): String!
  createTodaysAttendance(input: CreateTodaysAttendanceInput!): TodaysAttendance!
  updateTodaysAttendance(input: UpdateTodaysAttendanceInput!): TodaysAttendance!
  deleteTodaysAttendance(id: String!): String!
  createEmployeeSalary(input: CreateEmployeeSalaryInput!): EmployeeSalary!
  updateEmployeeSalary(input: UpdateEmployeeSalaryInput!): EmployeeSalary!
  deleteEmployeeSalary(id: String!): String!
  createVehicle(input: CreateVehicleInput!): Vehicle!
  updateVehicle(input: UpdateVehicleInput!): Vehicle!
  deleteVehicle(id: String!): String!
  createTransportRoute(input: CreateTransportRouteInput!): TransportRoute!
  updateTransportRoute(input: UpdateTransportRouteInput!): TransportRoute!
  deleteTransportRoute(id: String!): String!
  createDriver(input: CreateDriverInput!): Driver!
  updateDriver(input: UpdateDriverInput!): Driver!
  deleteDriver(id: String!): String!
  createStudentAllocation(input: CreateStudentAllocationInput!): StudentAllocation!
  updateStudentAllocation(input: UpdateStudentAllocationInput!): StudentAllocation!
  deleteStudentAllocation(id: String!): String!
  createTransportFee(input: CreateTransportFeeInput!): TransportFee!
  updateTransportFee(input: UpdateTransportFeeInput!): TransportFee!
  deleteTransportFee(id: String!): String!
  createNoticeBoard(input: CreateNoticeBoardInput!): NoticeBoard!
  updateNoticeBoard(input: UpdateNoticeBoardInput!): NoticeBoard!
  deleteNoticeBoard(id: String!): String!
  createAnnouncement(input: CreateAnnouncementInput!): Announcement!
  updateAnnouncement(input: UpdateAnnouncementInput!): Announcement!
  deleteAnnouncement(id: String!): String!
  createFees(input: CreateFeesInput!): Fees!
  updateFees(input: UpdateFeesInput!): Fees!
  deleteFees(id: String!): String!
  createFeesType(input: CreateFeesTypeInput!): FeesType!
  updateFeesType(input: UpdateFeesTypeInput!): FeesType!
  deleteFeesType(id: String!): String!
  createFeesDiscount(input: CreateFeesDiscountInput!): FeesDiscount!
  updateFeesDiscount(input: UpdateFeesDiscountInput!): FeesDiscount!
  deleteFeesDiscount(id: String!): String!
  createClassList(input: CreateClassListInput!): ClassList!
  updateClassList(input: UpdateClassListInput!): ClassList!
  deleteClassList(id: String!): String!
  createAcademicYear(input: CreateAcademicYearCustomInput!): AcademicYearCustom!
  updateAcademicYear(input: UpdateAcademicYearCustomInput!): AcademicYearCustom!
  deleteAcademicYear(id: String!): String!
  createSession(input: CreateSessionCustomInput!): SessionCustom!
  updateSession(input: UpdateSessionCustomInput!): SessionCustom!
  deleteSession(id: String!): String!
  createAcademicClass(input: CreateAcademicClassCustomInput!): AcademicClassCustom!
  updateAcademicClass(input: UpdateAcademicClassCustomInput!): AcademicClassCustom!
  deleteAcademicClass(id: String!): String!
  createAcademicSubject(input: CreateAcademicSubjectCustomInput!): AcademicSubjectCustom!
  updateAcademicSubject(input: UpdateAcademicSubjectCustomInput!): AcademicSubjectCustom!
  deleteAcademicSubject(id: String!): String!
  createCourseCurriculum(input: CreateCourseCurriculumCustomInput!): CourseCurriculumCustom!
  updateCourseCurriculum(input: UpdateCourseCurriculumCustomInput!): CourseCurriculumCustom!
  deleteCourseCurriculum(id: String!): String!
  createAssignment(input: CreateAssignmentCustomInput!): AssignmentCustom!
  updateAssignment(input: UpdateAssignmentCustomInput!): AssignmentCustom!
  deleteAssignment(id: String!): String!
  createLessonPlanning(input: CreateLessonPlanningCustomInput!): LessonPlanningCustom!
  updateLessonPlanning(input: UpdateLessonPlanningCustomInput!): LessonPlanningCustom!
  deleteLessonPlanning(id: String!): String!
  createHostelRoom(input: CreateHostelRoomCustomInput!): HostelRoomCustom!
  updateHostelRoom(input: UpdateHostelRoomCustomInput!): HostelRoomCustom!
  deleteHostelRoom(id: String!): String!
  createHostelRoomType(input: CreateHostelRoomTypeCustomInput!): HostelRoomTypeCustom!
  updateHostelRoomType(input: UpdateHostelRoomTypeCustomInput!): HostelRoomTypeCustom!
  deleteHostelRoomType(id: String!): String!
  createHostelAllocation(input: CreateHostelAllocationCustomInput!): HostelAllocationCustom!
  updateHostelAllocation(input: UpdateHostelAllocationCustomInput!): HostelAllocationCustom!
  deleteHostelAllocation(id: String!): String!
  createHostelAttendance(input: CreateHostelAttendanceCustomInput!): HostelAttendanceCustom!
  updateHostelAttendance(input: UpdateHostelAttendanceCustomInput!): HostelAttendanceCustom!
  deleteHostelAttendance(id: String!): String!
  createHostelFee(input: CreateHostelFeeCustomInput!): HostelFeeCustom!
  updateHostelFee(input: UpdateHostelFeeCustomInput!): HostelFeeCustom!
  deleteHostelFee(id: String!): String!
  createDepartment(input: CreateDepartmentCustomInput!): DepartmentCustom!
  updateDepartment(input: UpdateDepartmentCustomInput!): DepartmentCustom!
  deleteDepartment(id: String!): String!
  createAcademicReport(input: CreateAcademicReportCustomInput!): AcademicReportCustom!
  updateAcademicReport(input: UpdateAcademicReportCustomInput!): AcademicReportCustom!
  deleteAcademicReport(id: String!): String!
  createAttendanceReport(input: CreateAttendanceReportCustomInput!): AttendanceReportCustom!
  updateAttendanceReport(input: UpdateAttendanceReportCustomInput!): AttendanceReportCustom!
  deleteAttendanceReport(id: String!): String!
  createFeeReport(input: CreateFeeReportCustomInput!): FeeReportCustom!
  updateFeeReport(input: UpdateFeeReportCustomInput!): FeeReportCustom!
  deleteFeeReport(id: String!): String!
  createExamReport(input: CreateExamReportCustomInput!): ExamReportCustom!
  updateExamReport(input: UpdateExamReportCustomInput!): ExamReportCustom!
  deleteExamReport(id: String!): String!
  createCustomReport(input: CreateCustomReportCustomInput!): CustomReportCustom!
  updateCustomReport(input: UpdateCustomReportCustomInput!): CustomReportCustom!
  deleteCustomReport(id: String!): String!
  createTodaySchedule(input: CreateTodayScheduleCustomInput!): TodayScheduleCustom!
  updateTodaySchedule(input: UpdateTodayScheduleCustomInput!): TodayScheduleCustom!
  deleteTodaySchedule(id: String!): String!
  createTeacherClass(input: CreateTeacherClassCustomInput!): TeacherClassCustom!
  updateTeacherClass(input: UpdateTeacherClassCustomInput!): TeacherClassCustom!
  deleteTeacherClass(id: String!): String!
  createTeacherLessonPlan(input: CreateTeacherLessonPlanCustomInput!): TeacherLessonPlanCustom!
  updateTeacherLessonPlan(input: UpdateTeacherLessonPlanCustomInput!): TeacherLessonPlanCustom!
  deleteTeacherLessonPlan(id: String!): String!
  createStudentStudyMaterial(input: CreateStudentStudyMaterialCustomInput!): StudentStudyMaterialCustom!
  updateStudentStudyMaterial(input: UpdateStudentStudyMaterialCustomInput!): StudentStudyMaterialCustom!
  deleteStudentStudyMaterial(id: String!): String!
  createTeacherStudyMaterial(input: CreateTeacherStudyMaterialCustomInput!): TeacherStudyMaterialCustom!
  updateTeacherStudyMaterial(input: UpdateTeacherStudyMaterialCustomInput!): TeacherStudyMaterialCustom!
  deleteTeacherStudyMaterial(id: String!): String!
  createTeacherAssignment(input: CreateTeacherAssignmentCustomInput!): TeacherAssignmentCustom!
  updateTeacherAssignment(input: UpdateTeacherAssignmentCustomInput!): TeacherAssignmentCustom!
  deleteTeacherAssignment(id: String!): String!
  createTeacherClassStudent(input: CreateTeacherClassStudentCustomInput!): TeacherClassStudentCustom!
  updateTeacherClassStudent(input: UpdateTeacherClassStudentCustomInput!): TeacherClassStudentCustom!
  deleteTeacherClassStudent(id: String!): String!
  createTeacherStudentAttendance(input: CreateTeacherStudentAttendanceCustomInput!): TeacherStudentAttendanceCustom!
  updateTeacherStudentAttendance(input: UpdateTeacherStudentAttendanceCustomInput!): TeacherStudentAttendanceCustom!
  deleteTeacherStudentAttendance(id: String!): String!
  createTeacherStudentPerformance(input: CreateTeacherStudentPerformanceCustomInput!): TeacherStudentPerformanceCustom!
  updateTeacherStudentPerformance(input: UpdateTeacherStudentPerformanceCustomInput!): TeacherStudentPerformanceCustom!
  deleteTeacherStudentPerformance(id: String!): String!
  createTeacherMarksEntry(input: CreateTeacherMarksEntryCustomInput!): TeacherMarksEntryCustom!
  updateTeacherMarksEntry(input: UpdateTeacherMarksEntryCustomInput!): TeacherMarksEntryCustom!
  deleteTeacherMarksEntry(id: String!): String!
  createTeacherGradeSubmission(input: CreateTeacherGradeSubmissionCustomInput!): TeacherGradeSubmissionCustom!
  updateTeacherGradeSubmission(input: UpdateTeacherGradeSubmissionCustomInput!): TeacherGradeSubmissionCustom!
  deleteTeacherGradeSubmission(id: String!): String!
  createTeacherTimetable(input: CreateTeacherTimetableCustomInput!): TeacherTimetableCustom!
  updateTeacherTimetable(input: UpdateTeacherTimetableCustomInput!): TeacherTimetableCustom!
  deleteTeacherTimetable(id: String!): String!
  createTeacherSubstitutionRequest(input: CreateTeacherSubstitutionRequestCustomInput!): TeacherSubstitutionRequestCustom!
  updateTeacherSubstitutionRequest(input: UpdateTeacherSubstitutionRequestCustomInput!): TeacherSubstitutionRequestCustom!
  deleteTeacherSubstitutionRequest(id: String!): String!
  createTeacherNotice(input: CreateTeacherNoticeCustomInput!): TeacherNoticeCustom!
  updateTeacherNotice(input: UpdateTeacherNoticeCustomInput!): TeacherNoticeCustom!
  deleteTeacherNotice(id: String!): String!
  createTeacherAnnouncement(input: CreateTeacherAnnouncementCustomInput!): TeacherAnnouncementCustom!
  updateTeacherAnnouncement(input: UpdateTeacherAnnouncementCustomInput!): TeacherAnnouncementCustom!
  deleteTeacherAnnouncement(id: String!): String!
  createTeacherDailyAttendance(input: CreateTeacherDailyAttendanceCustomInput!): TeacherDailyAttendanceCustom!
  updateTeacherDailyAttendance(input: UpdateTeacherDailyAttendanceCustomInput!): TeacherDailyAttendanceCustom!
  deleteTeacherDailyAttendance(id: String!): String!
  createTeacherAttendanceSummary(input: CreateTeacherAttendanceSummaryCustomInput!): TeacherAttendanceSummaryCustom!
  updateTeacherAttendanceSummary(input: UpdateTeacherAttendanceSummaryCustomInput!): TeacherAttendanceSummaryCustom!
  deleteTeacherAttendanceSummary(id: String!): String!
  createTeacherLeaveStatus(input: CreateTeacherLeaveStatusCustomInput!): TeacherLeaveStatusCustom!
  updateTeacherLeaveStatus(input: UpdateTeacherLeaveStatusCustomInput!): TeacherLeaveStatusCustom!
  deleteTeacherLeaveStatus(id: String!): String!
  createTeacherLecture(input: CreateTeacherLectureCustomInput!): TeacherLectureCustom!
  updateTeacherLecture(input: UpdateTeacherLectureCustomInput!): TeacherLectureCustom!
  deleteTeacherLecture(id: String!): String!
}

input UpdateAdmissionInquiryInput {
  inquiryId: String!
  studentName: String!
  guardianName: String!
  contactNumber: String!
  emailAddress: String!
  dateOfInquiry: String!
  programOfInterest: String!
  preferredStartDate: String!
  inquirySource: String!
  status: String!
  notes: String
  followUpDate: String
  assignedTo: String
  campusLocation: String
  previousEducation: String
  img: String
}

input CreateAdmissionInquiryInput {
  studentName: String!
  guardianName: String!
  contactNumber: String!
  emailAddress: String!
  dateOfInquiry: String!
  programOfInterest: String!
  preferredStartDate: String!
  inquirySource: String!
  status: String!
  notes: String
  followUpDate: String
  assignedTo: String
  campusLocation: String
  previousEducation: String
  img: String
}

input LoginInput {
  username: String!
  password: String!
}

type LoginResponse {
  token: String!
  role: String!
}

type AdmissionInquiry {
  inquiryId: String!
  studentName: String!
  guardianName: String!
  contactNumber: String!
  emailAddress: String!
  dateOfInquiry: String!
  programOfInterest: String!
  preferredStartDate: String!
  inquirySource: String!
  status: String!
  notes: String!
  followUpDate: String!
  assignedTo: String!
  campusLocation: String!
  previousEducation: String!
  img: String!
}

type Complaint {
  complaintId: String!
  complaintDate: String!
  complaintTime: String!
  complainantName: String!
  img: String!
  complainantType: String!
  studentName: String!
  complaintDescription: String!
  department: String!
  status: String!
  assignedTo: String!
  resolutionDescription: String!
  resolutionDate: String!
  createdAt: String!
  updatedAt: String!
  priorityLevel: String!
  feedback: String!
}

input CreateComplaintInput {
  complaintDate: String!
  complaintTime: String!
  complainantName: String!
  img: String
  complainantType: String!
  studentName: String
  complaintDescription: String!
  department: String!
  status: String!
  assignedTo: String
  resolutionDescription: String
  resolutionDate: String
  priorityLevel: String!
  feedback: String
}

input UpdateComplaintInput {
  complaintId: String!
  complaintDate: String!
  complaintTime: String!
  complainantName: String!
  img: String
  complainantType: String!
  studentName: String
  complaintDescription: String!
  department: String!
  status: String!
  assignedTo: String
  resolutionDescription: String
  resolutionDate: String
  priorityLevel: String!
  feedback: String
}

type Visitor {
  visitorId: String!
  visitorName: String!
  visitDate: String!
  visitTime: String!
  purposeOfVisit: String!
  contactNumber: String!
  visitorType: String!
  studentName: String
  departmentPersonVisited: String!
  checkOutTime: String
  idProofType: String
  idProofNumber: String
  notes: String
  createdAt: String!
  updatedAt: String!
}

input CreateVisitorInput {
  visitorName: String!
  visitDate: String!
  visitTime: String!
  purposeOfVisit: String!
  contactNumber: String!
  visitorType: String!
  studentName: String
  departmentPersonVisited: String!
  checkOutTime: String
  idProofType: String
  idProofNumber: String
  notes: String
}

input UpdateVisitorInput {
  visitorId: String!
  visitorName: String!
  visitDate: String!
  visitTime: String!
  purposeOfVisit: String!
  contactNumber: String!
  visitorType: String!
  studentName: String
  departmentPersonVisited: String!
  checkOutTime: String
  idProofType: String
  idProofNumber: String
  notes: String
}

type TeacherInfo {
  id: String!
  img: String
  name: String!
  gender: String!
  email: String!
  department: String!
  mobile: String!
  degree: String!
  address: String!
  hireDate: String!
  salary: String!
  subjectSpecialization: String!
  experienceYears: Int!
  status: String!
  birthdate: String!
  bio: String
}

input CreateTeacherInfoInput {
  img: String
  name: String!
  gender: String!
  email: String!
  department: String!
  mobile: String!
  degree: String!
  address: String!
  hireDate: String!
  salary: String!
  subjectSpecialization: String!
  experienceYears: Int!
  status: String!
  birthdate: String!
  bio: String
}

input UpdateTeacherInfoInput {
  id: String!
  img: String
  name: String!
  gender: String!
  email: String!
  department: String!
  mobile: String!
  degree: String!
  address: String!
  hireDate: String!
  salary: String!
  subjectSpecialization: String!
  experienceYears: Int!
  status: String!
  birthdate: String!
  bio: String
}

type AssignClassTeacher {
  id: String!
  teacherId: String!
  teacherName: String!
  img: String
  classId: String!
  className: String!
  subject: String!
  startDate: String!
  endDate: String!
  assignedBy: String!
  assignmentStatus: String!
  academicYear: String!
  classTiming: String!
  roomNumber: String!
}

input CreateAssignClassTeacherInput {
  teacherId: String!
  teacherName: String!
  img: String
  classId: String!
  className: String!
  subject: String!
  startDate: String!
  endDate: String!
  assignedBy: String!
  assignmentStatus: String!
  academicYear: String!
  classTiming: String!
  roomNumber: String!
}

input UpdateAssignClassTeacherInput {
  id: String!
  teacherId: String!
  teacherName: String!
  img: String
  classId: String!
  className: String!
  subject: String!
  startDate: String!
  endDate: String!
  assignedBy: String!
  assignmentStatus: String!
  academicYear: String!
  classTiming: String!
  roomNumber: String!
}

type ClassInfo {
  classId: String!
  className: String!
  classCode: String!
}

type StudentInfo {
  id: String!
  img: String
  gender: String!
  email: String!
  department: String!
  mobile: String!
  name: String!
  rollNo: String!
  dateOfBirth: String!
  address: String!
  enrollmentDate: String!
  graduationYear: String!
  parentGuardianName: String!
  parentGuardianMobile: String!
  status: String!
  profileCompletionStatus: String!
  scholarshipStatus: String!
}

input CreateStudentInfoInput {
  img: String
  gender: String!
  email: String!
  department: String!
  mobile: String!
  name: String!
  rollNo: String!
  dateOfBirth: String!
  address: String!
  enrollmentDate: String!
  graduationYear: String!
  parentGuardianName: String!
  parentGuardianMobile: String!
  status: String!
  profileCompletionStatus: String!
  scholarshipStatus: String!
}

input UpdateStudentInfoInput {
  id: String!
  img: String
  gender: String!
  email: String!
  department: String!
  mobile: String!
  name: String!
  rollNo: String!
  dateOfBirth: String!
  address: String!
  enrollmentDate: String!
  graduationYear: String!
  parentGuardianName: String!
  parentGuardianMobile: String!
  status: String!
  profileCompletionStatus: String!
  scholarshipStatus: String!
}

type StudentAttendanceInfo {
  id: String!
  rollNo: String!
  img: String
  sName: String!
  class: String!
  date: String!
  status: String!
  note: String
  semester: String!
  subject: String!
  attendance_time: String
  present_count: Int
  absent_count: Int
  reason_for_absence: String
  approved: Boolean
  timestamp: String
}

input CreateStudentAttendanceInfoInput {
  rollNo: String!
  img: String
  sName: String!
  class: String!
  date: String!
  status: String!
  note: String
  semester: String!
  subject: String!
  attendance_time: String
  present_count: Int
  absent_count: Int
  reason_for_absence: String
  approved: Boolean
  timestamp: String
}

input UpdateStudentAttendanceInfoInput {
  id: String!
  rollNo: String!
  img: String
  sName: String!
  class: String!
  date: String!
  status: String!
  note: String
  semester: String!
  subject: String!
  attendance_time: String
  present_count: Int
  absent_count: Int
  reason_for_absence: String
  approved: Boolean
  timestamp: String
}

type StudentPromotionInfo {
  id: String!
  img: String
  student_name: String!
  rollNo: String!
  current_class: String!
  promoted_class: String!
  section: String!
  session: String!
  promotion_date: String!
  total_marks: Int
  obtained_marks: Int
  percentage: String
  result: String
  status: String
}

input CreateStudentPromotionInfoInput {
  img: String
  student_name: String!
  rollNo: String!
  current_class: String!
  promoted_class: String!
  section: String!
  session: String!
  promotion_date: String!
  total_marks: Int
  obtained_marks: Int
  percentage: String
  result: String
  status: String
}

input UpdateStudentPromotionInfoInput {
  id: String!
  img: String
  student_name: String!
  rollNo: String!
  current_class: String!
  promoted_class: String!
  section: String!
  session: String!
  promotion_date: String!
  total_marks: Int
  obtained_marks: Int
  percentage: String
  result: String
  status: String
}

type StudentCertificateInfo {
  id: String!
  img: String
  student_name: String!
  certificate_type: String!
  certificate_no: String!
  issued_by: String!
  issue_date: String!
  expiry_date: String!
  category: String
  description: String
  status: String
}

input CreateStudentCertificateInfoInput {
  img: String
  student_name: String!
  certificate_type: String!
  certificate_no: String!
  issued_by: String!
  issue_date: String!
  expiry_date: String!
  category: String
  description: String
  status: String
}

input UpdateStudentCertificateInfoInput {
  id: String!
  img: String
  student_name: String!
  certificate_type: String!
  certificate_no: String!
  issued_by: String!
  issue_date: String!
  expiry_date: String!
  category: String
  description: String
  status: String
}

type StudentDisciplineInfo {
  id: String!
  img: String
  student_name: String!
  incident_date: String!
  incident_type: String!
  incident_location: String!
  reported_by: String!
  action_taken: String
  action_date: String
  description: String
  severity: String
  status: String
}

input CreateStudentDisciplineInfoInput {
  img: String
  student_name: String!
  incident_date: String!
  incident_type: String!
  incident_location: String!
  reported_by: String!
  action_taken: String
  action_date: String
  description: String
  severity: String
  status: String
}

input UpdateStudentDisciplineInfoInput {
  id: String!
  img: String
  student_name: String!
  incident_date: String!
  incident_type: String!
  incident_location: String!
  reported_by: String!
  action_taken: String
  action_date: String
  description: String
  severity: String
  status: String
}

type StudentHealthRecordInfo {
  id: String!
  img: String
  student_name: String!
  blood_group: String!
  allergies: String
  last_checkup: String!
  status: String!
}

input CreateStudentHealthRecordInfoInput {
  img: String
  student_name: String!
  blood_group: String!
  allergies: String
  last_checkup: String!
  status: String!
}

input UpdateStudentHealthRecordInfoInput {
  id: String!
  img: String
  student_name: String!
  blood_group: String!
  allergies: String
  last_checkup: String!
  status: String!
}

type OnlineApplication {
  id: String!
  img: String!
  studentName: String!
  applicationNo: String!
  email: String!
  mobile: String!
  gender: String!
  dateOfBirth: String!
  course: String!
  applicationDate: String!
  paymentStatus: String!
  applicationStatus: String!
}

input CreateOnlineApplicationInput {
  img: String
  studentName: String!
  applicationNo: String!
  email: String!
  mobile: String!
  gender: String!
  dateOfBirth: String!
  course: String!
  applicationDate: String!
  paymentStatus: String!
  applicationStatus: String!
}

input UpdateOnlineApplicationInput {
  id: String!
  img: String
  studentName: String!
  applicationNo: String!
  email: String!
  mobile: String!
  gender: String!
  dateOfBirth: String!
  course: String!
  applicationDate: String!
  paymentStatus: String!
  applicationStatus: String!
}

type EntranceExam {
  id: String!
  examName: String!
  examCode: String!
  examDate: String!
  startTime: String!
  endTime: String!
  venue: String!
  maxMarks: Int!
  passingMarks: Int!
  status: String!
  description: String
}

input CreateEntranceExamInput {
  examName: String!
  examCode: String!
  examDate: String!
  startTime: String!
  endTime: String!
  venue: String!
  maxMarks: Int!
  passingMarks: Int!
  status: String!
  description: String
}

input UpdateEntranceExamInput {
  id: String!
  examName: String!
  examCode: String!
  examDate: String!
  startTime: String!
  endTime: String!
  venue: String!
  maxMarks: Int!
  passingMarks: Int!
  status: String!
  description: String
}

type MeritList {
  id: String!
  studentName: String!
  applicationNo: String!
  category: String!
  entranceScore: Float!
  academicScore: Float!
  totalScore: Float!
  rank: Int!
  course: String!
  selectionStatus: String!
}

input CreateMeritListInput {
  studentName: String!
  applicationNo: String!
  category: String!
  entranceScore: Float!
  academicScore: Float!
  totalScore: Float!
  rank: Int!
  course: String!
  selectionStatus: String!
}

input UpdateMeritListInput {
  id: String!
  studentName: String!
  applicationNo: String!
  category: String!
  entranceScore: Float!
  academicScore: Float!
  totalScore: Float!
  rank: Int!
  course: String!
  selectionStatus: String!
}

type SeatAllocation {
  id: String!
  studentName: String!
  applicationNo: String!
  course: String!
  category: String!
  allottedSeatType: String!
  allocationDate: String!
  reportingDate: String!
  status: String!
  feesPaid: Boolean!
}

input CreateSeatAllocationInput {
  studentName: String!
  applicationNo: String!
  course: String!
  category: String!
  allottedSeatType: String!
  allocationDate: String!
  reportingDate: String!
  status: String!
  feesPaid: Boolean!
}

input UpdateSeatAllocationInput {
  id: String!
  studentName: String!
  applicationNo: String!
  course: String!
  category: String!
  allottedSeatType: String!
  allocationDate: String!
  reportingDate: String!
  status: String!
  feesPaid: Boolean!
}

type ExamType {
  id: String!
  examName: String!
  examCode: String!
  description: String
  status: String!
}

input CreateExamTypeInput {
  examName: String!
  examCode: String!
  description: String
  status: String!
}

input UpdateExamTypeInput {
  id: String!
  examName: String!
  examCode: String!
  description: String
  status: String!
}

type ExamSchedule {
  id: String!
  examType: String!
  course: String!
  semester: String!
  subject: String!
  examDate: String!
  startTime: String!
  endTime: String!
  roomNo: String!
}

input CreateExamScheduleInput {
  examType: String!
  course: String!
  semester: String!
  subject: String!
  examDate: String!
  startTime: String!
  endTime: String!
  roomNo: String!
}

input UpdateExamScheduleInput {
  id: String!
  examType: String!
  course: String!
  semester: String!
  subject: String!
  examDate: String!
  startTime: String!
  endTime: String!
  roomNo: String!
}

type HallAllocation {
  id: String!
  examName: String!
  studentName: String!
  rollNo: String!
  hallNo: String!
  seatNo: String!
}

input CreateHallAllocationInput {
  examName: String!
  studentName: String!
  rollNo: String!
  hallNo: String!
  seatNo: String!
}

input UpdateHallAllocationInput {
  id: String!
  examName: String!
  studentName: String!
  rollNo: String!
  hallNo: String!
  seatNo: String!
}

type MarksEntry {
  id: String!
  examName: String!
  studentName: String!
  rollNo: String!
  subject: String!
  marksObtained: Int!
  maxMarks: Int!
  status: String!
}

input CreateMarksEntryInput {
  examName: String!
  studentName: String!
  rollNo: String!
  subject: String!
  marksObtained: Int!
  maxMarks: Int!
  status: String!
}

input UpdateMarksEntryInput {
  id: String!
  examName: String!
  studentName: String!
  rollNo: String!
  subject: String!
  marksObtained: Int!
  maxMarks: Int!
  status: String!
}

type ResultGeneration {
  id: String!
  examName: String!
  course: String!
  semester: String!
  resultDate: String!
  status: String!
}

input CreateResultGenerationInput {
  examName: String!
  course: String!
  semester: String!
  resultDate: String!
  status: String!
}

input UpdateResultGenerationInput {
  id: String!
  examName: String!
  course: String!
  semester: String!
  resultDate: String!
  status: String!
}

type ReportCard {
  id: String!
  studentName: String!
  rollNo: String!
  examName: String!
  totalMarks: Int!
  percentage: Float!
  grade: String!
  result: String!
}

input CreateReportCardInput {
  studentName: String!
  rollNo: String!
  examName: String!
  totalMarks: Int!
  percentage: Float!
  grade: String!
  result: String!
}

input UpdateReportCardInput {
  id: String!
  studentName: String!
  rollNo: String!
  examName: String!
  totalMarks: Int!
  percentage: Float!
  grade: String!
  result: String!
}

type LibraryAsset {
  id: String!
  no: String!
  title: String!
  subject: String!
  purchaseDate: String!
  department: String!
  type: String!
  status: String!
  lastBorrowed: String!
  borrowerName: String!
  dueDate: String!
  shelfLocation: String!
}

input CreateLibraryAssetInput {
  no: String!
  title: String!
  subject: String!
  purchaseDate: String!
  department: String!
  type: String!
  status: String!
  lastBorrowed: String!
  borrowerName: String!
  dueDate: String!
  shelfLocation: String!
}

input UpdateLibraryAssetInput {
  id: String!
  no: String!
  title: String!
  subject: String!
  purchaseDate: String!
  department: String!
  type: String!
  status: String!
  lastBorrowed: String!
  borrowerName: String!
  dueDate: String!
  shelfLocation: String!
}

type BookStatus {
  bookStatusID: String!
  bookID: String!
  bookName: String!
  status: String!
  dateUpdated: String!
  lastCheckedOutDate: String!
  dueDate: String!
  checkedOutBy: String!
  reservedBy: String!
  condition: String!
  returnDate: String!
  notes: String!
}

input CreateBookStatusInput {
  bookID: String!
  bookName: String!
  status: String!
  dateUpdated: String!
  lastCheckedOutDate: String!
  dueDate: String!
  checkedOutBy: String!
  reservedBy: String!
  condition: String!
  returnDate: String!
  notes: String!
}

input UpdateBookStatusInput {
  bookStatusID: String!
  bookID: String!
  bookName: String!
  status: String!
  dateUpdated: String!
  lastCheckedOutDate: String!
  dueDate: String!
  checkedOutBy: String!
  reservedBy: String!
  condition: String!
  returnDate: String!
  notes: String!
}

type IssueReturn {
  id: String!
  bookNo: String!
  bookTitle: String!
  studentName: String!
  rollNo: String!
  issueDate: String!
  returnDate: String!
  status: String!
}

input CreateIssueReturnInput {
  bookNo: String!
  bookTitle: String!
  studentName: String!
  rollNo: String!
  issueDate: String!
  returnDate: String!
  status: String!
}

input UpdateIssueReturnInput {
  id: String!
  bookNo: String!
  bookTitle: String!
  studentName: String!
  rollNo: String!
  issueDate: String!
  returnDate: String!
  status: String!
}

type LibraryReport {
  id: String!
  reportName: String!
  generatedDate: String!
  type: String!
  status: String!
}

input CreateLibraryReportInput {
  reportName: String!
  generatedDate: String!
  type: String!
  status: String!
}

input UpdateLibraryReportInput {
  id: String!
  reportName: String!
  generatedDate: String!
  type: String!
  status: String!
}

type Staff {
  id: String!
  img: String!
  name: String!
  email: String!
  address: String!
  mobile: String!
  department: String!
  status: String!
  joiningDate: String!
  salary: String!
  experience: String!
  role: String!
  dateOfBirth: String!
  gender: String!
}

input CreateStaffInput {
  img: String!
  name: String!
  email: String!
  address: String!
  mobile: String!
  department: String!
  status: String!
  joiningDate: String!
  salary: String!
  experience: String!
  role: String!
  dateOfBirth: String!
  gender: String!
}

input UpdateStaffInput {
  id: String!
  img: String!
  name: String!
  email: String!
  address: String!
  mobile: String!
  department: String!
  status: String!
  joiningDate: String!
  salary: String!
  experience: String!
  role: String!
  dateOfBirth: String!
  gender: String!
}

scalar Time

type StaffAttendance {
  id: String!
  img: String!
  name: String!
  employeeId: String!
  designation: String!
  date: String!
  checkIn: String!
  breakTime: String!
  checkOut: String!
  total: String!
  shift: String!
  lateArrival: String!
  earlyDeparture: String!
  absenceReason: String!
  overtime: String!
  totalBreaks: String!
  remarks: String!
  attendanceStatus: String!
  department: String!
}

input CreateStaffAttendanceInput {
  img: String!
  name: String!
  employeeId: String!
  designation: String!
  date: String!
  checkIn: String!
  breakTime: String!
  checkOut: String!
  total: String!
  shift: String!
  lateArrival: String!
  earlyDeparture: String!
  absenceReason: String!
  overtime: String!
  totalBreaks: String!
  remarks: String!
  attendanceStatus: String!
  department: String!
}

input UpdateStaffAttendanceInput {
  id: String!
  img: String!
  name: String!
  employeeId: String!
  designation: String!
  date: String!
  checkIn: String!
  breakTime: String!
  checkOut: String!
  total: String!
  shift: String!
  lateArrival: String!
  earlyDeparture: String!
  absenceReason: String!
  overtime: String!
  totalBreaks: String!
  remarks: String!
  attendanceStatus: String!
  department: String!
}

type LeaveRequest {
  id: String!
  img: String!
  name: String!
  employeeId: String!
  department: String!
  type: String!
  from: String!
  leaveTo: String!
  noOfDays: String!
  durationType: String!
  status: String!
  reason: String!
  note: String!
  requestedOn: String!
  approvedBy: String!
  approvalDate: String!
}

input CreateLeaveRequestInput {
  img: String!
  name: String!
  employeeId: String!
  department: String!
  type: String!
  from: String!
  leaveTo: String!
  noOfDays: String!
  durationType: String!
  status: String!
  reason: String!
  note: String!
  requestedOn: String!
  approvedBy: String!
  approvalDate: String!
}

input UpdateLeaveRequestInput {
  id: String!
  img: String!
  name: String!
  employeeId: String!
  department: String!
  type: String!
  from: String!
  leaveTo: String!
  noOfDays: String!
  durationType: String!
  status: String!
  reason: String!
  note: String!
  requestedOn: String!
  approvedBy: String!
  approvalDate: String!
}

type LeaveBalance {
  id: String!
  img: String!
  name: String!
  prev: String!
  current: String!
  total: String!
  used: String!
  accepted: String!
  rejected: String!
  expired: String!
  carryOver: String!
}

input CreateLeaveBalanceInput {
  img: String!
  name: String!
  prev: String!
  current: String!
  total: String!
  used: String!
  accepted: String!
  rejected: String!
  expired: String!
  carryOver: String!
}

input UpdateLeaveBalanceInput {
  id: String!
  img: String!
  name: String!
  prev: String!
  current: String!
  total: String!
  used: String!
  accepted: String!
  rejected: String!
  expired: String!
  carryOver: String!
}


type LeaveTypes {
  id: String!
  leaveName: String!
  leaveUnit: String!
  type: String!
  status: String!
  note: String!
  duration: Int!
  createdBy: String!
  carryOver: String!
  notificationPeriod: String!
  maxLeaves: Int!
  annualLimit: Int!
}

input CreateLeaveTypesInput {
  leaveName: String!
  leaveUnit: String!
  type: String!
  status: String!
  note: String!
  duration: Int!
  createdBy: String!
  carryOver: String!
  notificationPeriod: String!
  maxLeaves: Int!
  annualLimit: Int!
}

input UpdateLeaveTypesInput {
  id: String!
  leaveName: String!
  leaveUnit: String!
  type: String!
  status: String!
  note: String!
  duration: Int!
  createdBy: String!
  carryOver: String!
  notificationPeriod: String!
  maxLeaves: Int!
  annualLimit: Int!
}


type Holiday {
  id: String!
  holidayName: String!
  date: String!
  location: String!
  shift: String!
  details: String!
  holidayType: String!
  createdBy: String!
  creationDate: String!
  approvalStatus: String!
}

input CreateHolidayInput {
  holidayName: String!
  date: String!
  location: String!
  shift: String!
  details: String!
  holidayType: String!
  createdBy: String!
  creationDate: String!
  approvalStatus: String!
}

input UpdateHolidayInput {
  id: String!
  holidayName: String!
  date: String!
  location: String!
  shift: String!
  details: String!
  holidayType: String!
  createdBy: String!
  creationDate: String!
  approvalStatus: String!
}

type TodaysAttendance {
  id: String!
  img: String!
  name: String!
  firstIn: String!
  break: String!
  lastOut: String!
  total: String!
  status: String!
  shift: String!
}

input CreateTodaysAttendanceInput {
  img: String!
  name: String!
  firstIn: String!
  break: String!
  lastOut: String!
  total: String!
  status: String!
  shift: String!
}

input UpdateTodaysAttendanceInput {
  id: String!
  img: String!
  name: String!
  firstIn: String!
  break: String!
  lastOut: String!
  total: String!
  status: String!
  shift: String!
}


type EmployeeSalary {
  id: String!
  img: String!
  name: String!
  email: String!
  payslip: String!
  role: String!
  empId: String!
  department: String!
  salary: String!
  bonus: String!
  deductions: String!
  netSalary: String!
}

input CreateEmployeeSalaryInput {
  img: String!
  name: String!
  email: String!
  payslip: String!
  role: String!
  empId: String!
  department: String!
  salary: String!
  bonus: String!
  deductions: String!
  netSalary: String!
}

input UpdateEmployeeSalaryInput {
  id: String!
  img: String!
  name: String!
  email: String!
  payslip: String!
  role: String!
  empId: String!
  department: String!
  salary: String!
  bonus: String!
  deductions: String!
  netSalary: String!
}

type Vehicle {
  id: String!
  vehicleNo: String!
  vehicleModel: String!
  yearMade: String!
  driverName: String!
  driverLicense: String!
  vehicleType: String!
  status: String!
  img: String!
}

input CreateVehicleInput {
  vehicleNo: String!
  vehicleModel: String!
  yearMade: String!
  driverName: String!
  driverLicense: String!
  vehicleType: String!
  status: String!
  img: String!
}

input UpdateVehicleInput {
  id: String!
  vehicleNo: String!
  vehicleModel: String!
  yearMade: String!
  driverName: String!
  driverLicense: String!
  vehicleType: String!
  status: String!
  img: String!
}

type TransportRoute {
  id: String!
  routeName: String!
  startPoint: String!
  endPoint: String!
  distance: String!
  vehicleNo: String!
  routeFees: String!
  status: String!
}

input CreateTransportRouteInput {
  routeName: String!
  startPoint: String!
  endPoint: String!
  distance: String!
  vehicleNo: String!
  routeFees: String!
  status: String!
}

input UpdateTransportRouteInput {
  id: String!
  routeName: String!
  startPoint: String!
  endPoint: String!
  distance: String!
  vehicleNo: String!
  routeFees: String!
  status: String!
}

type Driver {
  id: String!
  driverName: String!
  licenseNo: String!
  phone: String!
  joiningDate: String!
  address: String!
  experience: String!
  status: String!
  img: String!
}

input CreateDriverInput {
  driverName: String!
  licenseNo: String!
  phone: String!
  joiningDate: String!
  address: String!
  experience: String!
  status: String!
  img: String!
}

input UpdateDriverInput {
  id: String!
  driverName: String!
  licenseNo: String!
  phone: String!
  joiningDate: String!
  address: String!
  experience: String!
  status: String!
  img: String!
}

type StudentAllocation {
  id: String!
  studentName: String!
  studentId: String!
  classSection: String!
  routeName: String!
  vehicleNo: String!
  stopPoint: String!
  allocationDate: String!
  status: String!
  img: String!
}

input CreateStudentAllocationInput {
  studentName: String!
  studentId: String!
  classSection: String!
  routeName: String!
  vehicleNo: String!
  stopPoint: String!
  allocationDate: String!
  status: String!
  img: String!
}

input UpdateStudentAllocationInput {
  id: String!
  studentName: String!
  studentId: String!
  classSection: String!
  routeName: String!
  vehicleNo: String!
  stopPoint: String!
  allocationDate: String!
  status: String!
  img: String!
}

type TransportFee {
  id: String!
  studentName: String!
  studentId: String!
  classSection: String!
  routeName: String!
  amount: String!
  paymentDate: String!
  paymentMethod: String!
  status: String!
  img: String!
}

input CreateTransportFeeInput {
  studentName: String!
  studentId: String!
  classSection: String!
  routeName: String!
  amount: String!
  paymentDate: String!
  paymentMethod: String!
  status: String!
  img: String!
}

input UpdateTransportFeeInput {
  id: String!
  studentName: String!
  studentId: String!
  classSection: String!
  routeName: String!
  amount: String!
  paymentDate: String!
  paymentMethod: String!
  status: String!
  img: String!
}

type NoticeBoard {
  id: String!
  img: String!
  title: String!
  postedBy: String!
  department: String!
  date: String!
  priority: String!
  status: String!
  description: String!
  targetAudience: String!
}

input CreateNoticeBoardInput {
  img: String!
  title: String!
  postedBy: String!
  department: String!
  date: String!
  priority: String!
  status: String!
  description: String!
  targetAudience: String!
}

input UpdateNoticeBoardInput {
  id: String!
  img: String!
  title: String!
  postedBy: String!
  department: String!
  date: String!
  priority: String!
  status: String!
  description: String!
  targetAudience: String!
}

type Announcement {
  id: String!
  img: String!
  title: String!
  announcementType: String!
  postedBy: String!
  startDate: String!
  endDate: String!
  status: String!
  description: String!
  priority: String!
}

input CreateAnnouncementInput {
  img: String!
  title: String!
  announcementType: String!
  postedBy: String!
  startDate: String!
  endDate: String!
  status: String!
  description: String!
  priority: String!
}

input UpdateAnnouncementInput {
  id: String!
  img: String!
  title: String!
  announcementType: String!
  postedBy: String!
  startDate: String!
  endDate: String!
  status: String!
  description: String!
  priority: String!
}

type Fees {
  id: String!
  rollNo: String!
  studentName: String!
  class: String!
  feesType: String!
  invoiceNo: String!
  paymentDueDate: String!
  paymentDate: String!
  paymentType: String!
  status: String!
  amount: String!
  lateFee: String!
  discount: String!
  createdAt: String!
  updatedAt: String!
  notes: String!
}

input CreateFeesInput {
  rollNo: String!
  studentName: String!
  class: String!
  feesType: String!
  invoiceNo: String!
  paymentDueDate: String!
  paymentDate: String!
  paymentType: String!
  status: String!
  amount: String!
  lateFee: String!
  discount: String!
  createdAt: String!
  updatedAt: String!
  notes: String!
}

input UpdateFeesInput {
  id: String!
  rollNo: String!
  studentName: String!
  class: String!
  feesType: String!
  invoiceNo: String!
  paymentDueDate: String!
  paymentDate: String!
  paymentType: String!
  status: String!
  amount: String!
  lateFee: String!
  discount: String!
  createdAt: String!
  updatedAt: String!
  notes: String!
}

type FeesType {
  feeTypeId: String!
  feeTypeName: String!
  category: String!
  description: String!
  amount: Float!
  applicableClasses: String!
  frequency: String!
  status: String!
  createdBy: String!
  createdDate: String!
  lastUpdated: String!
}

input CreateFeesTypeInput {
  feeTypeName: String!
  category: String!
  description: String!
  amount: Float!
  applicableClasses: String!
  frequency: String!
  status: String!
  createdBy: String!
  createdDate: String!
  lastUpdated: String!
}

input UpdateFeesTypeInput {
  feeTypeId: String!
  feeTypeName: String!
  category: String!
  description: String!
  amount: Float!
  applicableClasses: String!
  frequency: String!
  status: String!
  createdBy: String!
  createdDate: String!
  lastUpdated: String!
}

type FeesDiscount {
  discountId: String!
  discountType: String!
  discountAmount: Float!
  discountPercentage: Float!
  discountCode: String!
  startDate: String!
  endDate: String!
  appliedDate: String!
  status: String!
  remarks: String!
}

input CreateFeesDiscountInput {
  discountType: String!
  discountAmount: Float!
  discountPercentage: Float!
  discountCode: String!
  startDate: String!
  endDate: String!
  appliedDate: String!
  status: String!
  remarks: String!
}

input UpdateFeesDiscountInput {
  discountId: String!
  discountType: String!
  discountAmount: Float!
  discountPercentage: Float!
  discountCode: String!
  startDate: String!
  endDate: String!
  appliedDate: String!
  status: String!
  remarks: String!
}

type ClassList {
  classId: String!
  className: String!
  classCode: String!
  teacherId: String!
  startDate: String!
  endDate: String!
  roomNumber: String!
  schedule: String!
  semester: String!
  classCapacity: Int!
  status: String!
  description: String!
  classType: String!
  createdAt: String!
  updatedAt: String!
}

input CreateClassListInput {
  className: String!
  classCode: String!
  teacherId: String!
  startDate: String!
  endDate: String!
  roomNumber: String!
  schedule: String!
  semester: String!
  classCapacity: Int!
  status: String!
  description: String!
  classType: String!
  createdAt: String!
  updatedAt: String!
}

input UpdateClassListInput {
  classId: String!
  className: String!
  classCode: String!
  teacherId: String!
  startDate: String!
  endDate: String!
  roomNumber: String!
  schedule: String!
  semester: String!
  classCapacity: Int!
  status: String!
  description: String!
  classType: String!
  createdAt: String!
  updatedAt: String!
}

type AcademicYearCustom {
  id: String!
  academicYear: String!
  status: String!
  startDate: String!
  endDate: String!
  description: String!
  department: String!
}

input CreateAcademicYearCustomInput {
  academicYear: String!
  status: String!
  startDate: String!
  endDate: String!
  description: String!
  department: String!
}

input UpdateAcademicYearCustomInput {
  id: String!
  academicYear: String!
  status: String!
  startDate: String!
  endDate: String!
  description: String!
  department: String!
}

type SessionCustom {
  id: String!
  sessionName: String!
  startDate: String!
  endDate: String!
  status: String!
  instructor: String!
  room: String!
}

input CreateSessionCustomInput {
  sessionName: String!
  startDate: String!
  endDate: String!
  status: String!
  instructor: String!
  room: String!
}

input UpdateSessionCustomInput {
  id: String!
  sessionName: String!
  startDate: String!
  endDate: String!
  status: String!
  instructor: String!
  room: String!
}

type AcademicClassCustom {
  id: String!
  className: String!
  section: String!
  academicYear: String!
  teacher: String!
  status: String!
  studentCount: String!
  roomNumber: String!
}

input CreateAcademicClassCustomInput {
  className: String!
  section: String!
  academicYear: String!
  teacher: String!
  status: String!
  studentCount: String!
  roomNumber: String!
}

input UpdateAcademicClassCustomInput {
  id: String!
  className: String!
  section: String!
  academicYear: String!
  teacher: String!
  status: String!
  studentCount: String!
  roomNumber: String!
}

type AcademicSubjectCustom {
  id: String!
  subjectName: String!
  subjectCode: String!
  subjectType: String!
  status: String!
  prerequisites: String!
  credits: String!
}

input CreateAcademicSubjectCustomInput {
  subjectName: String!
  subjectCode: String!
  subjectType: String!
  status: String!
  prerequisites: String!
  credits: String!
}

input UpdateAcademicSubjectCustomInput {
  id: String!
  subjectName: String!
  subjectCode: String!
  subjectType: String!
  status: String!
  prerequisites: String!
  credits: String!
}

type CourseCurriculumCustom {
  id: String!
  courseName: String!
  className: String!
  subjectName: String!
  description: String!
  status: String!
  duration: String!
  referenceMaterial: String!
}

input CreateCourseCurriculumCustomInput {
  courseName: String!
  className: String!
  subjectName: String!
  description: String!
  status: String!
  duration: String!
  referenceMaterial: String!
}

input UpdateCourseCurriculumCustomInput {
  id: String!
  courseName: String!
  className: String!
  subjectName: String!
  description: String!
  status: String!
  duration: String!
  referenceMaterial: String!
}

type AssignmentCustom {
  id: String!
  className: String!
  subjectName: String!
  teacherName: String!
  assignmentDate: String!
  status: String!
  title: String!
  deadline: String!
  details: String!
}

input CreateAssignmentCustomInput {
  className: String!
  subjectName: String!
  teacherName: String!
  assignmentDate: String!
  status: String!
  title: String!
  deadline: String!
  details: String!
}

input UpdateAssignmentCustomInput {
  id: String!
  className: String!
  subjectName: String!
  teacherName: String!
  assignmentDate: String!
  status: String!
  title: String!
  deadline: String!
  details: String!
}

type LessonPlanningCustom {
  id: String!
  topicName: String!
  lessonName: String!
  className: String!
  subjectName: String!
  teacherName: String!
  lessonDate: String!
  status: String!
  objectives: String!
  teachingMethod: String!
}

input CreateLessonPlanningCustomInput {
  topicName: String!
  lessonName: String!
  className: String!
  subjectName: String!
  teacherName: String!
  lessonDate: String!
  status: String!
  objectives: String!
  teachingMethod: String!
}

input UpdateLessonPlanningCustomInput {
  id: String!
  topicName: String!
  lessonName: String!
  className: String!
  subjectName: String!
  teacherName: String!
  lessonDate: String!
  status: String!
  objectives: String!
  teachingMethod: String!
}

type HostelRoomCustom {
  roomId: String!
  roomNumber: String!
  roomType: String!
  floor: Int!
  capacity: Int!
  occupiedStatus: String!
  currentOccupants: Int!
  priceFees: Float!
  roomCondition: String!
  dateAssigned: String!
  roomSupervisorStaff: String!
  hostelBlock: String!
  checkInDate: String!
  checkOutDate: String!
  roomTypeCode: String!
  roomDescription: String!
}

input CreateHostelRoomCustomInput {
  roomNumber: String!
  roomType: String!
  floor: Int!
  capacity: Int!
  occupiedStatus: String!
  currentOccupants: Int!
  priceFees: Float!
  roomCondition: String!
  dateAssigned: String!
  roomSupervisorStaff: String!
  hostelBlock: String!
  checkInDate: String!
  checkOutDate: String!
  roomTypeCode: String!
  roomDescription: String!
}

input UpdateHostelRoomCustomInput {
  roomId: String!
  roomNumber: String!
  roomType: String!
  floor: Int!
  capacity: Int!
  occupiedStatus: String!
  currentOccupants: Int!
  priceFees: Float!
  roomCondition: String!
  dateAssigned: String!
  roomSupervisorStaff: String!
  hostelBlock: String!
  checkInDate: String!
  checkOutDate: String!
  roomTypeCode: String!
  roomDescription: String!
}

type HostelRoomTypeCustom {
  roomTypeId: String!
  roomTypeName: String!
  capacity: Int!
  roomCategory: String!
  roomDescription: String!
  roomPrice: Float!
  roomFacilities: String!
  roomArea: Float!
  roomCondition: String!
  roomTypeCode: String!
  createdAt: String!
  updatedAt: String!
  status: String!
  maxOccupants: Int!
}

input CreateHostelRoomTypeCustomInput {
  roomTypeName: String!
  capacity: Int!
  roomCategory: String!
  roomDescription: String!
  roomPrice: Float!
  roomFacilities: String!
  roomArea: Float!
  roomCondition: String!
  roomTypeCode: String!
  status: String!
  maxOccupants: Int!
}

input UpdateHostelRoomTypeCustomInput {
  roomTypeId: String!
  roomTypeName: String!
  capacity: Int!
  roomCategory: String!
  roomDescription: String!
  roomPrice: Float!
  roomFacilities: String!
  roomArea: Float!
  roomCondition: String!
  roomTypeCode: String!
  status: String!
  maxOccupants: Int!
}

type HostelAllocationCustom {
  id: String!
  img: String!
  student_name: String!
  roll_no: String!
  hostel_name: String!
  room_no: String!
  room_type: String!
  allocation_date: String!
  status: String!
}

input CreateHostelAllocationCustomInput {
  img: String!
  student_name: String!
  roll_no: String!
  hostel_name: String!
  room_no: String!
  room_type: String!
  allocation_date: String!
  status: String!
}

input UpdateHostelAllocationCustomInput {
  id: String!
  img: String!
  student_name: String!
  roll_no: String!
  hostel_name: String!
  room_no: String!
  room_type: String!
  allocation_date: String!
  status: String!
}

type HostelAttendanceCustom {
  id: String!
  img: String!
  student_name: String!
  roll_no: String!
  hostel_name: String!
  room_no: String!
  attendance_date: String!
  status: String!
  note: String!
}

input CreateHostelAttendanceCustomInput {
  img: String!
  student_name: String!
  roll_no: String!
  hostel_name: String!
  room_no: String!
  attendance_date: String!
  status: String!
  note: String!
}

input UpdateHostelAttendanceCustomInput {
  id: String!
  img: String!
  student_name: String!
  roll_no: String!
  hostel_name: String!
  room_no: String!
  attendance_date: String!
  status: String!
  note: String!
}

type HostelFeeCustom {
  id: String!
  img: String!
  student_name: String!
  roll_no: String!
  hostel_name: String!
  room_no: String!
  fee_type: String!
  amount: Float!
  payment_date: String!
  payment_status: String!
}

input CreateHostelFeeCustomInput {
  img: String!
  student_name: String!
  roll_no: String!
  hostel_name: String!
  room_no: String!
  fee_type: String!
  amount: Float!
  payment_date: String!
  payment_status: String!
}

input UpdateHostelFeeCustomInput {
  id: String!
  img: String!
  student_name: String!
  roll_no: String!
  hostel_name: String!
  room_no: String!
  fee_type: String!
  amount: Float!
  payment_date: String!
  payment_status: String!
}

type DepartmentCustom {
  id: String!
  img: String!
  department_name: String!
  hod: String!
  phone: String!
  email: String!
  student_capacity: String!
  establishedYear: String!
  totalFaculty: String!
}

input CreateDepartmentCustomInput {
  img: String!
  department_name: String!
  hod: String!
  phone: String!
  email: String!
  student_capacity: String!
  establishedYear: String!
  totalFaculty: String!
}

input UpdateDepartmentCustomInput {
  id: String!
  img: String!
  department_name: String!
  hod: String!
  phone: String!
  email: String!
  student_capacity: String!
  establishedYear: String!
  totalFaculty: String!
}

type AcademicReportCustom {
  id: String!
  img: String!
  reportType: String!
  className: String!
  subject: String!
  academicYear: String!
  term: String!
  generatedBy: String!
  date: String!
  status: String!
}

input CreateAcademicReportCustomInput {
  img: String!
  reportType: String!
  className: String!
  subject: String!
  academicYear: String!
  term: String!
  generatedBy: String!
  date: String!
  status: String!
}

input UpdateAcademicReportCustomInput {
  id: String!
  img: String!
  reportType: String!
  className: String!
  subject: String!
  academicYear: String!
  term: String!
  generatedBy: String!
  date: String!
  status: String!
}

type AttendanceReportCustom {
  id: String!
  img: String!
  reportType: String!
  className: String!
  dateFrom: String!
  dateTo: String!
  attendancePercentage: Float!
  generatedBy: String!
  date: String!
  status: String!
}

input CreateAttendanceReportCustomInput {
  img: String!
  reportType: String!
  className: String!
  dateFrom: String!
  dateTo: String!
  attendancePercentage: Float!
  generatedBy: String!
  date: String!
  status: String!
}

input UpdateAttendanceReportCustomInput {
  id: String!
  img: String!
  reportType: String!
  className: String!
  dateFrom: String!
  dateTo: String!
  attendancePercentage: Float!
  generatedBy: String!
  date: String!
  status: String!
}

type FeeReportCustom {
  id: String!
  img: String!
  reportType: String!
  feeCategory: String!
  dateFrom: String!
  dateTo: String!
  totalAmount: Float!
  generatedBy: String!
  date: String!
  status: String!
}

input CreateFeeReportCustomInput {
  img: String!
  reportType: String!
  feeCategory: String!
  dateFrom: String!
  dateTo: String!
  totalAmount: Float!
  generatedBy: String!
  date: String!
  status: String!
}

input UpdateFeeReportCustomInput {
  id: String!
  img: String!
  reportType: String!
  feeCategory: String!
  dateFrom: String!
  dateTo: String!
  totalAmount: Float!
  generatedBy: String!
  date: String!
  status: String!
}

type ExamReportCustom {
  id: String!
  img: String!
  examName: String!
  className: String!
  subject: String!
  examDate: String!
  passPercentage: Float!
  averageMarks: Float!
  generatedBy: String!
  date: String!
  status: String!
}

input CreateExamReportCustomInput {
  img: String!
  examName: String!
  className: String!
  subject: String!
  examDate: String!
  passPercentage: Float!
  averageMarks: Float!
  generatedBy: String!
  date: String!
  status: String!
}

input UpdateExamReportCustomInput {
  id: String!
  img: String!
  examName: String!
  className: String!
  subject: String!
  examDate: String!
  passPercentage: Float!
  averageMarks: Float!
  generatedBy: String!
  date: String!
  status: String!
}

type CustomReportCustom {
  id: String!
  reportName: String!
  description: String!
  category: String!
  createdBy: String!
  date: String!
  status: String!
}

input CreateCustomReportCustomInput {
  reportName: String!
  description: String!
  category: String!
  createdBy: String!
  date: String!
  status: String!
}

input UpdateCustomReportCustomInput {
  id: String!
  reportName: String!
  description: String!
  category: String!
  createdBy: String!
  date: String!
  status: String!
}

type TodayScheduleCustom {
  id: String!
  subject: String!
  class: String!
  time: String!
  duration: String!
  room: String!
  status: String!
}

input CreateTodayScheduleCustomInput {
  subject: String!
  class: String!
  time: String!
  duration: String!
  room: String!
  status: String!
}

input UpdateTodayScheduleCustomInput {
  id: String!
  subject: String!
  class: String!
  time: String!
  duration: String!
  room: String!
  status: String!
}

type TeacherClassCustom {
  id: String!
  className: String!
  subject: String!
  time: String!
  roomNo: String!
}

input CreateTeacherClassCustomInput {
  className: String!
  subject: String!
  time: String!
  roomNo: String!
}

input UpdateTeacherClassCustomInput {
  id: String!
  className: String!
  subject: String!
  time: String!
  roomNo: String!
}

type TeacherLessonPlanCustom {
  id: String!
  class: String!
  subject: String!
  topic: String!
  date: String!
  status: String!
  lessonDetails: String!
}

input CreateTeacherLessonPlanCustomInput {
  class: String!
  subject: String!
  topic: String!
  date: String!
  status: String!
  lessonDetails: String!
}

input UpdateTeacherLessonPlanCustomInput {
  id: String!
  class: String!
  subject: String!
  topic: String!
  date: String!
  status: String!
  lessonDetails: String!
}

type StudentStudyMaterialCustom {
  id: String!
  title: String!
  subject: String!
  type: String!
  date: String!
  downloadUrl: String!
}

input CreateStudentStudyMaterialCustomInput {
  title: String!
  subject: String!
  type: String!
  date: String!
  downloadUrl: String!
}

input UpdateStudentStudyMaterialCustomInput {
  id: String!
  title: String!
  subject: String!
  type: String!
  date: String!
  downloadUrl: String!
}

type TeacherStudyMaterialCustom {
  id: String!
  class: String!
  subject: String!
  title: String!
  type: String!
  uploadDate: String!
  fileUrl: String!
}

input CreateTeacherStudyMaterialCustomInput {
  class: String!
  subject: String!
  title: String!
  type: String!
  uploadDate: String!
  fileUrl: String!
}

input UpdateTeacherStudyMaterialCustomInput {
  id: String!
  class: String!
  subject: String!
  title: String!
  type: String!
  uploadDate: String!
  fileUrl: String!
}

type TeacherAssignmentCustom {
  id: String!
  class: String!
  subject: String!
  title: String!
  assignedDate: String!
  dueDate: String!
  status: String!
  submissions: Int!
}

input CreateTeacherAssignmentCustomInput {
  class: String!
  subject: String!
  title: String!
  assignedDate: String!
  dueDate: String!
  status: String!
  submissions: Int!
}

input UpdateTeacherAssignmentCustomInput {
  id: String!
  class: String!
  subject: String!
  title: String!
  assignedDate: String!
  dueDate: String!
  status: String!
  submissions: Int!
}

type TeacherClassStudentCustom {
  id: String!
  rollNo: String!
  name: String!
  gender: String!
  parentName: String!
  mobile: String!
  email: String!
  address: String!
}

input CreateTeacherClassStudentCustomInput {
  rollNo: String!
  name: String!
  gender: String!
  parentName: String!
  mobile: String!
  email: String!
  address: String!
}

input UpdateTeacherClassStudentCustomInput {
  id: String!
  rollNo: String!
  name: String!
  gender: String!
  parentName: String!
  mobile: String!
  email: String!
  address: String!
}

type TeacherStudentAttendanceCustom {
  id: String!
  rollNo: String!
  name: String!
  date: String!
  status: String!
  remarks: String!
}

input CreateTeacherStudentAttendanceCustomInput {
  rollNo: String!
  name: String!
  date: String!
  status: String!
  remarks: String!
}

input UpdateTeacherStudentAttendanceCustomInput {
  id: String!
  rollNo: String!
  name: String!
  date: String!
  status: String!
  remarks: String!
}

type TeacherStudentPerformanceCustom {
  id: String!
  rollNo: String!
  name: String!
  subject: String!
  internalMarks: Int!
  externalMarks: Int!
  totalMarks: Int!
  grade: String!
}

input CreateTeacherStudentPerformanceCustomInput {
  rollNo: String!
  name: String!
  subject: String!
  internalMarks: Int!
  externalMarks: Int!
  totalMarks: Int!
  grade: String!
}

input UpdateTeacherStudentPerformanceCustomInput {
  id: String!
  rollNo: String!
  name: String!
  subject: String!
  internalMarks: Int!
  externalMarks: Int!
  totalMarks: Int!
  grade: String!
}

type TeacherMarksEntryCustom {
  id: String!
  rollNo: String!
  studentName: String!
  class: String!
  subject: String!
  marksObtained: Int!
  maxMarks: Int!
  status: String!
}

input CreateTeacherMarksEntryCustomInput {
  rollNo: String!
  studentName: String!
  class: String!
  subject: String!
  marksObtained: Int!
  maxMarks: Int!
  status: String!
}

input UpdateTeacherMarksEntryCustomInput {
  id: String!
  rollNo: String!
  studentName: String!
  class: String!
  subject: String!
  marksObtained: Int!
  maxMarks: Int!
  status: String!
}

type TeacherGradeSubmissionCustom {
  id: String!
  rollNo: String!
  studentName: String!
  averageMarks: Int!
  grade: String!
  status: String!
  submissionDate: String!
}

input CreateTeacherGradeSubmissionCustomInput {
  rollNo: String!
  studentName: String!
  averageMarks: Int!
  grade: String!
  status: String!
  submissionDate: String!
}

input UpdateTeacherGradeSubmissionCustomInput {
  id: String!
  rollNo: String!
  studentName: String!
  averageMarks: Int!
  grade: String!
  status: String!
  submissionDate: String!
}

type TeacherTimetableCustom {
  id: String!
  day: String!
  timeSlot: String!
  subject: String!
  class: String!
  room: String!
}

input CreateTeacherTimetableCustomInput {
  day: String!
  timeSlot: String!
  subject: String!
  class: String!
  room: String!
}

input UpdateTeacherTimetableCustomInput {
  id: String!
  day: String!
  timeSlot: String!
  subject: String!
  class: String!
  room: String!
}

type TeacherSubstitutionRequestCustom {
  id: String!
  date: String!
  timeSlot: String!
  class: String!
  subject: String!
  reason: String!
  status: String!
}

input CreateTeacherSubstitutionRequestCustomInput {
  date: String!
  timeSlot: String!
  class: String!
  subject: String!
  reason: String!
  status: String!
}

input UpdateTeacherSubstitutionRequestCustomInput {
  id: String!
  date: String!
  timeSlot: String!
  class: String!
  subject: String!
  reason: String!
  status: String!
}

type TeacherNoticeCustom {
  id: String!
  title: String!
  date: String!
  category: String!
  details: String!
}

input CreateTeacherNoticeCustomInput {
  title: String!
  date: String!
  category: String!
  details: String!
}

input UpdateTeacherNoticeCustomInput {
  id: String!
  title: String!
  date: String!
  category: String!
  details: String!
}

type TeacherAnnouncementCustom {
  id: String!
  title: String!
  date: String!
  target: String!
  description: String!
}

input CreateTeacherAnnouncementCustomInput {
  title: String!
  date: String!
  target: String!
  description: String!
}

input UpdateTeacherAnnouncementCustomInput {
  id: String!
  title: String!
  date: String!
  target: String!
  description: String!
}

type TeacherDailyAttendanceCustom {
  id: String!
  rollNo: String!
  studentName: String!
  class: String!
  date: String!
  status: String!
  note: String!
}

input CreateTeacherDailyAttendanceCustomInput {
  rollNo: String!
  studentName: String!
  class: String!
  date: String!
  status: String!
  note: String!
}

input UpdateTeacherDailyAttendanceCustomInput {
  id: String!
  rollNo: String!
  studentName: String!
  class: String!
  date: String!
  status: String!
  note: String!
}

type TeacherAttendanceSummaryCustom {
  id: String!
  class: String!
  subject: String!
  totalStudents: Int!
  present: Int!
  absent: Int!
  onLeave: Int!
  attendancePercentage: String!
  date: String!
}

input CreateTeacherAttendanceSummaryCustomInput {
  class: String!
  subject: String!
  totalStudents: Int!
  present: Int!
  absent: Int!
  onLeave: Int!
  attendancePercentage: String!
  date: String!
}

input UpdateTeacherAttendanceSummaryCustomInput {
  id: String!
  class: String!
  subject: String!
  totalStudents: Int!
  present: Int!
  absent: Int!
  onLeave: Int!
  attendancePercentage: String!
  date: String!
}

type TeacherLeaveStatusCustom {
  id: String!
  leaveType: String!
  startDate: String!
  endDate: String!
  days: Int!
  applyDate: String!
  status: String!
  reason: String!
}

input CreateTeacherLeaveStatusCustomInput {
  leaveType: String!
  startDate: String!
  endDate: String!
  days: Int!
  applyDate: String!
  status: String!
  reason: String!
}

input UpdateTeacherLeaveStatusCustomInput {
  id: String!
  leaveType: String!
  startDate: String!
  endDate: String!
  days: Int!
  applyDate: String!
  status: String!
  reason: String!
}

type TeacherLectureCustom {
  id: String!
  subjectName: String!
  class: String!
  date: String!
  time: String!
  status: String!
  teacher_id: String!
  subject_id: String!
  student_group: String!
  duration: Int!
  location: String!
  attendance_count: Int!
  created_at: String!
  updated_at: String!
  reason_for_cancellation: String!
}

input CreateTeacherLectureCustomInput {
  subjectName: String!
  class: String!
  date: String!
  time: String!
  status: String!
  teacher_id: String!
  subject_id: String!
  student_group: String!
  duration: Int!
  location: String!
  attendance_count: Int!
  reason_for_cancellation: String!
}

input UpdateTeacherLectureCustomInput {
  id: String!
  subjectName: String!
  class: String!
  date: String!
  time: String!
  status: String!
  teacher_id: String!
  subject_id: String!
  student_group: String!
  duration: Int!
  location: String!
  attendance_count: Int!
  reason_for_cancellation: String!
}
