package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"go-seed/ent/user"
	"os"
	"time"

	jwt "github.com/golang-jwt/jwt/v5"
	_ "github.com/lib/pq"
	"golang.org/x/crypto/bcrypt"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input LoginInput) (*LoginResponse, error) {
	// Find user in database
	u, err := r.Client.User.
		Query().
		Where(user.UsernameEqualFold(input.Username)).
		Only(ctx)
	if err != nil {
		return nil, errors.New("invalid username or password")
	}

	// Compare passwords
	if err := bcrypt.CompareHashAndPassword([]byte(u.PasswordHash), []byte(input.Password)); err != nil {
		return nil, errors.New("invalid username or password")
	}

	// Verify user is active
	if !u.IsActive {
		return nil, errors.New("account is inactive")
	}

	// Get JWT secret
	secret := os.Getenv("JWT_SECRET")
	if secret == "" {
		secret = "school-management-system-super-secret-key-123"
	}

	// Generate JWT Token
	token := jwt.NewWithClaims(jwt.SigningMethodHS256, jwt.MapClaims{
		"user_id":  u.ID.String(),
		"username": u.Username,
		"role":     string(u.Role),
		"exp":      time.Now().Add(24 * time.Hour).Unix(),
	})

	tokenString, err := token.SignedString([]byte(secret))
	if err != nil {
		return nil, errors.New("could not generate token")
	}

	return &LoginResponse{
		Token: tokenString,
		Role:  string(u.Role),
	}, nil
}

// AdmissionInquiries is the resolver for the admissionInquiries field.
func (r *queryResolver) AdmissionInquiries(ctx context.Context) ([]*AdmissionInquiry, error) {
	dbURL := os.Getenv("DATABASE_URL")
	if dbURL == "" {
		host := os.Getenv("DB_HOST")
		if host == "" {
			host = "localhost"
		}
		port := os.Getenv("DB_PORT")
		if port == "" {
			port = "5432"
		}
		user := os.Getenv("DB_USER")
		if user == "" {
			user = "postgres"
		}
		pass := os.Getenv("DB_PASSWORD")
		if pass == "" {
			pass = "postgres"
		}
		dbname := os.Getenv("DB_NAME")
		if dbname == "" {
			dbname = "school"
		}
		dbURL = fmt.Sprintf("postgres://%s:%s@%s:%s/%s?sslmode=disable", user, pass, host, port, dbname)
	}

	db, err := sql.Open("postgres", dbURL)
	if err != nil {
		return nil, fmt.Errorf("failed to open database: %w", err)
	}
	defer db.Close()

	rows, err := db.QueryContext(ctx, `
		SELECT 
			inquiry_id, COALESCE(student_name, ''), COALESCE(guardian_name, ''), 
			COALESCE(contact_number, ''), COALESCE(email_address, ''), 
			date_of_inquiry, COALESCE(program_of_interest, ''), preferred_start_date, 
			COALESCE(inquiry_source, ''), COALESCE(status, ''), COALESCE(notes, ''), 
			follow_up_date, assigned_to, COALESCE(campus_location, ''), 
			COALESCE(previous_education, ''), COALESCE(img, '') 
		FROM admission_inquiries
	`)
	if err != nil {
		return nil, fmt.Errorf("failed to query admission inquiries: %w", err)
	}
	defer rows.Close()

	var list []*AdmissionInquiry
	for rows.Next() {
		var (
			id, studentName, guardianName, contactNumber, emailAddress string
			dateOfInquiry, preferredStartDate, followUpDate sql.NullTime
			programOfInterest, inquirySource, status, notes, campusLocation, previousEducation, img string
			assignedTo sql.NullString
		)
		err := rows.Scan(
			&id, &studentName, &guardianName, &contactNumber, &emailAddress,
			&dateOfInquiry, &programOfInterest, &preferredStartDate, &inquirySource,
			&status, &notes, &followUpDate, &assignedTo, &campusLocation,
			&previousEducation, &img,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to scan row: %w", err)
		}

		list = append(list, &AdmissionInquiry{
			InquiryID:          id,
			StudentName:        studentName,
			GuardianName:       guardianName,
			ContactNumber:      contactNumber,
			EmailAddress:       emailAddress,
			DateOfInquiry:      formatNullTime(dateOfInquiry),
			ProgramOfInterest:  programOfInterest,
			PreferredStartDate: formatNullTime(preferredStartDate),
			InquirySource:      inquirySource,
			Status:             status,
			Notes:              notes,
			FollowUpDate:       formatNullTime(followUpDate),
			AssignedTo:         assignedTo.String,
			CampusLocation:     campusLocation,
			PreviousEducation:  previousEducation,
			Img:                img,
		})
	}
	return list, nil
}

func formatNullTime(nt sql.NullTime) string {
	if !nt.Valid {
		return ""
	}
	return nt.Time.Format("2006-01-02")
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
