// Code generated by ent, DO NOT EDIT.

package student

import (
	"go-seed/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Student {
	return predicate.Student(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Student {
	return predicate.Student(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Student {
	return predicate.Student(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Student {
	return predicate.Student(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Student {
	return predicate.Student(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Student {
	return predicate.Student(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Student {
	return predicate.Student(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Student {
	return predicate.Student(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Student {
	return predicate.Student(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.Student {
	return predicate.Student(sql.FieldEQ(FieldUserID, v))
}

// RollNumber applies equality check predicate on the "roll_number" field. It's identical to RollNumberEQ.
func RollNumber(v string) predicate.Student {
	return predicate.Student(sql.FieldEQ(FieldRollNumber, v))
}

// FirstName applies equality check predicate on the "first_name" field. It's identical to FirstNameEQ.
func FirstName(v string) predicate.Student {
	return predicate.Student(sql.FieldEQ(FieldFirstName, v))
}

// LastName applies equality check predicate on the "last_name" field. It's identical to LastNameEQ.
func LastName(v string) predicate.Student {
	return predicate.Student(sql.FieldEQ(FieldLastName, v))
}

// DateOfBirth applies equality check predicate on the "date_of_birth" field. It's identical to DateOfBirthEQ.
func DateOfBirth(v time.Time) predicate.Student {
	return predicate.Student(sql.FieldEQ(FieldDateOfBirth, v))
}

// Phone applies equality check predicate on the "phone" field. It's identical to PhoneEQ.
func Phone(v string) predicate.Student {
	return predicate.Student(sql.FieldEQ(FieldPhone, v))
}

// ParentPhone applies equality check predicate on the "parent_phone" field. It's identical to ParentPhoneEQ.
func ParentPhone(v string) predicate.Student {
	return predicate.Student(sql.FieldEQ(FieldParentPhone, v))
}

// Address applies equality check predicate on the "address" field. It's identical to AddressEQ.
func Address(v string) predicate.Student {
	return predicate.Student(sql.FieldEQ(FieldAddress, v))
}

// ClassID applies equality check predicate on the "class_id" field. It's identical to ClassIDEQ.
func ClassID(v int) predicate.Student {
	return predicate.Student(sql.FieldEQ(FieldClassID, v))
}

// JoiningDate applies equality check predicate on the "joining_date" field. It's identical to JoiningDateEQ.
func JoiningDate(v time.Time) predicate.Student {
	return predicate.Student(sql.FieldEQ(FieldJoiningDate, v))
}

// AvatarURL applies equality check predicate on the "avatar_url" field. It's identical to AvatarURLEQ.
func AvatarURL(v string) predicate.Student {
	return predicate.Student(sql.FieldEQ(FieldAvatarURL, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.Student {
	return predicate.Student(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.Student {
	return predicate.Student(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.Student {
	return predicate.Student(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.Student {
	return predicate.Student(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.Student {
	return predicate.Student(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.Student {
	return predicate.Student(sql.FieldNotNull(FieldUserID))
}

// RollNumberEQ applies the EQ predicate on the "roll_number" field.
func RollNumberEQ(v string) predicate.Student {
	return predicate.Student(sql.FieldEQ(FieldRollNumber, v))
}

// RollNumberNEQ applies the NEQ predicate on the "roll_number" field.
func RollNumberNEQ(v string) predicate.Student {
	return predicate.Student(sql.FieldNEQ(FieldRollNumber, v))
}

// RollNumberIn applies the In predicate on the "roll_number" field.
func RollNumberIn(vs ...string) predicate.Student {
	return predicate.Student(sql.FieldIn(FieldRollNumber, vs...))
}

// RollNumberNotIn applies the NotIn predicate on the "roll_number" field.
func RollNumberNotIn(vs ...string) predicate.Student {
	return predicate.Student(sql.FieldNotIn(FieldRollNumber, vs...))
}

// RollNumberGT applies the GT predicate on the "roll_number" field.
func RollNumberGT(v string) predicate.Student {
	return predicate.Student(sql.FieldGT(FieldRollNumber, v))
}

// RollNumberGTE applies the GTE predicate on the "roll_number" field.
func RollNumberGTE(v string) predicate.Student {
	return predicate.Student(sql.FieldGTE(FieldRollNumber, v))
}

// RollNumberLT applies the LT predicate on the "roll_number" field.
func RollNumberLT(v string) predicate.Student {
	return predicate.Student(sql.FieldLT(FieldRollNumber, v))
}

// RollNumberLTE applies the LTE predicate on the "roll_number" field.
func RollNumberLTE(v string) predicate.Student {
	return predicate.Student(sql.FieldLTE(FieldRollNumber, v))
}

// RollNumberContains applies the Contains predicate on the "roll_number" field.
func RollNumberContains(v string) predicate.Student {
	return predicate.Student(sql.FieldContains(FieldRollNumber, v))
}

// RollNumberHasPrefix applies the HasPrefix predicate on the "roll_number" field.
func RollNumberHasPrefix(v string) predicate.Student {
	return predicate.Student(sql.FieldHasPrefix(FieldRollNumber, v))
}

// RollNumberHasSuffix applies the HasSuffix predicate on the "roll_number" field.
func RollNumberHasSuffix(v string) predicate.Student {
	return predicate.Student(sql.FieldHasSuffix(FieldRollNumber, v))
}

// RollNumberEqualFold applies the EqualFold predicate on the "roll_number" field.
func RollNumberEqualFold(v string) predicate.Student {
	return predicate.Student(sql.FieldEqualFold(FieldRollNumber, v))
}

// RollNumberContainsFold applies the ContainsFold predicate on the "roll_number" field.
func RollNumberContainsFold(v string) predicate.Student {
	return predicate.Student(sql.FieldContainsFold(FieldRollNumber, v))
}

// FirstNameEQ applies the EQ predicate on the "first_name" field.
func FirstNameEQ(v string) predicate.Student {
	return predicate.Student(sql.FieldEQ(FieldFirstName, v))
}

// FirstNameNEQ applies the NEQ predicate on the "first_name" field.
func FirstNameNEQ(v string) predicate.Student {
	return predicate.Student(sql.FieldNEQ(FieldFirstName, v))
}

// FirstNameIn applies the In predicate on the "first_name" field.
func FirstNameIn(vs ...string) predicate.Student {
	return predicate.Student(sql.FieldIn(FieldFirstName, vs...))
}

// FirstNameNotIn applies the NotIn predicate on the "first_name" field.
func FirstNameNotIn(vs ...string) predicate.Student {
	return predicate.Student(sql.FieldNotIn(FieldFirstName, vs...))
}

// FirstNameGT applies the GT predicate on the "first_name" field.
func FirstNameGT(v string) predicate.Student {
	return predicate.Student(sql.FieldGT(FieldFirstName, v))
}

// FirstNameGTE applies the GTE predicate on the "first_name" field.
func FirstNameGTE(v string) predicate.Student {
	return predicate.Student(sql.FieldGTE(FieldFirstName, v))
}

// FirstNameLT applies the LT predicate on the "first_name" field.
func FirstNameLT(v string) predicate.Student {
	return predicate.Student(sql.FieldLT(FieldFirstName, v))
}

// FirstNameLTE applies the LTE predicate on the "first_name" field.
func FirstNameLTE(v string) predicate.Student {
	return predicate.Student(sql.FieldLTE(FieldFirstName, v))
}

// FirstNameContains applies the Contains predicate on the "first_name" field.
func FirstNameContains(v string) predicate.Student {
	return predicate.Student(sql.FieldContains(FieldFirstName, v))
}

// FirstNameHasPrefix applies the HasPrefix predicate on the "first_name" field.
func FirstNameHasPrefix(v string) predicate.Student {
	return predicate.Student(sql.FieldHasPrefix(FieldFirstName, v))
}

// FirstNameHasSuffix applies the HasSuffix predicate on the "first_name" field.
func FirstNameHasSuffix(v string) predicate.Student {
	return predicate.Student(sql.FieldHasSuffix(FieldFirstName, v))
}

// FirstNameEqualFold applies the EqualFold predicate on the "first_name" field.
func FirstNameEqualFold(v string) predicate.Student {
	return predicate.Student(sql.FieldEqualFold(FieldFirstName, v))
}

// FirstNameContainsFold applies the ContainsFold predicate on the "first_name" field.
func FirstNameContainsFold(v string) predicate.Student {
	return predicate.Student(sql.FieldContainsFold(FieldFirstName, v))
}

// LastNameEQ applies the EQ predicate on the "last_name" field.
func LastNameEQ(v string) predicate.Student {
	return predicate.Student(sql.FieldEQ(FieldLastName, v))
}

// LastNameNEQ applies the NEQ predicate on the "last_name" field.
func LastNameNEQ(v string) predicate.Student {
	return predicate.Student(sql.FieldNEQ(FieldLastName, v))
}

// LastNameIn applies the In predicate on the "last_name" field.
func LastNameIn(vs ...string) predicate.Student {
	return predicate.Student(sql.FieldIn(FieldLastName, vs...))
}

// LastNameNotIn applies the NotIn predicate on the "last_name" field.
func LastNameNotIn(vs ...string) predicate.Student {
	return predicate.Student(sql.FieldNotIn(FieldLastName, vs...))
}

// LastNameGT applies the GT predicate on the "last_name" field.
func LastNameGT(v string) predicate.Student {
	return predicate.Student(sql.FieldGT(FieldLastName, v))
}

// LastNameGTE applies the GTE predicate on the "last_name" field.
func LastNameGTE(v string) predicate.Student {
	return predicate.Student(sql.FieldGTE(FieldLastName, v))
}

// LastNameLT applies the LT predicate on the "last_name" field.
func LastNameLT(v string) predicate.Student {
	return predicate.Student(sql.FieldLT(FieldLastName, v))
}

// LastNameLTE applies the LTE predicate on the "last_name" field.
func LastNameLTE(v string) predicate.Student {
	return predicate.Student(sql.FieldLTE(FieldLastName, v))
}

// LastNameContains applies the Contains predicate on the "last_name" field.
func LastNameContains(v string) predicate.Student {
	return predicate.Student(sql.FieldContains(FieldLastName, v))
}

// LastNameHasPrefix applies the HasPrefix predicate on the "last_name" field.
func LastNameHasPrefix(v string) predicate.Student {
	return predicate.Student(sql.FieldHasPrefix(FieldLastName, v))
}

// LastNameHasSuffix applies the HasSuffix predicate on the "last_name" field.
func LastNameHasSuffix(v string) predicate.Student {
	return predicate.Student(sql.FieldHasSuffix(FieldLastName, v))
}

// LastNameEqualFold applies the EqualFold predicate on the "last_name" field.
func LastNameEqualFold(v string) predicate.Student {
	return predicate.Student(sql.FieldEqualFold(FieldLastName, v))
}

// LastNameContainsFold applies the ContainsFold predicate on the "last_name" field.
func LastNameContainsFold(v string) predicate.Student {
	return predicate.Student(sql.FieldContainsFold(FieldLastName, v))
}

// GenderEQ applies the EQ predicate on the "gender" field.
func GenderEQ(v Gender) predicate.Student {
	return predicate.Student(sql.FieldEQ(FieldGender, v))
}

// GenderNEQ applies the NEQ predicate on the "gender" field.
func GenderNEQ(v Gender) predicate.Student {
	return predicate.Student(sql.FieldNEQ(FieldGender, v))
}

// GenderIn applies the In predicate on the "gender" field.
func GenderIn(vs ...Gender) predicate.Student {
	return predicate.Student(sql.FieldIn(FieldGender, vs...))
}

// GenderNotIn applies the NotIn predicate on the "gender" field.
func GenderNotIn(vs ...Gender) predicate.Student {
	return predicate.Student(sql.FieldNotIn(FieldGender, vs...))
}

// GenderIsNil applies the IsNil predicate on the "gender" field.
func GenderIsNil() predicate.Student {
	return predicate.Student(sql.FieldIsNull(FieldGender))
}

// GenderNotNil applies the NotNil predicate on the "gender" field.
func GenderNotNil() predicate.Student {
	return predicate.Student(sql.FieldNotNull(FieldGender))
}

// DateOfBirthEQ applies the EQ predicate on the "date_of_birth" field.
func DateOfBirthEQ(v time.Time) predicate.Student {
	return predicate.Student(sql.FieldEQ(FieldDateOfBirth, v))
}

// DateOfBirthNEQ applies the NEQ predicate on the "date_of_birth" field.
func DateOfBirthNEQ(v time.Time) predicate.Student {
	return predicate.Student(sql.FieldNEQ(FieldDateOfBirth, v))
}

// DateOfBirthIn applies the In predicate on the "date_of_birth" field.
func DateOfBirthIn(vs ...time.Time) predicate.Student {
	return predicate.Student(sql.FieldIn(FieldDateOfBirth, vs...))
}

// DateOfBirthNotIn applies the NotIn predicate on the "date_of_birth" field.
func DateOfBirthNotIn(vs ...time.Time) predicate.Student {
	return predicate.Student(sql.FieldNotIn(FieldDateOfBirth, vs...))
}

// DateOfBirthGT applies the GT predicate on the "date_of_birth" field.
func DateOfBirthGT(v time.Time) predicate.Student {
	return predicate.Student(sql.FieldGT(FieldDateOfBirth, v))
}

// DateOfBirthGTE applies the GTE predicate on the "date_of_birth" field.
func DateOfBirthGTE(v time.Time) predicate.Student {
	return predicate.Student(sql.FieldGTE(FieldDateOfBirth, v))
}

// DateOfBirthLT applies the LT predicate on the "date_of_birth" field.
func DateOfBirthLT(v time.Time) predicate.Student {
	return predicate.Student(sql.FieldLT(FieldDateOfBirth, v))
}

// DateOfBirthLTE applies the LTE predicate on the "date_of_birth" field.
func DateOfBirthLTE(v time.Time) predicate.Student {
	return predicate.Student(sql.FieldLTE(FieldDateOfBirth, v))
}

// DateOfBirthIsNil applies the IsNil predicate on the "date_of_birth" field.
func DateOfBirthIsNil() predicate.Student {
	return predicate.Student(sql.FieldIsNull(FieldDateOfBirth))
}

// DateOfBirthNotNil applies the NotNil predicate on the "date_of_birth" field.
func DateOfBirthNotNil() predicate.Student {
	return predicate.Student(sql.FieldNotNull(FieldDateOfBirth))
}

// PhoneEQ applies the EQ predicate on the "phone" field.
func PhoneEQ(v string) predicate.Student {
	return predicate.Student(sql.FieldEQ(FieldPhone, v))
}

// PhoneNEQ applies the NEQ predicate on the "phone" field.
func PhoneNEQ(v string) predicate.Student {
	return predicate.Student(sql.FieldNEQ(FieldPhone, v))
}

// PhoneIn applies the In predicate on the "phone" field.
func PhoneIn(vs ...string) predicate.Student {
	return predicate.Student(sql.FieldIn(FieldPhone, vs...))
}

// PhoneNotIn applies the NotIn predicate on the "phone" field.
func PhoneNotIn(vs ...string) predicate.Student {
	return predicate.Student(sql.FieldNotIn(FieldPhone, vs...))
}

// PhoneGT applies the GT predicate on the "phone" field.
func PhoneGT(v string) predicate.Student {
	return predicate.Student(sql.FieldGT(FieldPhone, v))
}

// PhoneGTE applies the GTE predicate on the "phone" field.
func PhoneGTE(v string) predicate.Student {
	return predicate.Student(sql.FieldGTE(FieldPhone, v))
}

// PhoneLT applies the LT predicate on the "phone" field.
func PhoneLT(v string) predicate.Student {
	return predicate.Student(sql.FieldLT(FieldPhone, v))
}

// PhoneLTE applies the LTE predicate on the "phone" field.
func PhoneLTE(v string) predicate.Student {
	return predicate.Student(sql.FieldLTE(FieldPhone, v))
}

// PhoneContains applies the Contains predicate on the "phone" field.
func PhoneContains(v string) predicate.Student {
	return predicate.Student(sql.FieldContains(FieldPhone, v))
}

// PhoneHasPrefix applies the HasPrefix predicate on the "phone" field.
func PhoneHasPrefix(v string) predicate.Student {
	return predicate.Student(sql.FieldHasPrefix(FieldPhone, v))
}

// PhoneHasSuffix applies the HasSuffix predicate on the "phone" field.
func PhoneHasSuffix(v string) predicate.Student {
	return predicate.Student(sql.FieldHasSuffix(FieldPhone, v))
}

// PhoneIsNil applies the IsNil predicate on the "phone" field.
func PhoneIsNil() predicate.Student {
	return predicate.Student(sql.FieldIsNull(FieldPhone))
}

// PhoneNotNil applies the NotNil predicate on the "phone" field.
func PhoneNotNil() predicate.Student {
	return predicate.Student(sql.FieldNotNull(FieldPhone))
}

// PhoneEqualFold applies the EqualFold predicate on the "phone" field.
func PhoneEqualFold(v string) predicate.Student {
	return predicate.Student(sql.FieldEqualFold(FieldPhone, v))
}

// PhoneContainsFold applies the ContainsFold predicate on the "phone" field.
func PhoneContainsFold(v string) predicate.Student {
	return predicate.Student(sql.FieldContainsFold(FieldPhone, v))
}

// ParentPhoneEQ applies the EQ predicate on the "parent_phone" field.
func ParentPhoneEQ(v string) predicate.Student {
	return predicate.Student(sql.FieldEQ(FieldParentPhone, v))
}

// ParentPhoneNEQ applies the NEQ predicate on the "parent_phone" field.
func ParentPhoneNEQ(v string) predicate.Student {
	return predicate.Student(sql.FieldNEQ(FieldParentPhone, v))
}

// ParentPhoneIn applies the In predicate on the "parent_phone" field.
func ParentPhoneIn(vs ...string) predicate.Student {
	return predicate.Student(sql.FieldIn(FieldParentPhone, vs...))
}

// ParentPhoneNotIn applies the NotIn predicate on the "parent_phone" field.
func ParentPhoneNotIn(vs ...string) predicate.Student {
	return predicate.Student(sql.FieldNotIn(FieldParentPhone, vs...))
}

// ParentPhoneGT applies the GT predicate on the "parent_phone" field.
func ParentPhoneGT(v string) predicate.Student {
	return predicate.Student(sql.FieldGT(FieldParentPhone, v))
}

// ParentPhoneGTE applies the GTE predicate on the "parent_phone" field.
func ParentPhoneGTE(v string) predicate.Student {
	return predicate.Student(sql.FieldGTE(FieldParentPhone, v))
}

// ParentPhoneLT applies the LT predicate on the "parent_phone" field.
func ParentPhoneLT(v string) predicate.Student {
	return predicate.Student(sql.FieldLT(FieldParentPhone, v))
}

// ParentPhoneLTE applies the LTE predicate on the "parent_phone" field.
func ParentPhoneLTE(v string) predicate.Student {
	return predicate.Student(sql.FieldLTE(FieldParentPhone, v))
}

// ParentPhoneContains applies the Contains predicate on the "parent_phone" field.
func ParentPhoneContains(v string) predicate.Student {
	return predicate.Student(sql.FieldContains(FieldParentPhone, v))
}

// ParentPhoneHasPrefix applies the HasPrefix predicate on the "parent_phone" field.
func ParentPhoneHasPrefix(v string) predicate.Student {
	return predicate.Student(sql.FieldHasPrefix(FieldParentPhone, v))
}

// ParentPhoneHasSuffix applies the HasSuffix predicate on the "parent_phone" field.
func ParentPhoneHasSuffix(v string) predicate.Student {
	return predicate.Student(sql.FieldHasSuffix(FieldParentPhone, v))
}

// ParentPhoneIsNil applies the IsNil predicate on the "parent_phone" field.
func ParentPhoneIsNil() predicate.Student {
	return predicate.Student(sql.FieldIsNull(FieldParentPhone))
}

// ParentPhoneNotNil applies the NotNil predicate on the "parent_phone" field.
func ParentPhoneNotNil() predicate.Student {
	return predicate.Student(sql.FieldNotNull(FieldParentPhone))
}

// ParentPhoneEqualFold applies the EqualFold predicate on the "parent_phone" field.
func ParentPhoneEqualFold(v string) predicate.Student {
	return predicate.Student(sql.FieldEqualFold(FieldParentPhone, v))
}

// ParentPhoneContainsFold applies the ContainsFold predicate on the "parent_phone" field.
func ParentPhoneContainsFold(v string) predicate.Student {
	return predicate.Student(sql.FieldContainsFold(FieldParentPhone, v))
}

// AddressEQ applies the EQ predicate on the "address" field.
func AddressEQ(v string) predicate.Student {
	return predicate.Student(sql.FieldEQ(FieldAddress, v))
}

// AddressNEQ applies the NEQ predicate on the "address" field.
func AddressNEQ(v string) predicate.Student {
	return predicate.Student(sql.FieldNEQ(FieldAddress, v))
}

// AddressIn applies the In predicate on the "address" field.
func AddressIn(vs ...string) predicate.Student {
	return predicate.Student(sql.FieldIn(FieldAddress, vs...))
}

// AddressNotIn applies the NotIn predicate on the "address" field.
func AddressNotIn(vs ...string) predicate.Student {
	return predicate.Student(sql.FieldNotIn(FieldAddress, vs...))
}

// AddressGT applies the GT predicate on the "address" field.
func AddressGT(v string) predicate.Student {
	return predicate.Student(sql.FieldGT(FieldAddress, v))
}

// AddressGTE applies the GTE predicate on the "address" field.
func AddressGTE(v string) predicate.Student {
	return predicate.Student(sql.FieldGTE(FieldAddress, v))
}

// AddressLT applies the LT predicate on the "address" field.
func AddressLT(v string) predicate.Student {
	return predicate.Student(sql.FieldLT(FieldAddress, v))
}

// AddressLTE applies the LTE predicate on the "address" field.
func AddressLTE(v string) predicate.Student {
	return predicate.Student(sql.FieldLTE(FieldAddress, v))
}

// AddressContains applies the Contains predicate on the "address" field.
func AddressContains(v string) predicate.Student {
	return predicate.Student(sql.FieldContains(FieldAddress, v))
}

// AddressHasPrefix applies the HasPrefix predicate on the "address" field.
func AddressHasPrefix(v string) predicate.Student {
	return predicate.Student(sql.FieldHasPrefix(FieldAddress, v))
}

// AddressHasSuffix applies the HasSuffix predicate on the "address" field.
func AddressHasSuffix(v string) predicate.Student {
	return predicate.Student(sql.FieldHasSuffix(FieldAddress, v))
}

// AddressIsNil applies the IsNil predicate on the "address" field.
func AddressIsNil() predicate.Student {
	return predicate.Student(sql.FieldIsNull(FieldAddress))
}

// AddressNotNil applies the NotNil predicate on the "address" field.
func AddressNotNil() predicate.Student {
	return predicate.Student(sql.FieldNotNull(FieldAddress))
}

// AddressEqualFold applies the EqualFold predicate on the "address" field.
func AddressEqualFold(v string) predicate.Student {
	return predicate.Student(sql.FieldEqualFold(FieldAddress, v))
}

// AddressContainsFold applies the ContainsFold predicate on the "address" field.
func AddressContainsFold(v string) predicate.Student {
	return predicate.Student(sql.FieldContainsFold(FieldAddress, v))
}

// ClassIDEQ applies the EQ predicate on the "class_id" field.
func ClassIDEQ(v int) predicate.Student {
	return predicate.Student(sql.FieldEQ(FieldClassID, v))
}

// ClassIDNEQ applies the NEQ predicate on the "class_id" field.
func ClassIDNEQ(v int) predicate.Student {
	return predicate.Student(sql.FieldNEQ(FieldClassID, v))
}

// ClassIDIn applies the In predicate on the "class_id" field.
func ClassIDIn(vs ...int) predicate.Student {
	return predicate.Student(sql.FieldIn(FieldClassID, vs...))
}

// ClassIDNotIn applies the NotIn predicate on the "class_id" field.
func ClassIDNotIn(vs ...int) predicate.Student {
	return predicate.Student(sql.FieldNotIn(FieldClassID, vs...))
}

// ClassIDIsNil applies the IsNil predicate on the "class_id" field.
func ClassIDIsNil() predicate.Student {
	return predicate.Student(sql.FieldIsNull(FieldClassID))
}

// ClassIDNotNil applies the NotNil predicate on the "class_id" field.
func ClassIDNotNil() predicate.Student {
	return predicate.Student(sql.FieldNotNull(FieldClassID))
}

// JoiningDateEQ applies the EQ predicate on the "joining_date" field.
func JoiningDateEQ(v time.Time) predicate.Student {
	return predicate.Student(sql.FieldEQ(FieldJoiningDate, v))
}

// JoiningDateNEQ applies the NEQ predicate on the "joining_date" field.
func JoiningDateNEQ(v time.Time) predicate.Student {
	return predicate.Student(sql.FieldNEQ(FieldJoiningDate, v))
}

// JoiningDateIn applies the In predicate on the "joining_date" field.
func JoiningDateIn(vs ...time.Time) predicate.Student {
	return predicate.Student(sql.FieldIn(FieldJoiningDate, vs...))
}

// JoiningDateNotIn applies the NotIn predicate on the "joining_date" field.
func JoiningDateNotIn(vs ...time.Time) predicate.Student {
	return predicate.Student(sql.FieldNotIn(FieldJoiningDate, vs...))
}

// JoiningDateGT applies the GT predicate on the "joining_date" field.
func JoiningDateGT(v time.Time) predicate.Student {
	return predicate.Student(sql.FieldGT(FieldJoiningDate, v))
}

// JoiningDateGTE applies the GTE predicate on the "joining_date" field.
func JoiningDateGTE(v time.Time) predicate.Student {
	return predicate.Student(sql.FieldGTE(FieldJoiningDate, v))
}

// JoiningDateLT applies the LT predicate on the "joining_date" field.
func JoiningDateLT(v time.Time) predicate.Student {
	return predicate.Student(sql.FieldLT(FieldJoiningDate, v))
}

// JoiningDateLTE applies the LTE predicate on the "joining_date" field.
func JoiningDateLTE(v time.Time) predicate.Student {
	return predicate.Student(sql.FieldLTE(FieldJoiningDate, v))
}

// AvatarURLEQ applies the EQ predicate on the "avatar_url" field.
func AvatarURLEQ(v string) predicate.Student {
	return predicate.Student(sql.FieldEQ(FieldAvatarURL, v))
}

// AvatarURLNEQ applies the NEQ predicate on the "avatar_url" field.
func AvatarURLNEQ(v string) predicate.Student {
	return predicate.Student(sql.FieldNEQ(FieldAvatarURL, v))
}

// AvatarURLIn applies the In predicate on the "avatar_url" field.
func AvatarURLIn(vs ...string) predicate.Student {
	return predicate.Student(sql.FieldIn(FieldAvatarURL, vs...))
}

// AvatarURLNotIn applies the NotIn predicate on the "avatar_url" field.
func AvatarURLNotIn(vs ...string) predicate.Student {
	return predicate.Student(sql.FieldNotIn(FieldAvatarURL, vs...))
}

// AvatarURLGT applies the GT predicate on the "avatar_url" field.
func AvatarURLGT(v string) predicate.Student {
	return predicate.Student(sql.FieldGT(FieldAvatarURL, v))
}

// AvatarURLGTE applies the GTE predicate on the "avatar_url" field.
func AvatarURLGTE(v string) predicate.Student {
	return predicate.Student(sql.FieldGTE(FieldAvatarURL, v))
}

// AvatarURLLT applies the LT predicate on the "avatar_url" field.
func AvatarURLLT(v string) predicate.Student {
	return predicate.Student(sql.FieldLT(FieldAvatarURL, v))
}

// AvatarURLLTE applies the LTE predicate on the "avatar_url" field.
func AvatarURLLTE(v string) predicate.Student {
	return predicate.Student(sql.FieldLTE(FieldAvatarURL, v))
}

// AvatarURLContains applies the Contains predicate on the "avatar_url" field.
func AvatarURLContains(v string) predicate.Student {
	return predicate.Student(sql.FieldContains(FieldAvatarURL, v))
}

// AvatarURLHasPrefix applies the HasPrefix predicate on the "avatar_url" field.
func AvatarURLHasPrefix(v string) predicate.Student {
	return predicate.Student(sql.FieldHasPrefix(FieldAvatarURL, v))
}

// AvatarURLHasSuffix applies the HasSuffix predicate on the "avatar_url" field.
func AvatarURLHasSuffix(v string) predicate.Student {
	return predicate.Student(sql.FieldHasSuffix(FieldAvatarURL, v))
}

// AvatarURLIsNil applies the IsNil predicate on the "avatar_url" field.
func AvatarURLIsNil() predicate.Student {
	return predicate.Student(sql.FieldIsNull(FieldAvatarURL))
}

// AvatarURLNotNil applies the NotNil predicate on the "avatar_url" field.
func AvatarURLNotNil() predicate.Student {
	return predicate.Student(sql.FieldNotNull(FieldAvatarURL))
}

// AvatarURLEqualFold applies the EqualFold predicate on the "avatar_url" field.
func AvatarURLEqualFold(v string) predicate.Student {
	return predicate.Student(sql.FieldEqualFold(FieldAvatarURL, v))
}

// AvatarURLContainsFold applies the ContainsFold predicate on the "avatar_url" field.
func AvatarURLContainsFold(v string) predicate.Student {
	return predicate.Student(sql.FieldContainsFold(FieldAvatarURL, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Student {
	return predicate.Student(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Student {
	return predicate.Student(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasClass applies the HasEdge predicate on the "class" edge.
func HasClass() predicate.Student {
	return predicate.Student(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ClassTable, ClassColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasClassWith applies the HasEdge predicate on the "class" edge with a given conditions (other predicates).
func HasClassWith(preds ...predicate.Class) predicate.Student {
	return predicate.Student(func(s *sql.Selector) {
		step := newClassStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Student) predicate.Student {
	return predicate.Student(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Student) predicate.Student {
	return predicate.Student(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Student) predicate.Student {
	return predicate.Student(sql.NotPredicates(p))
}
