// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-seed/ent/academicyear"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AcademicYearCreate is the builder for creating a AcademicYear entity.
type AcademicYearCreate struct {
	config
	mutation *AcademicYearMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetLabel sets the "label" field.
func (_c *AcademicYearCreate) SetLabel(v string) *AcademicYearCreate {
	_c.mutation.SetLabel(v)
	return _c
}

// SetStartDate sets the "start_date" field.
func (_c *AcademicYearCreate) SetStartDate(v time.Time) *AcademicYearCreate {
	_c.mutation.SetStartDate(v)
	return _c
}

// SetEndDate sets the "end_date" field.
func (_c *AcademicYearCreate) SetEndDate(v time.Time) *AcademicYearCreate {
	_c.mutation.SetEndDate(v)
	return _c
}

// SetIsCurrent sets the "is_current" field.
func (_c *AcademicYearCreate) SetIsCurrent(v bool) *AcademicYearCreate {
	_c.mutation.SetIsCurrent(v)
	return _c
}

// SetNillableIsCurrent sets the "is_current" field if the given value is not nil.
func (_c *AcademicYearCreate) SetNillableIsCurrent(v *bool) *AcademicYearCreate {
	if v != nil {
		_c.SetIsCurrent(*v)
	}
	return _c
}

// Mutation returns the AcademicYearMutation object of the builder.
func (_c *AcademicYearCreate) Mutation() *AcademicYearMutation {
	return _c.mutation
}

// Save creates the AcademicYear in the database.
func (_c *AcademicYearCreate) Save(ctx context.Context) (*AcademicYear, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AcademicYearCreate) SaveX(ctx context.Context) *AcademicYear {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AcademicYearCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AcademicYearCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AcademicYearCreate) defaults() {
	if _, ok := _c.mutation.IsCurrent(); !ok {
		v := academicyear.DefaultIsCurrent
		_c.mutation.SetIsCurrent(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AcademicYearCreate) check() error {
	if _, ok := _c.mutation.Label(); !ok {
		return &ValidationError{Name: "label", err: errors.New(`ent: missing required field "AcademicYear.label"`)}
	}
	if _, ok := _c.mutation.StartDate(); !ok {
		return &ValidationError{Name: "start_date", err: errors.New(`ent: missing required field "AcademicYear.start_date"`)}
	}
	if _, ok := _c.mutation.EndDate(); !ok {
		return &ValidationError{Name: "end_date", err: errors.New(`ent: missing required field "AcademicYear.end_date"`)}
	}
	if _, ok := _c.mutation.IsCurrent(); !ok {
		return &ValidationError{Name: "is_current", err: errors.New(`ent: missing required field "AcademicYear.is_current"`)}
	}
	return nil
}

func (_c *AcademicYearCreate) sqlSave(ctx context.Context) (*AcademicYear, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AcademicYearCreate) createSpec() (*AcademicYear, *sqlgraph.CreateSpec) {
	var (
		_node = &AcademicYear{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(academicyear.Table, sqlgraph.NewFieldSpec(academicyear.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Label(); ok {
		_spec.SetField(academicyear.FieldLabel, field.TypeString, value)
		_node.Label = value
	}
	if value, ok := _c.mutation.StartDate(); ok {
		_spec.SetField(academicyear.FieldStartDate, field.TypeTime, value)
		_node.StartDate = value
	}
	if value, ok := _c.mutation.EndDate(); ok {
		_spec.SetField(academicyear.FieldEndDate, field.TypeTime, value)
		_node.EndDate = value
	}
	if value, ok := _c.mutation.IsCurrent(); ok {
		_spec.SetField(academicyear.FieldIsCurrent, field.TypeBool, value)
		_node.IsCurrent = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AcademicYear.Create().
//		SetLabel(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AcademicYearUpsert) {
//			SetLabel(v+v).
//		}).
//		Exec(ctx)
func (_c *AcademicYearCreate) OnConflict(opts ...sql.ConflictOption) *AcademicYearUpsertOne {
	_c.conflict = opts
	return &AcademicYearUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AcademicYear.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AcademicYearCreate) OnConflictColumns(columns ...string) *AcademicYearUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AcademicYearUpsertOne{
		create: _c,
	}
}

type (
	// AcademicYearUpsertOne is the builder for "upsert"-ing
	//  one AcademicYear node.
	AcademicYearUpsertOne struct {
		create *AcademicYearCreate
	}

	// AcademicYearUpsert is the "OnConflict" setter.
	AcademicYearUpsert struct {
		*sql.UpdateSet
	}
)

// SetLabel sets the "label" field.
func (u *AcademicYearUpsert) SetLabel(v string) *AcademicYearUpsert {
	u.Set(academicyear.FieldLabel, v)
	return u
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *AcademicYearUpsert) UpdateLabel() *AcademicYearUpsert {
	u.SetExcluded(academicyear.FieldLabel)
	return u
}

// SetStartDate sets the "start_date" field.
func (u *AcademicYearUpsert) SetStartDate(v time.Time) *AcademicYearUpsert {
	u.Set(academicyear.FieldStartDate, v)
	return u
}

// UpdateStartDate sets the "start_date" field to the value that was provided on create.
func (u *AcademicYearUpsert) UpdateStartDate() *AcademicYearUpsert {
	u.SetExcluded(academicyear.FieldStartDate)
	return u
}

// SetEndDate sets the "end_date" field.
func (u *AcademicYearUpsert) SetEndDate(v time.Time) *AcademicYearUpsert {
	u.Set(academicyear.FieldEndDate, v)
	return u
}

// UpdateEndDate sets the "end_date" field to the value that was provided on create.
func (u *AcademicYearUpsert) UpdateEndDate() *AcademicYearUpsert {
	u.SetExcluded(academicyear.FieldEndDate)
	return u
}

// SetIsCurrent sets the "is_current" field.
func (u *AcademicYearUpsert) SetIsCurrent(v bool) *AcademicYearUpsert {
	u.Set(academicyear.FieldIsCurrent, v)
	return u
}

// UpdateIsCurrent sets the "is_current" field to the value that was provided on create.
func (u *AcademicYearUpsert) UpdateIsCurrent() *AcademicYearUpsert {
	u.SetExcluded(academicyear.FieldIsCurrent)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AcademicYear.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AcademicYearUpsertOne) UpdateNewValues() *AcademicYearUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AcademicYear.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AcademicYearUpsertOne) Ignore() *AcademicYearUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AcademicYearUpsertOne) DoNothing() *AcademicYearUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AcademicYearCreate.OnConflict
// documentation for more info.
func (u *AcademicYearUpsertOne) Update(set func(*AcademicYearUpsert)) *AcademicYearUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AcademicYearUpsert{UpdateSet: update})
	}))
	return u
}

// SetLabel sets the "label" field.
func (u *AcademicYearUpsertOne) SetLabel(v string) *AcademicYearUpsertOne {
	return u.Update(func(s *AcademicYearUpsert) {
		s.SetLabel(v)
	})
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *AcademicYearUpsertOne) UpdateLabel() *AcademicYearUpsertOne {
	return u.Update(func(s *AcademicYearUpsert) {
		s.UpdateLabel()
	})
}

// SetStartDate sets the "start_date" field.
func (u *AcademicYearUpsertOne) SetStartDate(v time.Time) *AcademicYearUpsertOne {
	return u.Update(func(s *AcademicYearUpsert) {
		s.SetStartDate(v)
	})
}

// UpdateStartDate sets the "start_date" field to the value that was provided on create.
func (u *AcademicYearUpsertOne) UpdateStartDate() *AcademicYearUpsertOne {
	return u.Update(func(s *AcademicYearUpsert) {
		s.UpdateStartDate()
	})
}

// SetEndDate sets the "end_date" field.
func (u *AcademicYearUpsertOne) SetEndDate(v time.Time) *AcademicYearUpsertOne {
	return u.Update(func(s *AcademicYearUpsert) {
		s.SetEndDate(v)
	})
}

// UpdateEndDate sets the "end_date" field to the value that was provided on create.
func (u *AcademicYearUpsertOne) UpdateEndDate() *AcademicYearUpsertOne {
	return u.Update(func(s *AcademicYearUpsert) {
		s.UpdateEndDate()
	})
}

// SetIsCurrent sets the "is_current" field.
func (u *AcademicYearUpsertOne) SetIsCurrent(v bool) *AcademicYearUpsertOne {
	return u.Update(func(s *AcademicYearUpsert) {
		s.SetIsCurrent(v)
	})
}

// UpdateIsCurrent sets the "is_current" field to the value that was provided on create.
func (u *AcademicYearUpsertOne) UpdateIsCurrent() *AcademicYearUpsertOne {
	return u.Update(func(s *AcademicYearUpsert) {
		s.UpdateIsCurrent()
	})
}

// Exec executes the query.
func (u *AcademicYearUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AcademicYearCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AcademicYearUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AcademicYearUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AcademicYearUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AcademicYearCreateBulk is the builder for creating many AcademicYear entities in bulk.
type AcademicYearCreateBulk struct {
	config
	err      error
	builders []*AcademicYearCreate
	conflict []sql.ConflictOption
}

// Save creates the AcademicYear entities in the database.
func (_c *AcademicYearCreateBulk) Save(ctx context.Context) ([]*AcademicYear, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AcademicYear, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AcademicYearMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AcademicYearCreateBulk) SaveX(ctx context.Context) []*AcademicYear {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AcademicYearCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AcademicYearCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AcademicYear.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AcademicYearUpsert) {
//			SetLabel(v+v).
//		}).
//		Exec(ctx)
func (_c *AcademicYearCreateBulk) OnConflict(opts ...sql.ConflictOption) *AcademicYearUpsertBulk {
	_c.conflict = opts
	return &AcademicYearUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AcademicYear.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AcademicYearCreateBulk) OnConflictColumns(columns ...string) *AcademicYearUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AcademicYearUpsertBulk{
		create: _c,
	}
}

// AcademicYearUpsertBulk is the builder for "upsert"-ing
// a bulk of AcademicYear nodes.
type AcademicYearUpsertBulk struct {
	create *AcademicYearCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AcademicYear.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AcademicYearUpsertBulk) UpdateNewValues() *AcademicYearUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AcademicYear.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AcademicYearUpsertBulk) Ignore() *AcademicYearUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AcademicYearUpsertBulk) DoNothing() *AcademicYearUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AcademicYearCreateBulk.OnConflict
// documentation for more info.
func (u *AcademicYearUpsertBulk) Update(set func(*AcademicYearUpsert)) *AcademicYearUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AcademicYearUpsert{UpdateSet: update})
	}))
	return u
}

// SetLabel sets the "label" field.
func (u *AcademicYearUpsertBulk) SetLabel(v string) *AcademicYearUpsertBulk {
	return u.Update(func(s *AcademicYearUpsert) {
		s.SetLabel(v)
	})
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *AcademicYearUpsertBulk) UpdateLabel() *AcademicYearUpsertBulk {
	return u.Update(func(s *AcademicYearUpsert) {
		s.UpdateLabel()
	})
}

// SetStartDate sets the "start_date" field.
func (u *AcademicYearUpsertBulk) SetStartDate(v time.Time) *AcademicYearUpsertBulk {
	return u.Update(func(s *AcademicYearUpsert) {
		s.SetStartDate(v)
	})
}

// UpdateStartDate sets the "start_date" field to the value that was provided on create.
func (u *AcademicYearUpsertBulk) UpdateStartDate() *AcademicYearUpsertBulk {
	return u.Update(func(s *AcademicYearUpsert) {
		s.UpdateStartDate()
	})
}

// SetEndDate sets the "end_date" field.
func (u *AcademicYearUpsertBulk) SetEndDate(v time.Time) *AcademicYearUpsertBulk {
	return u.Update(func(s *AcademicYearUpsert) {
		s.SetEndDate(v)
	})
}

// UpdateEndDate sets the "end_date" field to the value that was provided on create.
func (u *AcademicYearUpsertBulk) UpdateEndDate() *AcademicYearUpsertBulk {
	return u.Update(func(s *AcademicYearUpsert) {
		s.UpdateEndDate()
	})
}

// SetIsCurrent sets the "is_current" field.
func (u *AcademicYearUpsertBulk) SetIsCurrent(v bool) *AcademicYearUpsertBulk {
	return u.Update(func(s *AcademicYearUpsert) {
		s.SetIsCurrent(v)
	})
}

// UpdateIsCurrent sets the "is_current" field to the value that was provided on create.
func (u *AcademicYearUpsertBulk) UpdateIsCurrent() *AcademicYearUpsertBulk {
	return u.Update(func(s *AcademicYearUpsert) {
		s.UpdateIsCurrent()
	})
}

// Exec executes the query.
func (u *AcademicYearUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AcademicYearCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AcademicYearCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AcademicYearUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
