// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"go-seed/ent/academicyear"
	"go-seed/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AcademicYearDelete is the builder for deleting a AcademicYear entity.
type AcademicYearDelete struct {
	config
	hooks    []Hook
	mutation *AcademicYearMutation
}

// Where appends a list predicates to the AcademicYearDelete builder.
func (_d *AcademicYearDelete) Where(ps ...predicate.AcademicYear) *AcademicYearDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AcademicYearDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AcademicYearDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AcademicYearDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(academicyear.Table, sqlgraph.NewFieldSpec(academicyear.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AcademicYearDeleteOne is the builder for deleting a single AcademicYear entity.
type AcademicYearDeleteOne struct {
	_d *AcademicYearDelete
}

// Where appends a list predicates to the AcademicYearDelete builder.
func (_d *AcademicYearDeleteOne) Where(ps ...predicate.AcademicYear) *AcademicYearDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AcademicYearDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{academicyear.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AcademicYearDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
