// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-seed/ent/academicyear"
	"go-seed/ent/class"
	"go-seed/ent/department"
	"go-seed/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ClassUpdate is the builder for updating Class entities.
type ClassUpdate struct {
	config
	hooks    []Hook
	mutation *ClassMutation
}

// Where appends a list predicates to the ClassUpdate builder.
func (_u *ClassUpdate) Where(ps ...predicate.Class) *ClassUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ClassUpdate) SetName(v string) *ClassUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ClassUpdate) SetNillableName(v *string) *ClassUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAcademicYearID sets the "academic_year_id" field.
func (_u *ClassUpdate) SetAcademicYearID(v int) *ClassUpdate {
	_u.mutation.SetAcademicYearID(v)
	return _u
}

// SetNillableAcademicYearID sets the "academic_year_id" field if the given value is not nil.
func (_u *ClassUpdate) SetNillableAcademicYearID(v *int) *ClassUpdate {
	if v != nil {
		_u.SetAcademicYearID(*v)
	}
	return _u
}

// SetDepartmentID sets the "department_id" field.
func (_u *ClassUpdate) SetDepartmentID(v int) *ClassUpdate {
	_u.mutation.SetDepartmentID(v)
	return _u
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (_u *ClassUpdate) SetNillableDepartmentID(v *int) *ClassUpdate {
	if v != nil {
		_u.SetDepartmentID(*v)
	}
	return _u
}

// ClearDepartmentID clears the value of the "department_id" field.
func (_u *ClassUpdate) ClearDepartmentID() *ClassUpdate {
	_u.mutation.ClearDepartmentID()
	return _u
}

// SetCapacity sets the "capacity" field.
func (_u *ClassUpdate) SetCapacity(v int) *ClassUpdate {
	_u.mutation.ResetCapacity()
	_u.mutation.SetCapacity(v)
	return _u
}

// SetNillableCapacity sets the "capacity" field if the given value is not nil.
func (_u *ClassUpdate) SetNillableCapacity(v *int) *ClassUpdate {
	if v != nil {
		_u.SetCapacity(*v)
	}
	return _u
}

// AddCapacity adds value to the "capacity" field.
func (_u *ClassUpdate) AddCapacity(v int) *ClassUpdate {
	_u.mutation.AddCapacity(v)
	return _u
}

// ClearCapacity clears the value of the "capacity" field.
func (_u *ClassUpdate) ClearCapacity() *ClassUpdate {
	_u.mutation.ClearCapacity()
	return _u
}

// SetAcademicYear sets the "academic_year" edge to the AcademicYear entity.
func (_u *ClassUpdate) SetAcademicYear(v *AcademicYear) *ClassUpdate {
	return _u.SetAcademicYearID(v.ID)
}

// SetDepartment sets the "department" edge to the Department entity.
func (_u *ClassUpdate) SetDepartment(v *Department) *ClassUpdate {
	return _u.SetDepartmentID(v.ID)
}

// Mutation returns the ClassMutation object of the builder.
func (_u *ClassUpdate) Mutation() *ClassMutation {
	return _u.mutation
}

// ClearAcademicYear clears the "academic_year" edge to the AcademicYear entity.
func (_u *ClassUpdate) ClearAcademicYear() *ClassUpdate {
	_u.mutation.ClearAcademicYear()
	return _u
}

// ClearDepartment clears the "department" edge to the Department entity.
func (_u *ClassUpdate) ClearDepartment() *ClassUpdate {
	_u.mutation.ClearDepartment()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ClassUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ClassUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ClassUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ClassUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ClassUpdate) check() error {
	if _u.mutation.AcademicYearCleared() && len(_u.mutation.AcademicYearIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Class.academic_year"`)
	}
	return nil
}

func (_u *ClassUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(class.Table, class.Columns, sqlgraph.NewFieldSpec(class.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(class.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Capacity(); ok {
		_spec.SetField(class.FieldCapacity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCapacity(); ok {
		_spec.AddField(class.FieldCapacity, field.TypeInt, value)
	}
	if _u.mutation.CapacityCleared() {
		_spec.ClearField(class.FieldCapacity, field.TypeInt)
	}
	if _u.mutation.AcademicYearCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   class.AcademicYearTable,
			Columns: []string{class.AcademicYearColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(academicyear.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AcademicYearIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   class.AcademicYearTable,
			Columns: []string{class.AcademicYearColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(academicyear.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DepartmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   class.DepartmentTable,
			Columns: []string{class.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DepartmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   class.DepartmentTable,
			Columns: []string{class.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{class.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ClassUpdateOne is the builder for updating a single Class entity.
type ClassUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ClassMutation
}

// SetName sets the "name" field.
func (_u *ClassUpdateOne) SetName(v string) *ClassUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ClassUpdateOne) SetNillableName(v *string) *ClassUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAcademicYearID sets the "academic_year_id" field.
func (_u *ClassUpdateOne) SetAcademicYearID(v int) *ClassUpdateOne {
	_u.mutation.SetAcademicYearID(v)
	return _u
}

// SetNillableAcademicYearID sets the "academic_year_id" field if the given value is not nil.
func (_u *ClassUpdateOne) SetNillableAcademicYearID(v *int) *ClassUpdateOne {
	if v != nil {
		_u.SetAcademicYearID(*v)
	}
	return _u
}

// SetDepartmentID sets the "department_id" field.
func (_u *ClassUpdateOne) SetDepartmentID(v int) *ClassUpdateOne {
	_u.mutation.SetDepartmentID(v)
	return _u
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (_u *ClassUpdateOne) SetNillableDepartmentID(v *int) *ClassUpdateOne {
	if v != nil {
		_u.SetDepartmentID(*v)
	}
	return _u
}

// ClearDepartmentID clears the value of the "department_id" field.
func (_u *ClassUpdateOne) ClearDepartmentID() *ClassUpdateOne {
	_u.mutation.ClearDepartmentID()
	return _u
}

// SetCapacity sets the "capacity" field.
func (_u *ClassUpdateOne) SetCapacity(v int) *ClassUpdateOne {
	_u.mutation.ResetCapacity()
	_u.mutation.SetCapacity(v)
	return _u
}

// SetNillableCapacity sets the "capacity" field if the given value is not nil.
func (_u *ClassUpdateOne) SetNillableCapacity(v *int) *ClassUpdateOne {
	if v != nil {
		_u.SetCapacity(*v)
	}
	return _u
}

// AddCapacity adds value to the "capacity" field.
func (_u *ClassUpdateOne) AddCapacity(v int) *ClassUpdateOne {
	_u.mutation.AddCapacity(v)
	return _u
}

// ClearCapacity clears the value of the "capacity" field.
func (_u *ClassUpdateOne) ClearCapacity() *ClassUpdateOne {
	_u.mutation.ClearCapacity()
	return _u
}

// SetAcademicYear sets the "academic_year" edge to the AcademicYear entity.
func (_u *ClassUpdateOne) SetAcademicYear(v *AcademicYear) *ClassUpdateOne {
	return _u.SetAcademicYearID(v.ID)
}

// SetDepartment sets the "department" edge to the Department entity.
func (_u *ClassUpdateOne) SetDepartment(v *Department) *ClassUpdateOne {
	return _u.SetDepartmentID(v.ID)
}

// Mutation returns the ClassMutation object of the builder.
func (_u *ClassUpdateOne) Mutation() *ClassMutation {
	return _u.mutation
}

// ClearAcademicYear clears the "academic_year" edge to the AcademicYear entity.
func (_u *ClassUpdateOne) ClearAcademicYear() *ClassUpdateOne {
	_u.mutation.ClearAcademicYear()
	return _u
}

// ClearDepartment clears the "department" edge to the Department entity.
func (_u *ClassUpdateOne) ClearDepartment() *ClassUpdateOne {
	_u.mutation.ClearDepartment()
	return _u
}

// Where appends a list predicates to the ClassUpdate builder.
func (_u *ClassUpdateOne) Where(ps ...predicate.Class) *ClassUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ClassUpdateOne) Select(field string, fields ...string) *ClassUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Class entity.
func (_u *ClassUpdateOne) Save(ctx context.Context) (*Class, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ClassUpdateOne) SaveX(ctx context.Context) *Class {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ClassUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ClassUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ClassUpdateOne) check() error {
	if _u.mutation.AcademicYearCleared() && len(_u.mutation.AcademicYearIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Class.academic_year"`)
	}
	return nil
}

func (_u *ClassUpdateOne) sqlSave(ctx context.Context) (_node *Class, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(class.Table, class.Columns, sqlgraph.NewFieldSpec(class.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Class.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, class.FieldID)
		for _, f := range fields {
			if !class.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != class.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(class.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Capacity(); ok {
		_spec.SetField(class.FieldCapacity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCapacity(); ok {
		_spec.AddField(class.FieldCapacity, field.TypeInt, value)
	}
	if _u.mutation.CapacityCleared() {
		_spec.ClearField(class.FieldCapacity, field.TypeInt)
	}
	if _u.mutation.AcademicYearCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   class.AcademicYearTable,
			Columns: []string{class.AcademicYearColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(academicyear.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AcademicYearIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   class.AcademicYearTable,
			Columns: []string{class.AcademicYearColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(academicyear.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DepartmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   class.DepartmentTable,
			Columns: []string{class.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DepartmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   class.DepartmentTable,
			Columns: []string{class.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Class{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{class.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
