// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-seed/ent/academicyear"
	"go-seed/ent/class"
	"go-seed/ent/department"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ClassCreate is the builder for creating a Class entity.
type ClassCreate struct {
	config
	mutation *ClassMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *ClassCreate) SetName(v string) *ClassCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetAcademicYearID sets the "academic_year_id" field.
func (_c *ClassCreate) SetAcademicYearID(v int) *ClassCreate {
	_c.mutation.SetAcademicYearID(v)
	return _c
}

// SetDepartmentID sets the "department_id" field.
func (_c *ClassCreate) SetDepartmentID(v int) *ClassCreate {
	_c.mutation.SetDepartmentID(v)
	return _c
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (_c *ClassCreate) SetNillableDepartmentID(v *int) *ClassCreate {
	if v != nil {
		_c.SetDepartmentID(*v)
	}
	return _c
}

// SetCapacity sets the "capacity" field.
func (_c *ClassCreate) SetCapacity(v int) *ClassCreate {
	_c.mutation.SetCapacity(v)
	return _c
}

// SetNillableCapacity sets the "capacity" field if the given value is not nil.
func (_c *ClassCreate) SetNillableCapacity(v *int) *ClassCreate {
	if v != nil {
		_c.SetCapacity(*v)
	}
	return _c
}

// SetAcademicYear sets the "academic_year" edge to the AcademicYear entity.
func (_c *ClassCreate) SetAcademicYear(v *AcademicYear) *ClassCreate {
	return _c.SetAcademicYearID(v.ID)
}

// SetDepartment sets the "department" edge to the Department entity.
func (_c *ClassCreate) SetDepartment(v *Department) *ClassCreate {
	return _c.SetDepartmentID(v.ID)
}

// Mutation returns the ClassMutation object of the builder.
func (_c *ClassCreate) Mutation() *ClassMutation {
	return _c.mutation
}

// Save creates the Class in the database.
func (_c *ClassCreate) Save(ctx context.Context) (*Class, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ClassCreate) SaveX(ctx context.Context) *Class {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ClassCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ClassCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ClassCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Class.name"`)}
	}
	if _, ok := _c.mutation.AcademicYearID(); !ok {
		return &ValidationError{Name: "academic_year_id", err: errors.New(`ent: missing required field "Class.academic_year_id"`)}
	}
	if len(_c.mutation.AcademicYearIDs()) == 0 {
		return &ValidationError{Name: "academic_year", err: errors.New(`ent: missing required edge "Class.academic_year"`)}
	}
	return nil
}

func (_c *ClassCreate) sqlSave(ctx context.Context) (*Class, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ClassCreate) createSpec() (*Class, *sqlgraph.CreateSpec) {
	var (
		_node = &Class{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(class.Table, sqlgraph.NewFieldSpec(class.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(class.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Capacity(); ok {
		_spec.SetField(class.FieldCapacity, field.TypeInt, value)
		_node.Capacity = &value
	}
	if nodes := _c.mutation.AcademicYearIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   class.AcademicYearTable,
			Columns: []string{class.AcademicYearColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(academicyear.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AcademicYearID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DepartmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   class.DepartmentTable,
			Columns: []string{class.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DepartmentID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Class.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ClassUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *ClassCreate) OnConflict(opts ...sql.ConflictOption) *ClassUpsertOne {
	_c.conflict = opts
	return &ClassUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Class.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ClassCreate) OnConflictColumns(columns ...string) *ClassUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ClassUpsertOne{
		create: _c,
	}
}

type (
	// ClassUpsertOne is the builder for "upsert"-ing
	//  one Class node.
	ClassUpsertOne struct {
		create *ClassCreate
	}

	// ClassUpsert is the "OnConflict" setter.
	ClassUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *ClassUpsert) SetName(v string) *ClassUpsert {
	u.Set(class.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ClassUpsert) UpdateName() *ClassUpsert {
	u.SetExcluded(class.FieldName)
	return u
}

// SetAcademicYearID sets the "academic_year_id" field.
func (u *ClassUpsert) SetAcademicYearID(v int) *ClassUpsert {
	u.Set(class.FieldAcademicYearID, v)
	return u
}

// UpdateAcademicYearID sets the "academic_year_id" field to the value that was provided on create.
func (u *ClassUpsert) UpdateAcademicYearID() *ClassUpsert {
	u.SetExcluded(class.FieldAcademicYearID)
	return u
}

// SetDepartmentID sets the "department_id" field.
func (u *ClassUpsert) SetDepartmentID(v int) *ClassUpsert {
	u.Set(class.FieldDepartmentID, v)
	return u
}

// UpdateDepartmentID sets the "department_id" field to the value that was provided on create.
func (u *ClassUpsert) UpdateDepartmentID() *ClassUpsert {
	u.SetExcluded(class.FieldDepartmentID)
	return u
}

// ClearDepartmentID clears the value of the "department_id" field.
func (u *ClassUpsert) ClearDepartmentID() *ClassUpsert {
	u.SetNull(class.FieldDepartmentID)
	return u
}

// SetCapacity sets the "capacity" field.
func (u *ClassUpsert) SetCapacity(v int) *ClassUpsert {
	u.Set(class.FieldCapacity, v)
	return u
}

// UpdateCapacity sets the "capacity" field to the value that was provided on create.
func (u *ClassUpsert) UpdateCapacity() *ClassUpsert {
	u.SetExcluded(class.FieldCapacity)
	return u
}

// AddCapacity adds v to the "capacity" field.
func (u *ClassUpsert) AddCapacity(v int) *ClassUpsert {
	u.Add(class.FieldCapacity, v)
	return u
}

// ClearCapacity clears the value of the "capacity" field.
func (u *ClassUpsert) ClearCapacity() *ClassUpsert {
	u.SetNull(class.FieldCapacity)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Class.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ClassUpsertOne) UpdateNewValues() *ClassUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Class.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ClassUpsertOne) Ignore() *ClassUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ClassUpsertOne) DoNothing() *ClassUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ClassCreate.OnConflict
// documentation for more info.
func (u *ClassUpsertOne) Update(set func(*ClassUpsert)) *ClassUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ClassUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *ClassUpsertOne) SetName(v string) *ClassUpsertOne {
	return u.Update(func(s *ClassUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ClassUpsertOne) UpdateName() *ClassUpsertOne {
	return u.Update(func(s *ClassUpsert) {
		s.UpdateName()
	})
}

// SetAcademicYearID sets the "academic_year_id" field.
func (u *ClassUpsertOne) SetAcademicYearID(v int) *ClassUpsertOne {
	return u.Update(func(s *ClassUpsert) {
		s.SetAcademicYearID(v)
	})
}

// UpdateAcademicYearID sets the "academic_year_id" field to the value that was provided on create.
func (u *ClassUpsertOne) UpdateAcademicYearID() *ClassUpsertOne {
	return u.Update(func(s *ClassUpsert) {
		s.UpdateAcademicYearID()
	})
}

// SetDepartmentID sets the "department_id" field.
func (u *ClassUpsertOne) SetDepartmentID(v int) *ClassUpsertOne {
	return u.Update(func(s *ClassUpsert) {
		s.SetDepartmentID(v)
	})
}

// UpdateDepartmentID sets the "department_id" field to the value that was provided on create.
func (u *ClassUpsertOne) UpdateDepartmentID() *ClassUpsertOne {
	return u.Update(func(s *ClassUpsert) {
		s.UpdateDepartmentID()
	})
}

// ClearDepartmentID clears the value of the "department_id" field.
func (u *ClassUpsertOne) ClearDepartmentID() *ClassUpsertOne {
	return u.Update(func(s *ClassUpsert) {
		s.ClearDepartmentID()
	})
}

// SetCapacity sets the "capacity" field.
func (u *ClassUpsertOne) SetCapacity(v int) *ClassUpsertOne {
	return u.Update(func(s *ClassUpsert) {
		s.SetCapacity(v)
	})
}

// AddCapacity adds v to the "capacity" field.
func (u *ClassUpsertOne) AddCapacity(v int) *ClassUpsertOne {
	return u.Update(func(s *ClassUpsert) {
		s.AddCapacity(v)
	})
}

// UpdateCapacity sets the "capacity" field to the value that was provided on create.
func (u *ClassUpsertOne) UpdateCapacity() *ClassUpsertOne {
	return u.Update(func(s *ClassUpsert) {
		s.UpdateCapacity()
	})
}

// ClearCapacity clears the value of the "capacity" field.
func (u *ClassUpsertOne) ClearCapacity() *ClassUpsertOne {
	return u.Update(func(s *ClassUpsert) {
		s.ClearCapacity()
	})
}

// Exec executes the query.
func (u *ClassUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ClassCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ClassUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ClassUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ClassUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ClassCreateBulk is the builder for creating many Class entities in bulk.
type ClassCreateBulk struct {
	config
	err      error
	builders []*ClassCreate
	conflict []sql.ConflictOption
}

// Save creates the Class entities in the database.
func (_c *ClassCreateBulk) Save(ctx context.Context) ([]*Class, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Class, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ClassMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ClassCreateBulk) SaveX(ctx context.Context) []*Class {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ClassCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ClassCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Class.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ClassUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *ClassCreateBulk) OnConflict(opts ...sql.ConflictOption) *ClassUpsertBulk {
	_c.conflict = opts
	return &ClassUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Class.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ClassCreateBulk) OnConflictColumns(columns ...string) *ClassUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ClassUpsertBulk{
		create: _c,
	}
}

// ClassUpsertBulk is the builder for "upsert"-ing
// a bulk of Class nodes.
type ClassUpsertBulk struct {
	create *ClassCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Class.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ClassUpsertBulk) UpdateNewValues() *ClassUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Class.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ClassUpsertBulk) Ignore() *ClassUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ClassUpsertBulk) DoNothing() *ClassUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ClassCreateBulk.OnConflict
// documentation for more info.
func (u *ClassUpsertBulk) Update(set func(*ClassUpsert)) *ClassUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ClassUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *ClassUpsertBulk) SetName(v string) *ClassUpsertBulk {
	return u.Update(func(s *ClassUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ClassUpsertBulk) UpdateName() *ClassUpsertBulk {
	return u.Update(func(s *ClassUpsert) {
		s.UpdateName()
	})
}

// SetAcademicYearID sets the "academic_year_id" field.
func (u *ClassUpsertBulk) SetAcademicYearID(v int) *ClassUpsertBulk {
	return u.Update(func(s *ClassUpsert) {
		s.SetAcademicYearID(v)
	})
}

// UpdateAcademicYearID sets the "academic_year_id" field to the value that was provided on create.
func (u *ClassUpsertBulk) UpdateAcademicYearID() *ClassUpsertBulk {
	return u.Update(func(s *ClassUpsert) {
		s.UpdateAcademicYearID()
	})
}

// SetDepartmentID sets the "department_id" field.
func (u *ClassUpsertBulk) SetDepartmentID(v int) *ClassUpsertBulk {
	return u.Update(func(s *ClassUpsert) {
		s.SetDepartmentID(v)
	})
}

// UpdateDepartmentID sets the "department_id" field to the value that was provided on create.
func (u *ClassUpsertBulk) UpdateDepartmentID() *ClassUpsertBulk {
	return u.Update(func(s *ClassUpsert) {
		s.UpdateDepartmentID()
	})
}

// ClearDepartmentID clears the value of the "department_id" field.
func (u *ClassUpsertBulk) ClearDepartmentID() *ClassUpsertBulk {
	return u.Update(func(s *ClassUpsert) {
		s.ClearDepartmentID()
	})
}

// SetCapacity sets the "capacity" field.
func (u *ClassUpsertBulk) SetCapacity(v int) *ClassUpsertBulk {
	return u.Update(func(s *ClassUpsert) {
		s.SetCapacity(v)
	})
}

// AddCapacity adds v to the "capacity" field.
func (u *ClassUpsertBulk) AddCapacity(v int) *ClassUpsertBulk {
	return u.Update(func(s *ClassUpsert) {
		s.AddCapacity(v)
	})
}

// UpdateCapacity sets the "capacity" field to the value that was provided on create.
func (u *ClassUpsertBulk) UpdateCapacity() *ClassUpsertBulk {
	return u.Update(func(s *ClassUpsert) {
		s.UpdateCapacity()
	})
}

// ClearCapacity clears the value of the "capacity" field.
func (u *ClassUpsertBulk) ClearCapacity() *ClassUpsertBulk {
	return u.Update(func(s *ClassUpsert) {
		s.ClearCapacity()
	})
}

// Exec executes the query.
func (u *ClassUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ClassCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ClassCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ClassUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
