// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-seed/ent/academicyear"
	"go-seed/ent/class"
	"go-seed/ent/feestructure"
	"go-seed/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// FeeStructureUpdate is the builder for updating FeeStructure entities.
type FeeStructureUpdate struct {
	config
	hooks    []Hook
	mutation *FeeStructureMutation
}

// Where appends a list predicates to the FeeStructureUpdate builder.
func (_u *FeeStructureUpdate) Where(ps ...predicate.FeeStructure) *FeeStructureUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetClassID sets the "class_id" field.
func (_u *FeeStructureUpdate) SetClassID(v uuid.UUID) *FeeStructureUpdate {
	_u.mutation.SetClassID(v)
	return _u
}

// SetNillableClassID sets the "class_id" field if the given value is not nil.
func (_u *FeeStructureUpdate) SetNillableClassID(v *uuid.UUID) *FeeStructureUpdate {
	if v != nil {
		_u.SetClassID(*v)
	}
	return _u
}

// SetAcademicYearID sets the "academic_year_id" field.
func (_u *FeeStructureUpdate) SetAcademicYearID(v uuid.UUID) *FeeStructureUpdate {
	_u.mutation.SetAcademicYearID(v)
	return _u
}

// SetNillableAcademicYearID sets the "academic_year_id" field if the given value is not nil.
func (_u *FeeStructureUpdate) SetNillableAcademicYearID(v *uuid.UUID) *FeeStructureUpdate {
	if v != nil {
		_u.SetAcademicYearID(*v)
	}
	return _u
}

// SetFeeLabel sets the "fee_label" field.
func (_u *FeeStructureUpdate) SetFeeLabel(v string) *FeeStructureUpdate {
	_u.mutation.SetFeeLabel(v)
	return _u
}

// SetNillableFeeLabel sets the "fee_label" field if the given value is not nil.
func (_u *FeeStructureUpdate) SetNillableFeeLabel(v *string) *FeeStructureUpdate {
	if v != nil {
		_u.SetFeeLabel(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *FeeStructureUpdate) SetAmount(v float64) *FeeStructureUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *FeeStructureUpdate) SetNillableAmount(v *float64) *FeeStructureUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *FeeStructureUpdate) AddAmount(v float64) *FeeStructureUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetDueDate sets the "due_date" field.
func (_u *FeeStructureUpdate) SetDueDate(v time.Time) *FeeStructureUpdate {
	_u.mutation.SetDueDate(v)
	return _u
}

// SetNillableDueDate sets the "due_date" field if the given value is not nil.
func (_u *FeeStructureUpdate) SetNillableDueDate(v *time.Time) *FeeStructureUpdate {
	if v != nil {
		_u.SetDueDate(*v)
	}
	return _u
}

// ClearDueDate clears the value of the "due_date" field.
func (_u *FeeStructureUpdate) ClearDueDate() *FeeStructureUpdate {
	_u.mutation.ClearDueDate()
	return _u
}

// SetClass sets the "class" edge to the Class entity.
func (_u *FeeStructureUpdate) SetClass(v *Class) *FeeStructureUpdate {
	return _u.SetClassID(v.ID)
}

// SetAcademicYear sets the "academic_year" edge to the AcademicYear entity.
func (_u *FeeStructureUpdate) SetAcademicYear(v *AcademicYear) *FeeStructureUpdate {
	return _u.SetAcademicYearID(v.ID)
}

// Mutation returns the FeeStructureMutation object of the builder.
func (_u *FeeStructureUpdate) Mutation() *FeeStructureMutation {
	return _u.mutation
}

// ClearClass clears the "class" edge to the Class entity.
func (_u *FeeStructureUpdate) ClearClass() *FeeStructureUpdate {
	_u.mutation.ClearClass()
	return _u
}

// ClearAcademicYear clears the "academic_year" edge to the AcademicYear entity.
func (_u *FeeStructureUpdate) ClearAcademicYear() *FeeStructureUpdate {
	_u.mutation.ClearAcademicYear()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FeeStructureUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FeeStructureUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FeeStructureUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FeeStructureUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FeeStructureUpdate) check() error {
	if _u.mutation.ClassCleared() && len(_u.mutation.ClassIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FeeStructure.class"`)
	}
	if _u.mutation.AcademicYearCleared() && len(_u.mutation.AcademicYearIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FeeStructure.academic_year"`)
	}
	return nil
}

func (_u *FeeStructureUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(feestructure.Table, feestructure.Columns, sqlgraph.NewFieldSpec(feestructure.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FeeLabel(); ok {
		_spec.SetField(feestructure.FieldFeeLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(feestructure.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(feestructure.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DueDate(); ok {
		_spec.SetField(feestructure.FieldDueDate, field.TypeTime, value)
	}
	if _u.mutation.DueDateCleared() {
		_spec.ClearField(feestructure.FieldDueDate, field.TypeTime)
	}
	if _u.mutation.ClassCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   feestructure.ClassTable,
			Columns: []string{feestructure.ClassColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(class.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClassIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   feestructure.ClassTable,
			Columns: []string{feestructure.ClassColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(class.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AcademicYearCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   feestructure.AcademicYearTable,
			Columns: []string{feestructure.AcademicYearColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(academicyear.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AcademicYearIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   feestructure.AcademicYearTable,
			Columns: []string{feestructure.AcademicYearColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(academicyear.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{feestructure.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FeeStructureUpdateOne is the builder for updating a single FeeStructure entity.
type FeeStructureUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FeeStructureMutation
}

// SetClassID sets the "class_id" field.
func (_u *FeeStructureUpdateOne) SetClassID(v uuid.UUID) *FeeStructureUpdateOne {
	_u.mutation.SetClassID(v)
	return _u
}

// SetNillableClassID sets the "class_id" field if the given value is not nil.
func (_u *FeeStructureUpdateOne) SetNillableClassID(v *uuid.UUID) *FeeStructureUpdateOne {
	if v != nil {
		_u.SetClassID(*v)
	}
	return _u
}

// SetAcademicYearID sets the "academic_year_id" field.
func (_u *FeeStructureUpdateOne) SetAcademicYearID(v uuid.UUID) *FeeStructureUpdateOne {
	_u.mutation.SetAcademicYearID(v)
	return _u
}

// SetNillableAcademicYearID sets the "academic_year_id" field if the given value is not nil.
func (_u *FeeStructureUpdateOne) SetNillableAcademicYearID(v *uuid.UUID) *FeeStructureUpdateOne {
	if v != nil {
		_u.SetAcademicYearID(*v)
	}
	return _u
}

// SetFeeLabel sets the "fee_label" field.
func (_u *FeeStructureUpdateOne) SetFeeLabel(v string) *FeeStructureUpdateOne {
	_u.mutation.SetFeeLabel(v)
	return _u
}

// SetNillableFeeLabel sets the "fee_label" field if the given value is not nil.
func (_u *FeeStructureUpdateOne) SetNillableFeeLabel(v *string) *FeeStructureUpdateOne {
	if v != nil {
		_u.SetFeeLabel(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *FeeStructureUpdateOne) SetAmount(v float64) *FeeStructureUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *FeeStructureUpdateOne) SetNillableAmount(v *float64) *FeeStructureUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *FeeStructureUpdateOne) AddAmount(v float64) *FeeStructureUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetDueDate sets the "due_date" field.
func (_u *FeeStructureUpdateOne) SetDueDate(v time.Time) *FeeStructureUpdateOne {
	_u.mutation.SetDueDate(v)
	return _u
}

// SetNillableDueDate sets the "due_date" field if the given value is not nil.
func (_u *FeeStructureUpdateOne) SetNillableDueDate(v *time.Time) *FeeStructureUpdateOne {
	if v != nil {
		_u.SetDueDate(*v)
	}
	return _u
}

// ClearDueDate clears the value of the "due_date" field.
func (_u *FeeStructureUpdateOne) ClearDueDate() *FeeStructureUpdateOne {
	_u.mutation.ClearDueDate()
	return _u
}

// SetClass sets the "class" edge to the Class entity.
func (_u *FeeStructureUpdateOne) SetClass(v *Class) *FeeStructureUpdateOne {
	return _u.SetClassID(v.ID)
}

// SetAcademicYear sets the "academic_year" edge to the AcademicYear entity.
func (_u *FeeStructureUpdateOne) SetAcademicYear(v *AcademicYear) *FeeStructureUpdateOne {
	return _u.SetAcademicYearID(v.ID)
}

// Mutation returns the FeeStructureMutation object of the builder.
func (_u *FeeStructureUpdateOne) Mutation() *FeeStructureMutation {
	return _u.mutation
}

// ClearClass clears the "class" edge to the Class entity.
func (_u *FeeStructureUpdateOne) ClearClass() *FeeStructureUpdateOne {
	_u.mutation.ClearClass()
	return _u
}

// ClearAcademicYear clears the "academic_year" edge to the AcademicYear entity.
func (_u *FeeStructureUpdateOne) ClearAcademicYear() *FeeStructureUpdateOne {
	_u.mutation.ClearAcademicYear()
	return _u
}

// Where appends a list predicates to the FeeStructureUpdate builder.
func (_u *FeeStructureUpdateOne) Where(ps ...predicate.FeeStructure) *FeeStructureUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FeeStructureUpdateOne) Select(field string, fields ...string) *FeeStructureUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated FeeStructure entity.
func (_u *FeeStructureUpdateOne) Save(ctx context.Context) (*FeeStructure, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FeeStructureUpdateOne) SaveX(ctx context.Context) *FeeStructure {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FeeStructureUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FeeStructureUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FeeStructureUpdateOne) check() error {
	if _u.mutation.ClassCleared() && len(_u.mutation.ClassIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FeeStructure.class"`)
	}
	if _u.mutation.AcademicYearCleared() && len(_u.mutation.AcademicYearIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FeeStructure.academic_year"`)
	}
	return nil
}

func (_u *FeeStructureUpdateOne) sqlSave(ctx context.Context) (_node *FeeStructure, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(feestructure.Table, feestructure.Columns, sqlgraph.NewFieldSpec(feestructure.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FeeStructure.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, feestructure.FieldID)
		for _, f := range fields {
			if !feestructure.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != feestructure.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FeeLabel(); ok {
		_spec.SetField(feestructure.FieldFeeLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(feestructure.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(feestructure.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DueDate(); ok {
		_spec.SetField(feestructure.FieldDueDate, field.TypeTime, value)
	}
	if _u.mutation.DueDateCleared() {
		_spec.ClearField(feestructure.FieldDueDate, field.TypeTime)
	}
	if _u.mutation.ClassCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   feestructure.ClassTable,
			Columns: []string{feestructure.ClassColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(class.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClassIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   feestructure.ClassTable,
			Columns: []string{feestructure.ClassColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(class.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AcademicYearCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   feestructure.AcademicYearTable,
			Columns: []string{feestructure.AcademicYearColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(academicyear.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AcademicYearIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   feestructure.AcademicYearTable,
			Columns: []string{feestructure.AcademicYearColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(academicyear.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &FeeStructure{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{feestructure.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
