// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-seed/ent/class"
	"go-seed/ent/predicate"
	"go-seed/ent/student"
	"go-seed/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// StudentUpdate is the builder for updating Student entities.
type StudentUpdate struct {
	config
	hooks    []Hook
	mutation *StudentMutation
}

// Where appends a list predicates to the StudentUpdate builder.
func (_u *StudentUpdate) Where(ps ...predicate.Student) *StudentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *StudentUpdate) SetUserID(v uuid.UUID) *StudentUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *StudentUpdate) SetNillableUserID(v *uuid.UUID) *StudentUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *StudentUpdate) ClearUserID() *StudentUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetRollNumber sets the "roll_number" field.
func (_u *StudentUpdate) SetRollNumber(v string) *StudentUpdate {
	_u.mutation.SetRollNumber(v)
	return _u
}

// SetNillableRollNumber sets the "roll_number" field if the given value is not nil.
func (_u *StudentUpdate) SetNillableRollNumber(v *string) *StudentUpdate {
	if v != nil {
		_u.SetRollNumber(*v)
	}
	return _u
}

// SetFirstName sets the "first_name" field.
func (_u *StudentUpdate) SetFirstName(v string) *StudentUpdate {
	_u.mutation.SetFirstName(v)
	return _u
}

// SetNillableFirstName sets the "first_name" field if the given value is not nil.
func (_u *StudentUpdate) SetNillableFirstName(v *string) *StudentUpdate {
	if v != nil {
		_u.SetFirstName(*v)
	}
	return _u
}

// SetLastName sets the "last_name" field.
func (_u *StudentUpdate) SetLastName(v string) *StudentUpdate {
	_u.mutation.SetLastName(v)
	return _u
}

// SetNillableLastName sets the "last_name" field if the given value is not nil.
func (_u *StudentUpdate) SetNillableLastName(v *string) *StudentUpdate {
	if v != nil {
		_u.SetLastName(*v)
	}
	return _u
}

// SetGender sets the "gender" field.
func (_u *StudentUpdate) SetGender(v student.Gender) *StudentUpdate {
	_u.mutation.SetGender(v)
	return _u
}

// SetNillableGender sets the "gender" field if the given value is not nil.
func (_u *StudentUpdate) SetNillableGender(v *student.Gender) *StudentUpdate {
	if v != nil {
		_u.SetGender(*v)
	}
	return _u
}

// ClearGender clears the value of the "gender" field.
func (_u *StudentUpdate) ClearGender() *StudentUpdate {
	_u.mutation.ClearGender()
	return _u
}

// SetDateOfBirth sets the "date_of_birth" field.
func (_u *StudentUpdate) SetDateOfBirth(v time.Time) *StudentUpdate {
	_u.mutation.SetDateOfBirth(v)
	return _u
}

// SetNillableDateOfBirth sets the "date_of_birth" field if the given value is not nil.
func (_u *StudentUpdate) SetNillableDateOfBirth(v *time.Time) *StudentUpdate {
	if v != nil {
		_u.SetDateOfBirth(*v)
	}
	return _u
}

// ClearDateOfBirth clears the value of the "date_of_birth" field.
func (_u *StudentUpdate) ClearDateOfBirth() *StudentUpdate {
	_u.mutation.ClearDateOfBirth()
	return _u
}

// SetPhone sets the "phone" field.
func (_u *StudentUpdate) SetPhone(v string) *StudentUpdate {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *StudentUpdate) SetNillablePhone(v *string) *StudentUpdate {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// ClearPhone clears the value of the "phone" field.
func (_u *StudentUpdate) ClearPhone() *StudentUpdate {
	_u.mutation.ClearPhone()
	return _u
}

// SetParentPhone sets the "parent_phone" field.
func (_u *StudentUpdate) SetParentPhone(v string) *StudentUpdate {
	_u.mutation.SetParentPhone(v)
	return _u
}

// SetNillableParentPhone sets the "parent_phone" field if the given value is not nil.
func (_u *StudentUpdate) SetNillableParentPhone(v *string) *StudentUpdate {
	if v != nil {
		_u.SetParentPhone(*v)
	}
	return _u
}

// ClearParentPhone clears the value of the "parent_phone" field.
func (_u *StudentUpdate) ClearParentPhone() *StudentUpdate {
	_u.mutation.ClearParentPhone()
	return _u
}

// SetAddress sets the "address" field.
func (_u *StudentUpdate) SetAddress(v string) *StudentUpdate {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *StudentUpdate) SetNillableAddress(v *string) *StudentUpdate {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// ClearAddress clears the value of the "address" field.
func (_u *StudentUpdate) ClearAddress() *StudentUpdate {
	_u.mutation.ClearAddress()
	return _u
}

// SetClassID sets the "class_id" field.
func (_u *StudentUpdate) SetClassID(v uuid.UUID) *StudentUpdate {
	_u.mutation.SetClassID(v)
	return _u
}

// SetNillableClassID sets the "class_id" field if the given value is not nil.
func (_u *StudentUpdate) SetNillableClassID(v *uuid.UUID) *StudentUpdate {
	if v != nil {
		_u.SetClassID(*v)
	}
	return _u
}

// ClearClassID clears the value of the "class_id" field.
func (_u *StudentUpdate) ClearClassID() *StudentUpdate {
	_u.mutation.ClearClassID()
	return _u
}

// SetJoiningDate sets the "joining_date" field.
func (_u *StudentUpdate) SetJoiningDate(v time.Time) *StudentUpdate {
	_u.mutation.SetJoiningDate(v)
	return _u
}

// SetNillableJoiningDate sets the "joining_date" field if the given value is not nil.
func (_u *StudentUpdate) SetNillableJoiningDate(v *time.Time) *StudentUpdate {
	if v != nil {
		_u.SetJoiningDate(*v)
	}
	return _u
}

// SetAvatarURL sets the "avatar_url" field.
func (_u *StudentUpdate) SetAvatarURL(v string) *StudentUpdate {
	_u.mutation.SetAvatarURL(v)
	return _u
}

// SetNillableAvatarURL sets the "avatar_url" field if the given value is not nil.
func (_u *StudentUpdate) SetNillableAvatarURL(v *string) *StudentUpdate {
	if v != nil {
		_u.SetAvatarURL(*v)
	}
	return _u
}

// ClearAvatarURL clears the value of the "avatar_url" field.
func (_u *StudentUpdate) ClearAvatarURL() *StudentUpdate {
	_u.mutation.ClearAvatarURL()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *StudentUpdate) SetUser(v *User) *StudentUpdate {
	return _u.SetUserID(v.ID)
}

// SetClass sets the "class" edge to the Class entity.
func (_u *StudentUpdate) SetClass(v *Class) *StudentUpdate {
	return _u.SetClassID(v.ID)
}

// Mutation returns the StudentMutation object of the builder.
func (_u *StudentUpdate) Mutation() *StudentMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *StudentUpdate) ClearUser() *StudentUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearClass clears the "class" edge to the Class entity.
func (_u *StudentUpdate) ClearClass() *StudentUpdate {
	_u.mutation.ClearClass()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *StudentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StudentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *StudentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StudentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StudentUpdate) check() error {
	if v, ok := _u.mutation.Gender(); ok {
		if err := student.GenderValidator(v); err != nil {
			return &ValidationError{Name: "gender", err: fmt.Errorf(`ent: validator failed for field "Student.gender": %w`, err)}
		}
	}
	return nil
}

func (_u *StudentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(student.Table, student.Columns, sqlgraph.NewFieldSpec(student.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RollNumber(); ok {
		_spec.SetField(student.FieldRollNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.FirstName(); ok {
		_spec.SetField(student.FieldFirstName, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastName(); ok {
		_spec.SetField(student.FieldLastName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Gender(); ok {
		_spec.SetField(student.FieldGender, field.TypeEnum, value)
	}
	if _u.mutation.GenderCleared() {
		_spec.ClearField(student.FieldGender, field.TypeEnum)
	}
	if value, ok := _u.mutation.DateOfBirth(); ok {
		_spec.SetField(student.FieldDateOfBirth, field.TypeTime, value)
	}
	if _u.mutation.DateOfBirthCleared() {
		_spec.ClearField(student.FieldDateOfBirth, field.TypeTime)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(student.FieldPhone, field.TypeString, value)
	}
	if _u.mutation.PhoneCleared() {
		_spec.ClearField(student.FieldPhone, field.TypeString)
	}
	if value, ok := _u.mutation.ParentPhone(); ok {
		_spec.SetField(student.FieldParentPhone, field.TypeString, value)
	}
	if _u.mutation.ParentPhoneCleared() {
		_spec.ClearField(student.FieldParentPhone, field.TypeString)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(student.FieldAddress, field.TypeString, value)
	}
	if _u.mutation.AddressCleared() {
		_spec.ClearField(student.FieldAddress, field.TypeString)
	}
	if value, ok := _u.mutation.JoiningDate(); ok {
		_spec.SetField(student.FieldJoiningDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AvatarURL(); ok {
		_spec.SetField(student.FieldAvatarURL, field.TypeString, value)
	}
	if _u.mutation.AvatarURLCleared() {
		_spec.ClearField(student.FieldAvatarURL, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   student.UserTable,
			Columns: []string{student.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   student.UserTable,
			Columns: []string{student.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ClassCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   student.ClassTable,
			Columns: []string{student.ClassColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(class.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClassIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   student.ClassTable,
			Columns: []string{student.ClassColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(class.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{student.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// StudentUpdateOne is the builder for updating a single Student entity.
type StudentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StudentMutation
}

// SetUserID sets the "user_id" field.
func (_u *StudentUpdateOne) SetUserID(v uuid.UUID) *StudentUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *StudentUpdateOne) SetNillableUserID(v *uuid.UUID) *StudentUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *StudentUpdateOne) ClearUserID() *StudentUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetRollNumber sets the "roll_number" field.
func (_u *StudentUpdateOne) SetRollNumber(v string) *StudentUpdateOne {
	_u.mutation.SetRollNumber(v)
	return _u
}

// SetNillableRollNumber sets the "roll_number" field if the given value is not nil.
func (_u *StudentUpdateOne) SetNillableRollNumber(v *string) *StudentUpdateOne {
	if v != nil {
		_u.SetRollNumber(*v)
	}
	return _u
}

// SetFirstName sets the "first_name" field.
func (_u *StudentUpdateOne) SetFirstName(v string) *StudentUpdateOne {
	_u.mutation.SetFirstName(v)
	return _u
}

// SetNillableFirstName sets the "first_name" field if the given value is not nil.
func (_u *StudentUpdateOne) SetNillableFirstName(v *string) *StudentUpdateOne {
	if v != nil {
		_u.SetFirstName(*v)
	}
	return _u
}

// SetLastName sets the "last_name" field.
func (_u *StudentUpdateOne) SetLastName(v string) *StudentUpdateOne {
	_u.mutation.SetLastName(v)
	return _u
}

// SetNillableLastName sets the "last_name" field if the given value is not nil.
func (_u *StudentUpdateOne) SetNillableLastName(v *string) *StudentUpdateOne {
	if v != nil {
		_u.SetLastName(*v)
	}
	return _u
}

// SetGender sets the "gender" field.
func (_u *StudentUpdateOne) SetGender(v student.Gender) *StudentUpdateOne {
	_u.mutation.SetGender(v)
	return _u
}

// SetNillableGender sets the "gender" field if the given value is not nil.
func (_u *StudentUpdateOne) SetNillableGender(v *student.Gender) *StudentUpdateOne {
	if v != nil {
		_u.SetGender(*v)
	}
	return _u
}

// ClearGender clears the value of the "gender" field.
func (_u *StudentUpdateOne) ClearGender() *StudentUpdateOne {
	_u.mutation.ClearGender()
	return _u
}

// SetDateOfBirth sets the "date_of_birth" field.
func (_u *StudentUpdateOne) SetDateOfBirth(v time.Time) *StudentUpdateOne {
	_u.mutation.SetDateOfBirth(v)
	return _u
}

// SetNillableDateOfBirth sets the "date_of_birth" field if the given value is not nil.
func (_u *StudentUpdateOne) SetNillableDateOfBirth(v *time.Time) *StudentUpdateOne {
	if v != nil {
		_u.SetDateOfBirth(*v)
	}
	return _u
}

// ClearDateOfBirth clears the value of the "date_of_birth" field.
func (_u *StudentUpdateOne) ClearDateOfBirth() *StudentUpdateOne {
	_u.mutation.ClearDateOfBirth()
	return _u
}

// SetPhone sets the "phone" field.
func (_u *StudentUpdateOne) SetPhone(v string) *StudentUpdateOne {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *StudentUpdateOne) SetNillablePhone(v *string) *StudentUpdateOne {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// ClearPhone clears the value of the "phone" field.
func (_u *StudentUpdateOne) ClearPhone() *StudentUpdateOne {
	_u.mutation.ClearPhone()
	return _u
}

// SetParentPhone sets the "parent_phone" field.
func (_u *StudentUpdateOne) SetParentPhone(v string) *StudentUpdateOne {
	_u.mutation.SetParentPhone(v)
	return _u
}

// SetNillableParentPhone sets the "parent_phone" field if the given value is not nil.
func (_u *StudentUpdateOne) SetNillableParentPhone(v *string) *StudentUpdateOne {
	if v != nil {
		_u.SetParentPhone(*v)
	}
	return _u
}

// ClearParentPhone clears the value of the "parent_phone" field.
func (_u *StudentUpdateOne) ClearParentPhone() *StudentUpdateOne {
	_u.mutation.ClearParentPhone()
	return _u
}

// SetAddress sets the "address" field.
func (_u *StudentUpdateOne) SetAddress(v string) *StudentUpdateOne {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *StudentUpdateOne) SetNillableAddress(v *string) *StudentUpdateOne {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// ClearAddress clears the value of the "address" field.
func (_u *StudentUpdateOne) ClearAddress() *StudentUpdateOne {
	_u.mutation.ClearAddress()
	return _u
}

// SetClassID sets the "class_id" field.
func (_u *StudentUpdateOne) SetClassID(v uuid.UUID) *StudentUpdateOne {
	_u.mutation.SetClassID(v)
	return _u
}

// SetNillableClassID sets the "class_id" field if the given value is not nil.
func (_u *StudentUpdateOne) SetNillableClassID(v *uuid.UUID) *StudentUpdateOne {
	if v != nil {
		_u.SetClassID(*v)
	}
	return _u
}

// ClearClassID clears the value of the "class_id" field.
func (_u *StudentUpdateOne) ClearClassID() *StudentUpdateOne {
	_u.mutation.ClearClassID()
	return _u
}

// SetJoiningDate sets the "joining_date" field.
func (_u *StudentUpdateOne) SetJoiningDate(v time.Time) *StudentUpdateOne {
	_u.mutation.SetJoiningDate(v)
	return _u
}

// SetNillableJoiningDate sets the "joining_date" field if the given value is not nil.
func (_u *StudentUpdateOne) SetNillableJoiningDate(v *time.Time) *StudentUpdateOne {
	if v != nil {
		_u.SetJoiningDate(*v)
	}
	return _u
}

// SetAvatarURL sets the "avatar_url" field.
func (_u *StudentUpdateOne) SetAvatarURL(v string) *StudentUpdateOne {
	_u.mutation.SetAvatarURL(v)
	return _u
}

// SetNillableAvatarURL sets the "avatar_url" field if the given value is not nil.
func (_u *StudentUpdateOne) SetNillableAvatarURL(v *string) *StudentUpdateOne {
	if v != nil {
		_u.SetAvatarURL(*v)
	}
	return _u
}

// ClearAvatarURL clears the value of the "avatar_url" field.
func (_u *StudentUpdateOne) ClearAvatarURL() *StudentUpdateOne {
	_u.mutation.ClearAvatarURL()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *StudentUpdateOne) SetUser(v *User) *StudentUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetClass sets the "class" edge to the Class entity.
func (_u *StudentUpdateOne) SetClass(v *Class) *StudentUpdateOne {
	return _u.SetClassID(v.ID)
}

// Mutation returns the StudentMutation object of the builder.
func (_u *StudentUpdateOne) Mutation() *StudentMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *StudentUpdateOne) ClearUser() *StudentUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearClass clears the "class" edge to the Class entity.
func (_u *StudentUpdateOne) ClearClass() *StudentUpdateOne {
	_u.mutation.ClearClass()
	return _u
}

// Where appends a list predicates to the StudentUpdate builder.
func (_u *StudentUpdateOne) Where(ps ...predicate.Student) *StudentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *StudentUpdateOne) Select(field string, fields ...string) *StudentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Student entity.
func (_u *StudentUpdateOne) Save(ctx context.Context) (*Student, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StudentUpdateOne) SaveX(ctx context.Context) *Student {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *StudentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StudentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StudentUpdateOne) check() error {
	if v, ok := _u.mutation.Gender(); ok {
		if err := student.GenderValidator(v); err != nil {
			return &ValidationError{Name: "gender", err: fmt.Errorf(`ent: validator failed for field "Student.gender": %w`, err)}
		}
	}
	return nil
}

func (_u *StudentUpdateOne) sqlSave(ctx context.Context) (_node *Student, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(student.Table, student.Columns, sqlgraph.NewFieldSpec(student.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Student.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, student.FieldID)
		for _, f := range fields {
			if !student.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != student.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RollNumber(); ok {
		_spec.SetField(student.FieldRollNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.FirstName(); ok {
		_spec.SetField(student.FieldFirstName, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastName(); ok {
		_spec.SetField(student.FieldLastName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Gender(); ok {
		_spec.SetField(student.FieldGender, field.TypeEnum, value)
	}
	if _u.mutation.GenderCleared() {
		_spec.ClearField(student.FieldGender, field.TypeEnum)
	}
	if value, ok := _u.mutation.DateOfBirth(); ok {
		_spec.SetField(student.FieldDateOfBirth, field.TypeTime, value)
	}
	if _u.mutation.DateOfBirthCleared() {
		_spec.ClearField(student.FieldDateOfBirth, field.TypeTime)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(student.FieldPhone, field.TypeString, value)
	}
	if _u.mutation.PhoneCleared() {
		_spec.ClearField(student.FieldPhone, field.TypeString)
	}
	if value, ok := _u.mutation.ParentPhone(); ok {
		_spec.SetField(student.FieldParentPhone, field.TypeString, value)
	}
	if _u.mutation.ParentPhoneCleared() {
		_spec.ClearField(student.FieldParentPhone, field.TypeString)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(student.FieldAddress, field.TypeString, value)
	}
	if _u.mutation.AddressCleared() {
		_spec.ClearField(student.FieldAddress, field.TypeString)
	}
	if value, ok := _u.mutation.JoiningDate(); ok {
		_spec.SetField(student.FieldJoiningDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AvatarURL(); ok {
		_spec.SetField(student.FieldAvatarURL, field.TypeString, value)
	}
	if _u.mutation.AvatarURLCleared() {
		_spec.ClearField(student.FieldAvatarURL, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   student.UserTable,
			Columns: []string{student.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   student.UserTable,
			Columns: []string{student.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ClassCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   student.ClassTable,
			Columns: []string{student.ClassColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(class.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClassIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   student.ClassTable,
			Columns: []string{student.ClassColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(class.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Student{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{student.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
