// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-seed/ent/subject"
	"go-seed/ent/teacher"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// SubjectCreate is the builder for creating a Subject entity.
type SubjectCreate struct {
	config
	mutation *SubjectMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *SubjectCreate) SetName(v string) *SubjectCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetCode sets the "code" field.
func (_c *SubjectCreate) SetCode(v string) *SubjectCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_c *SubjectCreate) SetNillableCode(v *string) *SubjectCreate {
	if v != nil {
		_c.SetCode(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *SubjectCreate) SetDescription(v string) *SubjectCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *SubjectCreate) SetNillableDescription(v *string) *SubjectCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SubjectCreate) SetID(v uuid.UUID) *SubjectCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SubjectCreate) SetNillableID(v *uuid.UUID) *SubjectCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddTeacherIDs adds the "teachers" edge to the Teacher entity by IDs.
func (_c *SubjectCreate) AddTeacherIDs(ids ...uuid.UUID) *SubjectCreate {
	_c.mutation.AddTeacherIDs(ids...)
	return _c
}

// AddTeachers adds the "teachers" edges to the Teacher entity.
func (_c *SubjectCreate) AddTeachers(v ...*Teacher) *SubjectCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTeacherIDs(ids...)
}

// Mutation returns the SubjectMutation object of the builder.
func (_c *SubjectCreate) Mutation() *SubjectMutation {
	return _c.mutation
}

// Save creates the Subject in the database.
func (_c *SubjectCreate) Save(ctx context.Context) (*Subject, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SubjectCreate) SaveX(ctx context.Context) *Subject {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubjectCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubjectCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SubjectCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := subject.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SubjectCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Subject.name"`)}
	}
	return nil
}

func (_c *SubjectCreate) sqlSave(ctx context.Context) (*Subject, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SubjectCreate) createSpec() (*Subject, *sqlgraph.CreateSpec) {
	var (
		_node = &Subject{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(subject.Table, sqlgraph.NewFieldSpec(subject.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(subject.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(subject.FieldCode, field.TypeString, value)
		_node.Code = &value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(subject.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if nodes := _c.mutation.TeachersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   subject.TeachersTable,
			Columns: subject.TeachersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(teacher.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Subject.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubjectUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *SubjectCreate) OnConflict(opts ...sql.ConflictOption) *SubjectUpsertOne {
	_c.conflict = opts
	return &SubjectUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Subject.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubjectCreate) OnConflictColumns(columns ...string) *SubjectUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubjectUpsertOne{
		create: _c,
	}
}

type (
	// SubjectUpsertOne is the builder for "upsert"-ing
	//  one Subject node.
	SubjectUpsertOne struct {
		create *SubjectCreate
	}

	// SubjectUpsert is the "OnConflict" setter.
	SubjectUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *SubjectUpsert) SetName(v string) *SubjectUpsert {
	u.Set(subject.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SubjectUpsert) UpdateName() *SubjectUpsert {
	u.SetExcluded(subject.FieldName)
	return u
}

// SetCode sets the "code" field.
func (u *SubjectUpsert) SetCode(v string) *SubjectUpsert {
	u.Set(subject.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *SubjectUpsert) UpdateCode() *SubjectUpsert {
	u.SetExcluded(subject.FieldCode)
	return u
}

// ClearCode clears the value of the "code" field.
func (u *SubjectUpsert) ClearCode() *SubjectUpsert {
	u.SetNull(subject.FieldCode)
	return u
}

// SetDescription sets the "description" field.
func (u *SubjectUpsert) SetDescription(v string) *SubjectUpsert {
	u.Set(subject.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SubjectUpsert) UpdateDescription() *SubjectUpsert {
	u.SetExcluded(subject.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *SubjectUpsert) ClearDescription() *SubjectUpsert {
	u.SetNull(subject.FieldDescription)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Subject.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(subject.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SubjectUpsertOne) UpdateNewValues() *SubjectUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(subject.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Subject.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SubjectUpsertOne) Ignore() *SubjectUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubjectUpsertOne) DoNothing() *SubjectUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubjectCreate.OnConflict
// documentation for more info.
func (u *SubjectUpsertOne) Update(set func(*SubjectUpsert)) *SubjectUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubjectUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *SubjectUpsertOne) SetName(v string) *SubjectUpsertOne {
	return u.Update(func(s *SubjectUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SubjectUpsertOne) UpdateName() *SubjectUpsertOne {
	return u.Update(func(s *SubjectUpsert) {
		s.UpdateName()
	})
}

// SetCode sets the "code" field.
func (u *SubjectUpsertOne) SetCode(v string) *SubjectUpsertOne {
	return u.Update(func(s *SubjectUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *SubjectUpsertOne) UpdateCode() *SubjectUpsertOne {
	return u.Update(func(s *SubjectUpsert) {
		s.UpdateCode()
	})
}

// ClearCode clears the value of the "code" field.
func (u *SubjectUpsertOne) ClearCode() *SubjectUpsertOne {
	return u.Update(func(s *SubjectUpsert) {
		s.ClearCode()
	})
}

// SetDescription sets the "description" field.
func (u *SubjectUpsertOne) SetDescription(v string) *SubjectUpsertOne {
	return u.Update(func(s *SubjectUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SubjectUpsertOne) UpdateDescription() *SubjectUpsertOne {
	return u.Update(func(s *SubjectUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *SubjectUpsertOne) ClearDescription() *SubjectUpsertOne {
	return u.Update(func(s *SubjectUpsert) {
		s.ClearDescription()
	})
}

// Exec executes the query.
func (u *SubjectUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubjectCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubjectUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SubjectUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: SubjectUpsertOne.ID is not supported by MySQL driver. Use SubjectUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SubjectUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SubjectCreateBulk is the builder for creating many Subject entities in bulk.
type SubjectCreateBulk struct {
	config
	err      error
	builders []*SubjectCreate
	conflict []sql.ConflictOption
}

// Save creates the Subject entities in the database.
func (_c *SubjectCreateBulk) Save(ctx context.Context) ([]*Subject, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Subject, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubjectMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SubjectCreateBulk) SaveX(ctx context.Context) []*Subject {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubjectCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubjectCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Subject.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubjectUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *SubjectCreateBulk) OnConflict(opts ...sql.ConflictOption) *SubjectUpsertBulk {
	_c.conflict = opts
	return &SubjectUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Subject.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubjectCreateBulk) OnConflictColumns(columns ...string) *SubjectUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubjectUpsertBulk{
		create: _c,
	}
}

// SubjectUpsertBulk is the builder for "upsert"-ing
// a bulk of Subject nodes.
type SubjectUpsertBulk struct {
	create *SubjectCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Subject.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(subject.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SubjectUpsertBulk) UpdateNewValues() *SubjectUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(subject.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Subject.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SubjectUpsertBulk) Ignore() *SubjectUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubjectUpsertBulk) DoNothing() *SubjectUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubjectCreateBulk.OnConflict
// documentation for more info.
func (u *SubjectUpsertBulk) Update(set func(*SubjectUpsert)) *SubjectUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubjectUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *SubjectUpsertBulk) SetName(v string) *SubjectUpsertBulk {
	return u.Update(func(s *SubjectUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SubjectUpsertBulk) UpdateName() *SubjectUpsertBulk {
	return u.Update(func(s *SubjectUpsert) {
		s.UpdateName()
	})
}

// SetCode sets the "code" field.
func (u *SubjectUpsertBulk) SetCode(v string) *SubjectUpsertBulk {
	return u.Update(func(s *SubjectUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *SubjectUpsertBulk) UpdateCode() *SubjectUpsertBulk {
	return u.Update(func(s *SubjectUpsert) {
		s.UpdateCode()
	})
}

// ClearCode clears the value of the "code" field.
func (u *SubjectUpsertBulk) ClearCode() *SubjectUpsertBulk {
	return u.Update(func(s *SubjectUpsert) {
		s.ClearCode()
	})
}

// SetDescription sets the "description" field.
func (u *SubjectUpsertBulk) SetDescription(v string) *SubjectUpsertBulk {
	return u.Update(func(s *SubjectUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SubjectUpsertBulk) UpdateDescription() *SubjectUpsertBulk {
	return u.Update(func(s *SubjectUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *SubjectUpsertBulk) ClearDescription() *SubjectUpsertBulk {
	return u.Update(func(s *SubjectUpsert) {
		s.ClearDescription()
	})
}

// Exec executes the query.
func (u *SubjectUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SubjectCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubjectCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubjectUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
