// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-seed/ent/department"
	"go-seed/ent/predicate"
	"go-seed/ent/subject"
	"go-seed/ent/teacher"
	"go-seed/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// TeacherUpdate is the builder for updating Teacher entities.
type TeacherUpdate struct {
	config
	hooks    []Hook
	mutation *TeacherMutation
}

// Where appends a list predicates to the TeacherUpdate builder.
func (_u *TeacherUpdate) Where(ps ...predicate.Teacher) *TeacherUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TeacherUpdate) SetUserID(v uuid.UUID) *TeacherUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TeacherUpdate) SetNillableUserID(v *uuid.UUID) *TeacherUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetFirstName sets the "first_name" field.
func (_u *TeacherUpdate) SetFirstName(v string) *TeacherUpdate {
	_u.mutation.SetFirstName(v)
	return _u
}

// SetNillableFirstName sets the "first_name" field if the given value is not nil.
func (_u *TeacherUpdate) SetNillableFirstName(v *string) *TeacherUpdate {
	if v != nil {
		_u.SetFirstName(*v)
	}
	return _u
}

// SetLastName sets the "last_name" field.
func (_u *TeacherUpdate) SetLastName(v string) *TeacherUpdate {
	_u.mutation.SetLastName(v)
	return _u
}

// SetNillableLastName sets the "last_name" field if the given value is not nil.
func (_u *TeacherUpdate) SetNillableLastName(v *string) *TeacherUpdate {
	if v != nil {
		_u.SetLastName(*v)
	}
	return _u
}

// SetGender sets the "gender" field.
func (_u *TeacherUpdate) SetGender(v teacher.Gender) *TeacherUpdate {
	_u.mutation.SetGender(v)
	return _u
}

// SetNillableGender sets the "gender" field if the given value is not nil.
func (_u *TeacherUpdate) SetNillableGender(v *teacher.Gender) *TeacherUpdate {
	if v != nil {
		_u.SetGender(*v)
	}
	return _u
}

// ClearGender clears the value of the "gender" field.
func (_u *TeacherUpdate) ClearGender() *TeacherUpdate {
	_u.mutation.ClearGender()
	return _u
}

// SetDateOfBirth sets the "date_of_birth" field.
func (_u *TeacherUpdate) SetDateOfBirth(v time.Time) *TeacherUpdate {
	_u.mutation.SetDateOfBirth(v)
	return _u
}

// SetNillableDateOfBirth sets the "date_of_birth" field if the given value is not nil.
func (_u *TeacherUpdate) SetNillableDateOfBirth(v *time.Time) *TeacherUpdate {
	if v != nil {
		_u.SetDateOfBirth(*v)
	}
	return _u
}

// ClearDateOfBirth clears the value of the "date_of_birth" field.
func (_u *TeacherUpdate) ClearDateOfBirth() *TeacherUpdate {
	_u.mutation.ClearDateOfBirth()
	return _u
}

// SetPhone sets the "phone" field.
func (_u *TeacherUpdate) SetPhone(v string) *TeacherUpdate {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *TeacherUpdate) SetNillablePhone(v *string) *TeacherUpdate {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// ClearPhone clears the value of the "phone" field.
func (_u *TeacherUpdate) ClearPhone() *TeacherUpdate {
	_u.mutation.ClearPhone()
	return _u
}

// SetAddress sets the "address" field.
func (_u *TeacherUpdate) SetAddress(v string) *TeacherUpdate {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *TeacherUpdate) SetNillableAddress(v *string) *TeacherUpdate {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// ClearAddress clears the value of the "address" field.
func (_u *TeacherUpdate) ClearAddress() *TeacherUpdate {
	_u.mutation.ClearAddress()
	return _u
}

// SetDepartmentID sets the "department_id" field.
func (_u *TeacherUpdate) SetDepartmentID(v int) *TeacherUpdate {
	_u.mutation.SetDepartmentID(v)
	return _u
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (_u *TeacherUpdate) SetNillableDepartmentID(v *int) *TeacherUpdate {
	if v != nil {
		_u.SetDepartmentID(*v)
	}
	return _u
}

// ClearDepartmentID clears the value of the "department_id" field.
func (_u *TeacherUpdate) ClearDepartmentID() *TeacherUpdate {
	_u.mutation.ClearDepartmentID()
	return _u
}

// SetQualification sets the "qualification" field.
func (_u *TeacherUpdate) SetQualification(v string) *TeacherUpdate {
	_u.mutation.SetQualification(v)
	return _u
}

// SetNillableQualification sets the "qualification" field if the given value is not nil.
func (_u *TeacherUpdate) SetNillableQualification(v *string) *TeacherUpdate {
	if v != nil {
		_u.SetQualification(*v)
	}
	return _u
}

// ClearQualification clears the value of the "qualification" field.
func (_u *TeacherUpdate) ClearQualification() *TeacherUpdate {
	_u.mutation.ClearQualification()
	return _u
}

// SetJoiningDate sets the "joining_date" field.
func (_u *TeacherUpdate) SetJoiningDate(v time.Time) *TeacherUpdate {
	_u.mutation.SetJoiningDate(v)
	return _u
}

// SetNillableJoiningDate sets the "joining_date" field if the given value is not nil.
func (_u *TeacherUpdate) SetNillableJoiningDate(v *time.Time) *TeacherUpdate {
	if v != nil {
		_u.SetJoiningDate(*v)
	}
	return _u
}

// ClearJoiningDate clears the value of the "joining_date" field.
func (_u *TeacherUpdate) ClearJoiningDate() *TeacherUpdate {
	_u.mutation.ClearJoiningDate()
	return _u
}

// SetAvatarURL sets the "avatar_url" field.
func (_u *TeacherUpdate) SetAvatarURL(v string) *TeacherUpdate {
	_u.mutation.SetAvatarURL(v)
	return _u
}

// SetNillableAvatarURL sets the "avatar_url" field if the given value is not nil.
func (_u *TeacherUpdate) SetNillableAvatarURL(v *string) *TeacherUpdate {
	if v != nil {
		_u.SetAvatarURL(*v)
	}
	return _u
}

// ClearAvatarURL clears the value of the "avatar_url" field.
func (_u *TeacherUpdate) ClearAvatarURL() *TeacherUpdate {
	_u.mutation.ClearAvatarURL()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *TeacherUpdate) SetUser(v *User) *TeacherUpdate {
	return _u.SetUserID(v.ID)
}

// SetDepartment sets the "department" edge to the Department entity.
func (_u *TeacherUpdate) SetDepartment(v *Department) *TeacherUpdate {
	return _u.SetDepartmentID(v.ID)
}

// AddSubjectIDs adds the "subjects" edge to the Subject entity by IDs.
func (_u *TeacherUpdate) AddSubjectIDs(ids ...int) *TeacherUpdate {
	_u.mutation.AddSubjectIDs(ids...)
	return _u
}

// AddSubjects adds the "subjects" edges to the Subject entity.
func (_u *TeacherUpdate) AddSubjects(v ...*Subject) *TeacherUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubjectIDs(ids...)
}

// Mutation returns the TeacherMutation object of the builder.
func (_u *TeacherUpdate) Mutation() *TeacherMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *TeacherUpdate) ClearUser() *TeacherUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearDepartment clears the "department" edge to the Department entity.
func (_u *TeacherUpdate) ClearDepartment() *TeacherUpdate {
	_u.mutation.ClearDepartment()
	return _u
}

// ClearSubjects clears all "subjects" edges to the Subject entity.
func (_u *TeacherUpdate) ClearSubjects() *TeacherUpdate {
	_u.mutation.ClearSubjects()
	return _u
}

// RemoveSubjectIDs removes the "subjects" edge to Subject entities by IDs.
func (_u *TeacherUpdate) RemoveSubjectIDs(ids ...int) *TeacherUpdate {
	_u.mutation.RemoveSubjectIDs(ids...)
	return _u
}

// RemoveSubjects removes "subjects" edges to Subject entities.
func (_u *TeacherUpdate) RemoveSubjects(v ...*Subject) *TeacherUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubjectIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TeacherUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeacherUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TeacherUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeacherUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeacherUpdate) check() error {
	if v, ok := _u.mutation.Gender(); ok {
		if err := teacher.GenderValidator(v); err != nil {
			return &ValidationError{Name: "gender", err: fmt.Errorf(`ent: validator failed for field "Teacher.gender": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Teacher.user"`)
	}
	return nil
}

func (_u *TeacherUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teacher.Table, teacher.Columns, sqlgraph.NewFieldSpec(teacher.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FirstName(); ok {
		_spec.SetField(teacher.FieldFirstName, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastName(); ok {
		_spec.SetField(teacher.FieldLastName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Gender(); ok {
		_spec.SetField(teacher.FieldGender, field.TypeEnum, value)
	}
	if _u.mutation.GenderCleared() {
		_spec.ClearField(teacher.FieldGender, field.TypeEnum)
	}
	if value, ok := _u.mutation.DateOfBirth(); ok {
		_spec.SetField(teacher.FieldDateOfBirth, field.TypeTime, value)
	}
	if _u.mutation.DateOfBirthCleared() {
		_spec.ClearField(teacher.FieldDateOfBirth, field.TypeTime)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(teacher.FieldPhone, field.TypeString, value)
	}
	if _u.mutation.PhoneCleared() {
		_spec.ClearField(teacher.FieldPhone, field.TypeString)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(teacher.FieldAddress, field.TypeString, value)
	}
	if _u.mutation.AddressCleared() {
		_spec.ClearField(teacher.FieldAddress, field.TypeString)
	}
	if value, ok := _u.mutation.Qualification(); ok {
		_spec.SetField(teacher.FieldQualification, field.TypeString, value)
	}
	if _u.mutation.QualificationCleared() {
		_spec.ClearField(teacher.FieldQualification, field.TypeString)
	}
	if value, ok := _u.mutation.JoiningDate(); ok {
		_spec.SetField(teacher.FieldJoiningDate, field.TypeTime, value)
	}
	if _u.mutation.JoiningDateCleared() {
		_spec.ClearField(teacher.FieldJoiningDate, field.TypeTime)
	}
	if value, ok := _u.mutation.AvatarURL(); ok {
		_spec.SetField(teacher.FieldAvatarURL, field.TypeString, value)
	}
	if _u.mutation.AvatarURLCleared() {
		_spec.ClearField(teacher.FieldAvatarURL, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   teacher.UserTable,
			Columns: []string{teacher.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   teacher.UserTable,
			Columns: []string{teacher.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DepartmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   teacher.DepartmentTable,
			Columns: []string{teacher.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DepartmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   teacher.DepartmentTable,
			Columns: []string{teacher.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubjectsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   teacher.SubjectsTable,
			Columns: teacher.SubjectsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subject.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubjectsIDs(); len(nodes) > 0 && !_u.mutation.SubjectsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   teacher.SubjectsTable,
			Columns: teacher.SubjectsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subject.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubjectsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   teacher.SubjectsTable,
			Columns: teacher.SubjectsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subject.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teacher.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TeacherUpdateOne is the builder for updating a single Teacher entity.
type TeacherUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TeacherMutation
}

// SetUserID sets the "user_id" field.
func (_u *TeacherUpdateOne) SetUserID(v uuid.UUID) *TeacherUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TeacherUpdateOne) SetNillableUserID(v *uuid.UUID) *TeacherUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetFirstName sets the "first_name" field.
func (_u *TeacherUpdateOne) SetFirstName(v string) *TeacherUpdateOne {
	_u.mutation.SetFirstName(v)
	return _u
}

// SetNillableFirstName sets the "first_name" field if the given value is not nil.
func (_u *TeacherUpdateOne) SetNillableFirstName(v *string) *TeacherUpdateOne {
	if v != nil {
		_u.SetFirstName(*v)
	}
	return _u
}

// SetLastName sets the "last_name" field.
func (_u *TeacherUpdateOne) SetLastName(v string) *TeacherUpdateOne {
	_u.mutation.SetLastName(v)
	return _u
}

// SetNillableLastName sets the "last_name" field if the given value is not nil.
func (_u *TeacherUpdateOne) SetNillableLastName(v *string) *TeacherUpdateOne {
	if v != nil {
		_u.SetLastName(*v)
	}
	return _u
}

// SetGender sets the "gender" field.
func (_u *TeacherUpdateOne) SetGender(v teacher.Gender) *TeacherUpdateOne {
	_u.mutation.SetGender(v)
	return _u
}

// SetNillableGender sets the "gender" field if the given value is not nil.
func (_u *TeacherUpdateOne) SetNillableGender(v *teacher.Gender) *TeacherUpdateOne {
	if v != nil {
		_u.SetGender(*v)
	}
	return _u
}

// ClearGender clears the value of the "gender" field.
func (_u *TeacherUpdateOne) ClearGender() *TeacherUpdateOne {
	_u.mutation.ClearGender()
	return _u
}

// SetDateOfBirth sets the "date_of_birth" field.
func (_u *TeacherUpdateOne) SetDateOfBirth(v time.Time) *TeacherUpdateOne {
	_u.mutation.SetDateOfBirth(v)
	return _u
}

// SetNillableDateOfBirth sets the "date_of_birth" field if the given value is not nil.
func (_u *TeacherUpdateOne) SetNillableDateOfBirth(v *time.Time) *TeacherUpdateOne {
	if v != nil {
		_u.SetDateOfBirth(*v)
	}
	return _u
}

// ClearDateOfBirth clears the value of the "date_of_birth" field.
func (_u *TeacherUpdateOne) ClearDateOfBirth() *TeacherUpdateOne {
	_u.mutation.ClearDateOfBirth()
	return _u
}

// SetPhone sets the "phone" field.
func (_u *TeacherUpdateOne) SetPhone(v string) *TeacherUpdateOne {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *TeacherUpdateOne) SetNillablePhone(v *string) *TeacherUpdateOne {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// ClearPhone clears the value of the "phone" field.
func (_u *TeacherUpdateOne) ClearPhone() *TeacherUpdateOne {
	_u.mutation.ClearPhone()
	return _u
}

// SetAddress sets the "address" field.
func (_u *TeacherUpdateOne) SetAddress(v string) *TeacherUpdateOne {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *TeacherUpdateOne) SetNillableAddress(v *string) *TeacherUpdateOne {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// ClearAddress clears the value of the "address" field.
func (_u *TeacherUpdateOne) ClearAddress() *TeacherUpdateOne {
	_u.mutation.ClearAddress()
	return _u
}

// SetDepartmentID sets the "department_id" field.
func (_u *TeacherUpdateOne) SetDepartmentID(v int) *TeacherUpdateOne {
	_u.mutation.SetDepartmentID(v)
	return _u
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (_u *TeacherUpdateOne) SetNillableDepartmentID(v *int) *TeacherUpdateOne {
	if v != nil {
		_u.SetDepartmentID(*v)
	}
	return _u
}

// ClearDepartmentID clears the value of the "department_id" field.
func (_u *TeacherUpdateOne) ClearDepartmentID() *TeacherUpdateOne {
	_u.mutation.ClearDepartmentID()
	return _u
}

// SetQualification sets the "qualification" field.
func (_u *TeacherUpdateOne) SetQualification(v string) *TeacherUpdateOne {
	_u.mutation.SetQualification(v)
	return _u
}

// SetNillableQualification sets the "qualification" field if the given value is not nil.
func (_u *TeacherUpdateOne) SetNillableQualification(v *string) *TeacherUpdateOne {
	if v != nil {
		_u.SetQualification(*v)
	}
	return _u
}

// ClearQualification clears the value of the "qualification" field.
func (_u *TeacherUpdateOne) ClearQualification() *TeacherUpdateOne {
	_u.mutation.ClearQualification()
	return _u
}

// SetJoiningDate sets the "joining_date" field.
func (_u *TeacherUpdateOne) SetJoiningDate(v time.Time) *TeacherUpdateOne {
	_u.mutation.SetJoiningDate(v)
	return _u
}

// SetNillableJoiningDate sets the "joining_date" field if the given value is not nil.
func (_u *TeacherUpdateOne) SetNillableJoiningDate(v *time.Time) *TeacherUpdateOne {
	if v != nil {
		_u.SetJoiningDate(*v)
	}
	return _u
}

// ClearJoiningDate clears the value of the "joining_date" field.
func (_u *TeacherUpdateOne) ClearJoiningDate() *TeacherUpdateOne {
	_u.mutation.ClearJoiningDate()
	return _u
}

// SetAvatarURL sets the "avatar_url" field.
func (_u *TeacherUpdateOne) SetAvatarURL(v string) *TeacherUpdateOne {
	_u.mutation.SetAvatarURL(v)
	return _u
}

// SetNillableAvatarURL sets the "avatar_url" field if the given value is not nil.
func (_u *TeacherUpdateOne) SetNillableAvatarURL(v *string) *TeacherUpdateOne {
	if v != nil {
		_u.SetAvatarURL(*v)
	}
	return _u
}

// ClearAvatarURL clears the value of the "avatar_url" field.
func (_u *TeacherUpdateOne) ClearAvatarURL() *TeacherUpdateOne {
	_u.mutation.ClearAvatarURL()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *TeacherUpdateOne) SetUser(v *User) *TeacherUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetDepartment sets the "department" edge to the Department entity.
func (_u *TeacherUpdateOne) SetDepartment(v *Department) *TeacherUpdateOne {
	return _u.SetDepartmentID(v.ID)
}

// AddSubjectIDs adds the "subjects" edge to the Subject entity by IDs.
func (_u *TeacherUpdateOne) AddSubjectIDs(ids ...int) *TeacherUpdateOne {
	_u.mutation.AddSubjectIDs(ids...)
	return _u
}

// AddSubjects adds the "subjects" edges to the Subject entity.
func (_u *TeacherUpdateOne) AddSubjects(v ...*Subject) *TeacherUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubjectIDs(ids...)
}

// Mutation returns the TeacherMutation object of the builder.
func (_u *TeacherUpdateOne) Mutation() *TeacherMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *TeacherUpdateOne) ClearUser() *TeacherUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearDepartment clears the "department" edge to the Department entity.
func (_u *TeacherUpdateOne) ClearDepartment() *TeacherUpdateOne {
	_u.mutation.ClearDepartment()
	return _u
}

// ClearSubjects clears all "subjects" edges to the Subject entity.
func (_u *TeacherUpdateOne) ClearSubjects() *TeacherUpdateOne {
	_u.mutation.ClearSubjects()
	return _u
}

// RemoveSubjectIDs removes the "subjects" edge to Subject entities by IDs.
func (_u *TeacherUpdateOne) RemoveSubjectIDs(ids ...int) *TeacherUpdateOne {
	_u.mutation.RemoveSubjectIDs(ids...)
	return _u
}

// RemoveSubjects removes "subjects" edges to Subject entities.
func (_u *TeacherUpdateOne) RemoveSubjects(v ...*Subject) *TeacherUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubjectIDs(ids...)
}

// Where appends a list predicates to the TeacherUpdate builder.
func (_u *TeacherUpdateOne) Where(ps ...predicate.Teacher) *TeacherUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TeacherUpdateOne) Select(field string, fields ...string) *TeacherUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Teacher entity.
func (_u *TeacherUpdateOne) Save(ctx context.Context) (*Teacher, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeacherUpdateOne) SaveX(ctx context.Context) *Teacher {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TeacherUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeacherUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeacherUpdateOne) check() error {
	if v, ok := _u.mutation.Gender(); ok {
		if err := teacher.GenderValidator(v); err != nil {
			return &ValidationError{Name: "gender", err: fmt.Errorf(`ent: validator failed for field "Teacher.gender": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Teacher.user"`)
	}
	return nil
}

func (_u *TeacherUpdateOne) sqlSave(ctx context.Context) (_node *Teacher, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teacher.Table, teacher.Columns, sqlgraph.NewFieldSpec(teacher.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Teacher.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, teacher.FieldID)
		for _, f := range fields {
			if !teacher.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != teacher.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FirstName(); ok {
		_spec.SetField(teacher.FieldFirstName, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastName(); ok {
		_spec.SetField(teacher.FieldLastName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Gender(); ok {
		_spec.SetField(teacher.FieldGender, field.TypeEnum, value)
	}
	if _u.mutation.GenderCleared() {
		_spec.ClearField(teacher.FieldGender, field.TypeEnum)
	}
	if value, ok := _u.mutation.DateOfBirth(); ok {
		_spec.SetField(teacher.FieldDateOfBirth, field.TypeTime, value)
	}
	if _u.mutation.DateOfBirthCleared() {
		_spec.ClearField(teacher.FieldDateOfBirth, field.TypeTime)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(teacher.FieldPhone, field.TypeString, value)
	}
	if _u.mutation.PhoneCleared() {
		_spec.ClearField(teacher.FieldPhone, field.TypeString)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(teacher.FieldAddress, field.TypeString, value)
	}
	if _u.mutation.AddressCleared() {
		_spec.ClearField(teacher.FieldAddress, field.TypeString)
	}
	if value, ok := _u.mutation.Qualification(); ok {
		_spec.SetField(teacher.FieldQualification, field.TypeString, value)
	}
	if _u.mutation.QualificationCleared() {
		_spec.ClearField(teacher.FieldQualification, field.TypeString)
	}
	if value, ok := _u.mutation.JoiningDate(); ok {
		_spec.SetField(teacher.FieldJoiningDate, field.TypeTime, value)
	}
	if _u.mutation.JoiningDateCleared() {
		_spec.ClearField(teacher.FieldJoiningDate, field.TypeTime)
	}
	if value, ok := _u.mutation.AvatarURL(); ok {
		_spec.SetField(teacher.FieldAvatarURL, field.TypeString, value)
	}
	if _u.mutation.AvatarURLCleared() {
		_spec.ClearField(teacher.FieldAvatarURL, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   teacher.UserTable,
			Columns: []string{teacher.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   teacher.UserTable,
			Columns: []string{teacher.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DepartmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   teacher.DepartmentTable,
			Columns: []string{teacher.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DepartmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   teacher.DepartmentTable,
			Columns: []string{teacher.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubjectsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   teacher.SubjectsTable,
			Columns: teacher.SubjectsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subject.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubjectsIDs(); len(nodes) > 0 && !_u.mutation.SubjectsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   teacher.SubjectsTable,
			Columns: teacher.SubjectsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subject.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubjectsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   teacher.SubjectsTable,
			Columns: teacher.SubjectsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subject.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Teacher{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teacher.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
