-- Migration for admission_inquiries table derived from admission-inquiries.json
SET session_replication_role = 'replica';

CREATE TABLE IF NOT EXISTS public.admission_inquiries (
    "inquiry_id" INTEGER,
    "student_name" TEXT,
    "guardian_name" TEXT,
    "contact_number" TEXT,
    "email_address" TEXT,
    "date_of_inquiry" TIMESTAMP,
    "program_of_interest" TEXT,
    "preferred_start_date" TIMESTAMP,
    "inquiry_source" TEXT,
    "status" TEXT,
    "notes" TEXT,
    "follow_up_date" TIMESTAMP,
    "assigned_to" TEXT,
    "campus_location" TEXT,
    "previous_education" TEXT,
    "img" TEXT
);

INSERT INTO public.admission_inquiries ("inquiry_id", "student_name", "guardian_name", "contact_number", "email_address", "date_of_inquiry", "program_of_interest", "preferred_start_date", "inquiry_source", "status", "notes", "follow_up_date", "assigned_to", "campus_location", "previous_education", "img") VALUES (1, 'Alice Johnson', 'Michael Johnson', '+1234567891', 'alice.johnson@example.com', '2024-11-22', 'Biology', '2025-01-10', 'Website', 'Closed', 'Interested in campus tours.', '2024-11-29', 'Emily Clark', 'Main Campus', 'High School Diploma', 'assets/images/user/user1.jpg') ON CONFLICT DO NOTHING;
INSERT INTO public.admission_inquiries ("inquiry_id", "student_name", "guardian_name", "contact_number", "email_address", "date_of_inquiry", "program_of_interest", "preferred_start_date", "inquiry_source", "status", "notes", "follow_up_date", "assigned_to", "campus_location", "previous_education", "img") VALUES (2, 'David Smith', 'Laura Smith', '+1234567892', 'david.smith@example.com', '2024-11-21', 'Mathematics', '2025-02-01', 'Referral', 'In Process', 'Needs information about financial aid.', '2024-11-30', 'John Doe', 'North Campus', 'High School Diploma', 'assets/images/user/user2.jpg') ON CONFLICT DO NOTHING;
INSERT INTO public.admission_inquiries ("inquiry_id", "student_name", "guardian_name", "contact_number", "email_address", "date_of_inquiry", "program_of_interest", "preferred_start_date", "inquiry_source", "status", "notes", "follow_up_date", "assigned_to", "campus_location", "previous_education", "img") VALUES (3, 'Sophia Brown', 'David Brown', '+1234567893', 'sophia.brown@example.com', '2024-11-20', 'Psychology', '2025-03-15', 'Social Media', 'Closed', 'Looking for evening classes.', '2024-12-01', 'Jessica Taylor', 'Main Campus', 'A-Level', 'assets/images/user/user3.jpg') ON CONFLICT DO NOTHING;
INSERT INTO public.admission_inquiries ("inquiry_id", "student_name", "guardian_name", "contact_number", "email_address", "date_of_inquiry", "program_of_interest", "preferred_start_date", "inquiry_source", "status", "notes", "follow_up_date", "assigned_to", "campus_location", "previous_education", "img") VALUES (4, 'Liam Wilson', 'Rebecca Wilson', '+1234567894', 'liam.wilson@example.com', '2024-11-19', 'Engineering', '2025-01-25', 'Website', 'New', 'Wants to know about internships.', '2024-11-28', 'Mark Harris', 'South Campus', 'High School Diploma', 'assets/images/user/user4.jpg') ON CONFLICT DO NOTHING;
INSERT INTO public.admission_inquiries ("inquiry_id", "student_name", "guardian_name", "contact_number", "email_address", "date_of_inquiry", "program_of_interest", "preferred_start_date", "inquiry_source", "status", "notes", "follow_up_date", "assigned_to", "campus_location", "previous_education", "img") VALUES (5, 'Emma Martinez', 'Carlos Martinez', '+1234567895', 'emma.martinez@example.com', '2024-11-18', 'Business Administration', '2025-02-20', 'Email', 'New', 'Interested in part-time options.', '2024-11-27', 'Sophia Johnson', 'Main Campus', 'Associate Degree', 'assets/images/user/user5.jpg') ON CONFLICT DO NOTHING;
INSERT INTO public.admission_inquiries ("inquiry_id", "student_name", "guardian_name", "contact_number", "email_address", "date_of_inquiry", "program_of_interest", "preferred_start_date", "inquiry_source", "status", "notes", "follow_up_date", "assigned_to", "campus_location", "previous_education", "img") VALUES (6, 'Olivia Garcia', 'Thomas Garcia', '+1234567896', 'olivia.garcia@example.com', '2024-11-17', 'Computer Science', '2025-01-15', 'Website', 'New', 'Inquiring about coding boot camps.', '2024-11-26', 'Anna Lee', 'West Campus', 'High School Diploma', 'assets/images/user/user6.jpg') ON CONFLICT DO NOTHING;
INSERT INTO public.admission_inquiries ("inquiry_id", "student_name", "guardian_name", "contact_number", "email_address", "date_of_inquiry", "program_of_interest", "preferred_start_date", "inquiry_source", "status", "notes", "follow_up_date", "assigned_to", "campus_location", "previous_education", "img") VALUES (7, 'Noah Taylor', 'Linda Taylor', '+1234567897', 'noah.taylor@example.com', '2024-11-16', 'Graphic Design', '2025-03-01', 'Social Media', 'In Process', 'Asking about portfolio requirements.', '2024-11-25', 'Chris Green', 'Main Campus', 'High School Diploma', 'assets/images/user/user7.jpg') ON CONFLICT DO NOTHING;
INSERT INTO public.admission_inquiries ("inquiry_id", "student_name", "guardian_name", "contact_number", "email_address", "date_of_inquiry", "program_of_interest", "preferred_start_date", "inquiry_source", "status", "notes", "follow_up_date", "assigned_to", "campus_location", "previous_education", "img") VALUES (8, 'Ava Anderson', 'James Anderson', '+1234567898', 'ava.anderson@example.com', '2024-11-15', 'Nursing', '2025-01-10', 'Website', 'Closed', 'Wants to know about clinical placements.', '2024-11-24', 'David White', 'South Campus', 'High School Diploma', 'assets/images/user/user8.jpg') ON CONFLICT DO NOTHING;
INSERT INTO public.admission_inquiries ("inquiry_id", "student_name", "guardian_name", "contact_number", "email_address", "date_of_inquiry", "program_of_interest", "preferred_start_date", "inquiry_source", "status", "notes", "follow_up_date", "assigned_to", "campus_location", "previous_education", "img") VALUES (9, 'Ethan Lee', 'Patricia Lee', '+1234567899', 'ethan.lee@example.com', '2024-11-14', 'Physics', '2025-02-01', 'Referral', 'In Process', 'Inquiring about research opportunities.', '2024-11-23', 'Matthew King', 'East Campus', 'High School Diploma', 'assets/images/user/user9.jpg') ON CONFLICT DO NOTHING;
INSERT INTO public.admission_inquiries ("inquiry_id", "student_name", "guardian_name", "contact_number", "email_address", "date_of_inquiry", "program_of_interest", "preferred_start_date", "inquiry_source", "status", "notes", "follow_up_date", "assigned_to", "campus_location", "previous_education", "img") VALUES (10, 'Mia Rodriguez', 'Luis Rodriguez', '+1234567800', 'mia.rodriguez@example.com', '2024-11-13', 'History', '2025-03-15', 'Website', 'New', 'Interested in study abroad programs.', '2024-11-22', 'Emma Clark', 'Main Campus', 'A-Level', 'assets/images/user/user10.jpg') ON CONFLICT DO NOTHING;
INSERT INTO public.admission_inquiries ("inquiry_id", "student_name", "guardian_name", "contact_number", "email_address", "date_of_inquiry", "program_of_interest", "preferred_start_date", "inquiry_source", "status", "notes", "follow_up_date", "assigned_to", "campus_location", "previous_education", "img") VALUES (11, 'James Wilson', 'Karen Wilson', '+1234567801', 'james.wilson@example.com', '2024-11-12', 'Chemistry', '2025-01-20', 'Email', 'New', 'Asking about lab facilities.', '2024-11-21', 'Olivia Brown', 'North Campus', 'High School Diploma', 'assets/images/user/user11.jpg') ON CONFLICT DO NOTHING;
INSERT INTO public.admission_inquiries ("inquiry_id", "student_name", "guardian_name", "contact_number", "email_address", "date_of_inquiry", "program_of_interest", "preferred_start_date", "inquiry_source", "status", "notes", "follow_up_date", "assigned_to", "campus_location", "previous_education", "img") VALUES (12, 'Lucas Hall', 'Sarah Hall', '+1234567802', 'lucas.hall@example.com', '2024-11-11', 'Environmental Science', '2025-02-15', 'Website', 'In Process', 'Looking for scholarship options.', '2024-11-20', 'Ryan Young', 'Main Campus', 'High School Diploma', 'assets/images/user/user12.jpg') ON CONFLICT DO NOTHING;
INSERT INTO public.admission_inquiries ("inquiry_id", "student_name", "guardian_name", "contact_number", "email_address", "date_of_inquiry", "program_of_interest", "preferred_start_date", "inquiry_source", "status", "notes", "follow_up_date", "assigned_to", "campus_location", "previous_education", "img") VALUES (13, 'Zoe King', 'Mark King', '+1234567803', 'zoe.king@example.com', '2024-11-10', 'Philosophy', '2025-01-15', 'Social Media', 'Closed', 'Interested in online courses.', '2024-11-19', 'Lisa White', 'East Campus', 'A-Level', 'assets/images/user/user13.jpg') ON CONFLICT DO NOTHING;
INSERT INTO public.admission_inquiries ("inquiry_id", "student_name", "guardian_name", "contact_number", "email_address", "date_of_inquiry", "program_of_interest", "preferred_start_date", "inquiry_source", "status", "notes", "follow_up_date", "assigned_to", "campus_location", "previous_education", "img") VALUES (14, 'Lily Adams', 'Robert Adams', '+1234567804', 'lily.adams@example.com', '2024-11-09', 'Information Technology', '2025-02-05', 'Website', 'New', 'Inquiring about certification programs.', '2024-11-18', 'Andrew Johnson', 'West Campus', 'High School Diploma', 'assets/images/user/user14.jpg') ON CONFLICT DO NOTHING;
INSERT INTO public.admission_inquiries ("inquiry_id", "student_name", "guardian_name", "contact_number", "email_address", "date_of_inquiry", "program_of_interest", "preferred_start_date", "inquiry_source", "status", "notes", "follow_up_date", "assigned_to", "campus_location", "previous_education", "img") VALUES (15, 'Charlotte Nelson', 'Paul Nelson', '+1234567805', 'charlotte.nelson@example.com', '2024-11-08', 'Art and Design', '2025-01-30', 'Email', 'In Process', 'Wants information about workshops.', '2024-11-17', 'Jennifer Lewis', 'North Campus', 'High School Diploma', 'assets/images/user/user15.jpg') ON CONFLICT DO NOTHING;

SET session_replication_role = 'origin';