-- Migration for adv_tbl_data table derived from adv-tbl-data.json
SET session_replication_role = 'replica';

CREATE TABLE IF NOT EXISTS public.adv_tbl_data (
    "id" INTEGER PRIMARY KEY,
    "img" TEXT,
    "first_name" TEXT,
    "last_name" TEXT,
    "gender" TEXT,
    "phone" TEXT,
    "email" TEXT,
    "age" INTEGER,
    "address" TEXT
);

INSERT INTO public.adv_tbl_data ("id", "img", "first_name", "last_name", "gender", "phone", "email", "age", "address") VALUES (0, 'assets/images/user/user6.jpg', 'Darlene', 'Riggs', 'female', '+1 (811) 538-3408', 'example@test.com', 39, '406 Mill Avenue') ON CONFLICT DO NOTHING;
INSERT INTO public.adv_tbl_data ("id", "img", "first_name", "last_name", "gender", "phone", "email", "age", "address") VALUES (1, 'assets/images/user/user3.jpg', 'Head', 'Newton', 'male', '+1 (847) 585-2042', 'example@test.com', 34, '316 Monitor Street') ON CONFLICT DO NOTHING;
INSERT INTO public.adv_tbl_data ("id", "img", "first_name", "last_name", "gender", "phone", "email", "age", "address") VALUES (2, 'assets/images/user/user8.jpg', 'Desiree', 'Schneider', 'female', '+1 (995) 549-2754', 'example@test.com', 32, '267 Pacific Street') ON CONFLICT DO NOTHING;
INSERT INTO public.adv_tbl_data ("id", "img", "first_name", "last_name", "gender", "phone", "email", "age", "address") VALUES (3, 'assets/images/user/user5.jpg', 'Holman', 'Mann', 'male', '+1 (975) 430-3063', 'example@test.com', 20, '268 Taaffe Place') ON CONFLICT DO NOTHING;
INSERT INTO public.adv_tbl_data ("id", "img", "first_name", "last_name", "gender", "phone", "email", "age", "address") VALUES (4, 'assets/images/user/user3.jpg', 'Stephens', 'Vega', 'male', '+1 (841) 561-3826', 'example@test.com', 37, '315 Dahl Court') ON CONFLICT DO NOTHING;
INSERT INTO public.adv_tbl_data ("id", "img", "first_name", "last_name", "gender", "phone", "email", "age", "address") VALUES (5, 'assets/images/user/user10.jpg', 'Cassie', 'Abbott', 'female', '+1 (874) 592-2349', 'example@test.com', 27, '944 Clark Street') ON CONFLICT DO NOTHING;
INSERT INTO public.adv_tbl_data ("id", "img", "first_name", "last_name", "gender", "phone", "email", "age", "address") VALUES (6, 'assets/images/user/user9.jpg', 'Romero', 'Pierce', 'male', '+1 (954) 511-2933', 'example@test.com', 28, '898 Irving Place') ON CONFLICT DO NOTHING;
INSERT INTO public.adv_tbl_data ("id", "img", "first_name", "last_name", "gender", "phone", "email", "age", "address") VALUES (7, 'assets/images/user/user3.jpg', 'Juanita', 'Norris', 'female', '+1 (914) 512-2265', 'example@test.com', 40, '474 Wakeman Place') ON CONFLICT DO NOTHING;
INSERT INTO public.adv_tbl_data ("id", "img", "first_name", "last_name", "gender", "phone", "email", "age", "address") VALUES (8, 'assets/images/user/user6.jpg', 'Duke', 'Sargent', 'male', '+1 (916) 556-3683', 'example@test.com', 38, '818 Bragg Street') ON CONFLICT DO NOTHING;
INSERT INTO public.adv_tbl_data ("id", "img", "first_name", "last_name", "gender", "phone", "email", "age", "address") VALUES (9, 'assets/images/user/user9.jpg', 'Selena', 'West', 'female', '+1 (878) 551-2618', 'example@test.com', 25, '364 Greenwood') ON CONFLICT DO NOTHING;
INSERT INTO public.adv_tbl_data ("id", "img", "first_name", "last_name", "gender", "phone", "email", "age", "address") VALUES (10, 'assets/images/user/user3.jpg', 'Lane', 'Sims', 'male', '+1 (868) 545-3934', 'example@test.com', 20, '293 Cove Lane') ON CONFLICT DO NOTHING;
INSERT INTO public.adv_tbl_data ("id", "img", "first_name", "last_name", "gender", "phone", "email", "age", "address") VALUES (11, 'assets/images/user/user5.jpg', 'Alexandra', 'Carr', 'female', '+1 (921) 557-3444', 'example@test.com', 40, '119 Wallabout Street') ON CONFLICT DO NOTHING;
INSERT INTO public.adv_tbl_data ("id", "img", "first_name", "last_name", "gender", "phone", "email", "age", "address") VALUES (12, 'assets/images/user/user7.jpg', 'Tanner', 'Hoover', 'male', '+1 (825) 406-2792', 'example@test.com', 30, '351 Ashland Place') ON CONFLICT DO NOTHING;
INSERT INTO public.adv_tbl_data ("id", "img", "first_name", "last_name", "gender", "phone", "email", "age", "address") VALUES (13, 'assets/images/user/user3.jpg', 'Mathis', 'Harrell', 'male', '+1 (856) 403-3786', 'example@test.com', 40, '950 Throop Avenue') ON CONFLICT DO NOTHING;
INSERT INTO public.adv_tbl_data ("id", "img", "first_name", "last_name", "gender", "phone", "email", "age", "address") VALUES (14, 'assets/images/user/user8.jpg', 'Julia', 'Warren', 'female', '+1 (939) 423-3321', 'example@test.com', 24, '460 Boardwalk ') ON CONFLICT DO NOTHING;
INSERT INTO public.adv_tbl_data ("id", "img", "first_name", "last_name", "gender", "phone", "email", "age", "address") VALUES (15, 'assets/images/user/user9.jpg', 'Jaclyn', 'Lawson', 'female', '+1 (987) 565-3431', 'example@test.com', 25, '676 Harbor Lane') ON CONFLICT DO NOTHING;
INSERT INTO public.adv_tbl_data ("id", "img", "first_name", "last_name", "gender", "phone", "email", "age", "address") VALUES (16, 'assets/images/user/user5.jpg', 'Paul', 'Chapman', 'male', '+1 (864) 523-3163', 'example@test.com', 38, '148 Nichols Avenue') ON CONFLICT DO NOTHING;
INSERT INTO public.adv_tbl_data ("id", "img", "first_name", "last_name", "gender", "phone", "email", "age", "address") VALUES (17, 'assets/images/user/user10.jpg', 'Aimee', 'Walters', 'female', '+1 (995) 419-3671', 'example@test.com', 31, '403 Coles Street') ON CONFLICT DO NOTHING;
INSERT INTO public.adv_tbl_data ("id", "img", "first_name", "last_name", "gender", "phone", "email", "age", "address") VALUES (18, 'assets/images/user/user5.jpg', 'Verna', 'Barlow', 'female', '+1 (822) 553-3841', 'example@test.com', 24, '881 Montague Terrace') ON CONFLICT DO NOTHING;
INSERT INTO public.adv_tbl_data ("id", "img", "first_name", "last_name", "gender", "phone", "email", "age", "address") VALUES (19, 'assets/images/user/user9.jpg', 'Beck', 'Singleton', 'male', '+1 (895) 595-2333', 'example@test.com', 39, '805 Hinsdale Street') ON CONFLICT DO NOTHING;
INSERT INTO public.adv_tbl_data ("id", "img", "first_name", "last_name", "gender", "phone", "email", "age", "address") VALUES (20, 'assets/images/user/user2.jpg', 'Baird', 'Stone', 'male', '+1 (864) 583-3148', 'example@test.com', 34, '228 Opal Court') ON CONFLICT DO NOTHING;
INSERT INTO public.adv_tbl_data ("id", "img", "first_name", "last_name", "gender", "phone", "email", "age", "address") VALUES (21, 'assets/images/user/user5.jpg', 'Helena', 'Best', 'female', '+1 (930) 552-2302', 'example@test.com', 23, '311 Dorchester Road') ON CONFLICT DO NOTHING;
INSERT INTO public.adv_tbl_data ("id", "img", "first_name", "last_name", "gender", "phone", "email", "age", "address") VALUES (22, 'assets/images/user/user5.jpg', 'Buck', 'Parrish', 'male', '+1 (994) 565-2706', 'example@test.com', 20, '633 Emerson Place') ON CONFLICT DO NOTHING;
INSERT INTO public.adv_tbl_data ("id", "img", "first_name", "last_name", "gender", "phone", "email", "age", "address") VALUES (23, 'assets/images/user/user2.jpg', 'Albert', 'English', 'male', '+1 (824) 457-2870', 'example@test.com', 35, '551 Clarendon Road') ON CONFLICT DO NOTHING;
INSERT INTO public.adv_tbl_data ("id", "img", "first_name", "last_name", "gender", "phone", "email", "age", "address") VALUES (24, 'assets/images/user/user6.jpg', 'Elinor', 'Waters', 'female', '+1 (894) 487-2463', 'example@test.com', 34, '660 Lefferts Place') ON CONFLICT DO NOTHING;
INSERT INTO public.adv_tbl_data ("id", "img", "first_name", "last_name", "gender", "phone", "email", "age", "address") VALUES (25, 'assets/images/user/user4.jpg', 'Sosa', 'Foster', 'male', '+1 (994) 565-2578', 'example@test.com', 38, '532 Nixon Court') ON CONFLICT DO NOTHING;
INSERT INTO public.adv_tbl_data ("id", "img", "first_name", "last_name", "gender", "phone", "email", "age", "address") VALUES (26, 'assets/images/user/user2.jpg', 'David', 'Perry', 'male', '+1 (977) 485-2959', 'example@test.com', 32, '545 Macdougal Street') ON CONFLICT DO NOTHING;
INSERT INTO public.adv_tbl_data ("id", "img", "first_name", "last_name", "gender", "phone", "email", "age", "address") VALUES (27, 'assets/images/user/user9.jpg', 'Imogene', 'Deleon', 'female', '+1 (860) 492-2617', 'example@test.com', 37, '512 Chestnut Avenue') ON CONFLICT DO NOTHING;
INSERT INTO public.adv_tbl_data ("id", "img", "first_name", "last_name", "gender", "phone", "email", "age", "address") VALUES (28, 'assets/images/user/user8.jpg', 'Fay', 'England', 'female', '+1 (846) 595-3003', 'example@test.com', 33, '227 Seeley Street') ON CONFLICT DO NOTHING;
INSERT INTO public.adv_tbl_data ("id", "img", "first_name", "last_name", "gender", "phone", "email", "age", "address") VALUES (29, 'assets/images/user/user4.jpg', 'Benita', 'Benson', 'female', '+1 (917) 413-3569', 'example@test.com', 39, '577 Ryder Street') ON CONFLICT DO NOTHING;
INSERT INTO public.adv_tbl_data ("id", "img", "first_name", "last_name", "gender", "phone", "email", "age", "address") VALUES (30, 'assets/images/user/user2.jpg', 'Thelma', 'Hale', 'female', '+1 (950) 517-2905', 'example@test.com', 38, '630 Lott Street') ON CONFLICT DO NOTHING;
INSERT INTO public.adv_tbl_data ("id", "img", "first_name", "last_name", "gender", "phone", "email", "age", "address") VALUES (31, 'assets/images/user/user7.jpg', 'Larson', 'Graham', 'male', '+1 (902) 423-3030', 'example@test.com', 35, '825 Calyer Street') ON CONFLICT DO NOTHING;
INSERT INTO public.adv_tbl_data ("id", "img", "first_name", "last_name", "gender", "phone", "email", "age", "address") VALUES (32, 'assets/images/user/user5.jpg', 'Kenya', 'Nguyen', 'female', '+1 (913) 416-3912', 'example@test.com', 35, '163 Stuart Street') ON CONFLICT DO NOTHING;
INSERT INTO public.adv_tbl_data ("id", "img", "first_name", "last_name", "gender", "phone", "email", "age", "address") VALUES (33, 'assets/images/user/user7.jpg', 'Richmond', 'Clements', 'male', '+1 (880) 468-2272', 'example@test.com', 22, '830 Kosciusko Street') ON CONFLICT DO NOTHING;
INSERT INTO public.adv_tbl_data ("id", "img", "first_name", "last_name", "gender", "phone", "email", "age", "address") VALUES (34, 'assets/images/user/user8.jpg', 'Garner', 'Wolf', 'male', '+1 (817) 482-2274', 'example@test.com', 23, '471 Holmes Lane') ON CONFLICT DO NOTHING;
INSERT INTO public.adv_tbl_data ("id", "img", "first_name", "last_name", "gender", "phone", "email", "age", "address") VALUES (35, 'assets/images/user/user2.jpg', 'Tammi', 'Goodwin', 'female', '+1 (805) 550-3654', 'example@test.com', 25, '772 Stoddard Place') ON CONFLICT DO NOTHING;
INSERT INTO public.adv_tbl_data ("id", "img", "first_name", "last_name", "gender", "phone", "email", "age", "address") VALUES (36, 'assets/images/user/user4.jpg', 'Autumn', 'Phelps', 'female', '+1 (906) 580-2631', 'example@test.com', 35, '608 Lamont Court') ON CONFLICT DO NOTHING;
INSERT INTO public.adv_tbl_data ("id", "img", "first_name", "last_name", "gender", "phone", "email", "age", "address") VALUES (37, 'assets/images/user/user10.jpg', 'Iris', 'Brown', 'female', '+1 (800) 561-3799', 'example@test.com', 22, '538 Foster Avenue') ON CONFLICT DO NOTHING;
INSERT INTO public.adv_tbl_data ("id", "img", "first_name", "last_name", "gender", "phone", "email", "age", "address") VALUES (38, 'assets/images/user/user3.jpg', 'Hudson', 'Robinson', 'male', '+1 (961) 430-2999', 'example@test.com', 36, '566 Llama Court') ON CONFLICT DO NOTHING;
INSERT INTO public.adv_tbl_data ("id", "img", "first_name", "last_name", "gender", "phone", "email", "age", "address") VALUES (39, 'assets/images/user/user9.jpg', 'Hood', 'Morse', 'male', '+1 (848) 419-2983', 'example@test.com', 29, '489 Cobek Court') ON CONFLICT DO NOTHING;
INSERT INTO public.adv_tbl_data ("id", "img", "first_name", "last_name", "gender", "phone", "email", "age", "address") VALUES (40, 'assets/images/user/user5.jpg', 'Sue', 'Smith', 'female', '+1 (915) 551-3831', 'example@test.com', 20, '826 Alice Court') ON CONFLICT DO NOTHING;
INSERT INTO public.adv_tbl_data ("id", "img", "first_name", "last_name", "gender", "phone", "email", "age", "address") VALUES (41, 'assets/images/user/user10.jpg', 'Silvia', 'Lancaster', 'female', '+1 (880) 578-2923', 'example@test.com', 26, '981 Village Road') ON CONFLICT DO NOTHING;
INSERT INTO public.adv_tbl_data ("id", "img", "first_name", "last_name", "gender", "phone", "email", "age", "address") VALUES (42, 'assets/images/user/user4.jpg', 'Summers', 'Christian', 'male', '+1 (927) 479-3790', 'example@test.com', 40, '595 Livonia Avenue') ON CONFLICT DO NOTHING;
INSERT INTO public.adv_tbl_data ("id", "img", "first_name", "last_name", "gender", "phone", "email", "age", "address") VALUES (43, 'assets/images/user/user3.jpg', 'Jacobs', 'Terrell', 'male', '+1 (990) 491-3442', 'example@test.com', 29, '734 Scott Avenue') ON CONFLICT DO NOTHING;
INSERT INTO public.adv_tbl_data ("id", "img", "first_name", "last_name", "gender", "phone", "email", "age", "address") VALUES (44, 'assets/images/user/user5.jpg', 'Howell', 'Lang', 'male', '+1 (815) 542-3206', 'example@test.com', 33, '986 Coleman Street') ON CONFLICT DO NOTHING;
INSERT INTO public.adv_tbl_data ("id", "img", "first_name", "last_name", "gender", "phone", "email", "age", "address") VALUES (45, 'assets/images/user/user7.jpg', 'Eve', 'Battle', 'female', '+1 (828) 442-3156', 'example@test.com', 33, '235 Dare Court') ON CONFLICT DO NOTHING;
INSERT INTO public.adv_tbl_data ("id", "img", "first_name", "last_name", "gender", "phone", "email", "age", "address") VALUES (46, 'assets/images/user/user7.jpg', 'Jeri', 'Moran', 'female', '+1 (884) 490-2332', 'example@test.com', 31, '392 Cyrus Avenue') ON CONFLICT DO NOTHING;

SET session_replication_role = 'origin';