-- Migration for assign_class_teacher table derived from assign-class-teacher.json
SET session_replication_role = 'replica';

CREATE TABLE IF NOT EXISTS public.assign_class_teacher (
    "id" INTEGER PRIMARY KEY,
    "teacher_id" TEXT,
    "img" TEXT,
    "teacher_name" TEXT,
    "class_id" TEXT,
    "class_name" TEXT,
    "subject" TEXT,
    "start_date" TIMESTAMP,
    "end_date" TIMESTAMP,
    "assigned_by" TEXT,
    "assignment_status" TEXT,
    "academic_year" TEXT,
    "class_timing" TEXT,
    "room_number" TEXT
);

INSERT INTO public.assign_class_teacher ("id", "teacher_id", "img", "teacher_name", "class_id", "class_name", "subject", "start_date", "end_date", "assigned_by", "assignment_status", "academic_year", "class_timing", "room_number") VALUES (1, 'T1001', 'assets/images/user/user1.jpg', 'John Doe', 'C101', 'Grade 10 Science', 'Physics', '2024-09-01', '2025-06-30', 'Admin001', 'Active', '2024-2025', 'Monday, Wednesday, Friday - 10:00 AM to 11:30 AM', '101') ON CONFLICT DO NOTHING;
INSERT INTO public.assign_class_teacher ("id", "teacher_id", "img", "teacher_name", "class_id", "class_name", "subject", "start_date", "end_date", "assigned_by", "assignment_status", "academic_year", "class_timing", "room_number") VALUES (2, 'T1002', 'assets/images/user/user2.jpg', 'Jane Smith', 'C102', 'Grade 9 Math', 'Mathematics', '2024-09-01', '2025-06-30', 'Admin002', 'Active', '2024-2025', 'Tuesday, Thursday - 9:00 AM to 10:30 AM', '102') ON CONFLICT DO NOTHING;
INSERT INTO public.assign_class_teacher ("id", "teacher_id", "img", "teacher_name", "class_id", "class_name", "subject", "start_date", "end_date", "assigned_by", "assignment_status", "academic_year", "class_timing", "room_number") VALUES (3, 'T1003', 'assets/images/user/user3.jpg', 'Emily Green', 'C103', 'Grade 11 English', 'English Literature', '2024-09-01', '2025-06-30', 'Admin001', 'Inactive', '2024-2025', 'Monday, Wednesday - 1:00 PM to 2:30 PM', '103') ON CONFLICT DO NOTHING;
INSERT INTO public.assign_class_teacher ("id", "teacher_id", "img", "teacher_name", "class_id", "class_name", "subject", "start_date", "end_date", "assigned_by", "assignment_status", "academic_year", "class_timing", "room_number") VALUES (4, 'T1004', 'assets/images/user/user4.jpg', 'Michael Brown', 'C104', 'Grade 12 History', 'History', '2024-09-01', '2025-06-30', 'Admin003', 'Active', '2024-2025', 'Monday, Friday - 3:00 PM to 4:30 PM', '104') ON CONFLICT DO NOTHING;
INSERT INTO public.assign_class_teacher ("id", "teacher_id", "img", "teacher_name", "class_id", "class_name", "subject", "start_date", "end_date", "assigned_by", "assignment_status", "academic_year", "class_timing", "room_number") VALUES (5, 'T1005', 'assets/images/user/user5.jpg', 'Sophie Taylor', 'C105', 'Grade 10 Chemistry', 'Chemistry', '2024-09-01', '2025-06-30', 'Admin002', 'Active', '2024-2025', 'Tuesday, Thursday - 11:00 AM to 12:30 PM', '105') ON CONFLICT DO NOTHING;
INSERT INTO public.assign_class_teacher ("id", "teacher_id", "img", "teacher_name", "class_id", "class_name", "subject", "start_date", "end_date", "assigned_by", "assignment_status", "academic_year", "class_timing", "room_number") VALUES (6, 'T1006', 'assets/images/user/user6.jpg', 'Liam Johnson', 'C106', 'Grade 8 Geography', 'Geography', '2024-09-01', '2025-06-30', 'Admin004', 'Inactive', '2024-2025', 'Monday, Wednesday - 9:00 AM to 10:30 AM', '106') ON CONFLICT DO NOTHING;
INSERT INTO public.assign_class_teacher ("id", "teacher_id", "img", "teacher_name", "class_id", "class_name", "subject", "start_date", "end_date", "assigned_by", "assignment_status", "academic_year", "class_timing", "room_number") VALUES (7, 'T1007', 'assets/images/user/user7.jpg', 'Olivia Harris', 'C107', 'Grade 7 History', 'History', '2024-09-01', '2025-06-30', 'Admin005', 'Active', '2024-2025', 'Tuesday, Thursday - 1:00 PM to 2:30 PM', '107') ON CONFLICT DO NOTHING;
INSERT INTO public.assign_class_teacher ("id", "teacher_id", "img", "teacher_name", "class_id", "class_name", "subject", "start_date", "end_date", "assigned_by", "assignment_status", "academic_year", "class_timing", "room_number") VALUES (8, 'T1008', 'assets/images/user/user8.jpg', 'Isabella Clark', 'C108', 'Grade 6 English', 'English Language', '2024-09-01', '2025-06-30', 'Admin006', 'Active', '2024-2025', 'Monday, Wednesday - 11:00 AM to 12:30 PM', '108') ON CONFLICT DO NOTHING;
INSERT INTO public.assign_class_teacher ("id", "teacher_id", "img", "teacher_name", "class_id", "class_name", "subject", "start_date", "end_date", "assigned_by", "assignment_status", "academic_year", "class_timing", "room_number") VALUES (9, 'T1009', 'assets/images/user/user9.jpg', 'Ethan White', 'C109', 'Grade 8 Computer Science', 'Computer Science', '2024-09-01', '2025-06-30', 'Admin007', 'Inactive', '2024-2025', 'Tuesday, Thursday - 2:00 PM to 3:30 PM', '109') ON CONFLICT DO NOTHING;
INSERT INTO public.assign_class_teacher ("id", "teacher_id", "img", "teacher_name", "class_id", "class_name", "subject", "start_date", "end_date", "assigned_by", "assignment_status", "academic_year", "class_timing", "room_number") VALUES (10, 'T1010', 'assets/images/user/user10.jpg', 'Charlotte Lee', 'C110', 'Grade 11 Physics', 'Physics', '2024-09-01', '2025-06-30', 'Admin008', 'Active', '2024-2025', 'Monday, Wednesday - 9:30 AM to 11:00 AM', '110') ON CONFLICT DO NOTHING;
INSERT INTO public.assign_class_teacher ("id", "teacher_id", "img", "teacher_name", "class_id", "class_name", "subject", "start_date", "end_date", "assigned_by", "assignment_status", "academic_year", "class_timing", "room_number") VALUES (11, 'T1011', 'assets/images/user/user11.jpg', 'James Martin', 'C111', 'Grade 9 Chemistry', 'Chemistry', '2024-09-01', '2025-06-30', 'Admin009', 'Active', '2024-2025', 'Monday, Friday - 12:00 PM to 1:30 PM', '111') ON CONFLICT DO NOTHING;
INSERT INTO public.assign_class_teacher ("id", "teacher_id", "img", "teacher_name", "class_id", "class_name", "subject", "start_date", "end_date", "assigned_by", "assignment_status", "academic_year", "class_timing", "room_number") VALUES (12, 'T1012', 'assets/images/user/user2.jpg', 'Amelia Scott', 'C112', 'Grade 10 Biology', 'Biology', '2024-09-01', '2025-06-30', 'Admin010', 'Inactive', '2024-2025', 'Tuesday, Thursday - 10:00 AM to 11:30 AM', '112') ON CONFLICT DO NOTHING;
INSERT INTO public.assign_class_teacher ("id", "teacher_id", "img", "teacher_name", "class_id", "class_name", "subject", "start_date", "end_date", "assigned_by", "assignment_status", "academic_year", "class_timing", "room_number") VALUES (13, 'T1013', 'assets/images/user/user3.jpg', 'Benjamin Garcia', 'C113', 'Grade 11 Chemistry', 'Chemistry', '2024-09-01', '2025-06-30', 'Admin011', 'Inactive', '2024-2025', 'Wednesday, Friday - 10:30 AM to 12:00 PM', '113') ON CONFLICT DO NOTHING;
INSERT INTO public.assign_class_teacher ("id", "teacher_id", "img", "teacher_name", "class_id", "class_name", "subject", "start_date", "end_date", "assigned_by", "assignment_status", "academic_year", "class_timing", "room_number") VALUES (14, 'T1014', 'assets/images/user/user4.jpg', 'Lucas Walker', 'C114', 'Grade 12 Biology', 'Biology', '2024-09-01', '2025-06-30', 'Admin012', 'Active', '2024-2025', 'Monday, Wednesday - 2:00 PM to 3:30 PM', '114') ON CONFLICT DO NOTHING;
INSERT INTO public.assign_class_teacher ("id", "teacher_id", "img", "teacher_name", "class_id", "class_name", "subject", "start_date", "end_date", "assigned_by", "assignment_status", "academic_year", "class_timing", "room_number") VALUES (15, 'T1015', 'assets/images/user/user5.jpg', 'Mia Adams', 'C115', 'Grade 10 Mathematics', 'Mathematics', '2024-09-01', '2025-06-30', 'Admin013', 'Active', '2024-2025', 'Monday, Thursday - 1:00 PM to 2:30 PM', '115') ON CONFLICT DO NOTHING;

SET session_replication_role = 'origin';