-- Migration for complaint table derived from complaint.json
SET session_replication_role = 'replica';

CREATE TABLE IF NOT EXISTS public.complaint (
    "complaint_id" TEXT PRIMARY KEY,
    "complaint_date" TIMESTAMP,
    "complaint_time" TEXT,
    "complainant_name" TEXT,
    "complainant_type" TEXT,
    "student_name" TEXT,
    "complaint_description" TEXT,
    "department" TEXT,
    "status" TEXT,
    "assigned_to" TEXT,
    "resolution_description" TEXT,
    "resolution_date" TIMESTAMP,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    "priority_level" TEXT,
    "feedback" TEXT,
    "img" TEXT
);

INSERT INTO public.complaint ("complaint_id", "complaint_date", "complaint_time", "complainant_name", "complainant_type", "student_name", "complaint_description", "department", "status", "assigned_to", "resolution_description", "resolution_date", "created_at", "updated_at", "priority_level", "feedback", "img") VALUES ('C001', '2024-11-20', '09:00', 'Alice Johnson', 'Parent', 'Emma Johnson', 'The school lunch was cold and unappetizing.', 'Administration', 'Resolved', 'John Smith', 'Lunch quality was discussed with the cafeteria staff.', '2024-11-21', '2024-11-20T09:00:00Z', '2024-11-21T10:00:00Z', 'Medium', 'Thank you for addressing the issue promptly.', 'assets/images/user/user1.jpg') ON CONFLICT DO NOTHING;
INSERT INTO public.complaint ("complaint_id", "complaint_date", "complaint_time", "complainant_name", "complainant_type", "student_name", "complaint_description", "department", "status", "assigned_to", "resolution_description", "resolution_date", "created_at", "updated_at", "priority_level", "feedback", "img") VALUES ('C002', '2024-11-21', '13:15', 'David Brown', 'Student', 'David Brown', 'The chemistry lab equipment is outdated and not working properly.', 'Transportation', 'In Progress', 'Ms. Clara Green', NULL, NULL, '2024-11-21T01:15:00Z', '2024-11-21T01:15:00Z', 'High', NULL, 'assets/images/user/user2.jpg') ON CONFLICT DO NOTHING;
INSERT INTO public.complaint ("complaint_id", "complaint_date", "complaint_time", "complainant_name", "complainant_type", "student_name", "complaint_description", "department", "status", "assigned_to", "resolution_description", "resolution_date", "created_at", "updated_at", "priority_level", "feedback", "img") VALUES ('C003', '2024-11-19', '10:45', 'Sarah Miller', 'Staff', NULL, 'Inappropriate behavior from a student during class.', 'Administration', 'Closed', 'Principal Adams', 'A meeting was held with the student and parents.', '2024-11-20', '2024-11-19T10:45:00Z', '2024-11-20T11:00:00Z', 'Medium', 'The situation has improved since the meeting.', 'assets/images/user/user3.jpg') ON CONFLICT DO NOTHING;
INSERT INTO public.complaint ("complaint_id", "complaint_date", "complaint_time", "complainant_name", "complainant_type", "student_name", "complaint_description", "department", "status", "assigned_to", "resolution_description", "resolution_date", "created_at", "updated_at", "priority_level", "feedback", "img") VALUES ('C004', '2024-11-22', '11:30', 'Emily White', 'Parent', 'Noah White', 'The school bus was late on multiple occasions.', 'Transportation', 'Open', 'Mr. Alan Brown', NULL, NULL, '2024-11-22T11:30:00Z', '2024-11-22T11:30:00Z', 'High', NULL, 'assets/images/user/user4.jpg') ON CONFLICT DO NOTHING;
INSERT INTO public.complaint ("complaint_id", "complaint_date", "complaint_time", "complainant_name", "complainant_type", "student_name", "complaint_description", "department", "status", "assigned_to", "resolution_description", "resolution_date", "created_at", "updated_at", "priority_level", "feedback", "img") VALUES ('C005', '2024-11-21', '14:00', 'Michael Green', 'Student', 'Liam Green', 'The classroom is too noisy during study hours.', 'Classroom', 'In Progress', 'Mr. Johnson', NULL, NULL, '2024-11-21T14:00:00Z', '2024-11-21T14:00:00Z', 'Medium', NULL, 'assets/images/user/user5.jpg') ON CONFLICT DO NOTHING;
INSERT INTO public.complaint ("complaint_id", "complaint_date", "complaint_time", "complainant_name", "complainant_type", "student_name", "complaint_description", "department", "status", "assigned_to", "resolution_description", "resolution_date", "created_at", "updated_at", "priority_level", "feedback", "img") VALUES ('C006', '2024-11-22', '10:30', 'Sophia Clark', 'Parent', 'Olivia Clark', 'The school''s website is not user-friendly.', 'IT Department', 'Resolved', 'Ms. Laura White', 'Website updates are planned for next month.', '2024-11-22', '2024-11-22T10:30:00Z', '2024-11-22T10:45:00Z', 'Low', 'Appreciate the quick response!', 'assets/images/user/user6.jpg') ON CONFLICT DO NOTHING;
INSERT INTO public.complaint ("complaint_id", "complaint_date", "complaint_time", "complainant_name", "complainant_type", "student_name", "complaint_description", "department", "status", "assigned_to", "resolution_description", "resolution_date", "created_at", "updated_at", "priority_level", "feedback", "img") VALUES ('C007', '2024-11-23', '09:15', 'Alice Smith', 'Parent', 'Jack Smith', 'My child has been bullied by other students.', 'Human Resources', 'Open', 'Ms. Rebecca Turner', NULL, NULL, '2024-11-23T09:15:00Z', '2024-11-23T09:15:00Z', 'High', NULL, 'assets/images/user/user7.jpg') ON CONFLICT DO NOTHING;
INSERT INTO public.complaint ("complaint_id", "complaint_date", "complaint_time", "complainant_name", "complainant_type", "student_name", "complaint_description", "department", "status", "assigned_to", "resolution_description", "resolution_date", "created_at", "updated_at", "priority_level", "feedback", "img") VALUES ('C008', '2024-11-22', '15:00', 'Tom Williams', 'Staff', NULL, 'Insufficient resources in the library.', 'Library', 'In Progress', 'Mr. Robert Lane', NULL, NULL, '2024-11-22T15:00:00Z', '2024-11-22T15:00:00Z', 'Medium', NULL, 'assets/images/user/user8.jpg') ON CONFLICT DO NOTHING;
INSERT INTO public.complaint ("complaint_id", "complaint_date", "complaint_time", "complainant_name", "complainant_type", "student_name", "complaint_description", "department", "status", "assigned_to", "resolution_description", "resolution_date", "created_at", "updated_at", "priority_level", "feedback", "img") VALUES ('C009', '2024-11-21', '11:45', 'Emily Carter', 'Student', 'Ava Carter', 'The gym facilities are not well maintained.', 'Facilities', 'Resolved', 'Mr. Steve Brown', 'Scheduled maintenance for gym equipment.', '2024-11-22', '2024-11-21T11:45:00Z', '2024-11-22T12:00:00Z', 'Medium', 'Thanks for the quick action!', 'assets/images/user/user9.jpg') ON CONFLICT DO NOTHING;
INSERT INTO public.complaint ("complaint_id", "complaint_date", "complaint_time", "complainant_name", "complainant_type", "student_name", "complaint_description", "department", "status", "assigned_to", "resolution_description", "resolution_date", "created_at", "updated_at", "priority_level", "feedback", "img") VALUES ('C010', '2024-11-22', '12:30', 'Brian Johnson', 'Parent', 'Sophia Johnson', 'Lack of communication regarding school events.', 'Administration', 'Open', 'Ms. Linda Smith', NULL, NULL, '2024-11-22T12:30:00Z', '2024-11-22T12:30:00Z', 'Medium', NULL, 'assets/images/user/user10.jpg') ON CONFLICT DO NOTHING;
INSERT INTO public.complaint ("complaint_id", "complaint_date", "complaint_time", "complainant_name", "complainant_type", "student_name", "complaint_description", "department", "status", "assigned_to", "resolution_description", "resolution_date", "created_at", "updated_at", "priority_level", "feedback", "img") VALUES ('C011', '2024-11-23', '10:00', 'Rachel Adams', 'Student', 'Noah Adams', 'The classroom temperature is too cold.', 'Classroom', 'In Progress', 'Mr. Peter Taylor', NULL, NULL, '2024-11-23T10:00:00Z', '2024-11-23T10:00:00Z', 'Low', NULL, 'assets/images/user/user11.jpg') ON CONFLICT DO NOTHING;
INSERT INTO public.complaint ("complaint_id", "complaint_date", "complaint_time", "complainant_name", "complainant_type", "student_name", "complaint_description", "department", "status", "assigned_to", "resolution_description", "resolution_date", "created_at", "updated_at", "priority_level", "feedback", "img") VALUES ('C012', '2024-11-24', '08:30', 'Lucas Parker', 'Student', 'Lucas Parker', 'The Wi-Fi is slow and frequently disconnects.', 'IT Department', 'Resolved', 'Mr. James Walker', 'IT team has worked on improving the network speed.', '2024-11-24', '2024-11-24T08:30:00Z', '2024-11-24T08:45:00Z', 'Medium', 'Issue resolved quickly. Thank you.', 'assets/images/user/user12.jpg') ON CONFLICT DO NOTHING;

SET session_replication_role = 'origin';