-- Migration for fees_type table derived from fees-type.json
SET session_replication_role = 'replica';
CREATE TABLE IF NOT EXISTS public.fees_type (
    "fee_type_id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "fee_type_name" TEXT,
    "category" TEXT,
    "description" TEXT,
    "amount" INTEGER,
    "applicable_classes" TEXT,
    "frequency" TEXT,
    "status" TEXT,
    "created_by" TEXT,
    "created_date" TIMESTAMP,
    "last_updated" TIMESTAMP
);
INSERT INTO public.fees_type ("fee_type_id", "fee_type_name", "category", "description", "amount", "applicable_classes", "frequency", "status", "created_by", "created_date", "last_updated") VALUES ('2617be8e-919e-3615-991d-72943ecbc40a', 'Tuition Fee', 'Academic', 'Fee for academic tuition services', 15000, 'Class 1-10', 'Monthly', 'Inactive', 'Admin', '2024-11-01', '2024-11-20') ON CONFLICT DO NOTHING;
INSERT INTO public.fees_type ("fee_type_id", "fee_type_name", "category", "description", "amount", "applicable_classes", "frequency", "status", "created_by", "created_date", "last_updated") VALUES ('76408ce3-cf51-3585-922b-f67a80450613', 'Transport Fee', 'Miscellaneous', 'Fee for student transport services', 5000, 'Class 1-12', 'Monthly', 'Active', 'Admin', '2024-10-15', '2024-11-18') ON CONFLICT DO NOTHING;
INSERT INTO public.fees_type ("fee_type_id", "fee_type_name", "category", "description", "amount", "applicable_classes", "frequency", "status", "created_by", "created_date", "last_updated") VALUES ('019409d2-17d8-344c-b41e-e1070ba2ccd3', 'Library Fee', 'Academic', 'Fee for library maintenance', 2000, 'Class 6-12', 'Annually', 'Active', 'Admin', '2024-09-20', '2024-11-10') ON CONFLICT DO NOTHING;
INSERT INTO public.fees_type ("fee_type_id", "fee_type_name", "category", "description", "amount", "applicable_classes", "frequency", "status", "created_by", "created_date", "last_updated") VALUES ('9c027083-5f06-30db-91ef-123621fa260e', 'Sports Fee', 'Extracurricular', 'Fee for sports activities and facilities', 3000, 'Class 1-10', 'Annually', 'Inactive', 'Admin', '2024-08-10', '2024-11-05') ON CONFLICT DO NOTHING;
INSERT INTO public.fees_type ("fee_type_id", "fee_type_name", "category", "description", "amount", "applicable_classes", "frequency", "status", "created_by", "created_date", "last_updated") VALUES ('f51c63f8-adcf-3d75-9c6f-981b3912f6b2', 'Lab Fee', 'Academic', 'Fee for science lab usage and equipment', 4000, 'Class 9-12', 'Annually', 'Active', 'Admin', '2024-07-25', '2024-11-12') ON CONFLICT DO NOTHING;
INSERT INTO public.fees_type ("fee_type_id", "fee_type_name", "category", "description", "amount", "applicable_classes", "frequency", "status", "created_by", "created_date", "last_updated") VALUES ('665fa84d-cd7e-3dc0-a9ec-f2c95cd6dc06', 'Examination Fee', 'Academic', 'Fee for conducting exams', 2500, 'Class 1-12', 'Annually', 'Active', 'Admin', '2024-06-01', '2024-10-30') ON CONFLICT DO NOTHING;
INSERT INTO public.fees_type ("fee_type_id", "fee_type_name", "category", "description", "amount", "applicable_classes", "frequency", "status", "created_by", "created_date", "last_updated") VALUES ('4b18db81-913d-3511-99de-624351d17598', 'Development Fee', 'Academic', 'Fee for school infrastructure development', 10000, 'Class 1-12', 'Quarterly', 'Inactive', 'Admin', '2024-05-15', '2024-11-15') ON CONFLICT DO NOTHING;
INSERT INTO public.fees_type ("fee_type_id", "fee_type_name", "category", "description", "amount", "applicable_classes", "frequency", "status", "created_by", "created_date", "last_updated") VALUES ('753f6801-1d16-35d5-806f-3fe78e101757', 'Hostel Fee', 'Miscellaneous', 'Fee for boarding and lodging in the school hostel', 50000, 'Class 6-12', 'Quarterly', 'Active', 'Admin', '2024-04-01', '2024-11-01') ON CONFLICT DO NOTHING;
INSERT INTO public.fees_type ("fee_type_id", "fee_type_name", "category", "description", "amount", "applicable_classes", "frequency", "status", "created_by", "created_date", "last_updated") VALUES ('8bb81377-a6a0-3ac3-ac43-010141b79b30', 'Maintenance Fee', 'Miscellaneous', 'Fee for general school maintenance', 2000, 'Class 1-12', 'Annually', 'Active', 'Admin', '2024-03-15', '2024-11-20') ON CONFLICT DO NOTHING;
INSERT INTO public.fees_type ("fee_type_id", "fee_type_name", "category", "description", "amount", "applicable_classes", "frequency", "status", "created_by", "created_date", "last_updated") VALUES ('95b86757-c3b8-3f5f-8771-2e6ea8468aa3', 'Cultural Activities Fee', 'Extracurricular', 'Fee for participation in cultural events', 1500, 'Class 1-12', 'Annually', 'Active', 'Admin', '2024-02-10', '2024-11-14') ON CONFLICT DO NOTHING;
INSERT INTO public.fees_type ("fee_type_id", "fee_type_name", "category", "description", "amount", "applicable_classes", "frequency", "status", "created_by", "created_date", "last_updated") VALUES ('864f3292-8670-32fc-af3f-3cfba3f7a87b', 'Computer Lab Fee', 'Academic', 'Fee for computer lab access', 3000, 'Class 6-12', 'Annually', 'Active', 'Admin', '2024-01-25', '2024-11-05') ON CONFLICT DO NOTHING;
INSERT INTO public.fees_type ("fee_type_id", "fee_type_name", "category", "description", "amount", "applicable_classes", "frequency", "status", "created_by", "created_date", "last_updated") VALUES ('a4986f3f-ab27-3096-b383-76f75623dd09', 'Workshop Fee', 'Academic', 'Fee for attending workshops', 5000, 'Class 9-12', 'Per Event', 'Inactive', 'Admin', '2024-01-01', '2024-11-08') ON CONFLICT DO NOTHING;
INSERT INTO public.fees_type ("fee_type_id", "fee_type_name", "category", "description", "amount", "applicable_classes", "frequency", "status", "created_by", "created_date", "last_updated") VALUES ('f20ba59a-4d66-3042-bd09-308bb55c18a2', 'Medical Fee', 'Miscellaneous', 'Fee for medical facilities and emergencies', 1000, 'Class 1-12', 'Annually', 'Inactive', 'Admin', '2023-12-15', '2024-11-10') ON CONFLICT DO NOTHING;
INSERT INTO public.fees_type ("fee_type_id", "fee_type_name", "category", "description", "amount", "applicable_classes", "frequency", "status", "created_by", "created_date", "last_updated") VALUES ('5148f1b0-be36-3f59-a109-e665da904704', 'Uniform Fee', 'Miscellaneous', 'Fee for school uniforms', 3000, 'Class 1-12', 'Annually', 'Active', 'Admin', '2023-12-01', '2024-11-03') ON CONFLICT DO NOTHING;
INSERT INTO public.fees_type ("fee_type_id", "fee_type_name", "category", "description", "amount", "applicable_classes", "frequency", "status", "created_by", "created_date", "last_updated") VALUES ('3a2a3a0e-f190-3ff7-afad-de50ac7df2d3', 'Miscellaneous Fee', 'Miscellaneous', 'Fee for other general purposes', 1000, 'Class 1-12', 'Annually', 'Active', 'Admin', '2023-11-20', '2024-11-15') ON CONFLICT DO NOTHING;
SET session_replication_role = 'origin';
