-- Migration for hostel_room_list table derived from hostel-room-list.json
SET session_replication_role = 'replica';
CREATE TABLE IF NOT EXISTS public.hostel_room_list (
    "room_id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "room_number" TEXT,
    "room_type" TEXT,
    "floor" INTEGER,
    "capacity" INTEGER,
    "occupied_status" TEXT,
    "current_occupants" INTEGER,
    "price_fees" INTEGER,
    "room_condition" TEXT,
    "date_assigned" TIMESTAMP,
    "room_supervisor_staff" TEXT,
    "hostel_block" TEXT,
    "check_in_date" TIMESTAMP,
    "check_out_date" TIMESTAMP,
    "room_type_code" TEXT,
    "room_description" TEXT
);
INSERT INTO public.hostel_room_list ("room_id", "room_number", "room_type", "floor", "capacity", "occupied_status", "current_occupants", "price_fees", "room_condition", "date_assigned", "room_supervisor_staff", "hostel_block", "check_in_date", "check_out_date", "room_type_code", "room_description") VALUES ('747eb6f5-07c1-3ac9-9e7f-5aa646458552', '101', 'Single', 1, 1, 'Occupied', 1, 1000, 'Good', '2024-08-01', 'John Doe', 'A Block', '2024-08-01', '2025-07-31', 'SGL', 'A spacious air-conditioned room with an attached bathroom and study desk.') ON CONFLICT DO NOTHING;
INSERT INTO public.hostel_room_list ("room_id", "room_number", "room_type", "floor", "capacity", "occupied_status", "current_occupants", "price_fees", "room_condition", "date_assigned", "room_supervisor_staff", "hostel_block", "check_in_date", "check_out_date", "room_type_code", "room_description") VALUES ('59b0050f-eded-30d6-8e66-958ae17005c8', '102', 'Double', 1, 2, 'Occupied', 2, 1500, 'Good', '2024-08-01', 'Jane Smith', 'A Block', '2024-08-01', '2025-07-31', 'DBL', 'A double-occupancy room with two beds, a desk, and an attached bathroom.') ON CONFLICT DO NOTHING;
INSERT INTO public.hostel_room_list ("room_id", "room_number", "room_type", "floor", "capacity", "occupied_status", "current_occupants", "price_fees", "room_condition", "date_assigned", "room_supervisor_staff", "hostel_block", "check_in_date", "check_out_date", "room_type_code", "room_description") VALUES ('aac1a628-4d54-3e66-8e39-6e02b7ac6da9', '103', 'Triple', 1, 3, 'Vacant', 0, 1800, 'Needs Repair', NULL, 'Alice Johnson', 'B Block', NULL, NULL, 'TRL', 'A spacious room with three beds and a shared bathroom, currently under maintenance.') ON CONFLICT DO NOTHING;
INSERT INTO public.hostel_room_list ("room_id", "room_number", "room_type", "floor", "capacity", "occupied_status", "current_occupants", "price_fees", "room_condition", "date_assigned", "room_supervisor_staff", "hostel_block", "check_in_date", "check_out_date", "room_type_code", "room_description") VALUES ('cbe29e76-8985-3dd0-8500-fd7fbf3c0af6', '104', 'Single', 2, 1, 'Occupied', 1, 1000, 'Good', '2024-08-10', 'John Doe', 'C Block', '2024-08-10', '2025-08-09', 'SGL', 'A comfortable room with a single bed and an attached bathroom.') ON CONFLICT DO NOTHING;
INSERT INTO public.hostel_room_list ("room_id", "room_number", "room_type", "floor", "capacity", "occupied_status", "current_occupants", "price_fees", "room_condition", "date_assigned", "room_supervisor_staff", "hostel_block", "check_in_date", "check_out_date", "room_type_code", "room_description") VALUES ('6afc6d47-2b0a-33f7-85ab-8fdf2c7bedd2', '105', 'Double', 2, 2, 'Occupied', 2, 1200, 'Good', '2024-09-01', 'Emma Lee', 'C Block', '2024-09-01', '2025-08-31', 'DBL', 'A well-lit room with two beds, a study desk, and a shared bathroom.') ON CONFLICT DO NOTHING;
INSERT INTO public.hostel_room_list ("room_id", "room_number", "room_type", "floor", "capacity", "occupied_status", "current_occupants", "price_fees", "room_condition", "date_assigned", "room_supervisor_staff", "hostel_block", "check_in_date", "check_out_date", "room_type_code", "room_description") VALUES ('5c2763bf-d780-34a0-a1d4-97f20478e165', '106', 'Triple', 2, 3, 'Vacant', 0, 1500, 'Good', NULL, 'Alice Johnson', 'B Block', NULL, NULL, 'TRL', 'A spacious room with three beds and a shared bathroom.') ON CONFLICT DO NOTHING;
INSERT INTO public.hostel_room_list ("room_id", "room_number", "room_type", "floor", "capacity", "occupied_status", "current_occupants", "price_fees", "room_condition", "date_assigned", "room_supervisor_staff", "hostel_block", "check_in_date", "check_out_date", "room_type_code", "room_description") VALUES ('557bc228-b134-3121-beb9-a6c4737fe74c', '201', 'Single', 2, 1, 'Occupied', 1, 1100, 'Good', '2024-10-01', 'Mark Wood', 'D Block', '2024-10-01', '2025-09-30', 'SGL', 'A premium single room with modern amenities.') ON CONFLICT DO NOTHING;
INSERT INTO public.hostel_room_list ("room_id", "room_number", "room_type", "floor", "capacity", "occupied_status", "current_occupants", "price_fees", "room_condition", "date_assigned", "room_supervisor_staff", "hostel_block", "check_in_date", "check_out_date", "room_type_code", "room_description") VALUES ('cbd7ec39-84bb-3d66-b591-1d96809ddba3', '202', 'Double', 2, 2, 'Vacant', 0, 1600, 'Good', NULL, 'Mark Wood', 'D Block', NULL, NULL, 'DBL', 'A spacious double room in D block.') ON CONFLICT DO NOTHING;
INSERT INTO public.hostel_room_list ("room_id", "room_number", "room_type", "floor", "capacity", "occupied_status", "current_occupants", "price_fees", "room_condition", "date_assigned", "room_supervisor_staff", "hostel_block", "check_in_date", "check_out_date", "room_type_code", "room_description") VALUES ('cb2602ef-fa7c-30cc-8fa0-f8a648b0289d', '301', 'Single', 3, 1, 'Occupied', 1, 1200, 'Excellent', '2024-11-01', 'Sarah Hall', 'A Block', '2024-11-01', '2025-10-31', 'SGL', 'A top-floor single room with a great view.') ON CONFLICT DO NOTHING;
INSERT INTO public.hostel_room_list ("room_id", "room_number", "room_type", "floor", "capacity", "occupied_status", "current_occupants", "price_fees", "room_condition", "date_assigned", "room_supervisor_staff", "hostel_block", "check_in_date", "check_out_date", "room_type_code", "room_description") VALUES ('6198a8f2-8409-309e-857c-bc82a3940c53', '302', 'Double', 3, 2, 'Occupied', 1, 1700, 'Good', '2024-11-15', 'Sarah Hall', 'A Block', '2024-11-15', '2025-11-14', 'DBL', 'A double room with one occupant currently.') ON CONFLICT DO NOTHING;
INSERT INTO public.hostel_room_list ("room_id", "room_number", "room_type", "floor", "capacity", "occupied_status", "current_occupants", "price_fees", "room_condition", "date_assigned", "room_supervisor_staff", "hostel_block", "check_in_date", "check_out_date", "room_type_code", "room_description") VALUES ('c14ec4ff-6bb8-3c28-a7a8-a39989f2a4f7', '401', 'Triple', 4, 3, 'Occupied', 3, 2000, 'Good', '2024-12-01', 'Peter King', 'B Block', '2024-12-01', '2025-11-30', 'TRL', 'A large triple room fully occupied.') ON CONFLICT DO NOTHING;
INSERT INTO public.hostel_room_list ("room_id", "room_number", "room_type", "floor", "capacity", "occupied_status", "current_occupants", "price_fees", "room_condition", "date_assigned", "room_supervisor_staff", "hostel_block", "check_in_date", "check_out_date", "room_type_code", "room_description") VALUES ('00c2025e-9caa-3cb1-82b5-b28132327506', '402', 'Single', 4, 1, 'Vacant', 0, 1300, 'Good', NULL, 'Peter King', 'B Block', NULL, NULL, 'SGL', 'A quiet single room on the fourth floor.') ON CONFLICT DO NOTHING;
SET session_replication_role = 'origin';
