-- Migration for hostel_room_type table derived from hostel-room-type.json
SET session_replication_role = 'replica';
CREATE TABLE IF NOT EXISTS public.hostel_room_type (
    "room_type_id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "room_type_name" TEXT,
    "capacity" INTEGER,
    "room_category" TEXT,
    "room_description" TEXT,
    "room_price" INTEGER,
    "room_facilities" TEXT,
    "room_area" INTEGER,
    "room_condition" TEXT,
    "room_type_code" TEXT,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    "status" TEXT,
    "max_occupants" INTEGER
);
INSERT INTO public.hostel_room_type ("room_type_id", "room_type_name", "capacity", "room_category", "room_description", "room_price", "room_facilities", "room_area", "room_condition", "room_type_code", "created_at", "updated_at", "status", "max_occupants") VALUES ('e16c1ff7-dd11-302c-9df7-bf971dd57e2f', 'Single', 1, 'Regular', 'A spacious, air-conditioned room with an attached bathroom and study desk.', 1000, 'Bed, Desk, Chair, Wardrobe, Attached Bathroom, Air-conditioning', 200, 'Good', 'SGL', '2024-01-10', '2024-11-20', 'Active', 1) ON CONFLICT DO NOTHING;
INSERT INTO public.hostel_room_type ("room_type_id", "room_type_name", "capacity", "room_category", "room_description", "room_price", "room_facilities", "room_area", "room_condition", "room_type_code", "created_at", "updated_at", "status", "max_occupants") VALUES ('b519145f-72e3-3932-8dbb-5e0b943b92bf', 'Double', 2, 'Economy', 'A cozy double-occupancy room with two beds, study desks, and an attached bathroom.', 1500, '2 Beds, 2 Desks, Chair, Wardrobe, Attached Bathroom, Fan', 250, 'Good', 'DBL', '2024-02-05', '2024-11-20', 'Active', 2) ON CONFLICT DO NOTHING;
INSERT INTO public.hostel_room_type ("room_type_id", "room_type_name", "capacity", "room_category", "room_description", "room_price", "room_facilities", "room_area", "room_condition", "room_type_code", "created_at", "updated_at", "status", "max_occupants") VALUES ('01df36bd-8951-3a49-ac0d-29cce5514f18', 'Triple', 3, 'Regular', 'A spacious triple-occupancy room with three beds, study desks, and a shared bathroom.', 1800, '3 Beds, 3 Desks, Chair, Wardrobe, Shared Bathroom, Air-conditioning', 300, 'Needs Repair', 'TRL', '2024-03-15', '2024-11-20', 'Inactive', 3) ON CONFLICT DO NOTHING;
INSERT INTO public.hostel_room_type ("room_type_id", "room_type_name", "capacity", "room_category", "room_description", "room_price", "room_facilities", "room_area", "room_condition", "room_type_code", "created_at", "updated_at", "status", "max_occupants") VALUES ('85eedbc7-49f0-35be-85d7-e7ce291e6e18', 'Quad', 4, 'Premium', 'A large room for four occupants with four beds, a study area, and an attached bathroom.', 2200, '4 Beds, 4 Desks, Chair, Wardrobe, Attached Bathroom, Air-conditioning, TV', 400, 'Excellent', 'QD', '2024-04-10', '2024-11-20', 'Active', 4) ON CONFLICT DO NOTHING;
INSERT INTO public.hostel_room_type ("room_type_id", "room_type_name", "capacity", "room_category", "room_description", "room_price", "room_facilities", "room_area", "room_condition", "room_type_code", "created_at", "updated_at", "status", "max_occupants") VALUES ('da28270c-b47c-3a89-bd1b-9624761b2195', 'Single', 1, 'VIP', 'A luxury single room with premium amenities, an attached bathroom, and a study desk.', 2000, 'Bed, Desk, Chair, Wardrobe, Attached Bathroom, Air-conditioning, TV, Mini Fridge', 220, 'Good', 'SGL-VIP', '2024-05-01', '2024-11-20', 'Active', 1) ON CONFLICT DO NOTHING;
INSERT INTO public.hostel_room_type ("room_type_id", "room_type_name", "capacity", "room_category", "room_description", "room_price", "room_facilities", "room_area", "room_condition", "room_type_code", "created_at", "updated_at", "status", "max_occupants") VALUES ('86531340-7e32-39f3-8855-62116d5e9760', 'Double', 2, 'Economy', 'A comfortable double room with two beds, a shared bathroom, and a small study area.', 1400, '2 Beds, 2 Desks, Chair, Wardrobe, Shared Bathroom, Fan', 240, 'Good', 'DBL-ECO', '2024-06-18', '2024-11-20', 'Active', 2) ON CONFLICT DO NOTHING;
INSERT INTO public.hostel_room_type ("room_type_id", "room_type_name", "capacity", "room_category", "room_description", "room_price", "room_facilities", "room_area", "room_condition", "room_type_code", "created_at", "updated_at", "status", "max_occupants") VALUES ('cc7d022f-66b5-3d49-b28a-df4d0d8bfcb7', 'Triple', 3, 'Premium', 'Premium triple room with extra space.', 1900, '3 Beds, 3 Desks, AC, TV', 320, 'Excellent', 'TRL-PREM', '2024-07-01', '2024-11-20', 'Active', 3) ON CONFLICT DO NOTHING;
INSERT INTO public.hostel_room_type ("room_type_id", "room_type_name", "capacity", "room_category", "room_description", "room_price", "room_facilities", "room_area", "room_condition", "room_type_code", "created_at", "updated_at", "status", "max_occupants") VALUES ('5f8341b0-9469-38ef-a4d2-8e3df6a083bb', 'Quad', 4, 'Economy', 'Large economy room for four.', 2000, '4 Beds, 4 Desks, Fan', 380, 'Good', 'QD-ECO', '2024-08-01', '2024-11-20', 'Active', 4) ON CONFLICT DO NOTHING;
INSERT INTO public.hostel_room_type ("room_type_id", "room_type_name", "capacity", "room_category", "room_description", "room_price", "room_facilities", "room_area", "room_condition", "room_type_code", "created_at", "updated_at", "status", "max_occupants") VALUES ('3078648f-a1d9-32bd-bd4f-e5fff1f23c96', 'Single', 1, 'Regular', 'Standard single room.', 1050, 'Bed, Desk, Wardrobe', 180, 'Good', 'SGL-STD', '2024-09-01', '2024-11-20', 'Active', 1) ON CONFLICT DO NOTHING;
INSERT INTO public.hostel_room_type ("room_type_id", "room_type_name", "capacity", "room_category", "room_description", "room_price", "room_facilities", "room_area", "room_condition", "room_type_code", "created_at", "updated_at", "status", "max_occupants") VALUES ('f26cccfb-192e-3dc8-88bd-9bc0da9cb6d9', 'Double', 2, 'VIP', 'Luxury double room.', 2500, '2 Beds, AC, TV, Fridge', 280, 'Excellent', 'DBL-VIP', '2024-10-01', '2024-11-20', 'Active', 2) ON CONFLICT DO NOTHING;
INSERT INTO public.hostel_room_type ("room_type_id", "room_type_name", "capacity", "room_category", "room_description", "room_price", "room_facilities", "room_area", "room_condition", "room_type_code", "created_at", "updated_at", "status", "max_occupants") VALUES ('38fecf76-2edb-3f85-9dcc-0c16f3b34d1b', 'Triple', 3, 'Economy', 'Affordable triple room.', 1600, '3 Beds, Fan', 290, 'Fair', 'TRL-ECO', '2024-11-01', '2024-11-20', 'Active', 3) ON CONFLICT DO NOTHING;
INSERT INTO public.hostel_room_type ("room_type_id", "room_type_name", "capacity", "room_category", "room_description", "room_price", "room_facilities", "room_area", "room_condition", "room_type_code", "created_at", "updated_at", "status", "max_occupants") VALUES ('b9450727-d8f2-3edc-a012-698f197c3ac3', 'Quad', 4, 'Regular', 'Standard quad room.', 2100, '4 Beds, 4 Desks', 390, 'Good', 'QD-STD', '2024-12-01', '2024-11-20', 'Active', 4) ON CONFLICT DO NOTHING;
SET session_replication_role = 'origin';
