-- Migration for leave_types table derived from leave-types.json
SET session_replication_role = 'replica';
CREATE TABLE IF NOT EXISTS public.leave_types (
    "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "leave_name" TEXT,
    "leave_unit" TEXT,
    "type" TEXT,
    "status" TEXT,
    "note" TEXT,
    "duration" INTEGER,
    "created_by" TEXT,
    "carry_over" TEXT,
    "notification_period" TEXT,
    "max_leaves" INTEGER,
    "annual_limit" INTEGER
);
INSERT INTO public.leave_types ("id", "leave_name", "leave_unit", "type", "status", "note", "duration", "created_by", "carry_over", "notification_period", "max_leaves", "annual_limit") VALUES ('64821703-e582-383d-9cfc-d4ab2e81f59b', 'Work From Home Leave', 'Days', 'Paid', 'Deactive', 'Winged lights seed don''t to him. Be day fish whose had that it him sea bearing abundantly greater.', 5, 'HR Department', 'Allowed up to 2 days.', '48 hours prior.', 10, 15) ON CONFLICT DO NOTHING;
INSERT INTO public.leave_types ("id", "leave_name", "leave_unit", "type", "status", "note", "duration", "created_by", "carry_over", "notification_period", "max_leaves", "annual_limit") VALUES ('ceeea99b-f085-39a5-875f-5c603aade28e', 'Casual Leave', 'Hours', 'Unpaid', 'Active', 'Winged lights seed don''t to him. Be day fish whose had that it him sea bearing abundantly greater.', 8, 'HR Department', 'Not allowed.', '24 hours prior.', 12, 30) ON CONFLICT DO NOTHING;
INSERT INTO public.leave_types ("id", "leave_name", "leave_unit", "type", "status", "note", "duration", "created_by", "carry_over", "notification_period", "max_leaves", "annual_limit") VALUES ('0c395726-c056-3349-b001-6d249044f060', 'Emergency Leave', 'Days', 'Unpaid', 'Active', 'Winged lights seed don''t to him. Be day fish whose had that it him sea bearing abundantly greater.', 3, 'HR Department', 'Allowed up to 1 day.', 'Immediate.', 5, 10) ON CONFLICT DO NOTHING;
INSERT INTO public.leave_types ("id", "leave_name", "leave_unit", "type", "status", "note", "duration", "created_by", "carry_over", "notification_period", "max_leaves", "annual_limit") VALUES ('363550f7-9fd7-38c6-88ec-d7e27ef8a5e3', 'Family Leave', 'Hours', 'Unpaid', 'Deactive', 'Winged lights seed don''t to him. Be day fish whose had that it him sea bearing abundantly greater.', 12, 'HR Department', 'Not allowed.', '48 hours prior.', 6, 15) ON CONFLICT DO NOTHING;
INSERT INTO public.leave_types ("id", "leave_name", "leave_unit", "type", "status", "note", "duration", "created_by", "carry_over", "notification_period", "max_leaves", "annual_limit") VALUES ('459417e8-57ec-3a68-a544-0d5e8f77eff1', 'Sick Leave', 'Days', 'Unpaid', 'Active', 'Winged lights seed don''t to him. Be day fish whose had that it him sea bearing abundantly greater.', 10, 'HR Department', 'Allowed up to 5 days.', '48 hours prior.', 15, 20) ON CONFLICT DO NOTHING;
INSERT INTO public.leave_types ("id", "leave_name", "leave_unit", "type", "status", "note", "duration", "created_by", "carry_over", "notification_period", "max_leaves", "annual_limit") VALUES ('b97a1e19-420d-3def-900c-2c39eaf72592', 'Casual Leave', 'Days', 'Unpaid', 'Active', 'Winged lights seed don''t to him. Be day fish whose had that it him sea bearing abundantly greater.', 8, 'HR Department', 'Not allowed.', '24 hours prior.', 12, 30) ON CONFLICT DO NOTHING;
INSERT INTO public.leave_types ("id", "leave_name", "leave_unit", "type", "status", "note", "duration", "created_by", "carry_over", "notification_period", "max_leaves", "annual_limit") VALUES ('533c8acb-4f84-3e49-b655-09669325b686', 'Maternity Leave', 'Days', 'Paid', 'Deactive', 'Winged lights seed don''t to him. Be day fish whose had that it him sea bearing abundantly greater.', 90, 'HR Department', 'Allowed up to 10 days.', '1 month prior.', 1, 1) ON CONFLICT DO NOTHING;
INSERT INTO public.leave_types ("id", "leave_name", "leave_unit", "type", "status", "note", "duration", "created_by", "carry_over", "notification_period", "max_leaves", "annual_limit") VALUES ('61c49214-e20d-39fa-8c9a-cb2051e3340b', 'Sick Leave', 'Days', 'Unpaid', 'Active', 'Winged lights seed don''t to him. Be day fish whose had that it him sea bearing abundantly greater.', 10, 'HR Department', 'Allowed up to 5 days.', '48 hours prior.', 15, 20) ON CONFLICT DO NOTHING;
INSERT INTO public.leave_types ("id", "leave_name", "leave_unit", "type", "status", "note", "duration", "created_by", "carry_over", "notification_period", "max_leaves", "annual_limit") VALUES ('96669f9c-f56c-3f1f-a444-a842e9030dab', 'Sick Leave', 'Days', 'Unpaid', 'Active', 'Winged lights seed don''t to him. Be day fish whose had that it him sea bearing abundantly greater.', 10, 'HR Department', 'Allowed up to 5 days.', '48 hours prior.', 15, 20) ON CONFLICT DO NOTHING;
INSERT INTO public.leave_types ("id", "leave_name", "leave_unit", "type", "status", "note", "duration", "created_by", "carry_over", "notification_period", "max_leaves", "annual_limit") VALUES ('f385b2b1-b847-379c-ae65-e510a5638d3b', 'Casual Leave', 'Days', 'Unpaid', 'Active', 'Winged lights seed don''t to him. Be day fish whose had that it him sea bearing abundantly greater.', 8, 'HR Department', 'Not allowed.', '24 hours prior.', 12, 30) ON CONFLICT DO NOTHING;
INSERT INTO public.leave_types ("id", "leave_name", "leave_unit", "type", "status", "note", "duration", "created_by", "carry_over", "notification_period", "max_leaves", "annual_limit") VALUES ('bb610936-7417-381f-b879-054df4be9b3d', 'Casual Leave', 'Days', 'Unpaid', 'Active', 'Winged lights seed don''t to him. Be day fish whose had that it him sea bearing abundantly greater.', 8, 'HR Department', 'Not allowed.', '24 hours prior.', 12, 30) ON CONFLICT DO NOTHING;
INSERT INTO public.leave_types ("id", "leave_name", "leave_unit", "type", "status", "note", "duration", "created_by", "carry_over", "notification_period", "max_leaves", "annual_limit") VALUES ('8aa09d6c-29cd-3f16-a74d-70f43976f03d', 'Emergency Leave', 'Days', 'Unpaid', 'Active', 'Winged lights seed don''t to him. Be day fish whose had that it him sea bearing abundantly greater.', 3, 'HR Department', 'Allowed up to 1 day.', 'Immediate.', 5, 10) ON CONFLICT DO NOTHING;
INSERT INTO public.leave_types ("id", "leave_name", "leave_unit", "type", "status", "note", "duration", "created_by", "carry_over", "notification_period", "max_leaves", "annual_limit") VALUES ('0ef01e18-3bc1-3e25-b926-2f3437dd680c', 'Work From Home Leave', 'Days', 'Paid', 'Deactive', 'Winged lights seed don''t to him. Be day fish whose had that it him sea bearing abundantly greater.', 5, 'HR Department', 'Allowed up to 2 days.', '48 hours prior.', 10, 15) ON CONFLICT DO NOTHING;
SET session_replication_role = 'origin';
