-- Migration for students table derived from students.json
SET session_replication_role = 'replica';

CREATE TABLE IF NOT EXISTS public.students (
    "id" TEXT PRIMARY KEY,
    "img" TEXT,
    "gender" TEXT,
    "email" TEXT,
    "department" TEXT,
    "mobile" TEXT,
    "name" TEXT,
    "roll_no" TEXT,
    "date_of_birth" TIMESTAMP,
    "address" TEXT,
    "enrollment_date" TIMESTAMP,
    "graduation_year" TEXT,
    "parent_guardian_name" TEXT,
    "parent_guardian_mobile" TEXT,
    "status" TEXT,
    "profile_completion_status" TEXT,
    "scholarship_status" TEXT
);

INSERT INTO public.students ("id", "img", "gender", "email", "department", "mobile", "name", "roll_no", "date_of_birth", "address", "enrollment_date", "graduation_year", "parent_guardian_name", "parent_guardian_mobile", "status", "profile_completion_status", "scholarship_status") VALUES ('001', 'assets/images/user/user1.jpg', 'male', 'test@email.com', 'mathematics', '1234567890', 'John Deo', '1', '2005-06-15', '123 Main St, Anytown, USA', '2018-02-01', '2023', 'Jane Deo', '0987654321', 'active', 'complete', 'none') ON CONFLICT DO NOTHING;
INSERT INTO public.students ("id", "img", "gender", "email", "department", "mobile", "name", "roll_no", "date_of_birth", "address", "enrollment_date", "graduation_year", "parent_guardian_name", "parent_guardian_mobile", "status", "profile_completion_status", "scholarship_status") VALUES ('002', 'assets/images/user/user2.jpg', 'female', 'test@email.com', 'civil', '1234567890', 'Sarah Smith', '2', '2005-08-20', '456 Elm St, Anytown, USA', '2018-02-01', '2023', 'Emily Smith', '0987654322', 'active', 'complete', 'merit') ON CONFLICT DO NOTHING;
INSERT INTO public.students ("id", "img", "gender", "email", "department", "mobile", "name", "roll_no", "date_of_birth", "address", "enrollment_date", "graduation_year", "parent_guardian_name", "parent_guardian_mobile", "status", "profile_completion_status", "scholarship_status") VALUES ('003', 'assets/images/user/user3.jpg', 'male', 'test@email.com', 'computer', '1234567890', 'John Deo', '3', '2005-04-15', '789 Pine St, Anytown, USA', '2018-02-01', '2023', 'Mark Deo', '0987654323', 'active', 'complete', 'none') ON CONFLICT DO NOTHING;
INSERT INTO public.students ("id", "img", "gender", "email", "department", "mobile", "name", "roll_no", "date_of_birth", "address", "enrollment_date", "graduation_year", "parent_guardian_name", "parent_guardian_mobile", "status", "profile_completion_status", "scholarship_status") VALUES ('004', 'assets/images/user/user4.jpg', 'female', 'test@email.com', 'civil', '1234567890', 'Jay Soni', '4', '2005-05-10', '321 Oak St, Anytown, USA', '2018-02-01', '2023', 'Ava Soni', '0987654324', 'active', 'incomplete', 'none') ON CONFLICT DO NOTHING;
INSERT INTO public.students ("id", "img", "gender", "email", "department", "mobile", "name", "roll_no", "date_of_birth", "address", "enrollment_date", "graduation_year", "parent_guardian_name", "parent_guardian_mobile", "status", "profile_completion_status", "scholarship_status") VALUES ('005', 'assets/images/user/user5.jpg', 'male', 'test@email.com', 'science', '1234567890', 'Smita Parikh', '5', '2005-03-30', '654 Maple St, Anytown, USA', '2018-02-01', '2023', 'Priya Parikh', '0987654325', 'active', 'complete', 'none') ON CONFLICT DO NOTHING;
INSERT INTO public.students ("id", "img", "gender", "email", "department", "mobile", "name", "roll_no", "date_of_birth", "address", "enrollment_date", "graduation_year", "parent_guardian_name", "parent_guardian_mobile", "status", "profile_completion_status", "scholarship_status") VALUES ('006', 'assets/images/user/user6.jpg', 'male', 'test@email.com', 'computer', '1234567890', 'Pankaj Sinha', '6', '2005-02-12', '159 Cedar St, Anytown, USA', '2018-02-01', '2023', 'Ravi Sinha', '0987654326', 'active', 'complete', 'none') ON CONFLICT DO NOTHING;
INSERT INTO public.students ("id", "img", "gender", "email", "department", "mobile", "name", "roll_no", "date_of_birth", "address", "enrollment_date", "graduation_year", "parent_guardian_name", "parent_guardian_mobile", "status", "profile_completion_status", "scholarship_status") VALUES ('007', 'assets/images/user/user7.jpg', 'male', 'test@email.com', 'computer', '1234567890', 'Pankaj Sinha', '7', '2005-11-21', '852 Birch St, Anytown, USA', '2018-02-01', '2023', 'Sita Sinha', '0987654327', 'active', 'complete', 'none') ON CONFLICT DO NOTHING;
INSERT INTO public.students ("id", "img", "gender", "email", "department", "mobile", "name", "roll_no", "date_of_birth", "address", "enrollment_date", "graduation_year", "parent_guardian_name", "parent_guardian_mobile", "status", "profile_completion_status", "scholarship_status") VALUES ('008', 'assets/images/user/user8.jpg', 'female', 'test@email.com', 'civil', '1234567890', 'Jay Soni', '8', '2005-07-18', '147 Spruce St, Anytown, USA', '2018-02-01', '2023', 'Anita Soni', '0987654328', 'active', 'complete', 'none') ON CONFLICT DO NOTHING;
INSERT INTO public.students ("id", "img", "gender", "email", "department", "mobile", "name", "roll_no", "date_of_birth", "address", "enrollment_date", "graduation_year", "parent_guardian_name", "parent_guardian_mobile", "status", "profile_completion_status", "scholarship_status") VALUES ('009', 'assets/images/user/user9.jpg', 'female', 'test@email.com', 'mathematics', '1234567890', 'Smita Parikh', '9', '2005-09-25', '258 Fir St, Anytown, USA', '2018-02-01', '2023', 'Neha Parikh', '0987654329', 'active', 'complete', 'none') ON CONFLICT DO NOTHING;
INSERT INTO public.students ("id", "img", "gender", "email", "department", "mobile", "name", "roll_no", "date_of_birth", "address", "enrollment_date", "graduation_year", "parent_guardian_name", "parent_guardian_mobile", "status", "profile_completion_status", "scholarship_status") VALUES ('010', 'assets/images/user/user10.jpg', 'male', 'test@email.com', 'civil', '1234567890', 'Pooja Patel', '10', '2005-10-05', '369 Willow St, Anytown, USA', '2018-02-01', '2023', 'Rita Patel', '0987654330', 'active', 'complete', 'none') ON CONFLICT DO NOTHING;
INSERT INTO public.students ("id", "img", "gender", "email", "department", "mobile", "name", "roll_no", "date_of_birth", "address", "enrollment_date", "graduation_year", "parent_guardian_name", "parent_guardian_mobile", "status", "profile_completion_status", "scholarship_status") VALUES ('011', 'assets/images/user/user1.jpg', 'female', 'test@email.com', 'computer', '1234567890', 'Jay Soni', '11', '2005-12-15', '741 Cherry St, Anytown, USA', '2018-02-01', '2023', 'Kiran Soni', '0987654331', 'active', 'complete', 'none') ON CONFLICT DO NOTHING;
INSERT INTO public.students ("id", "img", "gender", "email", "department", "mobile", "name", "roll_no", "date_of_birth", "address", "enrollment_date", "graduation_year", "parent_guardian_name", "parent_guardian_mobile", "status", "profile_completion_status", "scholarship_status") VALUES ('012', 'assets/images/user/user1.jpg', 'male', 'test@email.com', 'mathematics', '1234567890', 'Pooja Patel', '12', '2005-01-20', '963 Ash St, Anytown, USA', '2018-02-01', '2023', 'Sunil Patel', '0987654332', 'active', 'complete', 'none') ON CONFLICT DO NOTHING;
INSERT INTO public.students ("id", "img", "gender", "email", "department", "mobile", "name", "roll_no", "date_of_birth", "address", "enrollment_date", "graduation_year", "parent_guardian_name", "parent_guardian_mobile", "status", "profile_completion_status", "scholarship_status") VALUES ('013', 'assets/images/user/user2.jpg', 'female', 'test@email.com', 'civil', '1234567890', 'Sarah Smith', '13', '2005-03-05', '852 Elm St, Anytown, USA', '2018-02-01', '2023', 'Mary Smith', '0987654333', 'active', 'complete', 'none') ON CONFLICT DO NOTHING;
INSERT INTO public.students ("id", "img", "gender", "email", "department", "mobile", "name", "roll_no", "date_of_birth", "address", "enrollment_date", "graduation_year", "parent_guardian_name", "parent_guardian_mobile", "status", "profile_completion_status", "scholarship_status") VALUES ('014', 'assets/images/user/user3.jpg', 'male', 'test@email.com', 'science', '1234567890', 'Smita Parikh', '14', '2005-07-22', '456 Oak St, Anytown, USA', '2018-02-01', '2023', 'Raj Parikh', '0987654334', 'active', 'complete', 'none') ON CONFLICT DO NOTHING;
INSERT INTO public.students ("id", "img", "gender", "email", "department", "mobile", "name", "roll_no", "date_of_birth", "address", "enrollment_date", "graduation_year", "parent_guardian_name", "parent_guardian_mobile", "status", "profile_completion_status", "scholarship_status") VALUES ('015', 'assets/images/user/user4.jpg', 'female', 'test@email.com', 'computer', '1234567890', 'Jay Soni', '15', '2005-11-30', '159 Maple St, Anytown, USA', '2018-02-01', '2023', 'Lina Soni', '0987654335', 'active', 'complete', 'none') ON CONFLICT DO NOTHING;
INSERT INTO public.students ("id", "img", "gender", "email", "department", "mobile", "name", "roll_no", "date_of_birth", "address", "enrollment_date", "graduation_year", "parent_guardian_name", "parent_guardian_mobile", "status", "profile_completion_status", "scholarship_status") VALUES ('016', 'assets/images/user/user5.jpg', 'male', 'test@email.com', 'computer', '1234567890', 'Pankaj Sinha', '16', '2005-02-05', '258 Fir St, Anytown, USA', '2018-02-01', '2023', 'Ravi Sinha', '0987654336', 'active', 'complete', 'none') ON CONFLICT DO NOTHING;

SET session_replication_role = 'origin';