-- Migration for teachers table derived from teachers.json
SET session_replication_role = 'replica';
CREATE TABLE IF NOT EXISTS public.teachers (
    "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "img" TEXT,
    "name" TEXT,
    "gender" TEXT,
    "email" TEXT,
    "department" TEXT,
    "mobile" TEXT,
    "degree" TEXT,
    "address" TEXT,
    "hire_date" TIMESTAMP,
    "salary" TEXT,
    "subject_specialization" TEXT,
    "experience_years" INTEGER,
    "status" TEXT,
    "birthdate" TIMESTAMP,
    "bio" TEXT
);
INSERT INTO public.teachers ("id", "img", "name", "gender", "email", "department", "mobile", "degree", "address", "hire_date", "salary", "subject_specialization", "experience_years", "status", "birthdate", "bio") VALUES ('790cff3f-11de-3d28-b920-ba8219b062c7', 'assets/images/user/user1.jpg', 'John Deo', 'male', 'test@email.com', 'mathematics', '1234567890', 'M.Sc., PHD.', '123 Main St, Anytown, USA', '2018-02-25', '50000', 'Mathematics', 5, 'active', '1985-06-15', 'Dedicated mathematics teacher with a passion for inspiring students.') ON CONFLICT DO NOTHING;
INSERT INTO public.teachers ("id", "img", "name", "gender", "email", "department", "mobile", "degree", "address", "hire_date", "salary", "subject_specialization", "experience_years", "status", "birthdate", "bio") VALUES ('1f1809b6-15f1-3eae-9cd6-51f505a96b4e', 'assets/images/user/user2.jpg', 'Sarah Smith', 'female', 'test@email.com', 'civil', '1234567890', 'M.C.A.', '123 Main St, Anytown, USA', '2018-02-12', '50000', 'Civil Engineering', 3, 'active', '1990-05-20', 'Experienced civil engineer with a focus on structural design.') ON CONFLICT DO NOTHING;
INSERT INTO public.teachers ("id", "img", "name", "gender", "email", "department", "mobile", "degree", "address", "hire_date", "salary", "subject_specialization", "experience_years", "status", "birthdate", "bio") VALUES ('b35c6707-c33a-39e8-806b-3172c9651e47', 'assets/images/user/user3.jpg', 'John Deo', 'male', 'test@email.com', 'civil', '1234567890', 'B.A., M.A.', '123 Main St, Anytown, USA', '2018-02-25', '50000', 'Civil Engineering', 4, 'active', '1987-08-15', 'Passionate about teaching civil engineering principles.') ON CONFLICT DO NOTHING;
INSERT INTO public.teachers ("id", "img", "name", "gender", "email", "department", "mobile", "degree", "address", "hire_date", "salary", "subject_specialization", "experience_years", "status", "birthdate", "bio") VALUES ('b5036c62-3714-3341-9156-9a95f5176286', 'assets/images/user/user4.jpg', 'Jay Soni', 'female', 'test@email.com', 'mathematics', '1234567890', 'M.Com., P.H.D.', '123 Main St, Anytown, USA', '2018-02-25', '50000', 'Mathematics', 6, 'active', '1984-04-10', 'Dedicated mathematics teacher with a love for numbers.') ON CONFLICT DO NOTHING;
INSERT INTO public.teachers ("id", "img", "name", "gender", "email", "department", "mobile", "degree", "address", "hire_date", "salary", "subject_specialization", "experience_years", "status", "birthdate", "bio") VALUES ('bf1f8a65-86c2-31ab-b506-368627957e7e', 'assets/images/user/user5.jpg', 'Smita Parikh', 'male', 'test@email.com', 'science', '1234567890', 'B.C.A., M.C.A.', '123 Main St, Anytown, USA', '2018-02-25', '50000', 'Computer Science', 5, 'active', '1989-09-09', 'Enthusiastic about teaching computer science concepts.') ON CONFLICT DO NOTHING;
INSERT INTO public.teachers ("id", "img", "name", "gender", "email", "department", "mobile", "degree", "address", "hire_date", "salary", "subject_specialization", "experience_years", "status", "birthdate", "bio") VALUES ('27100c72-ab37-365d-81c4-ff7d9c6fae90', 'assets/images/user/user6.jpg', 'Pankaj Sinha', 'male', 'test@email.com', 'Computer', '1234567890', 'M.Com., P.H.D.', '123 Main St, Anytown, USA', '2018-02-25', '50000', 'Computer Science', 4, 'active', '1985-11-11', 'Experienced computer science instructor with industry experience.') ON CONFLICT DO NOTHING;
INSERT INTO public.teachers ("id", "img", "name", "gender", "email", "department", "mobile", "degree", "address", "hire_date", "salary", "subject_specialization", "experience_years", "status", "birthdate", "bio") VALUES ('4a83ec6d-6dcf-38ff-ab97-708ce0732f44', 'assets/images/user/user7.jpg', 'Pankaj Sinha', 'male', 'test@email.com', 'mechanical', '1234567890', 'M.Sc., PHD.', '123 Main St, Anytown, USA', '2018-02-25', '50000', 'Mechanical Engineering', 5, 'active', '1986-03-12', 'Skilled in mechanical engineering and hands-on learning.') ON CONFLICT DO NOTHING;
INSERT INTO public.teachers ("id", "img", "name", "gender", "email", "department", "mobile", "degree", "address", "hire_date", "salary", "subject_specialization", "experience_years", "status", "birthdate", "bio") VALUES ('6fcf5bd8-62f1-3034-a6a2-6b34d1c71e37', 'assets/images/user/user8.jpg', 'Jay Soni', 'female', 'test@email.com', 'mathematics', '1234567890', 'B.B.A., M.B.A.', '123 Main St, Anytown, USA', '2018-02-25', '50000', 'Mathematics', 4, 'active', '1988-02-22', 'Focused on practical applications of mathematics.') ON CONFLICT DO NOTHING;
INSERT INTO public.teachers ("id", "img", "name", "gender", "email", "department", "mobile", "degree", "address", "hire_date", "salary", "subject_specialization", "experience_years", "status", "birthdate", "bio") VALUES ('ddb524c0-96f6-3674-8b9e-1c3277dc79a7', 'assets/images/user/user9.jpg', 'Smita Parikh', 'female', 'test@email.com', 'mathematics', '1234567890', 'B.B.A., M.B.A.', '123 Main St, Anytown, USA', '2018-02-25', '50000', 'Mathematics', 3, 'active', '1992-01-30', 'Enthusiastic about engaging students in mathematics.') ON CONFLICT DO NOTHING;
INSERT INTO public.teachers ("id", "img", "name", "gender", "email", "department", "mobile", "degree", "address", "hire_date", "salary", "subject_specialization", "experience_years", "status", "birthdate", "bio") VALUES ('55b6cb40-82c8-3d8d-add3-dcd49e235cd6', 'assets/images/user/user10.jpg', 'Pooja Patel', 'male', 'test@email.com', 'civil', '1234567890', 'M.Com., P.H.D.', '123 Main St, Anytown, USA', '2018-02-25', '50000', 'Civil Engineering', 4, 'active', '1990-12-20', 'Expert in civil engineering with a passion for teaching.') ON CONFLICT DO NOTHING;
INSERT INTO public.teachers ("id", "img", "name", "gender", "email", "department", "mobile", "degree", "address", "hire_date", "salary", "subject_specialization", "experience_years", "status", "birthdate", "bio") VALUES ('99281f6e-d5d5-34a9-a018-ca40b1529290', 'assets/images/user/user1.jpg', 'Jay Soni', 'female', 'test@email.com', 'civil', '1234567890', 'M.Sc., PHD.', '123 Main St, Anytown, USA', '2018-02-25', '50000', 'Civil Engineering', 3, 'active', '1989-04-01', 'Civil engineer passionate about education.') ON CONFLICT DO NOTHING;
INSERT INTO public.teachers ("id", "img", "name", "gender", "email", "department", "mobile", "degree", "address", "hire_date", "salary", "subject_specialization", "experience_years", "status", "birthdate", "bio") VALUES ('a2b6275c-8c3b-300a-9023-05b1dea8f401', 'assets/images/user/user1.jpg', 'Pooja Patel', 'male', 'test@email.com', 'mathematics', '1234567890', 'B.C.A., M.C.A.', '123 Main St, Anytown, USA', '2018-02-25', '50000', 'Mathematics', 2, 'active', '1991-07-05', 'Aspiring mathematics teacher with a fresh perspective.') ON CONFLICT DO NOTHING;
INSERT INTO public.teachers ("id", "img", "name", "gender", "email", "department", "mobile", "degree", "address", "hire_date", "salary", "subject_specialization", "experience_years", "status", "birthdate", "bio") VALUES ('7f4ff707-7bb1-3f31-80dc-d43083ec33a0', 'assets/images/user/user2.jpg', 'Sarah Smith', 'female', 'test@email.com', 'mathematics', '1234567890', 'M.C.A.', '123 Main St, Anytown, USA', '2018-02-25', '50000', 'Mathematics', 3, 'active', '1995-09-12', 'Passionate about inspiring students in mathematics.') ON CONFLICT DO NOTHING;
INSERT INTO public.teachers ("id", "img", "name", "gender", "email", "department", "mobile", "degree", "address", "hire_date", "salary", "subject_specialization", "experience_years", "status", "birthdate", "bio") VALUES ('32504a75-e319-3aa6-bc9a-ad762db7bd24', 'assets/images/user/user3.jpg', 'Smita Parikh', 'male', 'test@email.com', 'science', '1234567890', 'B.A., M.A.', '123 Main St, Anytown, USA', '2018-02-25', '50000', 'Science', 3, 'active', '1992-08-22', 'Dedicated science teacher with hands-on experience.') ON CONFLICT DO NOTHING;
INSERT INTO public.teachers ("id", "img", "name", "gender", "email", "department", "mobile", "degree", "address", "hire_date", "salary", "subject_specialization", "experience_years", "status", "birthdate", "bio") VALUES ('545e2605-697a-37af-9fbd-b3f7ac7de4b3', 'assets/images/user/user4.jpg', 'Jay Soni', 'female', 'test@email.com', 'mechanical', '1234567890', 'B.B.A., M.B.A.', '123 Main St, Anytown, USA', '2018-02-25', '50000', 'Mechanical Engineering', 4, 'active', '1986-03-25', 'Mechanical engineer with a strong teaching background.') ON CONFLICT DO NOTHING;
INSERT INTO public.teachers ("id", "img", "name", "gender", "email", "department", "mobile", "degree", "address", "hire_date", "salary", "subject_specialization", "experience_years", "status", "birthdate", "bio") VALUES ('453f726a-00b8-37b9-b0fa-e9f596cb8bf1', 'assets/images/user/user5.jpg', 'Pankaj Sinha', 'male', 'test@email.com', 'civil', '1234567890', 'M.Com., P.H.D.', '123 Main St, Anytown, USA', '2018-02-25', '50000', 'Civil Engineering', 4, 'active', '1985-11-11', 'Experienced civil engineering instructor.') ON CONFLICT DO NOTHING;
SET session_replication_role = 'origin';
