// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AcademicYear is the predicate function for academicyear builders.
type AcademicYear func(*sql.Selector)

// Class is the predicate function for class builders.
type Class func(*sql.Selector)

// Department is the predicate function for department builders.
type Department func(*sql.Selector)

// Employee is the predicate function for employee builders.
type Employee func(*sql.Selector)

// Event is the predicate function for event builders.
type Event func(*sql.Selector)

// Exam is the predicate function for exam builders.
type Exam func(*sql.Selector)

// FeePayment is the predicate function for feepayment builders.
type FeePayment func(*sql.Selector)

// FeeStructure is the predicate function for feestructure builders.
type FeeStructure func(*sql.Selector)

// Student is the predicate function for student builders.
type Student func(*sql.Selector)

// StudentAttendance is the predicate function for studentattendance builders.
type StudentAttendance func(*sql.Selector)

// Subject is the predicate function for subject builders.
type Subject func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)

// Teacher is the predicate function for teacher builders.
type Teacher func(*sql.Selector)

// TeacherAttendance is the predicate function for teacherattendance builders.
type TeacherAttendance func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
